antvis/G2

src/animate/animate.js
src/chart/controller/axis.js
src/chart/controller/tooltip.js
test/unit/chart/chart-spec.js

Hotfix 1127

---

src/global.js
src/scale/auto/util.js
test/unit/scale/auto/number-spec.js

* 浮点数计算时出现非常长的小数，之前处理过，但是限制了 20 位的小数，但是实际使用中可能会出现16位的，所以限制到12 位。

fix(scale): very little number ticks

---

.eslintrc
test/unit/scale/pow-spec.js

fix(eslint): close the linebreak-style rule to support windows os

---

demos/facets-list.html
src/chart/chart.js
src/chart/controller/event.js
src/chart/view.js
src/geom/base.js
src/geom/shape/area.js
src/geom/shape/line.js
src/util.js
test/bugs/bug-252-spec.js
test/unit/chart/chart-spec.js
test/unit/geom/geom-spec.js
test/unit/geom/shape/area-spec.js

* fixed bug of view event
* fixed bug of view filter

fix(view):fixed bug of filter and view event

---

src/component/guide/arc.js
src/component/guide/html.js
src/component/guide/line.js
src/component/guide/text.js
src/theme/default.js

fix: set appropriate value of zIndex.

---

src/global.js
test/unit/global-spec.js

fix: allow set partial theme. Closed #205.

---

.gitignore
.npmignore
package.json

feat: update deps

---

package.json

fix: clean up deprecation

---

src/chart/controller/axis.js
test/unit/chart/chart-spec.js

fix: axis'title setting. Close #299

---

.eslintrc
README.md
README.zh-CN.md
demos/map-drill-down.html
package.json

* 地图下钻的 demo 和修复
* 替换 README.md 上的截图

Daily 20171222

---

package.json
src/chart/chart.js

fix(chart): crush after resize

---

src/component/legend/slider.js

chore: better continous legend' mouse cursor.

---

demos/app.js

fix(demos): @lite-js/torch => torchjs

---

demos/facets-point.html
src/animate/index.js
src/chart/chart.js
src/chart/controller/legend.js
src/chart/view.js
src/component/plot.js
test/unit/chart/chart-padding-spec.js

* 添加padding 的支持，四个方向都可以支持
```js
new Chart({
padding: 'auto'
});
new Chart({
padding: ['auto', 100, 'auto', 20]
});
```
* 自动 padding 时可以通过 autoPaddingAppend 参数设置附加的像素，默认 5px

feat(chart): support auto padding

---

package.json
src/chart/controller/axis.js
src/component/axis/grid.js
test/bugs/issue-243-spec.js
test/unit/chart/controller/axis-spec.js

1. if scale.isLinear, fill gaps only if gridAlign is `center`
2. if scale.isCategory, always fill gaps
Closes: #243 
| center | normal | center | normal |
| ---- | ---- | ---- | ---- |
| ![image](https://user-images.githubusercontent.com/1655789/34246205-7f9e3178-e668-11e7-84a1-abde4cc77f7d.png) | ![image](https://user-images.githubusercontent.com/1655789/34246227-98669d12-e668-11e7-9c0e-c35b0b29538f.png) | ![image](https://user-images.githubusercontent.com/1655789/34246222-933be676-e668-11e7-8947-43b59c220ea7.png) | ![image](https://user-images.githubusercontent.com/1655789/34246228-9aeb196e-e668-11e7-89a7-09e265186b5a.png) |

Fill gaps for axis grid near edges 

---

src/chart/controller/axis.js

https://github.com/antvis/g2/issues/327

fix draw axis when ticks's length is 0

---

src/chart/controller/axis.js
src/chart/controller/legend.js
src/component/axis/line.js
src/component/guide/line.js

fix several bugs of legend and axis

---

src/scale/auto/cat.js
src/scale/time-cat.js
test/unit/scale/auto/cat-spec.js

* 调整 time-cat ticks 的计算方式，见 issues #323

feat(scale): update cat ticks calculate

---

src/geom/area.js
src/geom/base.js
src/geom/path.js
src/geom/point.js
src/geom/shape/line.js
test/bugs/issue-346-spec.js

* 解决自定义 line 的 shape 时出现的问题 #346 
* 合并一些重复的代码

fix(shape): fixed register shape error

---

src/chart/chart.js
src/chart/controller/event.js
test/bugs/issue-326-spec.js

* `prefix:evnetName` 的事件仅仅在对应的 view 上抛出，然后冒泡到 chart

fix(event): fixed bug of #326

---

src/chart/chart.js
src/geom/shape/shape.js
test/bugs/issue-311-spec.js
test/bugs/issue-360-spec.js
test/bugs/issue-369-spec.js

* 修复 forceFit 时父容器隐藏宽度 为 0 的 bug，#369
* 修复 空数据时图例报错的问题，#311
* 修复 设置选中报错的问题， #360

Daily 0111

---

src/chart/controller/tooltip.js
src/component/tooltip/index.js
test/bugs/issue-368-spec.js
test/bugs/issue-371-spec.js

* 修复点图和线图一起是点的点击无法触发的问题 #371 
* 修复 tooltip:change 概念不统一的问题 #368 
closes #368 #371

Daily 0112

---

src/chart/view.js
src/facet/base.js
test/bugs/issue-361-spec.js

fix(facet): fixed bug of #361

---

demos/point-shapes.html
package.json
src/geom/shape/point.js

Feat point shapes

---

package.json
src/chart/view.js
src/geom/base.js
src/geom/mixin/active.js
src/geom/mixin/select.js
src/geom/shape/point.js
test/bugs/issue-291-spec.js
test/bugs/issue-325-spec.js
test/bugs/issue-361-spec.js
test/bugs/issue-400-spec.js

* 修复 view/geom 默认 visible 的问题， closes #291 
* 支持 active 配置项， closes #325 
```js
chart.point().active(true);
chart.point().active(true, {
animate: true,
style: {
radius: 10,
fill: 'red'
}
});
```
* 增加根据数据设置图形选中
```js
var pie = chart.intevalStack().position('sold').color('genre');
chart.render(0);
pie.setSelected(data[0]);
```

Daily 0117

---

src/chart/controller/legend.js
src/component/legend/base.js
src/component/legend/category.js
test/bugs/issue-424-spec.js

fix(legend): event is not triggered due to lacking of viewId

---

src/index.d.ts
test/types/g2-test.ts

does no source change
1. Add ts-test
2.fix d.ts bug

Add ts-test & fix d.ts bug

---

src/chart/controller/legend.js
src/chart/controller/tooltip.js
src/component/legend/continuous.js
src/scale/auto/util.js
src/scale/time-cat.js
src/util.js
test/bugs/issue-368-spec.js
test/bugs/issue-378-spec.js
test/bugs/issue-406-spec.js
test/bugs/issue-408-spec.js
test/bugs/issue-432-spec.js

* 修复 tooltip:change 更改 title 无效的问题， closes #280 
* 修复 动画时坐标轴文本乱飞的问题, closes #378

Daily 0129

---

src/component/legend/category.js

fix: html legend in ie9.

---

src/animate/index.js
src/chart/controller/event.js
src/geom/index.js
src/geom/mixin/split.js
src/geom/mixin/tooltip.js
src/geom/point.js
src/geom/shape/interval.js
test/bugs/issue-213-spec.js
test/bugs/issue-439-spec.js
test/bugs/issue-454-spec.js
test/unit/chart/chart-area-spec.js
test/unit/chart/chart-line-spec.js
test/unit/chart/chart-point-spec.js
test/unit/geom/shape/interval-spec.js
test/unit/scale/auto/time-spec.js

* add chart.pointStack(), closes #437

 fix(geom): add chart.pointStack(), #437

---

demos/line.html
src/geom/shape/line.js

feat(line): make lineDash configurable

---

src/chart/controller/event.js
test/bugs/issue-325-spec.js

chore(dev): remove console logs

---

demos/venn.html
package.json
src/geom/base.js
src/geom/heatmap.js
src/geom/index.js
src/geom/shape/index.js
src/geom/shape/venn.js
src/geom/venn.js

feat(geom): add Venn Geom

---

src/geom/mixin/select.js
test/bugs/issue-515-spec.js

* 停止动画报错、停止 clip 引起的动画，修复初始化动画时进行选中，无法恢复的bug ,closes(#515, #459)

fix(selected): fixed bug of #515

---

src/chart/view.js
test/bugs/issue-528-spec.js

* 时间字段为 y 轴的坐标轴的刻度会自动 min: 0 导致柱状图显示不正常

fix(scale): fixed bug of #528

---

demos/heatmap.html
src/geom/heatmap.js

fix(heatmap): heatmap cannot be drew when reflecting coord

---

src/chart/controller/legend.js
src/geom/label/geom-labels.js
src/theme/default.js
test/bugs/issue-378-spec.js
test/bugs/issue-439-spec.js
test/bugs/issue-454-spec.js
test/bugs/issue-472-spec.js
test/bugs/issue-534-spec.js
test/unit/chart/chart-padding-spec.js

* 饼图中档文本为空（null,undefined, '')，labelLine 不在显示。closes(#534)
* auto padding 时，图例跟坐标轴重合，发生在图例在左，双轴图表图例在右，图表翻转，图表在上的场景。

Daily 0315

---

demos/histogram-binning.html
package.json
src/component/tooltip/index.js
src/geom/mixin/tooltip.js
test/bugs/issue-557-spec.js

fix: fixed #557

---

demos/bar-stack-percent.html
src/chart/controller/legend.js
src/geom/shape/interval.js
test/bugs/issue-472-spec.js
test/unit/geom/shape/interval-spec.js

* 层叠柱状图仅仅上面加一条白边
* 修复不显示坐标轴是图例位置错误的问题

Daily 0408

---

package.json
src/geom/base.js
src/geom/shape/area.js
test/bugs/issue-573-spec.js

* 修复了geom-shape-getPath()中对isInCircle的判断
* 为了stack-area在修正之后能够正确显示，geom-base-getDrawCfg()中，增加了cfg.hasStack

fix(area):fix bug of #573

---

src/geom/label/geom-labels.js
test/bugs/issue-569-spec.js

修复了geom-->label-->geom-label中pyramid sharp edge部分的判定问题

fix(pyramid):fix bug of #569

---

demos/area-basic.html
src/geom/shape/area.js

fix(area): urgent fix of basic area plot

---

package.json
src/geom/heatmap.js

fix(heatmap): not drawn properly after resize (caused by ctx cache)

---

demos/line-time.html
src/scale/time.js
test/bugs/issue-607-spec.js

fix(scale): time scale init error (caused by invalid min and max)

---

src/chart/chart.js

fix(chart): fix downloadImage method in chart to fit IE 10+ and Firefox. close #617

---

demos/region-filter.html
src/chart/controller/guide.js
src/chart/view.js
src/component/guide/index.js
src/component/guide/region-filter.js

添加regionFilter guide: 辅助区域过滤，将图表中位于矩形选区中的图形元素提取出来，重新着色。

feat(guide):add regionFilter guide

---

src/chart/controller/tooltip.js
src/component/tooltip/index.js

fix(tooltip): removing duplicated items, Closes #637

---

src/chart/view.js
src/geom/base.js
test/bugs/issue-629-spec.js

fix(geom): undefined container in changeVisible. Closes #629

---

src/chart/controller/axis.js
src/component/axis/grid.js

* 标记0轴线
当y轴值域出现负值，0基线不在轴线上，在这种情况下，我们认为 0 轴线是一个重要的参考指标，需要特别标记出来，辅助用户解读
同时提供配置项关闭0轴线的highlight状态

feat(axis):hightlightable zero baseline

---

src/chart/controller/guide.js
src/chart/view.js
src/component/guide/text.js
test/bugs/issue-649-spec.js
test/unit/chart/chart-spec.js
test/unit/chart/controller/guide-spec.js

* 保证所有 guide 的顺序都在栅格上面
* 调整文本的优先级默认在上面 #646 
* 恢复 guide 事件的支持 #649

fix(guide): fixed events of guide, and text default at top

---

src/chart/controller/legend.js
src/component/legend/index.js
src/component/legend/tail.js
test/unit/component/legend/tail-spec.js

尾部跟随legend，目前适用于line chart和line-stack-area chart。
用法：
chart.legend( {
attachLast:true
});

feat(legend):tail-legend

---

demos/heatmap.html
package.json
src/component/guide/image.js

fix(guide): exception when draw with reflected coord

---

package.json
src/global.js

3.2.0-beta.4

---

src/attr/color-util.js
test/bugs/issue-291-spec.js
test/bugs/issue-325-spec.js
test/bugs/issue-649-spec.js
test/bugs/issue-678-spec.js

Fix rgba color parsing

---

package.json
src/index.d.ts
tsconfig.json
tslint.json

- Fixed type definition for `Chart` class - corrected constructor argument type and added `get()` method
- Added `npm tslint` command to validate and lint `src/index.d.ts`
- Added `tsconfig.json` and `tslint.json` with basic `tslint` rules and fixed all (~8) code style issues

Chart typescript definition fix

---

src/component/axis/base.js
src/theme/default.js

fix(axis):cat axis support timeCat data type

---

src/chart/view.js

fix(theme): Global theme is not working

---

src/geom/shape/line.js

fix: fix path of legend marker of line chart

---

src/geom/mixin/tooltip.js

目前定义 defs 时：
```
chart.source(dv, {     
value: {
type: 'linear',
formatter: (val: number): string => {         
// 这里只有一个val
return `${val}`;
},
},
});
```
仅能对所有的 value 进行统一的数据格式化。
而我的场景中，是需要对不同的 value 进行不同的格式化的，目前没有找到可以配置自定义格式化的方式，所以我改了部分 g2 以及 scale 的代码，以做到：
```
chart.source(dv, {     
value: {
type: 'linear',
formatter: (val: number, key: string): string => {         
// 使用 key 识别当前是哪个 value 以自定义格式化
return customFormat(val, key);
},
},
});
```
如有不对，麻烦指出~
https://github.com/antvis/scale/pull/3

feat(tooltip): support custom format

---

src/theme/default.js

https://github.com/antvis/g2/issues/769
火狐上存在错位问题

注释掉TOOLTIP_CONTAINER_CLASS默认样式中的whiteSpace: 'nowrap'

---

src/chart/chart.js
src/chart/controller/legend.js
src/chart/view.js
test/bugs/issue-708-spec.js

Closes #708 
`LegendController`内部逻辑**记录*选中* 的图例**修改为**记录*未选中* 的图例**
> 同步修改`LegendController`实例方法`addLegend`第四个参数`filteredValues`由*选中* 的图例数组修改为*未选中* 的图例数组

 fix(legend): 修复'图例隐藏后，新增数据不显示'的问题 #708

---

src/component/legend/category.js
test/bugs/issue-775-spec.js

fix(legend): mouseover on customized legend title does not throw

---

demos/area-basic.html
src/chart/controller/tooltip.js

Feat tooltip blocking

---

src/global.js
src/track.js

feat(track): add trackingInfo for product analysis

---

src/chart/controller/event.js
src/chart/controller/tooltip.js
test/bugs/issue-502-spec.js
test/unit/chart/chart-option-spec.js

* 修复 plotleave 触发时机的 bug
* 修复 有时候 tooltip 无法隐藏的问题
#502 #761

fix(tooltip, event):fix plotleave and tooltip hide bugs

---

src/component/guide/line.js
test/bugs/issue-553-spec.js

* 目前使用 shape._id 或者 group.get('viewId') 来识别 view/chart 太不容易维护很容易出问题，后期需要改掉，当前先修复掉 closes(#553)

fix(event): fixed bug of guide-line click

---

src/component/tooltip/index.js
test/bugs/issue-811-spec.js

* 修复tooltip 无法进入的问题，https://github.com/antvis/g2/issues/811

fix(tooltip): fixed tooltip bug of enterable feature

---

src/component/guide/base.js
test/unit/component/guide/line-spec.js

feat(guide): add start,end support

---

src/geom/shape/interval.js

fix(liquidfill): clip shape should not be added into group

---

src/component/label/labels.js
test/bugs/issue-838-spec.js
test/unit/component/label/labels-spec.js

Label rotation

---

package.json
src/chart/controller/legend.js
test/unit/chart/controller/legend-spec.js

修复legend定义field时，legend定位错误及尾部跟随legend失效问题

fix(legend):field defined legend position error

---

src/chart/view.js

fix(Global): G2.Global.animate setting is not working, Closes #856

---

demos/gauge-value0.html
src/component/guide/arc.js
test/unit/component/guide/arc-spec.js

fix(arc): when start and end is equal, it should not be a circle

---

src/geom/mixin/tooltip.js
test/bugs/issue-885-spec.js

fix(chart): getSnapRecords for points. Closes #885

---

src/chart/controller/guide.js
src/component/guide/region-filter.js
test/unit/component/guide/region-filter-spec.js

refactor: better guide.render().

---

demos/arc.html
demos/pie.html
demos/rectangle-binning.html
demos/world-map.html

canvas    —    **area-stack.html**
canvas reactive    —    **area-line-stack.html**
useHtml — **streamGraph**
useHtml flipPage reactive = true — **pie.html**
Size sizeType = ‘circle’   —   **size-legend.html**
Size sizeType = null  reactive = true.  —   **world-map.html**
Size slidable = false.   —   **arc.html**
Color slidable = true   —   **day-hour-heatmap.html**
Color slidable = false   —   **daily-temperatures-in-boston.html**
Color reactive = true   —   **rectangle-dining.html**
—   **tail-legend.html**

feat: legend demos

---

package.json
src/geom/label/geom-labels.js

fix(geom-labels): fix callback value type

---

demos/guide-line.html
demos/guide-region-filter.html
demos/guide-region.html
src/component/guide/region-filter.js
test/unit/component/guide/region-filter-spec.js

需要配合升级 component: https://github.com/antvis/component/pull/22

revert: remove polar coordinate support

---

src/geom/label/geom-labels.js
src/geom/label/pie-labels.js
test/bugs/pr-935-spec.js

Fix label offset

---

src/geom/label/geom-labels.js
src/geom/label/pie-labels.js

fix(pie-label): fix labelLine end point error

---

.travis.yml

tests: add Node.js 10

---

package.json
src/chart/controller/axis.js
src/chart/controller/tooltip.js
src/geom/shape/area.js
test/unit/chart/chart-spec.js
test/unit/chart/controller/axis-spec.js

Fix axis title

---

src/chart/controller/tooltip.js

fix(tooltip): should not merge viewTheme into default tooltip cfg again

---

src/theme/default.js
test/bugs/issue-472-spec.js
test/unit/chart/chart-padding-spec.js

fix(axis): set default label offset to 8px

---

demos/area-line-stack.html
src/geom/shape/area.js

fix(legend): marker for area should be a closed path

---

CHANGELOG.md
demos/bar.html
package.json
src/component/guide/region-filter.js
src/global.js
src/index.d.ts

Chore type define and history

---

package.json
src/chart/controller/legend.js
src/global.js
test/bugs/issue-957-spec.js

Fix legend issues

---

package.json
src/chart/controller/axis.js
src/geom/label/polar-labels.js
test/bugs/issue-974-spec.js
test/unit/chart/controller/axis-spec.js

feat(axis): customized axis title. Closes #974

---

demos/arc.html
demos/bar-stack.html
demos/pie.html
src/chart/controller/legend.js
src/geom/label/geom-labels.js
src/geom/label/pie-labels.js
src/geom/label/polar-labels.js
src/theme/default.js
test/bugs/pr-935-spec.js
test/unit/geom/label/geom-labels-spec.js
test/unit/geom/label/pie-labels-spec.js
test/unit/geom/label/polar-labels-spec.js

Fix label styles

---

src/index.d.ts
test/types/g2-test.ts

fix the error of typescript definition

fix(facet): fix facet type

---

package.json
src/chart/controller/legend.js
src/global.js

Fix hover legend

---

src/theme/default.js

之前手抖，把 rectStyle 写成了 reactStyle， 修复下。

fix reactStyle to rectStyle

---

src/geom/label/geom-labels.js
src/geom/label/polar-labels.js

- fix rotate
- add option `content`
- fix textStyle callback

Fix label issues

---

src/geom/shape/area.js
src/geom/shape/edge.js
src/geom/shape/interval.js
src/geom/shape/line.js
src/geom/shape/point.js
src/geom/shape/polygon.js
src/geom/shape/schema.js
src/geom/shape/venn.js
src/geom/shape/violin.js
src/geom/util/shape.js
test/bugs/issue-1027-spec.js

fix(shape): default shape color is incorrect, Closes #1027

---

package.json
src/geom/label/geom-labels.js
src/geom/label/polar-labels.js
test/bugs/issue-1031-spec.js

Fix labelline

---

demos/area-basic.html
demos/brush.html
src/chart/controller/tooltip.js
src/geom/area.js
src/geom/path.js
src/interaction/brush.js

Fix interaction and theme

---

src/index.d.ts

[type] add some type def in Global

---

demos/area-line-stack.html
demos/scatter.html
package.json
src/chart/chart.js
src/chart/controller/tooltip.js
src/geom/base.js

fix(tooltip): failed to trigger tooltip on geom labels, fix #1035

---

demos/treemap-tiles.html
package.json
src/geom/shape/area.js
src/geom/shape/interval.js
src/geom/shape/schema.js
src/geom/shape/violin.js
src/geom/util/shape.js
src/interaction/drag.js

Daily 20181116

---

package.json
src/chart/controller/legend.js

Daily 20181120

---

src/chart/controller/legend.js
test/bugs/issue-1057-spec.js

fix(legend): shape mapping should not generate legend, Closes #1057

---

demos/tag-cloud.html

chore(demo): cfg.color should have a higher piority, Closes #1060

---

src/chart/controller/tooltip.js
src/theme/dark.js

* 修复 tooltip crosshair 样式在 theme 中配置不生效问题
* 复原 dark theme 的 tooltip 样式

fix tooltip crosshair theme & tooltip dark theme

---

src/geom/util/shape.js

fix(shape): add fillOpacity correctly, Closes #1065

---

src/geom/shape/interval.js

fix https://github.com/antvis/g2/issues/1099

Fix bug that the error bar can't show

---

src/chart/controller/tooltip.js

Fix [#1029](https://github.com/antvis/g2/issues/1029)

fix(tooltip): 多 view 下 interval 的 tooltip 辅助线不显示

---

src/chart/controller/legend.js

fix:https://github.com/antvis/g2/issues/1119

fix:https://github.com/antvis/g2/issues/1119

---

src/interaction/scroll-bar.js

Closes https://github.com/antvis/g2/issues/1133

clearInteraction不能清除scrollBar的bug

---

src/geom/shape/violin.js
test/bugs/issue-1144-spec.js
test/bugs/issue-1177-spec.js

fix(violin): error when data is empty. Closes #1144

---

src/geom/shape/venn.js
src/geom/venn.js
test/bugs/issue-1144-spec.js
test/bugs/issue-1146-spec.js
test/bugs/pr-935-spec.js

feat(venn): venn geom label supports position adjusting

---

src/chart/controller/guide.js
test/unit/chart/controller/guide-spec.js

Fix guide bug

---

src/geom/label/polar-labels.js

Closes #1148

---

src/chart/controller/guide.js
src/chart/controller/legend.js
src/chart/util/bbox-of-back-plot.js
src/chart/view.js
src/geom/label/polar-labels.js
test/bugs/issue-1149-spec.js
test/bugs/issue-553-spec.js
test/unit/chart/controller/guide-spec.js

fix: when guide.html() is defined, legends is not in view. Closes #1149

---

src/chart/util/bbox-of-back-plot.js
test/bugs/issue-1188-spec.js

fix: auto padding blocks axis title, Closes #1188

---

src/geom/label/geom-labels.js
test/bugs/issue-1184-spec.js

fix(label): show label for heatmap, Closes #1184

---

src/interaction/zoom.js

Closes https://github.com/antvis/g2/issues/1194

线性缩放时，需要深拷贝scale配置

---

src/geom/heatmap.js

Closes https://github.com/antvis/g2/issues/1178

热力图销毁时需清除缓冲canvas内容

---

src/index.d.ts

 [types] improve TooltipConfig type definition

---

src/chart/controller/scale.js
test/bugs/issue-1208-spec.js

fix(scale): Scale config should be effective when data is null or data length is 0

---

src/chart/controller/legend.js

Closes https://github.com/antvis/g2/issues/997

兼容，legend实例attr中存在x与y而canvas形式中是通过group获取的兼容

---

package.json
src/geom/base.js
test/bugs/issue-1208-spec.js

之前合并的这个 PR： https://github.com/antvis/g2/pull/1215/files 会因为没有处理饼图的逻辑而导致报错，这个 PR 修复这个问题。

fix: pie chart throws when data is empty

---

src/chart/controller/event.js
test/bugs/issue-1234-spec.js

fix issue #1234

---

src/index.d.ts

- Change all comments to `jsDoc` style for VSCode integration
- Clean and unify types. e.g. `Array<number>` => `number[]`
- Specify some of `any` type

improve type declaration

---

package.json
test/bugs/issue-1221-spec.js

fix(tooltip): not throw at the first mousemove event. Closes #1221

---

src/geom/label/geom-labels.js
test/bugs/issue-1306-spec.js
test/bugs/pr-935-spec.js

fix: legend cannot filter labels. Closes #1306

---

demos/guide-region-realtime-data.html
src/component/legend/tail.js

fix: tail legend is not working when data is empty

---

package.json
src/chart/chart.js
src/chart/controller/axis.js
src/chart/util/bbox-of-back-plot.js
src/global.js
test/bugs/issue-1186-spec.js
test/bugs/issue-1188-spec.js
test/bugs/issue-439-spec.js

* 由于 axis 的 group 没有单独的 group，所以无法被 view 通过检测，同时 name 没有声明成 axis-label

feat(bug): fixed bug of #1186

---

src/animate/action.js

feat(animate): add line && area slideleft animation

---

.travis.yml
lerna.json
package.json

test(*): add travis

---

package.json
packages/component/src/annotation/html.ts

feat: annotatiom html 适配 HTMLElement 和 string两种输入

feat: annotatiom html 适配 HTMLElement 和 string两种输入

---

packages/component/src/tooltip/crosshair.ts
packages/g2/src/plot/controller/tooltip.ts
packages/g2/src/theme/default.ts

rect类型的tooltip crosshairs 丢失了，这里按照以前旧版本的component补上。

fix(tooltip): add missing rect type crosshairs

---

src/chart/view.js
test/bugs/issue-1264-spec.js

fix(filter): keep getFilteredValues same with getFilteredOutValues

---

.torch.compile.opts.js
__tests__/index.spec.ts
__tests__/unit/index-spec.ts
__tests__/unit/template-spec.ts
package.json

test(torch): use torch as unit test framework

---

packages/g2/package.json

fix: 补充没有save到package.json 中包

---

packages/component/src/legend/base.ts
packages/component/src/legend/category/canvas.ts
packages/component/src/legend/category/html.ts

去掉之前添加的getFlippedBBox，改为getBBox并在base中添加默认实现，在canvas中有flipPage的时候去重载

fix(legend): add getBBox public method to legend

---

packages/component/src/legend/category/canvas.ts

https://github.com/antvis/G2Plot/issues/53

fix(legend): canvas legend getHeight

---

__tests__/unit/geometry/element-spec.ts
__tests__/unit/geometry/geometry-spec.ts
__tests__/unit/geometry/shape-spec.ts
__tests__/unit/util/scale-spec.ts
__tests__/util/theme.ts
src/geometry/element.ts
src/geometry/geometry.ts
src/geometry/interface.ts
src/geometry/polygon/shape.ts
src/geometry/shape.ts
src/geometry/util/path.ts
src/interface.ts
src/util/scale.ts

Element 2.0

---

__tests__/unit/chart/view-spec.ts
__tests__/util/dom.ts
src/chart/controller/coordinate.ts
src/chart/controller/legend.ts
src/chart/interface.ts
src/chart/layout/index.ts
src/chart/view.ts
src/geometry/geometry.ts
src/index.ts

View geometry 基本联调

---

src/chart/view.ts
src/dependents.ts
src/geometry/geometry.ts
src/geometry/interface.ts
src/geometry/shape.ts
src/geometry/util/path.ts
tsconfig.json

feat: use coordinate.update(cfg) to update instance

---

package.json
src/chart/chart.js
src/chart/controller/tooltip.js
src/global.js
test/bugs/issue-tooltip-lock-spec.js

* 添加 lockTooltip 和 unlockTooltip ，用户可以手动锁定 tooltip

feat(tooltip): add lock tooltip

---

__tests__/unit/geometry/geometry-spec.ts
package.json
src/geometry/geometry.ts

fix: Element updates when data changed.

---

src/geom/base.js
src/geom/label/geom-labels.js
test/bugs/issue-476-spec.js

feat(bug): fixed bug #476

---

src/chart/util/bbox-of-back-plot.js
test/bugs/issue-1249-spec.js

fix(auto-padding): fixed #1249, when y axis alias length <= 2

---

src/geom/schema.js
test/bugs/issue-600-spec.js

feat(bug): fixed bug of #600

---

src/index.d.ts

- Close #1325.
| 🇺🇸 English | 🐞 Fix type definition of `legend` params |
| 🇨🇳 Chinese | 🐞 修复 `legend` 的参数类型定义。 |

fix(ts): legend

---

src/chart/controller/tooltip.js
test/bugs/issue-1248-spec.js

fix: when color field === x field, tooltip crosshair'bug

---

packages/g2/src/theme/default.ts

chore: remove repeated color.

---

src/index.d.ts

#1489
correct `AxisTile` as `AxisTitle`
| 🇺🇸 English |     correct `AxisTile` as `AxisTitle`      |
| 🇨🇳 Chinese |   将 `AxisTile` 更正为 `AxisTitle`      |

fix(ts): fix #1489

---

src/chart/controller/axis.js
test/bugs/issue-1213-spec.js

> **等 https://github.com/antvis/component/pull/68 合并并发包之后，这个 issue 和单测 就会 pass，这个 pr 仅仅补充单测。**
* fixed #1213 
* fixed #1494

fix(label): fix label dom leak, fixed #1213

---

src/geom/base.js
test/unit/geom/geom-spec.js

https://github.com/antvis/g2/issues/1082
fixed: #1082

fix: fix error of intervalSymmetric  when data is empty, fix #1082

---

packages/component/package.json
packages/g2/package.json

chore: update version

---

packages/g2/__tests__/unit/element/util/path-spec.js
packages/g2/src/animate/animate.ts
packages/g2/src/animate/util.ts
packages/g2/src/element/controller/size.ts
packages/g2/src/element/util/path.ts

Related https://github.com/antvis/coord/pull/5

fix: modify the coordinate property call method.

---

packages/component/src/annotation/base.ts

fix: update coord getWidth/getHeight

---

src/geom/mixin/active.js
src/geom/mixin/select.js
src/geom/mixin/zindex-util.js
test/bugs/issue-792-spec.js
test/bugs/issue-813-spec.js
test/bugs/issue-999-spec.js
test/unit/chart/controller/guide-spec.js
test/unit/component/guide/region-filter-spec.js

Daily 0926 2

---

src/geom/mixin/active.js
src/geom/mixin/select.js
src/geom/mixin/zindex-util.js
src/geom/schema.js
test/bugs/issue-600-spec.js
test/bugs/issue-792-spec.js
test/bugs/issue-999-spec.js

* fixed #999 ，由于 g 动画上的 animating 标记导致的问题
* fixed #792，active 属性和 select 属性存在覆盖问题

Daily 0926

---

__tests__/unit/chart/multi-view-spec.ts
__tests__/unit/chart/view/index-spec.ts
__tests__/util/delay.ts
src/chart/chart.ts
src/chart/view.ts
src/index.ts
src/interface.ts

feat(view): view.changeData API, update the geometries

---

package.json
src/global.js

feat(version): update to 3.5.8

---

src/chart/controller/tooltip.js
src/theme/default.js
test/bugs/default-tooltip-marker-spec.js
test/bugs/tooltip-unfollow-spec.js

更改 tooltipMarker 以及 tooltip 中的 item marker 的默认形状的成本太高，会影响线上的展示，所以默认主题还是以 circle 为准，如果有个性化需求，可以在主题中或者 chart.tooltip() 中自己配置
```js
// 主题中配置
tooltip: {
marker: (markerCfg, item) {
return {
...markerCfg,
};
}  
}
// chart.tooltip()
chart.tooltip({
marker: (markerCfg, item) {
return {
...markerCfg,
};
}  
});
```
关联 https://github.com/antvis/component/pulls，先发 component

Tooltip fix

---

packages/g2/__tests__/unit/element/shape/base-spec.js
packages/g2/__tests__/unit/plot/controller/annotation-spec.js

部分 Coordinate 接口为修改

---

package.json
src/constant.ts
src/geometry/geometry.ts
src/geometry/interface.ts
src/geometry/util/path.ts
src/geometry/util/shape-size.ts
src/util/coordinate.ts

更新 adjust 模块依赖以及 Geometry 模块的接口、函数定义改进

---

src/chart/controller/tooltip.js

fix: when mouse enter tooltip and leave, the tooltip should hide.

---

src/chart/view.ts
src/dependents.ts
src/geometry/element.ts
src/geometry/geometry.ts
src/geometry/interface.ts
src/geometry/interval/index.ts
src/geometry/interval/shape.ts
src/geometry/polygon/shape.ts
src/geometry/shape.ts
src/interface.ts
src/util/scale.ts
tests/unit/geometry/geometry-spec.ts
tests/unit/util/scale-spec.ts

关联 Issue https://github.com/antvis/g2/issues/1511

Geometry module code review

---

package.json
src/geometry/geometry.ts
src/geometry/interval/index.ts
src/geometry/util/path.ts
src/util/scale.ts
tests/unit/geometry/interval/index-spec.ts
tests/unit/geometry/util/path-spec.ts
tests/unit/geometry/util/shape-size-spec.ts
tests/util/dom.ts
tests/util/theme.ts

添加 Geometry 模块的测试用例以及一些 BUGFIX

---

package.json
src/chart/__components__/mock-component.ts
src/chart/chart.ts
src/chart/controller/coordinate.ts
src/chart/interface.ts
src/chart/layout/index.ts
src/chart/view.ts
src/component/index.ts
src/dependents.ts
src/geometry/element.ts
src/geometry/geometry.ts
src/geometry/interface.ts
src/util/bbox.ts
src/util/direction.ts
src/util/transform.ts
tests/unit/chart/chart-spec.ts
tests/unit/chart/multi-view-spec.ts
tests/unit/chart/view/index-spec.ts
tests/unit/geometry/element-spec.ts
tests/unit/geometry/geometry-spec.ts
tests/unit/geometry/interval/index-spec.ts
tests/unit/geometry/shape-spec.ts
tests/unit/geometry/util/shape-size-spec.ts
tests/unit/util/bbox-spec.ts
tests/unit/util/direction-spec.ts
tests/util/dom.ts

* 为了便于管理，对 G 以及相应的类型引用都在 dependents.ts 下引入
* 目前 g-canvas 还有一些问题，待解决后统一移除代码中的 FIXME
升级点：
1. 对于 G 元素的类型定义，使用 IXxxx，即 g-base 中的接口类型定义
2. new Canvas() 中使用 `container` 取代 `containerDOM`
3. Shape.isGroup 属性改为 Shape.isGroup() 方法，Shape.isShape 同
4. container.move() 方法移除

使用 @antv/g-canvas

---

package.json
src/global.js

publish 3.5.9-beta.1

---

src/chart/controller/legend.js
test/bugs/issue-472-spec.js
test/unit/chart/controller/legend-spec.js

https://github.com/antvis/g2/issues/1525
| 🇺🇸 English |    fix left legend not visible       |
| 🇨🇳 Chinese |    修复legend位于左侧不显示       |

修复legend左侧不显示

---

packages/component/__tests__/unit/axis/line-spec.js
packages/component/__tests__/unit/legend/category/html-spec.js
packages/component/__tests__/unit/tooltip/html-spec.js
packages/g2/__tests__/unit/element/edge-spec.js
packages/g2/__tests__/unit/plot/controller/legend-spec.js
packages/g2/src/global.ts

修复测试用例报错的问题: 先skip掉,避免影响其他PR，后续请修复所有skip的测试用例

fix(testcases): Skip failed testcases

---

packages/component/src/annotation/base.ts
packages/component/src/axis/base.ts
packages/component/src/base.ts
packages/component/src/interface.ts
packages/component/src/label/base.ts
packages/component/src/legend/base.ts
packages/component/src/tooltip/base.ts
packages/component/src/tooltip/canvas.ts
packages/component/src/tooltip/crosshair.ts
packages/component/src/tooltip/html.ts
packages/component/src/tooltip/interface.ts
packages/g2/src/plot/controller/tooltip.ts

| 🇺🇸 English |    use  generic typings to define to constructor params   |
| 🇨🇳 Chinese |   使用generic定义component参数类型，便于正确获取组件属性        |

feat(typings):  add generic params typings for components

---

packages/component/src/axis/base.ts
packages/component/src/axis/line.ts
tslint.json

autoHideLabel开启后现在只隐藏了axis label，需要在隐藏label的同时把对应的axis tick line隐藏掉

fix: hide axis tick line when hide axis label

---

package.json
src/global.js

feat(update): update verson

---

src/chart/controller/axis.ts
src/chart/controller/legend.ts
src/chart/interface.ts
src/chart/view.ts
tests/unit/chart/view/index-spec.ts

feat(view): enhance axis, legend API, fixed #1554

---

packages/component/src/axis/line.ts
packages/g2/src/element/base.ts

always set id for shape draw cfg

---

src/geometry/animate/action.ts
src/geometry/animate/util.ts
src/geometry/path.ts
src/geometry/shape/interval.ts
src/geometry/shape/line.ts
src/geometry/shape/util/get-path-points.ts
src/geometry/shape/util/split-points.ts
src/interface.ts
tests/unit/geometry/path-spec.ts
tests/unit/geometry/shape/interval-spec.ts
tests/unit/geometry/shape/line-spec.ts
tests/unit/geometry/shape/util/get-path-points-spec.ts

添加 line shape 的测试用例及一系列 BUGFIX

---

src/geometry/element/index.ts
tests/unit/geometry/element/index-spec.ts

shape 打标，支持 name: eventName 事件

---

src/chart/view.ts
src/facet/facet.ts
tests/unit/facet/rect-spec.ts

fixed https://github.com/antvis/g2/issues/1562

fix(view): view.getData return filtererData

---

src/chart/chart.ts
src/chart/controller/axis.ts
src/chart/controller/legend.ts
src/chart/event.ts
src/chart/index.ts
src/chart/interface.ts
src/chart/layout/index.ts
src/chart/view.ts
src/constant.ts
src/core.ts
src/dependents.ts
src/util/coordinate.ts
src/util/helper.ts
tests/unit/chart/chart-spec.ts
tests/unit/chart/event-spec.ts
tests/unit/chart/event/event-class-spec.ts
tests/unit/chart/event/event-spec.ts
tests/util/simulate.ts

说明：
- 事件命名改成 plot:eventName 风格，和组件、Geometry 保持一致
- 这个 pr 提交有点杂，plot event 核心逻辑在于 `doPlotEvent` 方法
plot 事件方案：https://www.yuque.com/antv/g2-docs/eodp8y#Pngkq

Feat plot events

---

package.json
src/chart/chart.ts
src/chart/interface.ts
src/constant.ts
src/interface.ts
src/util/dom.ts
tests/unit/chart/chart-auto-fit-spec.ts
tests/unit/chart/chart-spec.ts
tests/unit/chart/event/event-spec.ts
tests/unit/chart/multi-view-spec.ts
tests/unit/facet/rect-spec.ts
tests/unit/util/dom-spec.ts
tsconfig.json

fixed https://github.com/antvis/g2/issues/1585, The plan is similar with `g2plot`.

process chart autoFit props.

---

packages/component/docs/zh-cn/label.md
packages/component/src/interface.ts
packages/component/src/label/base.ts
packages/g2/__tests__/unit/element/controller/state-spec.js

Fix: 修复 label typings定义问题

---

src/geometry/element/index.ts
tests/unit/geometry/element/index-spec.ts

feat: support element event

---

package.json
src/chart/controller/axis.ts
src/chart/layout/index.ts
src/chart/view.ts
src/dependents.ts
src/theme/antv.ts
src/util/axis.ts
src/util/scale.ts
tests/unit/chart/chart-spec.ts
tests/unit/chart/view/index-spec.ts
tests/unit/component/axis-spec.ts
tests/unit/util/axis-spec.ts

调试 axis component

---

src/chart/event.ts
src/chart/view.ts
src/util/event.ts
tests/unit/chart/event/event-spec.ts
tests/unit/interaction/index-spec.ts
tests/unit/util/event-spec.ts

联调 Geometry 事件

---

src/theme/default.js
test/bugs/issue-472-spec.js

fix: reset <li> style

---

src/chart/controller/legend.ts
src/chart/interface.ts
src/chart/layout/index.ts
src/chart/view.ts
src/dependents.ts
src/theme/antv.ts
src/util/attr.ts
src/util/legend.ts
tests/unit/chart/chart-spec.ts
tests/unit/chart/view/index-spec.ts
tests/unit/component/category-legend-spec.ts
tests/unit/util/attr-spec.ts
tests/unit/util/padding-spec.ts

调试 category legend component

---

src/chart/chart.ts
src/chart/controller/axis.ts
src/chart/controller/legend.ts
src/chart/controller/tooltip.ts
src/chart/interface.ts
src/chart/view.ts
src/constant.ts
src/dependents.ts
src/geometry/base.ts
src/interaction/base.ts
src/interaction/index.ts
src/interaction/tooltip.ts
src/interface.ts
src/theme/antv.ts
src/util/dom.ts
src/util/scale.ts
src/util/tooltip.ts
tests/unit/chart/view/index-spec.ts
tests/unit/component/axis-line-spec.ts
tests/unit/interaction/index-spec.ts
tests/unit/util/tooltip-spec.ts

Tooltip 组件接入以及对应的交互行为

---

src/chart/controller/tooltip.ts
src/theme/antv.ts

Fix tooltip

---

src/chart/controller/axis.ts
src/chart/controller/tooltip.ts
src/chart/interface.ts
src/chart/layout/index.ts
src/chart/view.ts
src/constant.ts
src/dependents.ts
src/theme/antv.ts
src/util/grid.ts
tests/unit/chart/view/index-spec.ts
tests/unit/util/grid-spec.ts

Feat axis grid

---

src/chart/controller/base.ts
src/chart/controller/legend.ts
tests/unit/chart/chart-spec.ts

Fix controller container

---

src/geometry/shape/polygon.ts
src/theme/antv.ts
tests/unit/geometry/polygon-spec.ts
tests/unit/geometry/shape/polygon-spec.ts

补充 polygon shape 以及添加相应的测试用例

---

gatsby-browser.js
package.json

chore: remove unnecessary insert-css

---

site/locale.json
site/pages/index.zh.tsx
src/component/plot.js
src/geom/label/geom-labels.js
src/geom/label/interval-labels.js
src/geom/label/pie-labels.js
src/geom/label/polar-labels.js
src/interaction/component/range.js

修复 Cannot assign to read only property 'constructor' of object '#<t>' 报错问题

---

src/chart/view.ts
src/geometry/line.ts
src/geometry/path.ts
src/index.ts

支持 chart.interval() api 的类型检查。
Related #1575

View module augment

---

packages/component/package.json
packages/component/src/tooltip/crosshair.ts

fix: rect crosshair should be under the shapes

---

.npmignore
README.md
README.zh-CN.md
site/pages/index.zh.tsx

Site review

---

packages/g2/src/theme/default.ts

解决 g2plot 上，tooltip 项目样式不正确的问题。

Fix add tooltip css reset

---

site/pages/index.zh.tsx

chore(site): update homepage icon

---

src/geometry/element/index.ts
src/interaction/active-region.ts
src/interaction/active.ts
src/interaction/tooltip.ts

chore: remove comment

---

src/chart/controller/legend.ts
src/chart/layout/index.ts
src/dependents.ts
src/theme/antv.ts
tests/unit/chart/view/index-spec.ts
tests/unit/component/legend-continuous-spec.ts
tests/unit/interaction/index-spec.ts

continuous legend component

---

site/pages/index.zh.tsx

fix: fix homepage link 404

---

src/geometry/animate/action.ts
src/geometry/animate/util.ts
src/geometry/area.ts
src/geometry/base.ts
src/geometry/element/index.ts
src/geometry/interface.ts
src/geometry/shape/base.ts
src/interface.ts

chore: add comments

---

src/geometry/base.ts
src/geometry/path.ts
src/theme/antv.ts
tests/unit/geometry/shape/area-spec.ts
tests/unit/geometry/shape/interval-spec.ts
tests/unit/geometry/shape/line-spec.ts
tests/unit/geometry/shape/point-spec.ts
tests/unit/geometry/shape/polygon-spec.ts

Adjust theme

---

site/pages/index.zh.tsx

fix: add international prefix

---

packages/g2/src/element/controller/label/components/pie.ts

feat(pie-label): 修改饼图label连接线样式

---

src/interaction/brush.js
test/bugs/issue-1405-spec.js

- [*] Bug fix
1.  brush startPonit; #1405 
2. forceFit 后，inplot：true情况下，新增的plotRange没有更新；
3. 如果brush鼠标在图表之外mouseup，再回到图表中，操作异常。

fix: brush startPonit; forcefie 新选区; 鼠标移出再回来;

---

examples/column/stack/demo/meta.json

chore(site): update screenshot

---

packages/component/src/axis/base.ts

fix: gridLines should be under axisLines

---

docs/api/chart.en.md
docs/api/chart.zh.md

docs: update api docs. Closed #978

---

examples/other/other/demo/line-realtime.js

chore(site): fix mask format. Closed #1597

---

src/index.d.ts

fix: 修复下legend position的类型定义

---

CHANGELOG.md
package.json
src/global.js

release 3.5.10

---

src/chart/chart.ts
src/chart/controller/axis.ts
src/chart/controller/base.ts
src/chart/controller/coordinate.ts
src/chart/controller/legend.ts
src/chart/event.ts
src/chart/view.ts
tests/unit/chart/view/index-spec.ts

Add comments

---

.npmignore
CHANGELOG.md
package.json
src/global.js

chore: update .npmignore

---

site/locale.json
site/pages/index.zh.tsx

Fix homepage

---

site/locale.json
site/pages/index.zh.tsx

chore(site): update homepage

---

site/pages/index.less
site/pages/index.zh.tsx

chore(site): adjust homepage thumbnail style

---

site/locale.json
site/pages/index.zh.tsx

chore(site): update title

---

src/index.d.ts

fix: fix index.d.ts legend layout definition

---

package.json

chore: upgrade gatsby-theme-antv version

---

packages/component/__tests__/unit/tooltip/html-spec.js
packages/component/src/tooltip/html.ts

fix: 同步开源3.5版本上的PR#54到3.6分支，修复Tooltip在边缘位置错误

---

src/chart/controller/annotation.ts
src/chart/controller/axis.ts
src/chart/controller/base.ts
src/chart/controller/legend.ts
src/chart/controller/tooltip.ts
src/chart/view.ts
src/constant.ts
src/dependents.ts
src/theme/antv.ts
tests/unit/chart/controller/tooltip-spec.ts
tests/unit/component/annotation-spec.ts

add annotation component

---

packages/component/package.json
packages/g2/package.json
packages/g2/src/global.ts

chore: 3.6分支3.6.0-beta.6版本

---

src/index.ts
tests/unit/chart/chart-auto-fit-spec.ts
tests/unit/chart/chart-spec.ts
tests/unit/chart/controller/tooltip-spec.ts
tests/unit/chart/event/event-spec.ts
tests/unit/chart/multi-view-spec.ts
tests/unit/chart/view/index-spec.ts
tests/unit/component/axis-circle-spec.ts
tests/unit/component/axis-line-spec.ts
tests/unit/component/legend-category-spec.ts
tests/unit/component/legend-continuous-spec.ts
tests/unit/facet/rect-spec.ts
tests/unit/interaction/index-spec.ts

chore: remove ts-ignore

---

src/index.d.ts

The [setSelected](https://github.com/antvis/g2/blob/master/src/geom/mixin/select.js#L174) and [clearSelected](https://github.com/antvis/g2/blob/master/src/geom/mixin/select.js#L157) are available via code and under some circumstances they're useful, but both are missing in the typescript definition.

chore: add setSelected and clearSelected

---

site/locale.json
site/pages/index.less
site/pages/index.zh.tsx

感觉没有什么必要... 但是都已经提了，就算了吧... 跑起来也好看点...

chore: site homepage

---

examples/line/double/demo/curved.js
examples/line/double/demo/dash.js
examples/line/double/demo/meta.json
examples/line/double/demo/rain-and-flow.js
examples/line/multiple/demo/kernel-smooth-regression-1.js
examples/line/multiple/demo/kernel-smooth-regression-2.js
examples/line/step/demo/step-series.js
examples/line/step/demo/step.js
gatsby-browser.js
package.json
src/chart/chart.ts
src/chart/controller/legend.ts
src/chart/view.ts
src/theme/antv.ts
src/util/dom.ts
tests/unit/chart/chart-spec.ts
tests/unit/chart/view/index-spec.ts
tests/unit/component/axis-line-spec.ts
tests/unit/util/theme-spec.ts

- demo
- bugfix https://github.com/antvis/g2/issues/1715
- feat

docs: demo line & bugfix

---

.commitlintrc.js
package.json

feat(changelog): add commit-msg and changelog generator

---

docs/support/upgrade.zh.md
examples/line/basic/demo/base.js
examples/line/double/demo/curved.js
examples/line/double/demo/dash.js
examples/line/double/demo/rain-and-flow.js
examples/line/multiple/demo/kernel-smooth-regression-1.js
src/theme/antv.ts
tests/unit/chart/view/index-spec.ts
tests/unit/component/annotation-spec.ts
tests/unit/component/legend-continuous-spec.ts
tests/unit/util/tooltip-spec.ts

Fix hustcc demos

---

docs/api/chart.en.md
docs/api/chart.zh.md

docs: 纠正 API 文档

---

examples/bar/basic/demo/basic.js
examples/bar/basic/demo/radial-bar.js
examples/bar/basic/demo/radial-line.js
examples/bar/basic/demo/ranged.js
examples/bar/basic/demo/time-bar.js
src/chart/controller/annotation.ts
src/chart/controller/axis.ts
src/chart/layout/index.ts
src/util/axis.ts
src/util/direction.ts
tests/unit/component/annotation-spec.ts
tests/unit/util/axis-spec.ts
tests/unit/util/direction-spec.ts

chore: bar demo & bugfix

---

examples/gauge/gauge/demo/basic.js
examples/gauge/gauge/demo/color.js
examples/gauge/gauge/demo/text.js
examples/gauge/gauge/demo/tick.js
examples/pie/rose/demo/color-rose.js
examples/pie/rose/demo/donut-rose.js
src/chart/controller/annotation.ts
src/util/axis.ts

目前仪表盘的 demo 的主要问题是 `chart.annotation().arc()` 的配置属性确认。
另外极坐标指定 startAngle 和 endAngle 不生效的问题应该解决了，因为没有将这两个参数传给 circle 类型的坐标轴~

添加仪表盘 demo && 一些 BUGFix

---

examples/column/basic/demo/marked.js
examples/column/basic/demo/waterfall.js
examples/column/stack/demo/rounded-stacked.js
examples/column/stack/demo/rounded.js

fix(register-shape): fix demo usage of registerShape API

---

src/util/legend.ts
tests/unit/util/legend-spec.ts

fix(legend): fix legend layout

---

examples/bar/dodge/demo/bar5.js
examples/gallery/bar/demo/bar3.js
examples/gallery/column/demo/column11.js
examples/gauge/gauge/demo/basic.js
examples/gauge/gauge/demo/color.js
examples/gauge/gauge/demo/text.js
src/chart/component/annotation.ts
tests/unit/component/annotation-spec.ts

Closed #1703 
chart.annotation().arc() 配置项如下：
```ts
chart.annotation().arc({
start,
end,
style,
top,
});
```
只会在极坐标下生效，同时 start 和 end 的 y 值需要相同。

Issue 1703

---

src/geometry/base.ts
tests/bugs/1746-spec.ts

fix(coordinate): shapeFactory cache cause coordinate update is invalid

---

src/util/bbox.ts
src/util/legend.ts
tests/unit/util/bbox-spec.ts
tests/unit/util/legend-spec.ts

我傻逼了，本地有一个提交没有 push 上来。囧~ fixed #1760

fix(layout): add layout for legend 12 directions

---

src/geometry/element/index.ts
tests/unit/geometry/element/index-spec.ts

feat: element 添加 getBBox() 方法，返回整体的包围盒

---

src/base.ts
src/chart/chart.ts
src/chart/component/base.ts
src/chart/component/tooltip.ts
src/chart/interface.ts
src/chart/view.ts
src/dependents.ts
src/geometry/base.ts
src/geometry/element/index.ts
tests/unit/chart/chart-spec.ts
tests/unit/chart/component/custom-title-spec.ts
tests/unit/chart/view/index-spec.ts
tests/unit/geometry/base-spec.ts
tests/unit/geometry/element/index-spec.ts

related #1763 
```ts
visible: false,
});
chart.show();
chart.hide();
const view = chart.createView({
visible: false,
});
view.show();
view.hide();
const interval = view.interval({
visible: false,
});
interval.show();
interval.hide();
chart.on('element:show', e => {
e.target.show();
});
```

为元素添加 show()、hide() 以及 visible 属性

---

src/chart/component/axis.ts
tests/unit/component/axis-circle-spec.ts

Fixed https://github.com/antvis/G2/issues/1715#issuecomment-564902036

fix: 修复极坐标下圆弧坐标轴文本首尾重叠的问题

---

packages/component/docs/zh-cn/legend.md
packages/component/src/legend/category/base.ts
packages/g2/src/theme/default.ts

antvis/G2Plot#372 同样画布下 legend 在上和在下表现不一致

fix(legend):  同样画布下 legend 在上和在下表现不一致

---

src/chart/component/tooltip.ts
tests/unit/chart/component/tooltip-spec.ts
tests/unit/interaction/action/active-region-spec.ts

https://github.com/antvis/G2/issues/1715#issuecomment-559373850

修复 tooltip 数据重复的问题

---

package.json
src/chart/chart.ts
src/chart/component/axis.ts
src/chart/component/legend.ts
src/chart/view.ts
src/theme/antv.ts
tests/unit/chart/component/axis-spec.ts
tests/unit/chart/component/legend-spec.ts
tests/unit/chart/event/event-spec.ts
tests/unit/chart/view/index-spec.ts
tests/unit/component/annotation-spec.ts
tests/unit/interaction/action/tooltip-spec.ts

fix(legend): fix component(legend, axis) clip bug

---

src/geometry/label/base.ts
tests/unit/geometry/label/pie-spec.ts

fix: 当 label 的 offset 小于等于 0 时，关闭 labelLine

---

packages/g2/package.json
packages/g2/src/global.ts

feat: publish-3.6.0-beta.7

---

src/chart/interface.ts
src/chart/view.ts
src/geometry/base.ts
src/geometry/interval.ts
src/geometry/label/base.ts
tests/unit/chart/view/index-spec.ts
tests/unit/geometry/area-spec.ts
tests/unit/geometry/base-spec.ts
tests/unit/geometry/interval-spec.ts
tests/unit/geometry/label/base-spec.ts
tests/unit/geometry/label/interval-spec.ts
tests/unit/geometry/label/labels-spec.ts
tests/unit/geometry/label/pie-spec.ts
tests/unit/geometry/label/polar-spec.ts
tests/unit/geometry/line-spec.ts
tests/unit/geometry/path-spec.ts
tests/unit/geometry/point-spec.ts
tests/unit/geometry/polygon-spec.ts
tests/unit/geometry/schema-spec.ts
tests/unit/geometry/util/shape-size-spec.ts
tests/util/scale.ts

1. `getScaleFields()` 方法获取 geometry 需要创建的 scale
2. 在 view 层创建 scales，然后传入 geometry: `geometry.scales = scales`
3. 更新的时候要注意，因为需要保持 scales 的引用，所以需要对 geometry.scales  进行同步操作
4. geometry 相关的测试用例都已经改了跑过了

Refactor geometry scales

---

src/chart/interface.ts
src/chart/view.ts
src/geometry/base.ts
src/geometry/interval.ts
src/geometry/label/base.ts
tests/unit/chart/view/index-spec.ts
tests/unit/geometry/area-spec.ts
tests/unit/geometry/base-spec.ts
tests/unit/geometry/interval-spec.ts
tests/unit/geometry/label/base-spec.ts
tests/unit/geometry/label/interval-spec.ts
tests/unit/geometry/label/labels-spec.ts
tests/unit/geometry/label/pie-spec.ts
tests/unit/geometry/label/polar-spec.ts
tests/unit/geometry/line-spec.ts
tests/unit/geometry/path-spec.ts
tests/unit/geometry/point-spec.ts
tests/unit/geometry/polygon-spec.ts
tests/unit/geometry/schema-spec.ts
tests/unit/geometry/util/shape-size-spec.ts
tests/unit/util/tooltip-spec.ts
tests/util/scale.ts

fix some bugs

---

src/chart/view.ts
src/geometry/base.ts
src/geometry/element/index.ts

修复 show() hide() 不生效的问题

---

packages/g2/__tests__/unit/element/base-spec.js
packages/g2/__tests__/unit/element/controller/state-spec.js
packages/g2/src/element/controller/label/index.ts
packages/g2/src/plot/view.ts

fix(label): move label to foregroundGroup

---

package.json
src/chart/controller/legend.ts
src/constant.ts
src/util/legend.ts
tests/unit/component/legend-category-spec.ts

feat: 分类图例支持翻页

---

packages/component/src/axis/base.ts
packages/component/src/axis/line.ts

[3.6.x]fix: auto rotate修复

---

packages/g2/package.json

build: upgrade version

---

packages/component/src/axis/line.ts

fix: add offset when auto rotate label

---

packages/component/package.json
packages/g2/package.json

buid(version): update version

---

packages/component/package.json
packages/component/src/axis/base.ts
packages/component/src/axis/line.ts
packages/g2/package.json

[3.6.x]feat: support axis formatter

---

src/chart/controller/annotation.ts
src/chart/controller/axis.ts
src/chart/controller/legend.ts
src/util/helper.ts
tests/unit/chart/controller/axis-update-spec.ts
tests/unit/util/helper-spec.ts

Feat axis update

---

examples/interaction/interaction/demo/continue-legend-filter.js
examples/interaction/interaction/demo/meta.json
package.json
src/chart/view.ts
src/dependents.ts
src/interaction/action/component/list-highlight.ts
src/interaction/action/component/list-state.ts
src/interaction/action/cursor.ts
src/interaction/action/data-filter.ts
src/interaction/action/element/filter.ts
src/interaction/action/element/highlight.ts
src/interaction/action/element/range-state.ts
src/interaction/action/element/single-state.ts
src/interaction/action/element/state.ts
src/interaction/action/index.ts
src/interaction/action/mask/base.ts
src/interaction/action/mask/circle.ts
src/interaction/action/mask/path.ts
src/interaction/action/mask/rect.ts
src/interaction/action/mask/smooth-path.ts
src/interaction/action/util.ts
src/interaction/index.ts
tests/unit/chart/event/event-class-spec.ts
tests/unit/interaction/action/cursor-spec.ts
tests/unit/interaction/action/data-fitler-spec.ts
tests/unit/interaction/action/mask-spec.ts
tests/unit/interaction/legend-filter-spec.ts

Mask action

---

packages/component/package.json
packages/component/src/axis/line.ts
packages/g2/package.json

[3.6.x]feat: 支持自定义多角度的axis label autoRotate

---

packages/component/package.json
packages/component/src/axis/line.ts
packages/g2/package.json

fix: auto rotate get labels fix

---

gatsby-config.js
package.json

chore: 网站 demo 支持 html 代码片段

---

gatsby-config.js

chore: fix html code snippt unwork

---

examples/column/histogram/demo/histogram.ts
tsconfig.json
typings.d.ts

修复演示 ts 不生效的问题。
现在 examples 里有大量 ts 错误，@simaQ 自行修一下。

fix: TypeScript issue

---

examples/gallery/index.en.md
examples/gallery/index.zh.md
examples/gallery/line/index.en.md
examples/gallery/line/index.zh.md
gatsby-config.js
package.json
site/pages/index.zh.tsx

| 🇺🇸 English |      none     |
| 🇨🇳 Chinese |    none       |

docs: fix gallery page

---

examples/gallery/index.en.md
examples/gallery/index.zh.md
gatsby-config.js

修复 https://github.com/antvis/gatsby-theme-antv/issues/89

docs: fix examples url 404

---

examples/interaction/interaction/demo/list-active.ts
package.json
src/interaction/action/register.ts
src/interaction/action/util.ts
src/interaction/context.ts
src/interaction/grammar-interaction.ts
src/interaction/index.ts
src/interface.ts
tests/unit/interaction/interaction-spec.ts
tsconfig.json

Refactor actions

---

src/chart/controller/axis.ts
tests/bugs/1823-spec.ts
tests/unit/chart/controller/axis-update-spec.ts

Fix polar grid

---

src/chart/view.ts
src/constant.ts
tests/unit/chart/event/event-spec.ts

```ts
export enum PLOT_EVENTS {
// mouse 事件
MOUSE_ENTER = 'plot:mouseenter',
MOUSE_DOWN = 'plot:mousedown',
MOUSE_MOVE = 'plot:mousemove',
MOUSE_UP = 'plot:mouseup',
MOUSE_LEAVE = 'plot:mouseleave',
// 移动端事件
TOUCH_START = 'plot:touchstart',
TOUCH_MOVE = 'plot:touchmove',
TOUCH_END = 'plot:touchend',
TOUCH_CANCEL = 'plot:touchcancel',
// click 事件
CLICK = 'plot:click',
}
```
rel issue: https://github.com/antvis/g/issues/336

Feat plot event

---

src/chart/view.ts
src/interaction/context.ts
src/util/scale.ts
tests/unit/chart/view/sync-scale-spec.ts
tests/util/data.ts

feat(sync-scale): sync min, max for linear scale

---

src/chart/view.ts
tests/unit/chart/event/event-spec.ts

Fix plot event mouseleave

---

examples/pie/rose/demo/rose-ranged.ts
src/chart/controller/axis.ts
src/chart/interface.ts
src/theme/antv.ts
src/util/grid.ts
tests/unit/animate/index-spec.ts

Fix polar grid type circle

---

src/chart/controller/legend.ts
src/chart/interface.ts
src/theme/antv.ts
tests/bugs/1823-spec.ts
tests/unit/chart/controller/legend-spec.ts

feat: legend 接口添加 reversed 属性

---

src/chart/controller/axis.ts
tests/unit/chart/controller/axis-update-spec.ts

fix(axis-title): fix axis title is undefined when option  with no title

---

src/chart/controller/axis.ts

fix(circle-grid): fix circle grid style is wrong

---

docs/tutorial/interaction.md
examples/interaction/interaction/demo/element-brush.ts
examples/interaction/interaction/demo/meta.json
examples/interaction/interaction/demo/pie-selected.ts
package.json
src/index.ts
src/interaction/action/base.ts
src/interaction/action/data/filter.ts
src/interaction/action/data/range-filter.ts
src/interaction/action/element/pie-selected.ts
src/interaction/action/index.ts
src/interaction/context.ts
src/interaction/grammar-interaction.ts
src/interaction/index.ts
src/interface.ts
src/util/transform.ts
tests/unit/interaction/action/data-fitler-spec.ts
tests/unit/interaction/action/highlight-spec.ts
tests/unit/interaction/action/range-filter-spec.ts
tests/unit/interaction/action/selected-spec.ts
tests/unit/interaction/element-spec.ts
tests/unit/interaction/interaction-spec.ts
tests/util/dom.ts

Brush and doc

---

src/chart/controller/axis.ts
src/chart/layout/index.ts
src/util/direction.ts
tests/unit/util/direction-spec.ts

fix(axis): 解决 axis 渲染出来有两个的问题

---

examples/box/box/demo/one-dim.ts
examples/box/box/demo/radial-box.ts
examples/box/box/demo/with-error.ts
examples/component/component/demo/label-map.ts
examples/component/component/demo/label-scatter.ts
examples/component/component/demo/label-treemap.ts
examples/component/component/demo/legend-size.ts
examples/gallery/area/demo/area7.ts
examples/pie/basic/demo/pie-size.ts
src/animate/animation/zoom.ts
src/geometry/interface.ts
src/geometry/label/labels.ts
src/geometry/shape/point.ts
src/geometry/shape/schema.ts
src/util/adjust-labels.ts
tests/unit/geometry/shape/point-spec.ts
tests/unit/geometry/shape/schema-spec.ts
tests/unit/schema-spec.ts

Fixed 
1. https://github.com/antvis/G2/issues/1715#issuecomment-569168283
2. https://github.com/antvis/G2/issues/1715#issuecomment-569168251
3. https://github.com/antvis/G2/issues/1715#issuecomment-568960629

2019-12-30 Kill bugs #1715

---

src/chart/util/scale-pool.ts
src/chart/view.ts
src/interface.ts
src/util/scale.ts
tests/unit/chart/chart-spec.ts
tests/unit/chart/view/scale-sync/multi-view-sync-scale-spec.ts
tests/unit/chart/view/scale-sync/simple-sync-scale-spec.ts
tests/unit/chart/view/sync-scale-spec.ts

design: https://www.yuque.com/antv/g2-docs/grwnr6

feat sync scale

---

examples/interaction/interaction/demo/drag-move.ts
examples/interaction/interaction/demo/meta.json
examples/interaction/interaction/demo/zoom.ts
package.json
src/interaction/action/base.ts
src/interaction/action/data/range-filter.ts
src/interaction/action/index.ts
src/interaction/action/register.ts
src/interaction/action/view/drag.ts
src/interaction/action/view/move.ts
src/interaction/action/view/scale-transform.ts
src/interaction/action/view/scale-translate.ts
src/interaction/action/view/scale-zoom.ts
src/interface.ts
tests/unit/interaction/action/view-scale-spec.ts
tests/unit/interaction/action/view-spec.ts
tests/unit/interaction/element-spec.ts

* 添加 View 的拖拽、移动，Scale 的平移、缩放 Action

feat(interaction): add view interaction

---

.gitignore
bin/typedoc-theme/helpers/member-title.js
bin/typedoc-theme/helpers/relative-url.js
bin/typedoc-theme/layouts/default.hbs
bin/typedoc-theme/partials/index.hbs
bin/typedoc-theme/partials/member.indexSignatures.hbs
bin/typedoc-theme/partials/reflection.hbs
bin/typedoc-theme/templates/index.hbs
bin/typedoc-theme/templates/reflection.hbs
bin/typedoc-theme/theme.js
gatsby-config.js
src/chart/view.ts
src/index.ts
tsconfig.json

https://www.yuque.com/antv/g2-docs/cchwwx
在以上基础上，通过自定义主题将 API 文档与目前的网站方案打通。
后续还需要完善下注释，这个下个 PR 提交。

4.0 API 自动化方案及 API 文档

---

src/theme/antv.ts
tests/unit/chart/controller/axis-spec.ts

https://github.com/antvis/G2/issues/1715#issuecomment-570103939

fix: 修复坐标轴网格线 grid 动画未生效的问题

---

docs/api/shape.en.md
docs/api/shape.zh.md
docs/api/slider.en.md
docs/api/slider.zh.md
docs/manual/tutorial/legend.en.md
docs/manual/tutorial/legend.zh.md

chore: 修复错误的代码标识

---

examples/interaction/interaction/demo/drag-move.ts
src/chart/event.ts
src/interaction/action/index.ts
src/interaction/action/view/button.ts
src/interaction/context.ts
src/interaction/index.ts
src/interface.ts
tests/unit/interaction/action/button-spec.ts
tests/unit/interaction/element-spec.ts
tests/unit/interaction/interaction-spec.ts

* 在 view 上添加 button，默认添加 reset-button 的 action

feat(action): add interaction

---

examples/area/range/demo/range.ts
examples/gallery/area/demo/area7.ts
examples/heatmap/heatmap/demo/hexagon.ts
examples/heatmap/heatmap/demo/hot-rect.ts
examples/heatmap/heatmap/demo/rectangle.ts
package.json
src/chart/interface.ts
src/chart/layout/auto.ts
src/chart/layout/index.ts
src/chart/layout/padding-cal.ts
src/chart/view.ts
src/interface.ts
src/util/padding.ts
tests/unit/chart/chart-spec.ts
tests/unit/chart/controller/axis-spec.ts
tests/unit/chart/event/event-spec.ts
tests/unit/chart/layout/padding-cal-spec.ts
tests/unit/chart/multi-view-spec.ts
tests/unit/chart/view/index-spec.ts
tests/unit/component/annotation-spec.ts
tests/unit/facet/rect-spec.ts
tests/unit/geometry/label/label-update-spec.ts

design: https://www.yuque.com/antv/g2-docs/zkrwpg
ref #1715  预计 2020-01-08 之前完成。

refactor(padding): refactor padding as geometry's padding

---

examples/component/component/demo/legend-size.ts
examples/gallery/area/demo/area7.ts
examples/gallery/line/demo/line2.ts
examples/line/multiple/demo/kernel-smooth-regression-2.ts
examples/relation/relation/demo/arc-polar.ts
examples/relation/relation/demo/arc.ts
examples/relation/relation/demo/chord.ts
examples/relation/relation/demo/radial-dendrogram.ts
examples/relation/relation/demo/radial-tidy-tree.ts
examples/relation/relation/demo/sankey.ts
src/animate/index.ts
src/geometry/edge.ts
src/geometry/shape/base.ts
src/geometry/shape/edge.ts
src/geometry/shape/point.ts
src/index.ts
src/interface.ts
src/theme/antv.ts
tests/unit/geometry/edge-spec.ts
tests/unit/geometry/shape/base-spec.ts
tests/unit/geometry/shape/edge-spec.ts
tests/unit/geometry/shape/point-spec.ts
tests/unit/interaction/action/button-spec.ts

Related https://github.com/antvis/G2/projects/2#card-31062639
另外，demo 里有一个同 sync scale 相关的 bug，@hustcc 康康~
* http://localhost:8000/zh/examples/relation/relation#sankey
* http://localhost:8000/zh/examples/relation/relation#chord

Feat geometry edge

---

examples/gallery/area/demo/area7.ts
src/chart/view.ts
tests/unit/chart/multi-view-spec.ts

feat(padding): sub view padding extends parent view padding

---

src/geometry/area.ts
src/geometry/base.ts
src/index.ts
tests/unit/geometry/area-spec.ts
tests/unit/geometry/line-spec.ts

feat: area Geometry 支持 startOnZero 属性

---

src/geometry/base.ts
src/geometry/util/group-data.ts
tests/unit/geometry/base-spec.ts
tests/unit/geometry/util/group-data-spec.ts

举个🌰：
```ts
const data = [
{ country: 'Asia', year: '1750', value: 502 },
{ country: 'Asia', year: '1800', value: 635 },
{ country: 'Asia', year: '1850', value: 809 },
{ country: 'Asia', year: '1900', value: 5268 },
{ country: 'Asia', year: '1950', value: 4400 },
{ country: 'Asia', year: '1999', value: 3634 },
{ country: 'Asia', year: '2050', value: 947 },
{ country: 'Africa', year: '1750', value: 106 },
{ country: 'Africa', year: '1800', value: 107 },
{ country: 'Africa', year: '1850', value: 111 },
{ country: 'Africa', year: '1900', value: 1766 },
{ country: 'Africa', year: '1950', value: 221 },
{ country: 'Africa', year: '1999', value: 767 },
{ country: 'Africa', year: '2050', value: 133 },
{ country: 'Europe', year: '1750', value: 163 },
{ country: …
```

feat: 当用户通过 scale 定义 values 后，geometry 也需要按照 values 对数据进行分组

---

packages/component/package.json
packages/component/src/legend/continuous/color.ts
packages/g2/package.json
packages/g2/src/dependents.ts

[3.6.x]fix: 使用color-util代替attr/color-util

---

.gitignore
package.json
src/core.ts
webpack.config.js

chore: webpack 打包

---

package.json
src/chart/controller/annotation.ts
tests/unit/component/annotation-spec.ts
tests/unit/component/legend-category-spec.ts

feat(annotation): 接入dataMaker dataRegion regionFilter组件

---

src/chart/controller/axis.ts
tests/unit/component/axis-circle-spec.ts

fix(circle-grid): fix circle grid center is not valid

---

src/chart/controller/axis.ts
src/chart/interface.ts
src/util/axis.ts
tests/unit/component/axis-line-spec.ts
tests/unit/util/axis-spec.ts

feat(axis): axis support position config

---

src/chart/controller/legend.ts
src/chart/interface.ts
src/theme/antv.ts
src/util/legend.ts
tests/unit/chart/controller/custom-legend-spec.ts
tests/unit/util/legend-spec.ts

Feat custom legend

---

examples/facet/facet/demo/mirror-transpose.ts
examples/facet/facet/demo/mirror.ts
src/facet/mirror.ts
src/facet/rect.ts
src/util/facet.ts
tests/unit/facet/mirror/mirror-spec.ts
tests/unit/facet/rect/col-spec.ts
tests/unit/facet/rect/row-col-spec.ts
tests/unit/facet/rect/row-spec.ts
tests/unit/util/facet-spec.ts

fix(facet): fix facet title

---

examples/column/dodge/demo/circular-stacked.ts
examples/column/histogram/demo/histogram-stacked.ts
examples/column/histogram/demo/histogram.ts
examples/gauge/gauge/demo/basic.ts
examples/gauge/gauge/demo/color.ts
examples/radar/radar/demo/flower-line.ts
package.json
src/geometry/shape/area/line.ts
src/geometry/shape/area/smooth-line.ts
src/geometry/shape/interval/hollow-rect.ts
src/geometry/shape/point/hollow.ts
src/geometry/shape/point/index.ts
tests/unit/geometry/shape/interval-spec.ts
tests/unit/geometry/shape/point-spec.ts

chore: 支持 tickInterval

---

src/chart/chart.ts
src/chart/controller/tooltip.ts
src/chart/interface.ts
tests/unit/chart/chart-spec.ts
tests/unit/interaction/action/tooltip-spec.ts
tests/unit/theme/geometry-theme-spec.ts

*  默认的 interactions 暂时仅支持 tooltip，其他的再讨论

feat(interaction): chart support defaultInteractions

---

examples/gallery/bar/demo/dynamic-bar.ts
package.json
src/chart/controller/annotation.ts
src/chart/controller/axis.ts
src/chart/controller/legend.ts
src/chart/controller/tooltip.ts
src/chart/view.ts
tests/unit/chart/controller/axis-changesize-spec.ts
tests/unit/chart/controller/axis-update-spec.ts
tests/unit/chart/controller/legend-spec.ts
tests/unit/chart/controller/title.ts

fix(axis): layout error after render twice 

---

examples/gallery/bar/demo/dynamic-bar.ts
src/chart/controller/axis.ts
tests/unit/chart/controller/axis-spec.ts
tests/unit/chart/controller/axis-update-spec.ts

Fix dynamic bar

---

src/chart/controller/tooltip.ts
src/theme/antv.ts
src/util/tooltip.ts
tests/unit/chart/controller/tooltip-spec.ts
tests/unit/util/tooltip-spec.ts

优化 tooltip 查找策略：
1. point, polygon, edge 使用图形拾取策略
2. area, line, path, heatmap 使用数据查找逼近策略
3. 其他几何标记根据 shared 参数， shared 为 true，则使用数据查找策略，false 则使用图形拾取

优化 tooltip 查找策略

---

examples/funnel/funnel/demo/comparision.ts
src/chart/controller/coordinate.ts
src/chart/view.ts
src/util/coordinate.ts
tests/unit/chart/controller/coordinate-spec.ts
tests/unit/chart/multi-view-spec.ts
tests/unit/chart/view/index-spec.ts
tests/unit/util/coordinate-spec.ts

refactor: add coordinate controller to create / cache coordinate

---

examples/gallery/line/demo/line3.ts
src/chart/controller/annotation.ts
tests/unit/component/annotation-spec.ts

fix: update data region options

---

src/animate/index.ts
tests/bugs/1980-spec.ts

fix: 修复重复调用 chart.render() 绘图异常问题

---

src/chart/controller/tooltip.ts

fix: 修复 tooltip crosshairs 失效的问题。Closed #1984

---

src/geometry/label/pie.ts
src/theme/antv.ts
src/util/scale.ts

Daily 02 06

---

src/interaction/action/element/pie-selected.ts
src/interaction/action/element/single-state.ts
tests/bugs/pie-unselected-spec.ts

定位的问题：
* 先调用了 element.setState('selected', false) 就把 shape 的状态(matrix) 取消了，所以取消动画无效果
* 当设置其他状态如 active 时，就会导致 selected 的效果丢失

feat(selected): pie selected animate

---

examples/facet/facet/demo/list.ts
src/facet/interface.ts
src/facet/list.ts
src/index.ts
tests/unit/facet/list/index-spec.ts

Feat facet list

---

examples/heatmap/heatmap/demo/basic.ts
examples/point/scatter/demo/pizza.ts
src/chart/controller/axis.ts
src/chart/interface.ts
src/theme/antv.ts
src/util/grid.ts
tests/unit/util/grid-spec.ts

Close #1966
* alignTick: true
* alignTick: false

axis grid 支持 alignTick 属性

---

examples/interaction/interaction/demo/continue-legend-filter.ts
src/chart/view.ts
src/interaction/action/element/pie-selected.ts
src/interaction/action/element/single-state.ts
tests/bugs/pie-unselected-spec.ts
tests/unit/chart/chart-spec.ts
tests/unit/chart/event/multiple-view-spec.ts

* 修复 plot:leave 在画布边缘无法触发的问题
* 修复 click 等事件重复触发的问题
* 修复 view 遮挡空白处无法触发事件的问题
* view 和 chart 都支持非委托事件，支持 drag事件
目前存在的问题：
* chart 和 view 上非委托事件（无前缀）和 plot 事件的顺序有问题，先触发了 chart 后触发 view，应该反过来，目前不影响现有的交互。后面遇到问题再调整。

View event

---

examples/facet/facet/demo/circle.ts
src/facet/circle.ts
src/facet/facet.ts
src/facet/interface.ts
src/facet/list.ts
src/facet/matrix.ts
src/facet/mirror.ts
src/facet/rect.ts
src/index.ts
src/util/facet.ts
tests/unit/facet/circle/index-spec.ts

Feat facet circle

---

examples/interaction/interaction/demo/brush-polygon.ts
examples/interaction/interaction/demo/element-brush.ts
src/index.ts
src/interaction/action/element/filter.ts
src/interaction/action/element/highlight-util.ts
src/interaction/action/element/range-state.ts
src/interaction/action/element/state-base.ts
src/interaction/action/util.ts
src/interaction/action/view/scale-translate.ts
src/interaction/action/view/scale-zoom.ts
tests/unit/interaction/action/mask-filter-spec.ts

Brush visible

---

src/geometry/base.ts
tests/unit/geometry/base-spec.ts

feat: geometry 添加 getShapes() 接口已获取所有的 shapes 图形

---

src/chart/controller/axis.ts
tests/bugs/1935-spec.ts

fix(axis): update axis component when coordinate changed

---

examples/interaction/interaction/demo/range-highlight.ts
src/index.ts
src/interaction/action/element/filter.ts
src/interaction/action/element/range-state.ts
src/interaction/action/mask/base.ts
src/interaction/action/mask/circle.ts
src/interaction/action/mask/path.ts
src/interaction/action/mask/rect.ts
src/interaction/action/util.ts
tests/unit/interaction/action/mask-filter-spec.ts
tests/unit/interaction/action/mask-range-state-spec.ts
tests/unit/interaction/action/mask-spec.ts
tests/unit/interaction/element-spec.ts

* 实现 mask 的拖拽，并且拖拽过程中支持 active， highlight, filter

feat(interaction): drag mask

---

packages/component/package.json
packages/g2/package.json

[3.6.x] update scale to 0.3 stable version

---

src/geometry/base.ts
tests/bugs/2021-spec.ts

fix: 修复通过大配置项配置饼图 position 映射时未自动补齐 1 的问题

---

src/geometry/base.ts
src/geometry/path.ts
tests/bugs/2016-spec.ts

Issue 2016，处理数据源中存在重复数据的情况

---

src/animate/animation/util.ts
src/animate/animation/wave-in.ts
src/chart/chart.ts
src/chart/view.ts
src/interface.ts
src/util/coordinate.ts
tests/unit/chart/chart-auto-fit-spec.ts
tests/unit/chart/chart-clip-spec.ts

view 上支持 limitInPlot 属性

---

examples/interaction/interaction/demo/brush-filter-record.ts
examples/interaction/interaction/demo/brush-filter-shape.ts
package.json
src/index.ts
src/interaction/action/data/sibling-filter.ts
src/interaction/action/element/filter.ts
src/interaction/action/element/range-state.ts
src/interaction/action/element/sibling-filter.ts
src/interaction/action/util.ts
src/interaction/context.ts
src/interaction/grammar-interaction.ts
tests/bugs/2032-spec.ts
tests/unit/interaction/action/element-sibling-filter-spec.ts
tests/unit/interaction/action/sibling-filter-spec.ts
tests/unit/interaction/interaction-spec.ts

* 支持按照 mask 的 bbox 进行过滤，也支持按照数据过滤

Sibling filter

---

src/geometry/base.ts
tests/bugs/2032-spec.ts

fix: 修复多 view 共享一个 shapeFactory 实例，导致 Coordinate 混用

---

examples/component/component/demo/tooltip-1.ts
examples/component/component/demo/tooltip-2.ts
examples/component/component/demo/tooltip-3.ts
src/geometry/base.ts
tests/bugs/2034-spec.ts

Issue 2034

---

examples/area/basic/demo/area-large.ts
package.json
src/chart/controller/slider.ts
src/chart/layout/index.ts
src/chart/view.ts
src/dependents.ts
src/index.ts
src/interface.ts
tests/unit/chart/chart-spec.ts
tests/unit/chart/controller/index-spec.ts
tests/unit/chart/controller/slider-spec.ts
tests/unit/chart/controller/tooltip-spec.ts

feat(slider): add slider controller and component

---

examples/interaction/interaction/demo/brush-highlight.ts
src/index.ts
src/interaction/action/element/range-highlight.ts
src/interaction/action/element/range-state.ts
src/interaction/action/element/sibling-filter.ts
src/interaction/action/element/state-base.ts
src/interaction/action/util.ts
src/interaction/grammar-interaction.ts
tests/unit/interaction/action/sibling-range-state-spec.ts
tests/unit/interaction/interaction-spec.ts

Sibling state

---

package.json
src/geometry/base.ts
src/geometry/element/index.ts
src/geometry/label/base.ts
src/geometry/path.ts
tests/bugs/2040-spec.ts
tests/unit/chart/controller/legend-update-spec.ts
tests/unit/geometry/label/labels-spec.ts

Fix element

---

src/chart/controller/tooltip.ts
src/interface.ts
src/theme/antv.ts
tests/unit/chart/controller/tooltip-spec.ts
tests/unit/interaction/action/tooltip-spec.ts

tooltip 添加 showContent 属性

---

examples/interaction/interaction/demo/meta.json
examples/interaction/interaction/demo/views-tooltip.ts
src/chart/chart.ts
src/chart/util/scale-pool.ts
src/index.ts
src/interaction/action/component/list-state.ts
src/interaction/action/component/sibling-tooltp.ts
src/interaction/action/component/tooltip.ts
src/interaction/action/data/filter.ts
src/interaction/action/util.ts
tests/unit/interaction/action/data-fitler-spec.ts
tests/unit/interaction/action/tooltip-spec.ts
tests/unit/interaction/action/views-legend-spec.ts

* 支持 多 view  legend 交互（active， highlight, filter)
* 支持多 view  tooltip 联动
* 内置默认的交互 ['tooltip', 'legend-filter', 'legend-active', 'element-active','continuous-filter']

Legend views

---

package.json
src/animate/animation/position-update.ts
src/animate/index.ts
src/geometry/base.ts
src/geometry/util/is-model-change.ts
src/index.ts
tests/bugs/2045-spec.ts

Issue 2031 2045

---

src/geometry/base.ts
src/geometry/interval.ts
src/geometry/schema.ts
tests/bugs/2049-spec.ts

Issue 2049

---

examples/column/dodge/demo/grouped.ts
examples/column/dodge/demo/polar-grouped.ts
gatsby-config.js
src/animate/index.ts
src/core.ts
src/interaction/action/active-region.ts
tests/bugs/active-region-spec.ts
tests/unit/animate/index-spec.ts

* Close #2058
* Finish https://github.com/antvis/G2/issues/2054#issuecomment-586570369

Daily 0217

---

src/chart/view.ts
src/util/tooltip.ts
tests/unit/chart/multi-view-spec.ts
tests/unit/chart/view/index-spec.ts
tests/unit/util/tooltip-spec.ts

feat: 添加 view.getSnapRecords() 接口

---

src/chart/chart.ts
src/index.ts
src/interaction/action/element/highlight-by-color.ts
src/interaction/action/element/highlight-by-x.ts
src/interaction/action/element/highlight.ts
src/interaction/action/element/state.ts
tests/unit/interaction/action/highlight-spec.ts

* 去除 element-active 默认的交互
* 增加 element-highlight-by-x, element-higlight-by-color 的交互

feat(interaction): add actions of higlight

---

src/chart/controller/legend.ts
src/chart/util/scale-pool.ts
tests/bugs/legend-check-spec.ts

* 问题定位比较曲折：
+ G 的 invert matrix 出错
+ axis 生成的时候包围盒计算错误
+ axis 的 ticks 的 value: NaN
+ 数据为空是，render(true) 时 scale 生成的有问题
* 最终在 syncScale 的时候判定了下是否是同一种类型，解决了问题

Legend unchecked

---

src/animate/animation/sector-path-update.ts
src/chart/util/scale-pool.ts
src/util/graphics.ts
tests/bugs/pie-update-spec.ts

修复如下问题：
1. 饼图更新动画异常
2. 饼图更新后，hover 图例项，图形 active 异常
3. 饼图更新数据后。将图例项全部取消选中后再选中出错

Daily 0220

---

examples/area/streamgraph/demo/streamgraph.ts
examples/bar/basic/demo/radial-bar.ts
examples/bar/basic/demo/ranged.ts
examples/bar/basic/demo/time-bar.ts
examples/bar/stack/demo/stacked.ts
examples/component/tooltip/demo/tooltip-2.ts
examples/funnel/funnel/demo/basic.ts
examples/funnel/funnel/demo/comparision.ts
examples/funnel/funnel/demo/pyramid.ts
examples/funnel/funnel/demo/symmetric.ts
examples/gallery/pie/demo/pie2.ts
src/chart/controller/tooltip.ts
src/chart/view.ts
src/constant.ts
src/geometry/base.ts
src/geometry/element/index.ts
src/interaction/action/component/tooltip.ts
src/interaction/action/data/filter.ts
src/interface.ts
src/theme/antv.ts
tests/bugs/tooltip-share-spec.ts
tests/bugs/tooltip-spec.ts
tests/unit/chart/chart-spec.ts
tests/unit/chart/controller/tooltip-spec.ts
tests/unit/component/tooltip-crosshairs-spec.ts
tests/unit/interaction/action/tooltip-spec.ts

修复如下问题：
1. element.hide() 之后 tooltip 上仍展示的问题
2. 优化 tooltip 闪烁的问题：https://github.com/antvis/G2/issues/2054#issuecomment-586567117
3. 区分 tooltip 内容框的 follow 和 crosshairs 的 follow，默认 tooltip 跟随鼠标移动，crosshairs 默认不跟随鼠标（直接定位到数据点）
4. 优化 tooltip 展示逻辑以提升性能，当内容未发生更新的时候，tooltip 组件只需更新位置
5. 修复 tooltip shared: false  对 line、area 不生效的问题

Tooltip 体验优化

---

src/interaction/action/component/list-highlight.ts
src/interaction/action/component/list-state.ts
src/interaction/action/element/state.ts
tests/unit/interaction/action/highlight-spec.ts
tests/unit/interaction/action/list-active-spec.ts
tests/unit/interaction/action/list-highlight-spec.ts

feat(action): when iten has unchecked, no highlight

---

src/chart/controller/axis.ts
src/util/axis.ts
tests/unit/util/axis-spec.ts

feat(axis): axis support set title.text property

---

README.md
README.zh-CN.md
src/chart/controller/tooltip.ts
src/geometry/base.ts
tests/bugs/2085-spec.ts
tests/bugs/tooltip-spec.ts

1. 修复热力图 tooltip 失效的问题
2. 修复 #2085 ， shape({ values: ['funnel'] }) 无法生效的问题
Close #2085

 Bugfix 0225

---

src/chart/view.ts
src/geometry/base.ts
tests/unit/interaction/action/active-spec.ts

* 暂时解决 label 的事件问题，目前解决的不是很好，还需要调整

feat(label): add label event

---

src/interaction/action/element/single-state.ts
src/interaction/action/element/state.ts
src/interaction/action/util.ts
tests/unit/interaction/action/highlight-spec.ts

feat(highlight): stop shine of highlight

---

packages/g2/package.json

【3.6.x】feat: update g version

---

examples/interaction/element/demo/element-link.ts
examples/interaction/element/demo/meta.json
package.json
src/index.ts
src/interaction/action/element/link-by-color.ts
src/interaction/action/util.ts
tests/unit/interaction/action/link-by-color-spec.ts

* 暂时仅支持直角坐标系下的连接， transpose 和 极坐标下的 link 可以后面再做

Element link

---

docs/manual/developer/registerinteraction.en.md
docs/manual/developer/registerinteraction.zh.md
docs/manual/tutorial/interaction.en.md
docs/manual/tutorial/interaction.zh.md
examples/interaction/element/demo/meta.json

docs(interaction): update interaction docs

---

packages/component/package.json
packages/g2/package.json

[3.6.x] 升级scale & 发布新版本

---

docs/manual/tutorial/interaction.zh.md
src/index.ts
src/interaction/action/data/range-filter.ts
src/interaction/action/mask/base.ts
src/interaction/action/mask/circle.ts
src/interaction/action/mask/path.ts
src/interaction/action/mask/rect.ts
src/interaction/action/util.ts
src/util/bbox.ts
tests/unit/interaction/action/mask-range-state-spec.ts
tests/unit/interaction/action/mask-spec.ts

feat(interaction): path mask improve

---

docs/manual/tutorial/interaction.en.md
docs/manual/tutorial/interaction.zh.md

seleted=>selected
riddle https://riddle.alibaba-inc.com/riddles/f2700af8
复制文档，没发现拼写错误然后GG
蹭 mr

docs: interaction page element single selected spelling mistakes

---

src/chart/chart.ts
tests/bugs/2158-spec.ts
tests/unit/chart/chart-auto-fit-spec.ts

fix(auto-fix): fix height when autoFit and container has padding

---

src/chart/controller/slider.ts
tests/unit/chart/controller/slider-spec.ts

fix(slider): when changeData, slider min max text should be update

---

docs/manual/faq.en.md
docs/manual/faq.zh.md
examples/column/stack/demo/meta.json
examples/column/stack/demo/polar-stack.ts
examples/column/stack/demo/ripple.ts
examples/interaction/others/demo/meta.json
examples/interaction/others/demo/pie-legend.ts

Add demos docs

---

docs/manual/tutorial/interaction.en.md
docs/manual/tutorial/interaction.zh.md

chore(interaction): add action to docs

---

docs/manual/tutorial/interaction.en.md
docs/manual/tutorial/interaction.zh.md
examples/interaction/others/demo/drag-move.ts
examples/interaction/others/demo/zoom.ts
src/chart/view.ts
src/index.ts
src/interaction/action/view/scale-zoom.ts
src/interaction/grammar-interaction.ts
tests/unit/interaction/action/view-scale-spec.ts
tests/unit/interaction/interaction-spec.ts

feat(action): add throttle and debounce

---

docs/manual/tutorial/interaction.en.md
docs/manual/tutorial/interaction.zh.md
src/core.ts
src/index.ts
src/interaction/action/index.ts
src/interaction/action/register.ts
src/interaction/index.ts
tests/unit/interaction/interaction-spec.ts

Legend highlight

---

src/geometry/base.ts
src/geometry/heatmap.ts
src/geometry/path.ts
tests/bugs/2016-spec.ts
tests/bugs/2141-spec.ts

Closed #2141 
应该将所有的数据都渲染出来（即使存在重复数据）。

fix(geometry): 修复 element 打标策略导致的数据未被全部绘制的问题。Closed #2141

---

docs/manual/tutorial/schema.en.md
docs/manual/tutorial/schema.zh.md
src/chart/view.ts
src/interface.ts
tests/bugs/2157-spec.ts

fix(options): 修复 chart.updateOptions() 更新失败的问题

---

docs/manual/tutorial/event.en.md
docs/manual/tutorial/event.zh.md
examples/interaction/others/demo/pie-legend.ts
src/chart/view.ts
src/geometry/element/index.ts
tests/unit/chart/event/multiple-view-spec.ts
tests/unit/chart/event/statechange-spec.ts

Issue 2181

---

src/chart/controller/tooltip.ts
src/interaction/action/active-region.ts
tests/bugs/1265-spec.ts
tests/bugs/2174-spec.ts

修复 active-reigon 计算错误的问题

---

package.json

refactor: use unpkg other than browser field in package.json

---

src/chart/view.ts

Facet 问题修复

---

src/constant.ts
tests/bugs/2215-spec.ts
tests/unit/util/dom-spec.ts

fix(#2215): fix chart min size = 100

---

src/chart/chart.ts
tests/bugs/2197-spec.ts

feat(force-fit): add forceFit api for chart

---

src/chart/util/scale-pool.ts
src/chart/view.ts
tests/bugs/2222-spec.ts
tests/unit/chart/chart-spec.ts
tests/unit/chart/view/scale-sync/multi-view-sync-scale-spec.ts
tests/unit/chart/view/scale-sync/simple-sync-scale-spec.ts

修复 scale pool 在 view 销毁重建过程中的泄露问题

---

src/chart/controller/slider.ts
src/chart/view.ts
tests/bugs/2212-spec.ts

fix(#2212): fix when slider option has no start or end

---

docs/manual/dataset/transform.en.md
docs/manual/dataset/transform.zh.md
src/geometry/shape/point/image.ts
src/geometry/shape/point/util.ts
tests/bugs/2202-spec.ts

Issue 2202

---

src/chart/view.ts
tests/unit/chart/multi-view-spec.ts
tests/unit/chart/view/index-spec.ts

feat: 添加一些方法的别名，以兼容 3.x，但是这些方法将会在 4.1 版本中移除

---

src/chart/controller/legend.ts
tests/bugs/2173-spec.ts

fix(#2173): fix legend overlap when in same direction

---

src/chart/view.ts
src/facet/facet.ts
tests/bugs/2232-spec.ts

fix(#2232): fix 当 legend item 点击的时候, 图例项变少

---

src/chart/chart.ts
src/util/dom.ts
tests/bugs/2264-spec.ts

fix(#2264): 修复 canvas 样式导致的 resize 问题, 修复容器层级

---

src/chart/controller/tooltip.ts
src/util/tooltip.ts
tests/bugs/2241-spec.ts
tests/bugs/2261-spec.ts

tooltip 问题修复 

---

docs/manual/dataset/transform.en.md
docs/manual/dataset/transform.zh.md
examples/relation/relation/demo/sankey.ts
package.json

feat: add sankey sort

---

src/chart/controller/tooltip.js

viewTheme.tooltipCrosshairsLine 配置无法对散点图生效

fix: fix scatter crosshairs style

---

src/geometry/element/index.ts
tests/bugs/state-style-spec.ts
tests/unit/chart/controller/gesture-spec.ts

性能优化的时候改坏了，主要解决用户自定义 shape 的时候获取不到 state 样式的问题。

Fix state style

---

package.json
src/chart/view.ts
src/geometry/base.ts
src/geometry/element/index.ts
tests/bugs/2307-spec.ts
tests/unit/chart/controller/gesture-spec.ts
tests/unit/geometry/element/index-spec.ts
tests/unit/geometry/label/layout/limit-in-canvas-spec.ts

* name 支持数组或者字符串
* 委托事件不再支持 inheritNames

fix(delegation): mouse leave failed

---

src/chart/controller/tooltip.ts
src/interface.ts
tests/unit/chart/controller/tooltip-spec.ts

fix: do not set tooltip position when follow is false

---

bin/doc.sh
bin/typedoc-theme/theme.js
package.json

* generate-changelog 这个工具更好用~~~ 我都是用这个工具更新的 changelog，所以就把命令改成这个吧~
* 优化自动生成文本脚本，site:deploy 一键生成+部署

changlog 以及文档自动生成命令优化

---

CHANGELOG.md
package.json
src/core.ts

chore: release v4.0.7

---

tsconfig.json

turn on TS compiler option `inlineSources`

chore: add sourcesContent to sourcemap close #2338

---

docs/manual/contact.en.md
docs/manual/contact.zh.md

chore: 去掉外部钉钉群二维码

---

src/index.ts

虽然使用 `import { LooseObject } from '@antv/g2/lib/interface';` 完全没有问题，但对于 [ngcc](https://github.com/angular/ngcc-validation) 会收到一些警告【This is probably not a problem, but may cause the compilation of entry points to be out of order.】虽然并不影响使用，但是在体验上略差一点，比如像这样：
```ts
import { LooseObject } from '@antv/g2/lib/interface';
```
相比较：
```ts
import { Chart, LooseObject } from '@antv/g2';
```
优雅非常多

refactor: 增加所有接口的导出

---

src/interaction/action/element/state.ts
tests/unit/geometry/label/label-update-spec.ts

fix(interaction): delegate object error

---

src/chart/view.ts

docs(view): component docs

---

src/chart/controller/gesture.ts
tests/unit/chart/controller/gesture-spec.ts

fix: gesture controller off event when destroy

---

docs/manual/tutorial/axis.en.md
docs/manual/tutorial/axis.zh.md

修改了教程中 axis.md中小错误

---

src/util/theme.ts
tests/bugs/2412-spec.ts

关联 https://github.com/antvis/component/pull/163，需要 component 发包，发包后 CI 就过了~~~

fix(2412): 修复 axis title offset 设置不生效的问题，默认自动计算

---

src/util/axis.ts
tests/bugs/2365-spec.ts

fix(2365): 修复极坐标系圆弧坐标轴文本不响应坐标系 rotate 的问题

---

package.json
src/util/axis.ts

coord 依赖 @antv/matrix-util，也需要升级。

chore(deps): 升级 @antv/coord 依赖

---

src/index.ts
src/util/axis.ts
src/util/transform.ts

fix: fix some ts error to pass build

---

src/chart/controller/legend.ts
tests/bugs/2442-spec.ts

- [ x] `npm test` passes
- [x ] tests and/or benchmarks are included
- [x ] commit message follows commit guidelines

fix: fix min/max value map to color

---

docs/manual/tutorial/scale.zh.md

fix(typo): fix typo

---

src/chart/controller/legend.ts
tests/unit/chart/controller/legend-spec.ts

close https://github.com/antvis/G2Plot/issues/923

fix: 图例应于坐标轴对齐

---

src/chart/layout/index.ts
tests/bugs/2495-spec.ts

fix(#2495): fix layout error after render twice

---

CHANGELOG.md
package.json
src/core.ts

chore: release v4.0.9

---

examples/interaction/brush/demo/brush-filter-shape.ts

In line 40 of "G2/examples/interaction/brush/demo/brush-filter-shape.ts," replaced '!=' with '!=='.

fix(line 40): replace '!=' with '!=='

---

CHANGELOG.md
package.json
src/global.js

chore: release v3.5.17

---

CHANGELOG.md
package.json
src/core.ts

chore: release v4.0.10

---

README.md
README.zh-CN.md
gatsby-config.js

docs(site): update size nav

---

src/chart/chart.ts

fix(lint): 手工 prettier

---

CHANGELOG.md
package.json
src/core.ts

chore: release 4.0.11

---

package.json

chore: 添加 lint-staged 配置

---

CHANGELOG.md
package.json
src/core.ts

chore: release v4.0.12

---

src/base.ts

refactor: 删除不必要的代码

---

src/util/tooltip.ts
tests/unit/util/tooltip-spec.ts

fix: 拆分字段有空数值时不使用tooltip title来显示

---

examples/area/basic/demo/area-large.ts

改正示例“大规模区域图”中的时间格式

---

examples/gallery/pie/demo/pie3.ts

Fixing description mistakes shown in Gallery -> Pie -> Demo 2.
修正 Gallery -> Pie -> Demo 2 中代码与描述不同的问题。

fix: issues of pie demo 2

---

docs/manual/tutorial/event.en.md

docs(event.en.md): fix typo

---

src/chart/view.ts
tests/bugs/2658-spec.ts

fix: #2658

---

src/geometry/area.ts
src/geometry/path.ts
src/geometry/shape/area/util.ts
src/geometry/shape/line/index.ts
src/geometry/shape/line/step.ts
src/geometry/shape/util/get-path-points.ts
src/interface.ts
tests/bugs/2665-spec.ts
tests/unit/geometry/shape/util/get-path-points-spec.ts

效果：
* Line/Path 单个点的大小跟随 lineWidth，本质上也是 path 绘制的，只是让它的长度等于 lineWidth;
* Area  则只绘制一条 1px 的值

feat: path line area 三类 Geometry 支持 showSinglePoint 属性，用于支持单点孤立数据点的绘制

---

src/component/labels.ts
tests/bugs/component-label-spec.ts

fix(label): 修复 labelItem 不存在时，coordinate 为空，获取cetner中心坐标点出错

---

CHANGELOG.md
package.json
src/core.ts

chore: v4.0.13

---

examples/gallery/dynamic/demo/dynamic-bar.ts
examples/gallery/dynamic/demo/dynamic-bubble.ts

Fixing two path errors in dynamic demos
修复动态demo中的数据路径bug

fix: path err in dynamic demos

---

examples/point/bubble/demo/bubble-text.ts

fix: error in bubbleplot demo

---

examples/other/other/demo/word-cloud.ts

fix: #2706

---

.gitignore
docs/api/chart.en.md
docs/api/chart.zh.md
docs/api/element.en.md
docs/api/element.zh.md
docs/api/geometry/area.en.md
docs/api/geometry/area.zh.md
docs/api/geometry/edge.en.md
docs/api/geometry/edge.zh.md
docs/api/geometry/geometry.en.md
docs/api/geometry/geometry.zh.md
docs/api/geometry/heatmap.en.md
docs/api/geometry/heatmap.zh.md
docs/api/geometry/interval.en.md
docs/api/geometry/interval.zh.md
docs/api/geometry/line.en.md
docs/api/geometry/line.zh.md
docs/api/geometry/path.en.md
docs/api/geometry/path.zh.md
docs/api/geometry/point.en.md
docs/api/geometry/point.zh.md
docs/api/geometry/schema.en.md
docs/api/geometry/schema.zh.md
docs/api/interaction.en.md
docs/api/interaction.zh.md
docs/api/scale.en.md
docs/api/scale.zh.md
gatsby-config.js
package.json

docs: add part API documents

---

package.json

chore: gatsby version update

---

examples/other/other/demo/word-cloud.ts

Fixing bugs in the word cloud demo
修复词云demo显示错误问题

fix: bugs in wordcloud demo

---

api-extractor.json
src/api.ts
src/geometry/base.ts

1. add typescript file extraction configuration
2. fix typescript file extraction error in base.ts

feat: add api-extractor  for extract typescript declare file

---

src/chart/chart.ts
tests/unit/chart/chart-auto-fit-spec.ts

fix(change-size): when size is equal, not render

---

src/chart/controller/axis.ts

> 单测通过，demo 都点了一遍。
ref: https://github.com/antvis/G2/issues/2014

refactor(axis): axis update 包含有 create 逻辑,删除容易的 create 逻辑,简化代码

---

CHANGELOG.md
package.json
src/core.ts

chore: upgrade version

---

src/chart/view.ts
tests/bugs/2505-spec.ts
tests/unit/theme/background-spec.ts

fix(background): backgroup shape should set capture = false

---

docs/manual/developer/registerinteraction.zh.md

fix: the doc example error

---

src/chart/view.ts
tests/unit/theme/background-spec.ts

fix(background): 背景色 shape z-index 顺序不对

---

src/chart/controller/tooltip.ts
src/interaction/action/component/tooltip/geometry.ts
src/interface.ts
src/util/bbox.ts
tests/unit/component/axis-line-spec.ts
tests/unit/interaction/action/tooltip-spec.ts
tests/unit/util/bbox-spec.ts

fix(tooltip): make tooltip enterable

---

src/chart/controller/slider.ts
src/interface.ts
tests/unit/chart/controller/slider-spec.ts

chore(slider): export typedefine

---

src/chart/view.ts
src/geometry/base.ts
src/interface.ts
tests/unit/options/events-spec.ts
tests/unit/options/label-spec.ts
tests/unit/options/options-spec.ts
tests/unit/options/slider-spec.ts
tests/unit/schema-spec.ts

> 获取 labelType 错误导致
> coordinateBBox 未重置导致

Options 配置项优化系列

---

src/chart/controller/slider.ts
src/chart/layout/auto.ts
src/constant.ts
src/interface.ts
src/util/bbox.ts
src/util/theme.ts
tests/bugs/2212-spec.ts
tests/unit/chart/controller/slider-spec.ts
tests/unit/util/bbox-spec.ts

fix(slider): slider + layout, add slider padding

---

examples/pie/basic/demo/meta.json
examples/pie/basic/demo/pie-spider-label.ts
examples/pie/basic/demo/pie-spider-with-hideOverlap.ts
src/geometry/label/interface.ts
src/geometry/label/layout/pie/outer.ts
src/geometry/label/layout/pie/spider.ts
src/geometry/label/layout/pie/util.ts
src/geometry/label/polar.ts
src/index.ts
tests/unit/geometry/label/layout/pie-outer-spec.ts
tests/unit/geometry/label/layout/pie-spider-spec.ts

feat(spider-label): 增加蜘蛛标签 & spider label layout

---

src/chart/controller/legend.ts
src/chart/view.ts
src/interface.ts
tests/unit/options/annotation-spec.ts

继续一些 options 相关的 BUG 修复，详见 commit

Fix slider cfg and options

---

src/chart/controller/legend.ts
src/chart/layout/auto.ts
src/chart/view.ts
src/interface.ts
src/theme/style-sheet/light.ts
src/util/theme.ts
tests/bugs/2173-spec.ts
tests/unit/chart/controller/legend-padding-spec.ts
tests/unit/chart/controller/legend-spec.ts

Feat legend padding

---

CHANGELOG.md
package.json
src/core.ts

chore: 4.1.0-beta.1

---

src/component/labels.ts
tests/bugs/2778-spec.ts

fix(issue-2778): 修复 label 点击的时候，没有获取到数据

---

package.json

fix: add dom-util dependence

---

src/chart/view.ts
src/interface.ts
tests/unit/options/facet-spec.ts

Options facets

---

src/util/bbox.ts
tests/bugs/2433-spec.ts
tests/unit/util/bbox-spec.ts

fix(#2433): fix slider collide legend

---

src/util/legend.ts
tests/bugs/2763-spec.ts

fix(#2763): 修复 legend-filter 在view中行为错误

---

src/chart/controller/base.ts
src/interface.ts

Walk through

---

src/chart/view.ts
tests/bugs/2799-spec.ts
tests/unit/chart/chart-spec.ts

fix(clear): chart.clear then render, memory leak

---

src/index.ts
src/interaction/grammar-interaction.ts

fix(typos): correct spelling

---

src/chart/chart.ts
src/chart/controller/scrollbar.ts
src/chart/layout/auto.ts
src/chart/layout/index.ts
src/chart/view.ts
src/constant.ts
src/dependents.ts
src/index.ts
src/interface.ts
src/util/theme.ts
tests/data/sales.ts
tests/unit/chart/chart-spec.ts
tests/unit/chart/controller/index-spec.ts
tests/unit/chart/controller/scrollbar-spec.ts
tests/unit/chart/controller/tooltip-spec.ts

feat: support scrollbar component

---

package.json

gatsby-theme-antv extractor type definition for smart tip for examples need parse index.d.ts

fix: build before deploy to get latest type definition

---

src/geometry/base.ts
src/interface.ts
tests/unit/geometry/base-spec.ts

https://github.com/antvis/G2/issues/2796

feat(geometry): add geometry.custom API for registerShape

---

src/chart/controller/tooltip.ts
src/interface.ts
tests/unit/component/tooltip-custom-content-spec.ts

- tooltip 内内置 class="g2-tooltip" 逻辑

feat: tooltip custom content 内置 class: "g2-tooltip"

---

src/chart/controller/scrollbar.ts
src/chart/controller/slider.ts
tests/unit/chart/controller/scrollbar-spec.ts
tests/unit/chart/controller/slider-spec.ts

fix: fix slider changeSize bug and scrollbar overlap with legend

---

src/geometry/label/polar.ts

fix(demo): 修复环图自定义 label 的 demo, 获取 labelItems 为空

---

src/chart/controller/axis.ts

哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈

fix(axis): 回调带上默认主题

---

examples/gallery/line/demo/line1.ts
src/chart/chart.ts
src/chart/controller/axis.ts
src/chart/layout/auto.ts
src/chart/layout/index.ts
src/chart/view.ts
src/interface.ts
tests/bugs/2356-spec.ts
tests/bugs/2570-spec.ts
tests/bugs/2658-spec.ts
tests/bugs/2841-spec.ts
tests/bugs/2849-spec.ts
tests/unit/chart/controller/legend-spec.ts
tests/unit/component/legend-category-spec.ts
tests/unit/options/options-spec.ts

feat: view padding sync

---

package.json
src/core.ts

chore: 4.1.0-beta.8 release

---

src/chart/controller/slider.ts
tests/bugs/slider-spec.ts

fix: 修复数据为空时 slider 报错的问题

---

src/geometry/label/base.ts
src/geometry/label/interval.ts
tests/data/positive-negative.ts
tests/unit/geometry/label/interval-spec.ts

feat: improve interval label position

---

CHANGELOG.md
package.json
src/core.ts

chore: release 4.1.0-beta.10

---

.github/workflows/preview.yml

chore: run PR preview on pull_request

---

src/chart/controller/legend.ts

fixed #2014 
legend 的更新和渲染使用同一个逻辑，减少冗余代码。

refactor(legend): legend update and render with same logic

---

src/interface.ts

fix(types): add legend option

---

examples/pie/nested/demo/multi-level.ts

fix(pie-demo): typo, fixed #2884

---

CHANGELOG.md
package.json
src/core.ts

chore: v4.1.0-beta.11

---

src/geometry/label/interval.ts
tests/unit/geometry/label/interval-spec.ts

fix: 漏斗图 label position 可生效

---

docs/api-zh/legend.md
docs/manual/tutorial/event.en.md
docs/manual/tutorial/event.zh.md

docs: marker单词拼写错误修正

---

src/geometry/element/index.ts
tests/bugs/2541-spec.ts
tests/unit/chart/controller/scrollbar-spec.ts

fix(issue-2541): state 状态依然存在时，但由于changeSize, changeData 等重绘后丢失

---

docs/api-zh/legend.md
docs/manual/dataset/transform.en.md
docs/manual/dataset/transform.zh.md

* 修正 binsWidth 为 binWidth
* 根据源码统一 legendCfg 为 legendOption

docs: modify some descriptions

---

src/util/color.ts
tests/unit/util/color-spec.ts

fix: 修复 adjust-color label layout 对一些颜色不生效的问题

---

src/util/annotation.ts
tests/unit/util/annotation-spec.ts

fix: median typo

---

src/chart/controller/annotation.ts
tests/bugs/2851-spec.ts

fix(annotation): text annotation re-render will be hidden

---

docs/api/general/theme.zh.md

docs: add theme doc

---

docs/api/general/event.zh.md

feat(docs): add event document

---

package.json
src/chart/controller/annotation.ts
src/chart/controller/axis.ts
src/chart/controller/legend.ts
src/chart/controller/slider.ts
src/interface.ts
tests/unit/component/annotation-spec.ts

feat: G2 层支持 custom annotation html annotation

---

docs/manual/concepts/composition.zh.md

docs(component): add docs for components

---

docs/manual/concepts/coordinate.zh.md

docs: coordinate

---

docs/api/general/adjust.zh.md
docs/api/general/axis.zh.md
docs/api/general/coordinate.zh.md
docs/api/general/interaction.zh.md
docs/api/general/label.zh.md
docs/api/general/legend.zh.md
docs/api/general/scale.zh.md
docs/common/annotation-position.md

统一方法说明为 sign 代码块，替换之前的 highlight-start

docs: unified types hightlight to sign code

---

src/util/theme.ts

feat(line-style): default use round style

---

docs/api/general/annotation.zh.md
docs/api/general/scrollbar.zh.md
docs/api/general/slider.zh.md
docs/common/scrollbar-options.md
docs/common/slider-options.md
docs/manual/concepts/composition.zh.md

docs: add docs for slider/scrollbar/annotation

---

docs/api/general/coordinate.zh.md
docs/api/general/event.zh.md
docs/api/general/interaction.zh.md

docs: event & interaction API

---

docs/api/advanced/dive-into-theme.en.md
docs/api/advanced/dive-into-theme.zh.md
docs/api/advanced/gesture.zh.md
docs/api/advanced/register-animate.zh.md
docs/api/advanced/register-facet.zh.md
docs/api/advanced/register-geometry.zh.md
docs/api/advanced/register-interaction.zh.md
docs/api/advanced/register-label-layout.zh.md
docs/api/advanced/register-shape.zh.md
docs/api/advanced/register-theme.zh.md
docs/api/advanced/registeranimation.en.md
docs/api/advanced/registeranimation.zh.md
docs/api/advanced/registerfacet.en.md
docs/api/advanced/registerfacet.zh.md
docs/api/advanced/registerinteraction.en.md
docs/api/advanced/registerinteraction.zh.md
docs/api/advanced/registerlabel.en.md
docs/api/advanced/registerlabel.zh.md
docs/api/advanced/registershape.en.md
docs/api/advanced/registershape.zh.md
docs/api/advanced/registertheme.en.md
docs/api/advanced/registertheme.zh.md
docs/api/advanced/require.en.md
docs/api/advanced/require.zh.md

docs: advances

---

docs/manual/tutorial/scale.en.md
docs/manual/tutorial/scale.zh.md

docs: scale docs

---

src/geometry/label/interval.ts
tests/data/positive-negative.ts
tests/unit/geometry/label/interval-spec.ts

修复 https://github.com/antvis/G2Plot/issues/1698

fix(label): fix label position for zero data

---

src/interaction/action/element/link-by-color.ts
tests/unit/interaction/action/link-by-color-spec.ts

fix(interaction): fix link-by-color path for transposed coord

---

package.json
src/chart/controller/tooltip.ts
src/core.ts

fix(tooltip): 先对 Geometry 数据判空再进行查找

---

src/geometry/shape/interval/line.ts
tests/unit/geometry/shape/interval-spec.ts

fix: delete fill attr in interval-line

---

CHANGELOG.md
package.json
src/core.ts

chore: 4.1.0-beta.16

---

.github/workflows/ci.yml

fix: ci hang

---

docs/manual/tutorial/event.zh.md

the event variable is misspelled

fix: the event variable is misspelled

---

src/chart/controller/annotation.ts
tests/unit/chart/controller/annotation-update-spec.ts

fix(annotation): :smile: 修复 html-annotation 没有 clear

---

CHANGELOG.md
package.json
src/core.ts

chore: release 4.1.0-beta.17

---

package.json
src/chart/util/scale-pool.ts
src/chart/view.ts
src/util/scale.ts
tests/bugs/2996-spec.ts
tests/unit/theme/multiple-pie-width-ratio-spec.ts

解决 https://github.com/antvis/G2/issues/2996

fix: #2996

---

.github/workflows/mirror.yml

只更新 gh-pages 分支吧，现在 push 太多触发了我 gitee 帐户的短信提醒。

chore: only sync gh-pages to Gitee Mirror

---

gatsby-config.js
package.json

chore: upgrade site theme

---

src/chart/controller/scrollbar.ts
src/chart/controller/slider.ts
tests/bugs/g2plot-1899-spec.ts

fixed https://github.com/antvis/G2Plot/issues/1899

fix(slider): slider, scrollbar filter data

---

CHANGELOG.md
package.json
src/core.ts

chore: release 4.1.0-beta.19

---

src/geometry/shape/edge/util.ts
tests/unit/geometry/shape/util/c-path-spec.ts

|  before  | after  |
|---|---|
| ![image](https://user-images.githubusercontent.com/7856674/99644839-68ad3500-2a89-11eb-86ae-e8c7061fac50.png)  | ![image](https://user-images.githubusercontent.com/7856674/99662499-4c68c280-2aa0-11eb-9b8d-1e9461f6ec55.png) |

fix(san-key): 贝塞尔曲线的方向不对

---

.github/workflows/mirror.yml

fix: change the triggering condition

---

CHANGELOG.md
package.json
src/core.ts

chore: version 4.1.0-beta.20

---

src/chart/view.ts
tests/unit/chart/chart-clip-spec.ts

fix: limitInPlot 更新后需要清除 clip

---

CHANGELOG.md
package.json
src/core.ts

chore: release 4.1.0-beta.21

---

docs/api/general/facet.en.md
docs/api/general/interaction.en.md

docs: 补充丢失的分面&交互的英文文档

---

CHANGELOG.md
package.json
src/core.ts

chore: v4.1.0

---

src/geometry/label/layout/pie/outer.ts
src/geometry/label/layout/pie/util.ts
src/geometry/label/polar.ts
tests/bugs/3056-spec.ts

close #3056 
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/15646325/100575143-729b2780-3316-11eb-8c0a-b69a2bf99920.png)|![image](https://user-images.githubusercontent.com/15646325/100575250-a8401080-3316-11eb-8171-c690c01df4a5.png)|

fix(pie-label): 修复饼图 label 溢出

---

src/geometry/label/layout/limit-in-plot.ts
src/util/text.ts
tests/bugs/3065-spec.ts
tests/unit/util/text-spec.ts

feat(label-layout): 标签布局 limit-in-plot 支持 ellipsis 展示

---

src/geometry/label/layout/pie/outer.ts
tests/bugs/3073-spec.ts

fix(issue-3073): 修复数据存在null值，在pie-outer 标签布局下报错

---

CHANGELOG.md
package.json
src/core.ts

chore: release 4.1.1

---

.github/workflows/preview-build.yml

chore: fix preview build workflow

---

.github/workflows/ci.yml
.github/workflows/preview-build.yml
.github/workflows/preview-upload.yml

chore: update ci worfklow
