- demos/assets/index.css
问题描述如下：
1. html标签不该被隐藏
2. 在最下方敲击几个回车后，上面的按钮被挤出去，滚动也不能恢复
修复完样子如下：
> fix(demo): buttons and html tag is hidden, but they should be visible

- src/component/legend/category.js
set theme in Global.legend.html, but the chart.legend({ useHtml: true }) still use default theme. Because category.js get the LEGEND_STYLE first and never change even after Global.setTheme(). So I move the LEGEND_STYLE into method  _renderHTML() , and set theme legend.html is ok now.
> fix: set theme for legend.html but not work

- package.json
- src/scale/time.js
- test/bugs/issue-240-spec.js
- test/bugs/issue-242-spec.js
- test/bugs/issue-285-spec.js
1. throw an error when date scale is not correctly set
2. tooltip error when shape's area is 0 (fixed in @antv/g)
3. update @antv/data-set
Closes: #240, #242, #285
> fix(scale): throw an error to avoid stack overflow, etc.

- CHANGELOG.md
- CONTRIBUTING.md
Fixed some typos in the documentation.
> docs: fix typos

- src/theme/default.js
If the color of the left axis line is different from the grid line, we will see the gird line overlay on the axis line. So I set the grid default zIndex to -1 to fix it.
Please make sure this change didn't effect other render.
> fix: left axis grid cover the axis line

- src/geom/mixin/tooltip.js
- test/bugs/issue-318-spec.js
* 由于柱状图显示 tooltip 时后面有辅助框，所以要获取宽度，而这时候没有传入对应的数据，所以报错。
> fix(tooltip): fixed bug of #318, size(filed) caused error of tooltip

- demos/multiple-chart.html
- src/chart/controller/legend.js
* 用户自定义 legend 时传入 marker 的配置项而不是名称，为了保持兼容性，保持原先的写法，但是在文档中移除。
```js
{ value: 'people', marker: {
symbol: 'square',
fill: '#fdae6b'
// radius: 4.5  
} 
```
> feat(legend): add default size of custom legend marker

- src/theme/default.js
Because the default style in Global.legend.html[LEGEND_CONTAINER_CLASS] set "overflow: scroll", the html legend always has the scroll bar. So I set it "overflow: auto" to make it more beautiful.
This issue like this -> https://codepen.io/anon/pen/rpWRyq
> fix: default style of legend.useHtml has scroll bar

- src/chart/controller/tooltip.js
React 的使用场景下出了一个 BUG，就是在某些情况下 geoms 为空，这时候 tooltip 的渲染就会报错。我先绕过这个错，发个小版本（3.0.4-beta.1）让 BizCharts 调试一下。
> fix(tooltip): rendering without geoms

- src/chart/chart.js
BizCharts 现在支持改 Padding 之后自动重绘，这时旧的 chart instance 会被销毁，但 resize 事件是延后 200ms 执行的，就会出现 resize 事件执行时 chart instance 已销毁的问题
> Hotfix force fit clear resize timer after destroyed

- src/chart/chart.js
For compatible FireFox (-v 57.0.4 in macOS)
The function downloadImage of chart is not work in FireFox, because of in Firefox, you can explicitly add the created element to the DOM【`document.body.appendChild(link)`】 or deal with the commit code.
> change downloadImage func

- src/component/legend/category.js
问题复现与 Issue #422 ，由于https://github.com/antvis/g2/blob/master/src/component/legend/category.js#L421 这里更新checked状态的时机不对导致的。于是这里把更新时机往后移，再判断跳过最后一个图例item的逻辑（L453）后面再作修改。由于比较难提供测试样例就没有添加对应的测试。
> fix(legend): html legend checked status error. Closes #422

- src/geom/label/pie-labels.js
- src/scale/linear.js
- test/bugs/issue-378-spec.js
- test/bugs/issue-500-spec.js
- test/bugs/issue-520-spec.js
* #520  由于目前 time scale 为了避免一次排序，所以仅仅取了第一个时间点和第二个时间点作为最小的间距，正好给出的 demo 的数据，第一个时间点和第二个时间点的日期间隔过大，导致仅生成了两个 ticks，而nice:f alse 又把两个坐标点都去掉了，目前先修复这个坐标轴不显示的问题。后面最小时间间隔的计算再进行调整。
* #500 文本布局时坐标系旋转时，需要将坐标转换成画布坐标，defaultOffset 的计算在饼图下也不应该计算，直接返回默认的即可。
> fix(scale): fixed bug of #520

- src/index.d.ts
Some func signature is wrong and cause typescript to throw error to block compile
有些typescript定义漏掉了，导致typescript在编译的时候会报错，我根据代码把漏掉的加上了。
> fix(typing): add missing implicit type definition

- src/chart/controller/axis.js
- src/component/axis/base.js
坐标轴样式根据linear和category区分
使用：
默认为linear和cat样式分开
如果在axis配置项设置为alignWithLabel:true,则cat数据坐标轴回到3.1默认状态：
—————————————————————————————
我们先讨论下这样区分可不可行，如果可行的话我把用例和文档加上
> Linear category axis

- src/component/tooltip/index.js
将crosshair的辅助线中增加capture属性设置为false，使其能够在鼠标滑动后不触发事件
> 禁用crosshair辅助线的捕获

- package.json
+ fix typescipt requirement issue
+ package.json 中 `main` 字段指向无效，build 过后的 lib 文件夹中并没有 g2.js。
+ 由于 `browser` 字段指向是对的，所以通常使用的时候会直接用 `browser` 代替掉 `main`，所以不会有问题。
+ 在 typescript 中引用的话就会找不到导致编译失败。
> 修复 package.json 中的 main 字段

- src/chart/chart.js
- src/chart/controller/legend.js
- test/unit/chart/controller/legend-spec.js
> feat(legend):multi-geom legend support

- src/coord/polar.js
- test/bugs/issue-689-spec.js
- test/unit/chart/controller/axis-spec.js
修复 #689 
修改边缘检测逻辑:  从startAngle到endAngle 每10角度取样
> fix(Coord.Polar): 修复极坐标图像超出画布的问题

- src/geom/util/path.js
- test/bugs/issue-730-spec.js
> fix(PathUtil.convertPolarPath): 保证极坐标图形圆弧方向为圆心向外

- src/component/legend/category.js
当使用legend的useHtml为true时，由于传入的字段name中存在双引号会直接导致在legend的节点中data-value的数据出现问题，之后点击legend无法顺利隐藏图例，使用正则转义一下
> 修复如果legend值中存在双引号"时，导致的无法点击触发legend正常操作bug

- src/chart/controller/legend.js
- src/theme/default.js
修复了svg支持时变更的backrange计算问题，此问题会导致使用自定义legend和使用guide的场景下legend定位错误。
> fix(legend):chart backplot range calculation

- src/geom/mixin/active.js
之前萧庆提的issue: https://github.com/antvis/g2/issues/723
看了一下源码确实是一个bug，原因是线图为stoke绘制，fillOpacity不生效，改成了整个shape的透明度，修复这个bug
> 修复线图active高亮不生效的bug

- src/component/tooltip/index.js
将 tooltip.setMarkers 函数中 markerCfg 的 fill, symbol, shadowColor 属性调整到前面作为默认项。可以被 Theme 设置覆盖。
> fix(tooltip): Theme.tooltipMarker invalid. Closes #757

- src/component/legend/size.js
- src/component/legend/slider.js
- src/component/legend/tail.js
- test/unit/component/legend/color-spec.js
- test/unit/component/legend/size-spec.js
* size-legend的scroll-bar尺寸加约束
* 修复了(size/color legend里slider的mousemove事件，使mousemove的作用域限定在legend本身的区域范围内）
* 将pie chart label的布局算法移植到tail legend，基本解决了纵向布局问题。同时开启了autoLayout配置项，默认开启，如设置为false，则不进行legend的重新布局。
> fix(legend):constrain size legend scroll bar size

- src/index.d.ts
原来为：
tooltip(tooltipConfig: TooltipConfig): this;
tooltip(tooltipConfig: boolean): this;
改为：
tooltip(tooltipConfig: TooltipConfig | boolean ): this;
>  d.ts文件方法定义bug，修改tooltip方法，旧的存在bug，导致typscript报错，无法使用第一个方法。

- src/chart/controller/tooltip.js
- test/unit/component/guide/arc-spec.js
1.当设置tooltip的shared字段为false时，tooltip默认为top位置，注释掉赋值代码，使tooltip随鼠标随动
2.由于pre-commit时，猜测是之前兼容svg导致的测试项宽高不再是负无穷了，改为0
> Fix shared bug

- src/chart/controller/legend.js
问题描述：https://riddle.alibaba-inc.com/riddles/c8576dc9
如上述riddle展示的，新版本g23.3.1中由于legend直接获取x和y的值为undefined，导致后续矩阵计算时出现NaN，引起legend位置错乱。
修复方案：
获取的实际x和y的值是在legend内部的示例group上，所以加深获取一层，通过先获取group再获取其上的坐标值
> 修复多面图时导致的legend显示位置bug

- src/geom/label/geom-labels.js
Protect `items`, because `getLabelItems` may get the result of `null`.
> Protect label of `null` value.

- src/theme/dark.js
- src/theme/default.js
theme 中的 tooltipCrosshairsLine 和 tooltipCrosshairsRect 无效。
原因 theme 中的命名是 tooltipCrosshairsRect: {
style: {
fill: '#CCD6EC',
opacity: 0.3
}
},
在 crosshair 组件中使用样式时区分的，分别是 lineStyle 和 reactStyle
使用直接取 lineStyle 和 reactStyle  所以 theme 中的 style 失效了。
因此修改 theme 模板命名，这样就不用动代码了。
> fix issue1014

- src/geom/label/geom-labels.js
> fix(geom-labels): if htmlTemplate is set, useHtml is true by default

- src/chart/controller/legend.js
- src/index.d.ts
to enable/disable the default legend-item handler function when the legend's "itemclick" event
triggered, even if the customer defined his/her own click handler.
fix #1051
> feat(legend): enable default legend-item handler

- src/chart/controller/scale.js
- src/chart/view.js
这个修复主要是针对用brush筛选数据时, 如果对应列指定了min和max, 那么筛选后生成的ticks还是会受其影响; 如下图
在个人从实际使用的角度来看, 对于filter后数据min max应该是没有意义的
> fix(scale & filter): remove min max limit if field filtered

- src/geom/shape/interval.js
https://antv.alipay.com/zh-cn/g2/3.x/demo/other/column-error.html#
抱歉，由于之前修复问题时没有验证完全，直接采用size为线宽的话违背了这个图想要展示的样子，引以为戒，之后验证实现会更仔细一点
> 修复显示钉子图后直接完全覆盖绘制的bug

- src/component/tooltip/index.js
---
setInterval 1000秒调用chart.changeData(data)时, 同时在canvas中高频率的滚动鼠标滚轮和移动鼠标指针
```
g2.js:38493 Uncaught TypeError: Cannot read property 'style' of undefined
at HtmlTooltip.hide (g2.js:38493)
at TooltipController.hideTooltip (g2.js:44215)
at TooltipController.showTooltip (g2.js:44453)
at TooltipController.onMouseMove (g2.js:44235)
at Chart.method (g2.js:30471)
at Chart.emitEvent (g2.js:6533)
at Chart.emit (g2.js:6561)
at EventController.onMove (g2.js:44673)
at Canvas.method (g2.js:30471)
at Canvas.emitEvent (g2.js:6533)
at Canvas.emit (g2.js:6561)
at Canvas._triggerEvent (g2.js:23450)
at HTMLCanvasElement.<anonymous> (g2.js:23476)
```
---
> fix(HtmlTooltip): 在特定场景下HtmlTooltip.hide()时大概率获取不到container

- src/geom/shape/schema.js
> fix(schema): use cfg.color for lineAttrs.stroke if available.

- src/index.d.ts
- test/types/g2-test.ts
'line' type wasn't available in TooltipConfig but works when used. So I updated G2.TooltipConfig type definitions and according tests.
> fix(tooltip): Added line to TooltipConfig crosshairs type

- package.json
- src/chart/controller/legend.js
- test/bugs/issue-1158-spec.js
- test/bugs/issue-439-spec.js
#1158  出现的原因是部分 marker 的绘制是需要设置 `stroke` 描边颜色的，而我们在代码里面统一使用了 `fill` 填充属性，另外对于不再支持的 marker 文档没有及时更新，同时 G 的 marker 也需要提供容错机制。
> Fix issue 1158

- src/geom/label/geom-labels.js
When we add labels of geom, some labels are often overflowed because of the range of canvas. I want to add `point` and `index` to the callback of label to enable return different `offset` through calculating the position of geom. 
- https://github.com/antvis/g2/issues/1045
> add parameters `point` and `index` to the callback of label

- src/chart/controller/tooltip.js
- test/bugs/issue-1271-spec.js
由于tooltip是DOM而不是Canvas，设置渐变色时，marker无法正常显示。在src/chart/controller/tooltip.js中的showTooltip()函数里增加了判断条件。如果，设置的颜色是渐变色，则取渐变色的起始颜色作为marker的颜色，可以暂时解决这个问题。
> Fix issue 1271

- demos/arc.html
当视口宽度过小时，chart的初始化左右padding为0会造成节点上的文字溢出而被遮盖
**修改前**
**修改后**
> fix: 修复了demos/arc.html初始化左右padding过小引起的文字遮盖

- src/chart/controller/tooltip.js
- test/bugs/issue-1271-spec.js
When the user sets the tooltip to be rendered in Canvas, previous fix to issue 1271 could cause problems. This commit fixes aforementioned problem.
> fix 1271 supplementally to fit the tooltip rendered by canvas

- src/interaction/brush.js
fix #1321 
brush拖动距离少于1px时，会被视为点击事件误触，但brush矩形不会被清除。修复该bug。
> fix(brush):fix the bug that the selection rect is not cleared

- .travis.yml
- demos/area-line-stack.html
- package.json
- src/chart/controller/tooltip.js
- src/component/tooltip/index.js
- src/theme/default.js
tooltip开放`marker`配置，能够返回`activeSymbol`来实现如下效果：
> 开放定制tooltip中marker，以及图形上对应的marker

- packages/component/__tests__/unit/tooltip/base-spec.js
- packages/component/__tests__/unit/tooltip/canvas-spec.js
- packages/component/__tests__/unit/tooltip/html-spec.js
- packages/component/src/tooltip/canvas.ts
- packages/component/src/tooltip/html.ts
- packages/g2/src/plot/controller/tooltip.ts
修改Tooltip.setPosition方法，在inPanel条件下，去看panelRange是否有clip属性，如果有clip属性，则需要在clip range的范围内调整tooltip位置，应用在柱形图有滚动条的情景下；不影响原有情况即panelRange无clip的情形。
> fix(tooltip): fix tooltip position when panelGroup has clip attr

- packages/g2/src/plot/controller/legend.ts
在滚动条场景下给panelGroup设置了clip后，需要对legend的maxWidth/maxHeight做修正
> legend在panelGroup有clip属性的时候的高宽限制

- src/component/tooltip/index.js
…init
modify file: /src/component/tooltip/index.js
modify function: setPosition.
change container to visible before get width&height of container, and change back after set position.
> fix(tooltip position):position will be wrong when tooltip init

- src/interaction/brush.js
现在brush的时候仍然会按transpose之前的字段进行filter，我加了一下tranpose的判断。
另外不太清楚brush type里 'X' 和 'Y' 需不需要受transpose影响
> fix(brush): brush filter wrong data when coord transpose

- src/geometry/geometry.ts
- tests/unit/geometry/geometry-spec.ts
https://github.com/antvis/g2/issues/1511 
是由于缓存了 groupScales 导致的，如果重复调用 chart.render() 方法，在进行 geometry.init() 时会影响数据的分组。
> 修复重复调用 chart.render() 绘制出错的问题

- src/chart/__components__/mock-component.ts
- src/chart/view.ts
- src/geometry/interval.ts
- tsconfig.json
`baseUrl` 会导致编译出来的代码一样是以 baseUrl 为相对路径的，那么在上层 import g2 的时候，会导致找不到文件路径。
所以删除掉，并更新 import 的写法，还是以相对路径来写。
> remove baseUrl of tsconfig

- src/chart/view.ts
- src/geometry/base.ts
- src/util/scale.ts
- src/util/tooltip.ts
- tests/unit/util/scale-spec.ts
- tests/unit/util/tooltip-spec.ts
主要迁移 3.6.x 中的 geometry 下 tooltipController 的代码，在 4.0 里面通过工具函数的形式提供
* `findDataByPoint(point, data, geometry)` 对应 3.6 的 `findPoint(point, data)`
* `getTooltipItems(data, geometry)` 对应 3.6 的 `getTooltipItems(data, title)`，4.0 中不再支持传入 title 字段，后续以 Tooltip 组件的需求为准，看是否加入
> 添加 Tooltip 相关的工具函数

- package.json
- src/dependents.ts
- src/geometry/base.ts
- src/geometry/shape/area.ts
- src/geometry/shape/base.ts
- src/geometry/shape/index.ts
- src/geometry/shape/interval.ts
- src/geometry/shape/line.ts
- src/geometry/shape/point.ts
- src/geometry/shape/polygon.ts
- src/geometry/shape/util/path.ts
- src/interface.ts
- tests/unit/geometry/element/index-spec.ts
- tests/unit/geometry/shape/area-spec.ts
- tests/unit/geometry/shape/base-spec.ts
- tests/unit/geometry/shape/interval-spec.ts
- tests/unit/geometry/shape/line-spec.ts
- tests/unit/geometry/shape/point-spec.ts
- tests/unit/geometry/shape/util/path-spec.ts
API：
```ts
const shapeFactory = geometry.getShapeFactory();
const marker = shapeFactory.getMarker(shapeType, color, isInPolar);
```
返回的结果类型见： https://github.com/antvis/g2/commit/06caa1301f83600b5a5550d8dc59684874ceb45e#diff-cfe98604c7d056c8adca06c7dfddd5cdR120
另外该分支引入了 g-base 的 PathCommand 类型定义，目前会报错，需要这个 PR 合并，G 发个版本方可。https://github.com/antvis/g/pull/258
> Shape 添加 getMarker() 方法

- examples/column/stack/demo/rounded-stacked.js
> fix: fix rounded-stacked demo

- src/chart/controller/legend.js
[Demo Link](https://jsfiddle.net/hengwensite/6Lrhkqfx/4/)
场景：一个图里有三条线，当日值，对比日值和比对比日的比率，希望图里只展示当日值和对比日值两条线，比对比日的数据不在趋势图和图例上呈现，只在 tooltip 显示。
解决方案：在 `addMixedLegend` 方法中过滤掉不需要展示的y轴。
| 🇺🇸 English |    Fix failure of `chart.legend(field, false)` in case of multiple y axes      |
| 🇨🇳 Chinese |  修复多y轴情况下`chart.legend(field, false)`失效问题    |
> fix: 多y轴无法隐藏指定legend

- CHANGELOG.md
- README.md
- README.zh-CN.md
- gatsby-config.js
- package.json
> 🚀 g2.antv.vision

- src/chart/controller/tooltip.ts
- src/geometry/animate/index.ts
- src/geometry/base.ts
- src/geometry/interval.ts
- src/geometry/path.ts
- src/geometry/point.ts
- src/geometry/polygon.ts
- src/interface.ts
- src/util/tooltip.ts
- tests/unit/geometry/element/index-spec.ts
- tests/unit/util/tooltip-spec.ts
Closed #1653 
* 保留 shape.get('origin')，`origin` 存储的是绘制 shape 的所有信息，即传入自定义 shape `draw(cfg, element)` 方法的第一个参数 cfg 的值
* `_orgin` 字段只在内部使用
* 外部用户通过获取  shape.get('origin') 的 `origin `属性中的 `mappingData` 和  `data` 来取得映射后的数据和原始数据。后面给用户的认知就是： mappingData 代表的是映射后的数据，`data` 代表的就是原始数据
* 优化 geometry 代码中关于数据的类型定义，让代码阅读者更好得理解数据流转过程
> 优化 Geometry 中数据相关的类型定义

- packages/component/src/tooltip/crosshair.ts
- packages/component/src/tooltip/html.ts
> 3.6.x: 组件绘制层级错误

- src/chart/view.ts
解决 view 中各个 Geometry  label 遮挡的问题。 Geometry 的 label 将统一存储在 foregroundGroup 中。
> refactor: view 的三层 group 不从父 view 的 middleGroup 中创建，而是从父 view 对应的层级中创建

- examples/column/basic/demo/helix-coordinate.js
- examples/column/basic/demo/image-top.js
- examples/column/basic/demo/marked.js
- examples/column/basic/demo/waterfall.js
- examples/column/dodge/demo/circular-stacked.js
- examples/column/dodge/demo/column-clustered-stacked.js
- examples/column/dodge/demo/column12.js
- examples/column/histogram/demo/histogram-binwidth.js
- examples/column/histogram/demo/histogram-stacked.js
- examples/column/histogram/demo/histogram.js
- examples/column/stack/demo/polar-stack.js
- examples/column/stack/demo/rounded-stacked.js
- examples/column/stack/demo/rounded.js
- examples/column/stack/demo/stacked-percentage.js
- examples/column/stack/demo/wind-rose.js
- examples/pie/basic/demo/pie-size.js
- src/chart/controller/annotation.ts
- src/chart/controller/legend.ts
- src/chart/layout/index.ts
- src/chart/view.ts
- src/geometry/element/index.ts
- src/util/grid.ts
> column demos & bugfix

- src/util/bbox.ts
> fix(coordinate): fix coordinate is undefined after layout

- src/chart/component/axis.ts
- tests/unit/component/axis-circle-spec.ts
Fixed https://github.com/antvis/G2/issues/1715#issuecomment-563052470
> fix: 极坐标下值坐标轴文本应该朝左放置

- src/chart/view.ts
- tests/unit/chart/chart-spec.ts
> fix(event-rect): not remove event rect after clear

- gatsby-config.js
https://github.com/gatsbyjs/gatsby/issues/20082#issuecomment-568292986
| 🇺🇸 English |    none       |
| 🇨🇳 Chinese |   none        |
> fix: Reducers may not dispatch actions

- src/chart/controller/legend.ts
- src/chart/layout/index.ts
> fix(layout): legend 布局上，需要和 coordinateBBox 对齐

- src/util/direction.ts
- tests/unit/util/direction-spec.ts
> fix(reflect): 修复 reflect 之后，轴位置不正确的问题

- examples/relation/relation/demo/chord.ts
- examples/relation/relation/demo/sankey.ts
- src/chart/view.ts
- tests/unit/chart/view/scale-sync/multi-view-sync-scale-spec.ts
多 view 嵌套的时候，因为 view.render 的递归执行中，一个 view 完全渲染完成之后，才渲染另外一个。
导致先渲染的 view geometries 使用的 scale 不是完全同步完成的 scale，所以图形对不齐。
- renderDataRecursive
- renderLayoutRecursive
- renderUIRecursive
render 的三个步骤中，每个步骤都是执行完所有的嵌套 view，才执行下一步。
> Fix view render recursive

- examples/component/component/demo/meta.json
- examples/component/component/demo/tooltip-1.ts
- examples/component/component/demo/tooltip-2.ts
- examples/component/component/demo/tooltip-3.ts
- src/chart/controller/tooltip.ts
- src/chart/interface.ts
- src/dependents.ts
- src/theme/antv.ts
- tests/unit/chart/controller/tooltip-spec.ts
- tests/unit/component/tooltip-crosshairs-spec.ts
1. 移除当前 Tooltip  组件默认自带 html crosshairs，HTML 版本的 crosshairs 组件的支持需要将来 Component 将其从 Tooltip 组件中拆分出来，详见： https://github.com/antvis/component/issues/122
2. 接入 Crosshairs 组件，修改 G2 层 tooltip 的配置项，同时支持极坐标下的  crosshairs ~~~ 同时 crosshairs 可以带文本
```ts
chart.tooltip({
showCrosshairs: true,
crosshairs: {
type: 'xy',
line: {
style: {
stroke: '#565656',
lineDash: [4],
},
},
}
});
```
| **坐标系** | **type = 'x'** | **type = 'xy'** | **type = 'y'** |
| :---: | :---: | :---: | :---: |
| 直角坐标系 |  ![6](https://user-images.githubusercontent.com/6628666/72583993-53282580-3923-11ea-8373-dac583cab8c4.gif)  |  ![2](https://user-images.githubusercontent.com/6628666/72583996-57544300-3923-11ea-9488-ab42fde69307.gif) |   ![7](https://user-images.githubusercontent.com/6628666/72584000-5b806080-3923-11ea-8d99-d0a7da81 …
> 可『弯』可『直』的 tooltip 辅助线

- src/chart/controller/legend.ts
- src/theme/antv.ts
- tests/unit/chart/controller/legend-spec.ts
- tests/unit/component/legend-category-spec.ts
> fix(legend): fix legend overlap

- src/chart/view.ts
- src/util/legend.ts
- tests/unit/chart/view/index-spec.ts
- tests/unit/component/legend-unchecked-spec.ts
目前存在问题：交互上，可以将所有的图例项都 unchecked，然后控制台报错 @dxq613 ，大概是交互中无法通过 items.unchecked 获取 unchecked 状态。
> Feat category legend unchecked

- packages/component/src/legend/category/canvas.ts
原有判断逻辑存问题，应该是当前绘制区域宽/高与实际图例宽/高进行对比，会导致无需翻页器的场景计入翻页器高度，导致 padding 过多。例如：https://github.com/antvis/G2Plot/issues/617
> 【G2 3.6.x】fix: 修复 legend 翻页判断问题

- tsconfig.json
由于 tsconfig.json 中 include 包含了 tests，因此编辑结果如下：
这样导致 package.json 中 main、module、types 的引用地址出现错误，使用 npm 包时会使用 g.min.js，在 G2Plot 中不易调试 G2
test 文件由于已经使用了 ts-jest，理论上不需要在 build 阶段编译了，可以去除
> fix: 修复 package.json 中 main、module、types 的引用地址问题

- src/chart/controller/coordinate.ts
- tests/bugs/2044-spec.ts
- tests/bugs/active-region-spec.ts
Closed #2044
等待 https://github.com/antvis/coord/pull/7 合并之后发版本，这边的 ci 才能通过。
> fix(coordinate): redo matrix actions when adjust coordinate start end

- src/chart/controller/legend.ts
- tests/unit/component/legend-category-spec.ts
> fix(legend): 分页图例设置 maxWidth、maxHeight 导致位置不正确

- packages/g2/package.json
- packages/g2/src/element/base.ts
从4.x的PR https://github.com/antvis/G2/pull/2035 迁移到3.5.x分支上
> fix: 堆叠下scale的min/max设置修复

- packages/component/src/legend/category/canvas.ts
修改 isNeedFlip 的逻辑正确后，正确的流程应该是：
1. 渲染所有的 items
2. 根据所有的 item 的 bbox 判断是否需要翻页
3. 调整 items 自动换行
4. 根据是否需要翻页，渲染翻页器
之前 2，3 反了
> [3.6.x] fix: 修复legend 无法翻页的问题

- examples/pie/basic/demo/labelline.ts
- src/component/labels.ts
- src/geometry/label/index.ts
- src/geometry/label/layout/distribute.ts
- src/geometry/label/layout/limit-in-canvas.ts
- src/geometry/label/layout/limit-in-shape.ts
- src/geometry/label/layout/overlap.ts
- src/geometry/label/pie.ts
- src/index.ts
- tests/unit/geometry/label/labels-spec.ts
- tests/unit/geometry/label/layout/limit-in-canvas-spec.ts
- tests/unit/geometry/label/pie-spec.ts
将 pie-label 的 ajustItems 调整至layout处理，由于饼图label 布局中需要使用到 labelItem信息，因此需要将labelItem传递至layoutFn
> refactor(pie-label): 饼图label的调整，移动至layout中处理

- src/chart/controller/annotation.ts
- src/chart/controller/axis.ts
- src/interface.ts
- tests/bugs/2146-spec.ts
Closed #2146.
BUG 原因：没有将用户配置的 `animateOption` 属性传入。
> 修复 chart.annotation() 接口 animateOption 属性不生效的问题

- src/chart/view.ts
- src/geometry/base.ts
- tests/bugs/2186-spec.ts
- tests/bugs/candle-legend-spec.ts
- tests/unit/geometry/label/labels-spec.ts
Closed #2186 
**原因分析：**
因为 View 和 Geometry 的数据保持引用关系（除存在 chart.filter() 外），所以用户在外部通过 data.push() 等不改变引用却修改了内容的方式更新数据源的时候，https://github.com/antvis/G2/blob/master/src/geometry/base.ts#L795 
Geometry 这里的代码判断数据是相等的（因为是引用关系，外部 data 改变了 geometry.data 也相应改变了），所以就会出现不更新的情况。
> fix(data): 修复使用数据引用造成数据未更新的问题

- examples/bar/basic/demo/radial-bar.ts
- examples/bar/basic/demo/radial-line.ts
- examples/bar/stack/demo/meta.json
- examples/bar/stack/demo/radial-stacked.ts
- src/chart/controller/axis.ts
- src/util/grid.ts
- tests/bugs/1744-spec.ts
- tests/unit/util/grid-spec.ts
Closed #1744 
1. 默认在用户不配置的情况下不渲染。
2. 当用户通过配置可以开启
```ts
chart.axis(true);
chart.axis('x', true | {});
chart.axis('y', true | {});
```
3. 同 polar 不同的是，转置后，半径轴渲染的是直角坐标系下的 x 轴，圆弧轴渲染的是直角坐标系下的 y 轴
> 支持转置极坐标下坐标轴的渲染

- CHANGELOG.md
- package.json
- src/core.ts
- **axis:** 支持转置极坐标坐标轴的渲染， Closed [#1744](https://github.com/antvis/g2/pull/1744) ([67a8beb0](https://github.com/antvis/g2/commit/67a8beb042093774f6746450251ce2bfd472719f))
- **scale:** 支持用户指定确定数据 id 的字段 ([25caa91f](https://github.com/antvis/g2/commit/25caa91f05dd918b3e798b57b6d6f524f67354cb))
- **tooltip:**
- `position` 属性新增 'auto' 值配置，并作为默认值 ([8c3fda47](https://github.com/antvis/g2/commit/8c3fda47779d49649776a16e55829f20793004f9))
- tooltip 体验优化，当鼠标离开 tooltip 内容框时，非 locked 状态自动隐藏 ([9f8fcad2](https://github.com/antvis/g2/commit/9f8fcad2175704dc6f3ba742c77e4f1d95e9e211))
- 通过 pointer-events 属性来达到 tooltip 躲避鼠标的交互效果 ([2e750aa4](https://github.com/antvis/g2/commit/2e750aa4fab269d573da9d035804e1bcd8fe53de))([d5f1e21c](https://github.com/antvis/g2/commit/d5f1e21ca9508f957d994634dc62d1d2b7f2cfcc …
> chore: release v4.0.3

- package.json
- src/chart/chart.ts
- src/util/dom.ts
- tests/bugs/2195-spec.ts
- tests/unit/chart/chart-auto-fit-spec.ts
closed #2195 
chart 的大小，还是使用用户传入的 size，然后在计算 container size 的时候，处理掉 padding 影响。
> fix(#2195): fix autoFit 不生效

- src/index.ts
- src/interaction/action/element/range-state.ts
- src/interaction/grammar-interaction.ts
- tests/unit/interaction/action/highlight-spec.ts
* 个别交互在频繁操作的时候，有 js 报错的现象，发现是由于交互引起了新的事件，导致 context.event 清空了，所以每次执行前需要设置 context.event 。
> feat(interaction): avoid event error

- src/geometry/label/base.ts
- tests/bugs/2272-spec.ts
label 的问题已修复，但是无法绘制的问题需要  G2 层解决，详见 https://github.com/antvis/g2/issues/2272#issuecomment-610212056
但是可以像测试用例一样把局部刷新关掉！https://github.com/antvis/G2/compare/issue-2272?expand=1#diff-8ea33c131492f7875704e54499100cb6R16
> fix(#2272): 当映射数据中不存在 x 和 y 时，不绘制 label

- package.json
修复 site build 报错的问题。
注意不能用 `tnpm` 和 `cnpm`，会报 `$export is not a function` 的问题，原因未知。
先用 `npm` 或者 `tnpm i --by=npm` 来安装。
> fix: site build

- docs/manual/tutorial/slider.en.md
- docs/manual/tutorial/slider.zh.md
- src/chart/controller/slider.ts
- tests/unit/chart/controller/slider-spec.ts
若直接 `mask: 'HH:mm'` 之类需要额外增加 time 的处理，但是 G2 目前没有统一的时间，因此由一种外部自定义选择如何格式化。
- close #2332
> feat(slider): add `formatter` property

- package.json
- src/core.ts
- src/index.ts
> fix(types): remove syntax export * as

- docs/manual/developer/registerlabel.en.md
- docs/manual/developer/registerlabel.zh.md
开发者教程 - 自定义 Label - 自定义Label布局函数 中的example中给出的limitInShape参数有误。
正确的应为
`function limitInShape(items: LabelItem[], labels: IGroup[], shapes: IShape[] | IGroup[], region: BBox)`
> docs(label): 修复文档中Layout Function参数的错误

- CHANGELOG.md
> chore: release v4.0.8

- src/chart/controller/tooltip.ts
- src/index.ts
- src/interaction/action/component/tooltip.ts
- tests/unit/interaction/action/tooltip-spec.ts
两个问题：
- 鼠标直接从 tooltip container 上移动出画布范围时，需要隐藏 tooltip
- 鼠标移动到 tooltip container 上后，在 container 上面移动的时候，也需要更新 tooltip：关联 https://github.com/antvis/component/pull/170 ，配合位置调整后，之前说的闪烁问题大部分情况也还好：需要先隐藏，然后再次触发，再次触发的位置也会更新
> fix: tooltip 调整

- src/chart/controller/legend.ts
- src/util/theme.ts
- tests/unit/chart/controller/legend-spec.ts
G2Plot 中有 bleeding 的概念，在 legend 默认布局上需要加个 margin 才能对齐
> feat: support legend layout margin

- src/chart/controller/annotation.ts
- src/chart/controller/base.ts
- tests/bugs/sub-view-region-filter-spec.ts
> fix(annotation): fix regionFilter not work on sub view

- src/chart/chart.ts
- tests/unit/chart/chart-spec.ts
Check if the chart is destroyed before attempting to resize chart.
The onResize method is debounced so it always gets called
> fix: error if chart destroyed during resize

- src/chart/controller/legend.ts
- src/interface.ts
- tests/unit/chart/controller/legend-spec.ts
目前 legend 的布局范围已经改为整个画布了，但是的最大宽高还是 coordinateBBox，就导致了本该展示一行的图例意外折行了
> fix(legend): 修改 legend 布局的宽高限制

- src/chart/controller/tooltip.ts
之前看源码没注意到 `this.tooltip.set` 方法，测试后可以使用。
> fix: 修复#2279 canvas resize 之后tooltip越界的问题

- package.json
- src/chart/chart.ts
- src/chart/controller/axis.ts
- src/constant.ts
- src/interface.ts
- src/util/theme.ts
- tests/unit/chart/controller/axis-auto-overlap.ts
1. 只作用于直角坐标系
2. 默认 x 轴文本占据最大高度为图表高度的 1/2，y 轴文本占据最大宽度为图表宽度的 1/3，超出则自动旋转、省略
3. 开放 `verticalLimitLength` 属性用于范围限制
> 优化坐标轴超常文本展现策略

- src/component/labels.ts
- src/geometry/label/layout/distribute.ts
- tests/bugs/2347-spec.ts
- tests/bugs/2629-spec.ts
详细看 commit:
close #2647
close #2629
close #2347 
**before**
**after**
> fix(pie-label): 饼图 label 若干修复

- src/geometry/shape/interval/line.ts
- src/geometry/shape/interval/util.ts
- tests/unit/geometry/shape/interval-spec.ts
> fix: 修复 interval 下 shape='line' 设置 lineCap 失效的问题

- docs/manual/tutorial/scale.en.md
- docs/manual/tutorial/scale.zh.md
[scale docs](https://g2.antv.vision/en/docs/manual/tutorial/scale#%E6%89%80%E6%9C%89%E8%BF%9E%E7%BB%AD%E5%BA%A6%E9%87%8F%E9%83%BD%E6%94%AF%E6%8C%81%E7%9A%84%E9%85%8D%E7%BD%AE%E9%A1%B9) ：该文档说明左侧图中 y 轴的数据范围是 【0-12】，并不是【0-1】
> docs: modified scale.md document error

- src/util/theme.ts
解决 tooltip customContent 频繁闪动问题。
> fix: resolve tooltip debounce

- src/chart/controller/annotation.ts
- src/interface.ts
- tests/unit/component/annotation-spec.ts
**背景**
环图使用 annotation 绘制中心汇总指标卡的时候，首次render之前，使用 `chart.getData()` 获取数据为空；
另外，由于饼图图例可以进行数据过滤，相应的中心汇总指标卡也应该进行过滤，所以需要通过 `chart.getData()` 来获取数据
两种解决方案：
1. text annotation， 提供 content 回调的方式，将图表 filteredData 作为入参
2. 业务层监听 图表 render 之后，再执行 annotation，但同时维护也较难
```js
const data = [
{ item: '事例一', count: 40, percent: 0.4 },
{ item: '事例二', count: 21, percent: 0.21 },
{ item: '事例三', count: 17, percent: 0.17 },
{ item: '事例四', count: 13, percent: 0.13 },
{ item: '事例五', count: 9, percent: 0.09 },
];
autoFit: true,
height: 500,
});
chart.data(data);
chart.coordinate('theta', {
radius: 0.75,
innerRadius: 0.6,
});
// 辅助文本
chart
.annotation()
.text({
position: ['50%', '50%'],
content: (chart.getData() || []).reduce((a, b) …
```
> feat(annotation): text annotation content 提供回调，将图表filteredData作为回调参数

- src/chart/view.ts
> chore(view-recursive): add warning message before refactor

- docs/manual/tutorial/tooltip.en.md
- docs/manual/tutorial/tooltip.zh.md
- src/chart/controller/tooltip.ts
- src/chart/event.ts
- tests/unit/chart/controller/tooltip-spec.ts
- tests/unit/chart/view/index-spec.ts
> Fix tooltip events

- src/geometry/element/index.ts
- tests/bugs/2798-spec.ts
> fix(offscreen): sync clip style in offscreen group

- src/chart/layout/auto.ts
- tests/bugs/padding-update-spec.ts
> test(padding): add a test case

- src/chart/controller/scrollbar.ts
- src/chart/controller/slider.ts
- src/util/types.ts
- tests/bugs/2295-spec.ts
- tests/bugs/2433-spec.ts
- tests/unit/chart/controller/slider-spec.ts
> fix: slider bugfix

- src/chart/controller/annotation.ts
- src/constant.ts
- src/geometry/element/index.ts
- tests/bugs/2851-spec.ts
- tests/bugs/sub-view-region-filter-spec.ts
- tests/unit/component/annotation-spec.ts
- tests/unit/geometry/base-spec.ts
- tests/unit/geometry/element/index-spec.ts
- tests/util/omit.ts
> feat(region-filter): add geometry life circle, after draw animate

- docs/api/general/chart.zh.md
- docs/api/general/data.zh.md
- docs/common/style.md
- docs/manual/getting-started.zh.md
- examples/column/basic/demo/basic.ts
- package.json
- site/pages/docs.less
- site/pages/index.less
1. 更新 教程 - get started；API - chart, data 的描述信息；
2. 升级 gatsby 在 markdown 中插入 code playground ➡️ preview url: zh/docs/manual/getting-started
> docs: update chart, data, get-started. add demo playground

- src/util/theme.ts
- tests/unit/component/legend-category-spec.ts
200px 相对来说比较靠谱一些。这个参数对业务来说应该还是很重要的。
> feat(legend): set default maxItemWidth = 200

- docs/manual/concepts/view.zh.md
- examples/map/map/demo/choropleth-map.ts
发现 playground 一个 bug，当一个页面中有多个 demo 的时候，图形绘制到一起了，代码还是分离的。
> docs(view): add docs for view

- src/geometry/base.ts
- src/geometry/shape/base.ts
- src/interface.ts
- tests/bugs/2905-spec.ts
获取图形绘制数据时,若 theme 中未注册,则默认取 shapeFactory 默认shapeType注册的主题样式
closed: #2905
> fix(issue-2905): 自定义 shape 的默认样式设置

- src/chart/controller/annotation.ts
- src/util/annotation.ts
- src/util/stat.ts
- tests/unit/util/annotation-spec.ts
- tests/unit/util/stat-spec.ts
> feat(annotation): add support for mean / median 

- package.json
- src/chart/layout/padding-cal.ts
- src/chart/util/sync-view-padding.ts
- src/chart/view.ts
- src/core.ts
- src/interface.ts
- tests/bugs/2849-spec.ts
- tests/unit/chart/layout/padding-cal-spec.ts
> feat(view): add syncViewPadding support callback

- src/geometry/label/layout/adjust-color.ts
- src/interface.ts
- src/theme/style-sheet/dark.ts
- src/theme/style-sheet/light.ts
- src/util/color.ts
- src/util/theme.ts
- tests/unit/geometry/label/layout/adjust-color-spec.ts
- tests/unit/util/color-spec.ts
- 主题 label 相关的配置增加 overflowLabels 配置
- adjustColor 判断是否 overflow 来应用样式
adjust-color 仍只使用与处理在图形内部的 label，即 innerLabels，需要事将 label 设置为内部的，或使用其他 layout 来让 label 变成 inner。
> fix: adjust color 支持超出图形的数据标签

- src/animate/animation/sector-path-update.ts
In a project, I'm getting `Cannot read property '0' of undefined`. Sentry report:
```
Crashed in non-app:
/tmp/build_dfe7ac4f_/node_modules/@antv/g2/esm/animate/animation/sector-path-update.js in getArcStartPoint
```
This is (superficially) because there's nothing that checks whether `toAttrs.path` is a valid `PathCommand[]`. I've added that check with an early return.
> fix: return early from sectorPathUpdate if path is invalid

- src/chart/controller/tooltip.ts
- src/interface.ts
- tests/unit/chart/controller/tooltip-spec.ts
tooltip 支持配置 reversed 来逆序默认的 tooltip items，配合 G2Plot bar 将数据逆序后的 tooltip 顺序和柱子顺序不一致问题
> feat: support tooltip reversed cfg

- src/geometry/label/layout/limit-in-plot.ts
- src/index.ts
- src/util/coordinate.ts
- tests/unit/geometry/label/layout/limit-in-plot-spec.ts
- tests/unit/util/coordinate-spec.ts
limitInPlot 用来解决 label 和 坐标轴之类的组件出现的重叠遮挡问题：
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1142242/100705827-dd199980-33e2-11eb-8e1f-c922ddcaec6d.png) | ![image](https://user-images.githubusercontent.com/1142242/100705979-1d791780-33e3-11eb-95c9-fd9e64f99906.png) |
配置方式：
```js
view1.line().position('Year*Deaths').label('Deaths', {
layout: [
{ type: 'limit-in-plot' },
{ type: 'path-adjust-position' },
{ type: 'limit-in-plot', cfg: { action: 'hide' } }
]
});
```
> feat(label): add limitInPlot label layout

- src/util/scale.ts
- tests/unit/geometry/interval-spec.ts
- tests/unit/util/scale-spec.ts
对于‘2010-10-01’ 类似的数据，默认使用 timeCat 类型
> fix: 更改默认 scale type 设置：time -> timeCat

- src/interface.ts
- src/theme/style-sheet/dark.ts
- src/theme/style-sheet/light.ts
- src/theme/util/create-by-style-sheet.ts
- tests/unit/chart/controller/axis-spec.ts
- tests/unit/chart/controller/legend-padding-spec.ts
- tests/unit/chart/controller/legend-spec.ts
- tests/unit/interaction/action/ellipsis-text-spec.ts
- tests/unit/theme/create-theme-spec.ts
1. 调整坐标轴标签默认的 autoHide 配置，默认开启 autoHide，并设置最小间距 6px
| before | after|
|--- | --- |
| ![image](https://user-images.githubusercontent.com/1142242/100538364-517cfd00-326a-11eb-9a09-1ba080ad86a9.png)| ![image](https://user-images.githubusercontent.com/1142242/100538359-3f02c380-326a-11eb-953a-dcd451a7af6f.png)| 
2. 调整图例的默认 padding，使得图例和图形对齐
- 可通过主题分别对水平布局的图例和垂直布局的图例分别配置 padding
- 默认的 light/dark 主题设置合适的 padding
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1142242/101777075-e7e3d500-3b2c-11eb-843c-5d67a65b3066.png) | ![image](https://user-images.githubusercontent.com/1142242/101777282-35604200-3b2d-11eb-84c9-7dd476f8ea1a.png) |
> fix auto hide legend padding

- src/chart/controller/annotation.ts
- tests/bugs/3108-spec.ts
修复问题：https://github.com/antvis/G2/issues/3108
之前添加一个 html container 是为了修复 html annotation 没有清除掉，这里可以像其他 controller 一样，clear 的时候直接清除创建的组件就可以。
> fix: fix empty div container for annotation

- examples/case/line/demo/line8.ts
https://g2.antv.vision/zh/examples/case/line#line8 因为自定义 Shape 写法不规范，导致图形在更新的时候好出错，将进一步导致如图例筛选等交互无法使用，这里更正下 DEMO 中的自定义 Shape 写法。
> docs: fix legend filter bug on case line demo

- package.json
- src/animate/animation/sector-path-update.ts
- src/core.ts
- src/dependents.ts
- src/geometry/element/index.ts
- src/interaction/action/component/list-highlight-util.ts
- src/interaction/action/util.ts
- src/interaction/action/view/button.ts
- src/theme/util/create-by-style-sheet.ts
- tests/bugs/2173-spec.ts
- tests/unit/component/axis-circle-spec.ts
- fixed https://github.com/antvis/G2/issues/3053
- fixed https://github.com/antvis/G2Plot/issues/1894
- fixed https://github.com/antvis/G2/issues/2928
> fix(esm): remove all lib import

- src/component/labels.ts
- src/geometry/label/pie.ts
- tests/bugs/3146-spec.ts
**背景** label 标签色跟随了 theme 设置，存在一个默认色。在 deepMix 下，undefined 会取默认色，null 则会导致标签渲染不出，因此可以在 `fill` 为 `null` 或空字符串的时候，处理为跟随切片颜色，若用户的确不想渲染 label，可以取 `fillOpactity` 为 0，或`label: false`
- fill 为 undefined 时，跟随旧逻辑，取默认色
- fill 设置为 null 时，映射为对应块的颜色
close: #3146
> feat: 增强饼图标签跟随切片颜色

- src/geometry/label/base.ts
- tests/bugs/g2plot-2081-spec.ts
修复使用interval绘制直方图情况下的 Label 的位置：x 方向取平均值，而不是最后一个对应的 X
close https://github.com/antvis/G2Plot/issues/2081
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1142242/103011007-2be6c900-4574-11eb-93d5-6d19e1aebc5c.png) | ![image](https://user-images.githubusercontent.com/1142242/103011057-402ac600-4574-11eb-9139-db55e934476d.png) |
> fix: correct label position for histogram

- src/geometry/base.ts
- tests/unit/geometry/base-spec.ts
- **feat:** geometry 增加 `sortZIndex` 配置项，允许配置 geometry 下的 elements 的展示(zIndex)排序规则
> feat: 支持对 geometry 下的 elements zIndex 进行降序

- src/interaction/action/component/tooltip/ellipsis-text.ts
- tests/bugs/tooltip-tip-max-width-spec.ts
1. tooltip  tip 最大宽度 50%
2. 超长自动换行
> fix(tooltip-tip): label tip max width 50%, and break word

- examples/column/basic/demo/corner-radius.ts
- examples/column/basic/demo/meta.json
- src/geometry/shape/interval/index.ts
- src/geometry/shape/interval/util.ts
- tests/unit/geometry/shape/interval-spec.ts
- tests/unit/geometry/shape/interval-util-spec.ts
**interval 支持配置 `style.radius`**: 柱状图支持圆角
- 目前支持笛卡尔坐标系下的 `interval` geometry 且 shape 为 `rect` 的几何图形进行设置 `radius`
- radius 配置说明
|||
|---|---|
|非转置坐标系|![image](https://user-images.githubusercontent.com/15646325/104416266-7b864680-55ae-11eb-9bdc-5cc005393f96.png)|
|转置坐标系|![image](https://user-images.githubusercontent.com/15646325/104417065-c6ed2480-55af-11eb-8155-c27f9e4a0d83.png)|
| **Config**| **After** |
|---|---|
| `interval().position('x*y').style({ radius: [20,20,0,0] })` | ![](https://gw.alipayobjects.com/zos/antfincdn/7asolORz4s/2781b4e3-3d12-43c7-8646-124e400d5182.png)|
|||
|---|---|
|正常场景|![image](https://user-images.githubusercontent.com/15646325/103509954-30c64980-4e9f-11eb-9120-a629f010308f.png)|
|堆叠场景|![image](https://user-images.githubusercontent.com/15646325/103509888-10968a80 …
> feat: interval support cornerRadius(方案梳理中)

- src/chart/controller/tooltip.ts
- src/interface.ts
- src/util/tooltip.ts
- tests/bugs/1518-spec.ts
> feat(tooltip): add tooltip.showNil

- package.json
- src/geometry/shape/line/index.ts
- tests/performance/component/tooltip/pick-spec.ts
需要全量回归。smooth 绘制使用 path，而鼠标事件在 path 的拾取非常慢，1000 个点足以崩溃。
> perf(smooth): smooth line do not capture event

- docs/common/marker-cfg.md
- src/interface.ts
- src/util/legend.ts
- tests/unit/util/legend-spec.ts
| **config** | **4.1.9** |**4.1.10** |
| --- | --- | --- |
| `chart.legend({ marker: { symbol: 'hyphen',  style: { lineWidth: 2, stroke: 'red'  } } })` | ![image](https://user-images.githubusercontent.com/15646325/106421546-de754a00-6497-11eb-9797-9583936ce323.png)| ![image](https://user-images.githubusercontent.com/15646325/106422729-0e255180-649a-11eb-810c-9310742a5c32.png) |
| **旧写法：** `chart.legend({ marker: { symbol: 'square', style: { stroke: '#ddd', fill: null } }})`  **新写法：** `chart.legend({ marker: { symbol: 'square', style:  ({ fill, ...args }) => ({ ...args, lineWidth: 1, stroke: fill, fill: null }) }})`  |  ![image](https://user-images.githubusercontent.com/15646325/106422986-84c24f00-649a-11eb-836b-669f2dcc89ce.png) interval 设置空心的图例 marker，描边色无法对应 | …
> fix: 修复实心的 shape 设置空心的 marker，会导致marker.style设置不生效

- src/chart/controller/tooltip.ts
- src/interface.ts
- tests/bugs/g2plot-2223-spec.ts
- tests/unit/chart/controller/tooltip-spec.ts
在 G2Plot 桑基图中，需要根据不同的数据，决定是否显示 tooltip，G2Plot 内置默认 node 不显示 tooltip，edge 显示 tooltip！
> feat(tooltip): tooltip.showContent support function

- src/index.ts
> feat: export constants like: view-life-circle

- src/chart/view.ts
- tests/unit/chart/event/event-spec.ts
触发 plot 事件的时候，不应该修改事件 type。应该保持 emit 类型 和 event 的 type 类型一致
> fix(event): 修复相同 type 时间触发两次

- src/chart/view.ts
- src/interaction/action/active-region.ts
- tests/unit/interaction/action/active-region-spec.ts
目前建议全局使用统一的 active-region 交互样式，因此需要先注册交互，再进行使用
使用方式 1⃣️：
```ts
// 覆盖注册, 且需要 chart 重新绑定交互. 或者不进行覆盖，使用新的 interaction name
registerInteraction('active-region', {
start: [
{ trigger: 'plot:mousemove', action: 'active-region:show', arg: { style: { fill: 'rgba(255,0,0,0.25' } } },
],
end: [{ trigger: 'plot:mouseleave', action: 'active-region:hide' }],
});
chart.interaction('active-region');
```
使用方式 2⃣️：
```ts
// 方式2: 重新绑定交互，且传入参数
chart.interaction('active-region', {
start: [{ trigger: 'plot:mousemove', action: 'active-region:show', arg: { style: { fill: 'pink' } } }],
});
```
使用方式 2⃣️（多 actions）：
```ts
// multiple actions with args
registerInteraction('custom', {
start: [{ trigger: 'plot:mousemove', action: ['tooltip:show', 'active-region:show'] }],
end: [{ trigger: 'plot:mouseleave', action: …
```
> feat(active-region): 支持配置底色样式，全局统一注册一个 配置样式

- docs/api/general/event.zh.md
> docs(typo): dblclick, not dbclick

- src/core.ts
Such they could be auto erased from the output, otherwise, bundlers like rollup will throw an error.
Currently `src/interface.ts` was compiled to the following(cjs):
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=interface.js.map
```
Not only this is useless also will causes rollup error when use @antv/g2 as dependency, `require('./interface')` from `src/core.js`
```
'default' is not exported by interface.js (imported by core.js)
```
Change `import * as Types from './interface'` to `import type * as Types from './interface';`, the entire `interface.ts` would be auto erased from the output and everything works as expected.
> update type-only import

- src/geometry/base.ts
- src/geometry/label/layout/pie/spider.ts
- tests/bugs/3160-spec.ts
- tests/unit/geometry/label/layout/pie-spider-spec.ts
- fix: 修复 color 字段为 linear 类型时，不会存入 groupScales，导致获取 label-id 不唯一
- fix: spider 布局，如果 labelItem 的 id 存在 ‘.' , 会因为 get 解析 key 值，导致获取错误 ，如下：
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/15646325/114275026-8d637280-9a53-11eb-9942-700c1538e3d2.png)|![image](https://user-images.githubusercontent.com/15646325/114274962-568d5c80-9a53-11eb-812b-f76497359d1b.png)|
- closed: #3160 
- closed: https://github.com/antvis/G2Plot/issues/2497
- ref: #3349
> fix(issue-3160): 修复饼图使用连续型图例，标签无法展示

- .eslintrc
- package.json
- src/chart/chart.ts
- src/chart/index.ts
- src/chart/view.ts
- src/core.ts
- src/geometry/element.ts
- src/geometry/geometry.ts
- src/geometry/index.ts
- src/types.ts
> chore(api): add API for chart, view, geometry

- src/animate/animation/sector-path-update.ts
- tests/bugs/charts-574-spec.ts
饼图存在空数据时 sector-path-update 会导致动画超出画布。
| -------- | ------ |
|  <img src="https://user-images.githubusercontent.com/31396322/114974044-3ecf3180-9eb4-11eb-8716-fc0f9c335ae6.png" width="300" />  |  <img src="https://user-images.githubusercontent.com/31396322/114974107-5a3a3c80-9eb4-11eb-8029-406afb0f7c03.png" width="300" /> 
|
> fix: 修复数据为 0 时动画更新出错

- src/theme/util/create-by-style-sheet.ts
legend 的状态样式写死在 `component` 中，其实是可以修改的；参考下面两个文件：
1. https://github.com/antvis/component/blob/7d74c4753ce4cc5bcb54f8f278f9ea62d6a0c6bf/src/util/theme.ts
2. https://github.com/antvis/component/blob/912fb582894be39307b508edbd0468ea7fca16d1/src/legend/category.ts#L109
closed: #3375
> feat: 主题中增加图例样式的配置，便于用户了解怎么修改

- .github/workflows/build.yml
- package.json
PS. 旧的 ci 模板不适合缓存,我做了一些修改（缓存机制是作为action 基于**一个**job 的，那么相应的 action 得复制三遍，代码太丑O(∩_∩)O~）
**当前 v5 版本效率 x2**
> ci(cache): add cache support for github action

- gatsby-config.js
> chore: gatsby 加上 ts 依赖，以使 codesandbox 可以打开

- src/geometry/element/index.ts
>  fix: 修复 view.changeData 在重新渲染的时候 报 toFront 为 underfind 的错误

- src/interaction/action/mask/base.ts
- tests/unit/interaction/action/mask-spec.ts
close: #3456 
带 mask 的交互支持配置 maskStyle，使用方式如下：
```ts
chart.interaction('element-range-highlight', {
start: [
{
trigger: 'plot:mousedown',
isEnable(context) {
// 不要点击在 mask 上重新开始
return !context.isInShape('mask');
},
action: ['rect-mask:start', 'rect-mask:show'],
// 对应第一个action的参数
arg: [{ maskStyle: { fill: 'rgba(255,0,0,0.15)' } }]
},
{
trigger: 'mask:dragstart',
action: ['rect-mask:moveStart'],
},
],
});
```
> feat(mask): mask 交互支持配置样式

- src/chart/controller/legend.ts
> fix: 过滤连续图例的 value 参数，防止影响到 component legend 的 value 属性 导致交互问题

- src/index.ts
- src/interaction/action/data/range-filter.ts
- src/interaction/action/element/range-highlight.ts
- src/interaction/action/element/range-state.ts
> feat(range-highlight): 为区间高亮增加 events 事件

- src/geometry/label/layout/limit-in-plot.ts
The double slash in the path was causing jspm.dev to not be able to build the library. It's a simple fix that shouldn't introduce any bugs or breaking changes.
> style(geometry): removed double slash in path

- CONTRIBUTING.md
There are small typos in:
- CONTRIBUTING.md
Fixes:
- Should read `written` rather than `wirtten`.
- Should read `reason` rather than `reasone`.
- Should read `guarantee` rather than `garantee`.
- Should read `details` rather than `detials`.
- Should read `describe` rather than `descirbe`.
- Should read `congratulations` rather than `congradulations`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- package.json
- src/geometry/shape/interval/pyramid.ts
- src/geometry/shape/interval/util.ts
- tests/bugs/funnel-pyramid-spec.ts
- tests/unit/geometry/label/chart/funnel-spec.ts
- tests/unit/geometry/shape/interval-spec.ts
**漏斗图最下面一层的绘制问题**
出现问题的原因应该是 registerShape 的 getPoints 对于 pyramid 的最下面一层只返回了一个点，导致布局计算错误。所以解决办法就是 getPoints 的方法不论是不是 pyramid 都返回相同的 points，只是在渲染的时候区别一下就好。
> fix(funnel): pyramid shape 最下面一层的 label 绘制不对齐

- src/chart/view.ts
修复详情参见🔎
https://www.yuque.com/docs/share/7def9b80-f24c-4d2d-95f9-5a936a49ea5f?# 《G2 Scroball的bug》
> fix(scrollbar): 修复了由于getYScales方法中去重方法错误导致的 scrollbar会在特定情况下失效(#3569）

- examples/funnel/funnel/demo/basic.ts
- src/util/annotation.ts
- tests/unit/util/annotation-spec.ts
漏斗图中annotation使用position: 'median' 来控制位置，当中位数不为0.5时，将会导致annotation位置偏移，因此提供了position: 'center' 选项
before:
after:
> refactor(funnel): annotation 位置添加center，支持在漏斗图中正常显示

- package.json
- src/theme/style-sheet/dark.ts
- src/theme/style-sheet/light.ts
> fix: crash on safari 15 when fillText with unicode

- docs/api/general/legend.zh.md
- src/index.ts
- src/interaction/action/component/list-checked.ts
- src/interaction/action/component/list-focus.ts
- src/interaction/action/component/list-radio.ts
- src/interface.ts
- tests/unit/component/legend-category-radio-spec.ts
添加分类图例的正反选功能，参考 #3736
使用方式如下：
```js
// 默认不开启
char.legend({
// 开启并且设置样式
radio: {
fill: 'red',
stroke: 'yellow'
}
})
```
https://user-images.githubusercontent.com/49330279/147554277-3cbd416b-bbeb-4c0a-b281-0a3a82de73b4.mov
> feat(legend): 添加图例的正反选功能

- src/chart/controller/scrollbar.ts
…llbar
The tickMethod option is drop when enable scrollbar, only min,max,type,foratter are passed.
> fix(scrollbar): Scale option tickMethod doesn't work with scrollbar

- src/chart/controller/scrollbar.ts
- src/chart/controller/slider.ts
- tests/bugs/scrollbar-xscale-linear-spec.ts
- tests/bugs/slider-xscale-linear-spec.ts
开始值和结束值都是按照 data 原始的顺序来的， 而线性xScale 会排列数据， 导致 滚动条和缩略轴 交互不是线性的，而是 cat的
> fix(slider,scrollbar): 滚动条和缩略轴 在xScale 为线性时筛选错误的问题

- src/chart/controller/annotation.ts
- tests/bugs/3723-spec.ts
1、parsePosition 后的位置如果存在 NaN 时，直接返回 null；从 annotationCfg 为 null 的情况下，来决定 visible 是否展示
2、主要场景是：filterData 的场景下
close: https://github.com/antvis/G2/issues/3723
close: https://github.com/antvis/G2/pull/3730
> fix(issue-3723): 修复annotation 在筛选条件下，范围外的标注不需要展示

- src/geometry/base.ts
- src/util/scale.ts
- src/util/tooltip.ts
- tests/bugs/g2plot-2601-spec.ts
- tests/unit/animate/index-spec.ts
~~容我元旦假期回来之后，梳理下这里边的逻辑，避免踩坑~~
color 通道对应字段，是否可以作为分组字段，需要由 scale 定义、data、以及 geometry 类型决定
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/15646325/150137354-7cd7c7f8-1499-4982-b0a7-311ef65872f5.png)|![image](https://user-images.githubusercontent.com/15646325/150137494-0f7b33a6-30e9-4087-a928-0a52e8e5ec29.png)|
> fix: 修复获取分组scale错误 & tooltip 获取 value-scale 不忽略 color、shape 通道相关字段

- src/geometry/shape/interval/util.ts
- tests/unit/geometry/shape/interval-util-spec.ts
- [✅] `npm test` passes
- [✅ ] tests and/or benchmarks are included
- [✅ ] commit message follows commit guidelines
复现条件：
转置后的圆角条形图，当radius大于最小边的长度时，渲染会多出一部分，复现链接：https://codesandbox.io/s/purple-violet-v7vfly
修改方法：
parseRadius处理边界值的时候只处理了非转置情况，所以先调用parseRadius，再转置
> fix(interval): 修复转置后的圆角条形图渲染多出一部分

- __tests__/unit/geometry/point.spec.ts
- __tests__/unit/infer/index.spec.ts
- __tests__/unit/runtime/point.spec.ts
- __tests__/unit/scale/index.spec.ts
- __tests__/unit/shape/line/line.spec.ts
- __tests__/unit/shape/line/smooth.spec.ts
- __tests__/unit/shape/point/hollowPoint.spec.ts
- __tests__/unit/shape/point/point.spec.ts
- __tests__/unit/stdlib/index.spec.ts
- src/geometry/index.ts
- src/geometry/point.ts
- src/infer/index.ts
- src/infer/maybeKey.ts
- src/infer/maybeSize.ts
- src/infer/maybeSplitPosition.ts
- src/infer/maybeZeroY1.ts
- src/runtime/scale.ts
- src/scale/index.ts
- src/scale/log.ts
- src/scale/pow.ts
- src/shape/index.ts
- src/shape/point/colorPoint.ts
- src/shape/point/hollowPoint.ts
- src/shape/point/point.ts
- src/spec/geometry.ts
- src/spec/scale.ts
- src/stdlib/index.ts
feat(point): add components for chart related to point geometry
- Geometry: Point
- Shape: Point, HollowPoint
- Scale: Log, Pow
- Infer: MaybeSize, MaybeZeroY1
Basic scatter.
```js
const config = {
type: 'point',
transform: [
{
type: 'fetch',
url: 'https://gw.alipayobjects.com/os/basement_prod/6b4aa721-b039-49b9-99d8-540b3f87d339.json',
},
],
encode: {
x: 'height',
y: 'weight',
color: 'gender',
shape: 'hollowPoint',
},
}
```
Scatter with only one dimension.
```js
const config = {
type: 'point',
transform: [
{
type: 'fetch',
url: 'https://gw.alipayobjects.com/os/basement_prod/6b4aa721-b039-49b9-99d8-540b3f87d339.json',
},
],
height: 120,
scale: { y: { guide: null } },
encode: {
x: 'height',
shape: 'hollowPoint',
},
}
```
Bubble chart.
```js
const config = {
type: 'point',
transform: [
{ …
```
> feat(point): add components for chart related to point geometry

- __tests__/unit/transform/fetch.spec.ts
- __tests__/unit/transform/utils.spec.ts
- src/transform/fetch.ts
- src/transform/utils/memo.ts
Connector transform should ignore the change of data reference when memorize it.
```js
// Before
const fetch = Fetch({url:'xxx'});
// This will fetch twice because the two calls of fetch have different {}
fetch({});
fetch({});
```
```js
// After
const fetch = Fetch({url:'xxx'});
// This will fetch only once because  fetch ignore the change of {}
fetch({});
fetch({});
```
> fix(fetch): add useMemoConnector to memorize fetch

- __tests__/unit/composition/mark.spec.ts
- __tests__/unit/composition/view.spec.ts
- __tests__/unit/stdlib/index.spec.ts
- src/animation/utils.ts
- src/composition/flex.ts
- src/composition/index.ts
- src/composition/layer.ts
- src/composition/mark.ts
- src/composition/view.ts
- src/runtime/interaction.ts
- src/runtime/mark.ts
- src/runtime/plot.ts
- src/runtime/render.ts
- src/runtime/types/common.ts
- src/runtime/types/component.ts
- src/spec/composition.ts
- src/stdlib/index.ts
- src/utils/container.ts
refactor(runtime): separate compute and render logic for plotting a view
- Separate compute and render logic for plotting a view
```js
// Before
plotView(options, selection);
```
```js
// After
const view = initializeView(options);
plotView(view, selection);
```
- Using BFS instead of recursion to plot view tree.
```js
// Before
function plot(root) {
plotView(root);
root.children.forEach(plotView);
}
```
```js
// After
function plot(root) {
const views = BFS(root);
views.forEach(plotView);
}
```
- Add view and mark specification as composition, both of them will be transformed into standard view specification.
```js
// Transform view to standard view 
const view = {
type: 'view',
children: [{}, {}],
};
const standardView = {
type: 'standardView',
marks: [{}, {}]
}
```
```js
// Transform …
```
> refactor(runtime): separate compute and render logic for plotting a view

- CHANGELOG.md
- package.json
- src/core.ts
- tests/unit/geometry/label/layout/hide-overlap-spec.ts
**Release:**  v4.2.0
version 4.2.0 对 label 渲染做了改造，如果需要获取操作 labels，需要延迟等待 labels 渲染完毕
-  操作方式：
```ts
await delay(0);
const labels = chart.geometries[0].labelsRenderer.getChildren();
```
> chore: v4.2.0, use deferred label & web worker to do layout

- __tests__/unit/runtime/grid.spec.ts
- __tests__/unit/runtime/interval.spec.ts
- docs/grid.md
- docs/interval.md
- docs/scale.md
- src/component/axis.ts
- src/geometry/grid.ts
- src/geometry/interval.ts
- src/runtime/types/component.ts
feat(runtime): support flex options for interval and grid. ([demo](https://pearmini.github.io/hello-g2v5/#/interval))
Currently the flex options can only specified by non-declarative method, this should be solved in the next stage. And this PR should be merged after https://github.com/antvis/scale/pull/182 being merged and @antv/scale releasing 0.4.7. At the time, the CI will pass.
**Flex Interval.**
```js
G2.render({
data: [
],
scale: {
x: { flex: [2, 3, 1, 4, 2] },
},
encode: {
x: 'genre',
y: 'sold',
color: 'genre',
},
});
```
**Flex Grid.**
```js
G2.render({
type: 'grid',
data: [
{ name: 'A', course: 'a' },
{ …
```
> feat(runtime): support flex options for interval and grid

- __tests__/unit/animation/scaleInY.spec.ts
- __tests__/unit/shape/interval/hollowRect.spec.ts
- __tests__/unit/shape/point/point.spec.ts
- src/animation/scaleInY.ts
Using a short fadeIn transition to hide element with scale(0.001, 1) which is still visible.
> fix(animate): optimize scale-in by break the animation into two phases

- jest.config.js
- package.json
- src/component/axis.ts
- src/component/legendCategory.ts
update `@antv/gui` to `0.4.3-alpha.5`. Details to see: https://github.com/antvis/GUI/pull/148
- **fix:** position of facet axis-title
- **feat:** axis support `title.bounds` to make title not out-of bounds.
force axis-title to show, `label.maxLength`  may cause axis-label ellipsis.
> feat(axis): update @antv/gui, limit axis-title in bounds

- __tests__/unit/runtime/unit.spec.ts
- __tests__/unit/shape/text/text.spec.ts
- docs/unit.md
- src/composition/rect.ts
- src/shape/text/text.ts
fix: some bugs showing in examples.
- Text shape requires deg as the unit for rotate transformation.
```js
// before
const text = new Text({
style: {
transform: 'rotate(90)' // This is invalid.
}
});
// after
const text = new Text({
style: {
transform: 'rotate(90deg)' // This is valid.
}
});
```
- For guide options of axis, it will only affect displayed axis if it is an object in facet.
```js
// before
const o1 = {
scale: {
y: {
guide: ({ columnValue }) => 
// Control the the visibility of axis explicitly.
columnValue === '0' ? { position: 'left' } : null,
},
},
};
// after
const o2 = {
scale: {
y: {
// Only the left-most axis will show by default.
// This is no need to control the visibility of axis explicitly.
// The option below will only affect the displayed axis.
guide: { position: …
```
> fix: some bugs showing in examples

- .gitignore
- package.json
- rollup.config.js
> 控制包大小，从开始做起。
使用方式： 
1. npm run bundle-vis
2. 然后用浏览器打开目录中的 `stats.html`
> chore: add bundle analysis visualizer

- __tests__/unit/runtime/interval.spec.ts
- src/runtime/mark.ts
Support array field to render chart with array position such as treemap. The tooltip bug should be fixed in the future PR.
```js
const options = {
data: [
{ month: 'Jan.', profit: 387264, y: [0, 387264] },
{ month: 'Feb.', profit: 772096, y: [387264, 1159360] },
{ month: 'Mar.', profit: 638075, y: [1159360, 1797435] },
{ month: 'Apr.', profit: -211386, y: [1797435, 1586049] },
{ month: 'May', profit: -138135, y: [1586049, 1447914] },
{ month: 'Jun', profit: -267238, y: [1447914, 1180676] },
{ month: 'Jul.', profit: 431406, y: [1180676, 1612082] },
{ month: 'Aug.', profit: 363018, y: [1612082, 1975100] },
{ month: 'Sep.', profit: -224638, y: [1975100, 1750462] },
{ month: 'Oct.', profit: -299867, y: [1750462, 1450595] },
{ month: 'Nov.', profit: 607365, y: [1450595, …
```
> feat(encode): support array field

- __tests__/data/sales.ts
- __tests__/unit/runtime/area.spec.ts
- __tests__/unit/runtime/interval.spec.ts
- src/component/axis.ts
- src/component/legendCategory.ts
- src/component/legendContinuous.ts
- src/runtime/component.ts
- src/runtime/layout.ts
- src/runtime/types/common.ts
- src/utils/coordinate.ts
**feat:** support axis in polar coordinate
**Features:** components
- add `axisArc` (default in `circle` position)
- `axis` support `circle` position
- support custom axisStyleProps by config `scale.guide`
```ts
const chart = render({
type: 'area',
data: SCORE_OF_ITEM_WITH_TYPE,
encode: {
x: 'item',
y: 'score',
color: 'type',
},
scale: {
x: { guide: { type: 'axisX' }, padding: 0.5, align: 0 },
y: { guide: { type: 'axisY', zIndex: 1 }, tickCount: 5 },
},
coordinate: [{ type: 'polar' }],
style: {
fillOpacity: 0.25,
},
});
```
```ts
const chart = render({
data: SALE_OF_YEAR,
coordinate: [
{ type: 'transpose' },
{ type: 'polar' },
{ type: 'cartesian' },
],
scale: {
x: { guide: { type: 'axisX', title: null } },
y: { guide: { type: 'axisY', }, nice: true },
},
encode: {
x: …
```
> feat(axis): support arc axis in polar coordinate

- __tests__/unit/runtime/annotationConnector.spec.ts
- __tests__/unit/runtime/interval.spec.ts
- __tests__/unit/shape/annotation/connector.spec.ts
- __tests__/unit/shape/interval/rect.spec.ts
- src/component/legendCategory.ts
- src/component/legendContinuous.ts
- src/shape/annotation/connector.ts
- src/shape/annotation/text.ts
- fix: G will convert `x: ""` to `x: 0"` and `y: ""` to `y: 0"` internal.
- [todo] fix: GUI legend types definition later
> fix: ts errors in ci

- __tests__/unit/shape/annotation/text.spec.ts
- __tests__/unit/shape/text/text.spec.ts
- src/shape/annotation/text.ts
- Text annotation 的 transform 是作用在整个 group 上的。text 和 background 都在这个 group 下，background 的大小等价于 text 的大小。text.getLocalBounds() 之前，需要将 group 的欧拉角先置为 0，而不是 text 的欧拉角
> fix(test): text annotation rotate transform is apply to group

- .genjirc
- __tests__/unit/mark/geometry/point.spec.ts
- __tests__/unit/runtime/statistic.spec.ts
- __tests__/unit/shape/point/point.spec.ts
- __tests__/unit/shape/text/text.spec.ts
- __tests__/unit/stdlib/index.spec.ts
- docs/jitter.md
- docs/overview.md
- src/mark/geometry/point.ts
- src/runtime/mark.ts
- src/runtime/types/transform.ts
- src/shape/point/colorPoint.ts
- src/spec/statistic.ts
- src/stdlib/index.ts
- src/transform/index.ts
- src/transform/statistic/Jitter.ts
- src/transform/statistic/JitterY.ts
- src/transform/statistic/stackY.ts
- src/utils/coordinate.ts
- src/utils/helper.ts
feat: add jitter and jitterY transform
The **jitter** transform produce dy channels for marks (especially for point) with ordinal x and y dimension, say to make them jitter in their own space. It is useful to see the density of distribution for data.
- _Jitter_ - Produce both dx and y channels.
- _JitterY_ - Produce only dy channel, which result in produce dy channel in transpose coordinate.
It also supports _padding_ option to specify padding of space.
**Jitter Both**
```js
G2.render({
type: 'point',
transform: [
{
type: 'fetch',
url: 'https://gw.alipayobjects.com/os/antvdemo/assets/data/diamond.json',
},
{ type: 'jitter' },
],
scale: { x: { padding: 0.5 }, y: { guide: null } },
encode: {
x: 'clarity',
color: 'clarity',
},
});
```
**Jitter In Polar**
Specify _paddingX_ and _paddingY_ …
> feat: add jitter and jitterY transform

- __tests__/unit/mark/annotation/lineX.ts
- __tests__/unit/mark/annotation/lineY.spec.ts
- __tests__/unit/runtime/annotationLine.spec.ts
- __tests__/unit/runtime/statistic.spec.ts
- docs/stack.md
- src/mark/annotation/index.ts
- src/mark/annotation/lineX.ts
- src/mark/annotation/lineY.ts
- `lineX` rename to `lineY`, require `y` channel encode.
- `lineY` rename to `lineX`, require `x` channel encode.
> refactor(annotation): lineX and lineY swap rename

- __tests__/unit/runtime/statistic.spec.ts
- src/component/legendCategory.ts
**feat:** support config category legend
```ts
{
scale: {
x: { field: 'Date', utc: true },
y: { guide: { label: { formatter: (d) => `${+d.text / 1000}k` } } },
// config legend.
color: { guide: { autoWrap: true, size: 68, maxRows: 3, cols: 5 } },
},
}
```
config `autoWrap` and `cols`
> feat(legend): support config category legend

- src/runtime/plot.ts
- src/runtime/types/component.ts
feat(shape): add index and point2d params
This is for get drawing context for some shapes, such as funnel. Point2d means two dimension point array.
```js
function Funnel() {
return (points, value, coordinate, theme, point2d) => {
const {index} = value; // The index of current shape.
const prePoints = point2d[index - 1]; // The points of next shape.
// ...
}
}
```
> feat(shape): add index and point2d params

- src/transform/preprocessor/wordCloud.ts
- src/transform/utils/helper.ts
The helper function `merge` update encode options only when newEncode is defined.
> fix(transform): merge ignore undefined new encode

- src/index.ts
`renderer:'svg' mouseleave 事件不能触发`
fiexd #3849
> fix(axis-label): 修复 axis-label tooltip 移开没有 hide 的问题

- src/geometry/shape/interval/index.ts
- tests/bugs/3748-spec.ts
> fix(backgroundName): 修复 柱形存在背景时添加 interval:click 触发两次的问题

- .genjirc
- __tests__/unit/runtime/statistic.spec.ts
- __tests__/unit/stdlib/index.spec.ts
- docs/group.md
- docs/overview.md
- src/spec/statistic.ts
- src/stdlib/index.ts
- src/transform/index.ts
- src/transform/inference/maybeStackY.ts
- src/transform/statistic/groupX.ts
- src/transform/utils/helper.ts
The GroupX transform group data by x channel, and aggregate. ([preview](http://g2-next.antv.vision/group#groupX))
```js
G2.render({
transform: [
{
type: 'fetch',
url: 'https://gw.alipayobjects.com/os/antvdemo/assets/data/diamond.json',
},
{
type: 'groupX',
y: 'mean',
},
],
paddingLeft: 60,
encode: {
x: 'clarity',
y: 'price',
color: 'clarity',
},
});
```
> feat: add groupX

- .genjirc
- __tests__/unit/mark/geometry/area.spec.ts
- __tests__/unit/mark/geometry/line.spec.ts
- __tests__/unit/mark/helper.ts
- __tests__/unit/runtime/area.spec.ts
- __tests__/unit/runtime/line.spec.ts
- docs/area.md
- docs/line.md
- src/component/legendContinuous.ts
- src/mark/geometry/area.ts
- src/mark/geometry/line.ts
- src/runtime/plot.ts
- src/runtime/types/component.ts
- src/runtime/types/mark.ts
- src/runtime/types/transform.ts
- src/shape/area/curveArea.ts
- src/shape/line/curveLine.ts
- src/shape/utils.ts
Each _Series Mark_ such as _Line_ and _Area_ will return series index as the third element of the returned array. 
```js
// Before
const [I, P] = Line(/**...**/);
// After
const [I, P, S] = Line(/**...**/);
I // [0, 1]
S // [[0, 1, 2], [3, 4, 5]]
```
And then bind datum with value using "series"  as the prefix of  the key to each element.
```js
// Before
line.__data__  // {title, key, color, ...}
// After
line.__data__ // {title, key, color, seriesTitle, seriesKey, seriesColor, ...}
```
This is useful for tooltip of Series Mark, and bind gradient to datum.
[**Gradient Line**](http://g2-next.antv.vision/line/#gradient-line)
```js
G2.render({
type: 'line',
data: [
{ year: '1991', value: 15468 },
{ year: '1992', value: 16100 },
{ year: '1993', value: 15900 },
{ year: '1994', value: 17409 }, …
```
> feat: bind series value to series mark

- src/geometry/shape/area/index.ts
- src/geometry/shape/area/smooth.ts
- tests/unit/geometry/shape/area-spec.ts
- [✅ ] `npm test` passes
- [ ✅] tests and/or benchmarks are included
- [✅ ] commit message follows commit guidelines
before | after
-- | --
 <img width="884" alt="截屏2022-06-30 下午12 36 52" src="https://user-images.githubusercontent.com/20794675/176593815-00fc1fcc-efb9-4112-9126-72d3aa717f5b.png"> | <img width="652" alt="截屏2022-06-30 下午12 32 59" src="https://user-images.githubusercontent.com/20794675/176593374-78dec0aa-7672-410f-92b9-cee49509e65e.png">
area-area 和 area-smooth 这两种内置shape的默认getMarker没有初始的的fillOpacity值，导致使用了默认主题中areaFillOpacity=0.25的值
fixed https://github.com/antvis/G2/issues/3123
> fix(area-shape): fix marker fillOpacity

- src/interaction/action/active-region.ts
Need: 
使用以下代码按需引入
```javascript
import ActiveRegion from '@antv/g2/lib/interaction/action/active-region'
```
Updating Reason: 
上述代码tsc编译会报错，原因是用户环境直接引入该文件，无法识别src/chart的路径。所以这里更改了引入的路径
Related Testing: 
只修改了模块的引入路径，不涉及到功能的调整，暂无测试用例
> fix(active-region): Fix type error when importing on demand

- __tests__/unit/interaction/index.spec.ts
- __tests__/unit/interaction/stdlib.spec.ts
- package.json
- src/interaction/action/index.ts
- src/interaction/action/service/elementSelection.ts
- src/interaction/action/service/recordCurrentPoint.ts
- src/interaction/action/transformer/cursor.ts
- src/interaction/action/transformer/mask.ts
- src/interaction/action/transformer/move.ts
- src/interaction/builtin/brush.ts
- src/interaction/builtin/brushHighlight.ts
- src/interaction/builtin/brushVisible.ts
- src/interaction/builtin/elementActive.ts
- src/interaction/stdlib.ts
- src/renderer/canvas.ts
- src/runtime/types/component.ts
- src/spec/action.ts
- **feat(interaction):** support brush mask draggable and resizable.
- **feat(action):** add `recordCurrentPoint` service ([Docs]( https://www.yuque.com/antv/g2-docs/interaction-plan#OZhO1)) and `move` transformer（[Docs](https://www.yuque.com/antv/g2-docs/interaction-plan#Fq6sy)）
- **update(action):** update `cursor` transformer to use the cursor style of target when cursor option is null.
- **update(interaction):** update `brushHighlight` interactionDescriptor 
- **fix(action):** elementSelection error pickup selectedElements when from is `polygon-mask`
```ts
const InteractionDescriptor = (options?: BrushHighlightOptions) => {
const { brushType } = options;
const maskPrefix = brushType === 'polygon' ? 'polygon' : 'rect';
const dim = brushType === 'rectX' ? 'x' : brushType === 'rectY' ? …
```
> feat(interaction): implement draggable and resizable mask

- __tests__/unit/runtime/line.spec.ts
- docs/interval.md
- docs/line.md
- src/component/axis.ts
- src/runtime/component.ts
1. **Changes:** Display axis in polar or transpose coordinate by default.
2. **Marks:** Polar, transpose, and parallel coordinates do not adapt fisheye yet.
> should specify guide type
```ts
{
scale: { y: { guide: { type: 'axisY' } } }
}
```
> feat(component): display axis in polar or transpose coordinate by default

- docs/api/advanced/register-interaction.en.md
- docs/api/advanced/register-interaction.zh.md
- docs/api/general/interaction.zh.md
- src/interaction/action/cursor.ts
- tests/unit/interaction/action/cursor-spec.ts
You can use zoomIn and zoomOut cursor in register-interaction. 
This is useful. For example, you use scale-transform zooming.
```js
registerInteraction('custom-zoom', {
showEnable: [
{ trigger: 'plot:mouseenter', action: 'cursor:zoomIn' },
{ trigger: 'plot:mouseleave', action: 'cursor:zoomOut' },
],
});
```
> feat: add zoom-in zoom-out cursor

- docs/interval.md
- docs/spatial.md
- docs/view.md
- src/component/axis.ts
- src/composition/matrix.ts
- src/composition/rect.ts
- **feat(component):** GUI axis supports `grid` options. In G2, should calculate grid.items by the actual ticks, now support non-discrete scale to display grid by default.
- **change(facet):** modify the createGuide method of `rect` and `matrix`, make sure axis grid display elegant by default.
> feat(component): support axis grid

- .genjirc
- __tests__/unit/interaction/action/transformer/button.spec.ts
- __tests__/unit/interaction/action/transformer/mask.spec.ts
- __tests__/unit/interaction/builtin/brush.spec.ts
- __tests__/unit/interaction/builtin/elementHightlight.spec.ts
- __tests__/unit/interaction/builtin/legend.spec.ts
- __tests__/unit/interaction/builtin/tooltip.spec.ts
- __tests__/unit/interaction/helper.ts
- __tests__/unit/interaction/index.spec.ts
- __tests__/unit/interaction/stdlib.spec.ts
- __tests__/unit/stdlib/index.spec.ts
- docs/annotation.md
- docs/interaction-component.md
- docs/interaction-element.md
- docs/normalize.md
- src/component/legendCategory.ts
- src/interaction/action/index.ts
- src/interaction/action/transformer/activeRegion.ts
- src/interaction/action/transformer/button.ts
- src/interaction/builtin/activeRegion.ts
- src/interaction/create.ts
- src/interaction/index.ts
- src/interaction/stdlib.ts
- src/spec/action.ts
- src/spec/interaction.ts
- src/stdlib/index.ts
- **feat(interactions):** implement `ActiveRegion` interaction with `ActiveRegion` transformer action (with the same name), which is only supported when x scale is a band scale.
```ts
export const InteractionDescriptor = (options: ActiveRegionOptions = {}) => {
return {
start: [
{
trigger: 'plot:mousemove',
action: [{ type: 'activeRegion', ...options }],
},
{
trigger: 'plot:mouseleave',
action: [{ type: 'activeRegion', clear: true }],
},
],
};
};
```
**Active region in transpose coordinate.**
**Active region with flex band scale and custom options.**
```ts
G2.render({
type: "interval",
data: [
{ genre: "Sports", sold: 275 },
{ genre: "Strategy", sold: 115 },
{ genre: "Action", sold: 120 },
{ genre: "Shooter", sold: 350 },
{ genre: "Other", sold: 150 },
],
scale: {
x: { flex: [2, 3, 1, 4, …
```
> feat(interaction): implement activeRegion interaction and add docs

- __tests__/unit/interaction/stdlib.spec.ts
- __tests__/unit/stdlib/index.spec.ts
- docs/interaction-more.md
- src/component/title.ts
- src/component/utils.ts
- src/interaction/action/index.ts
- src/interaction/action/service/recordTip.ts
- src/interaction/action/transformer/button.ts
- src/interaction/action/transformer/poptip.ts
- src/interaction/builtin/ellipsisText.ts
- src/interaction/create.ts
- src/interaction/index.ts
- src/interaction/stdlib.ts
- src/runtime/plot.ts
- src/spec/action.ts
- src/spec/interaction.ts
- src/stdlib/index.ts
**feat(interaction):** implement `ellipsisText` interaction [[Design docs](https://www.yuque.com/antv/g2-docs/interaction-plan#UNJV1)]
- add `recordTip` as a service action to store tip attribute
- add `poptip` as a transformer` action to show a poptip component
```ts
export const InteractionDescriptor = (options?: EllipsisTextOptions) => ({
start: [
{
trigger: 'mousemove',
throttle: { wait: 50, leading: true, trailing: false },
action: [
{ type: 'surfacePointSelection' },
{ type: 'recordTip' },
{ type: 'poptip', ...options },
],
},
],
});
```
```ts
G2.render({
type: 'area',
transform: [
{
type: 'fetch',
url: 'https://gw.alipayobjects.com/os/bmw-prod/e58c9758-0a09-4527-aa90-fbf175b45925.json',
},
{ type: 'stackY' },
{ type: 'normalizeY' },
],
paddingTop: 72,
scale: {
x: { field: 'Date' }, …
```
> feat(interaction): implement ellipsisText interaction

- __tests__/unit/api/chart.spec.ts
- __tests__/unit/api/interval.spec.ts
- __tests__/unit/api/node.spec.ts
- __tests__/unit/api/props.spec.ts
- src/api/chart.ts
- src/api/index.ts
- src/api/interval.ts
- src/api/node.ts
- src/api/props.ts
- src/api/types.ts
- src/index.ts
feat(api): add part of chart and interval api
```js
});
chart.data([
]);
chart
.interval()
.encode('x', 'genre')
.encode('y', 'sold')
.encode('color', 'genre');
```
> feat: add chart and interval api

- .genjirc
- package.json
Update genji-notebook to 0.1.0 to support interactive notebook and adjust the outline as follows:
> chore(website): update genji to 0.1.0 and adjust the outline

- src/chart/controller/tooltip.ts
- tests/bugs/tooltip-spec.ts
当 tooltip 的 配置 enterable 为 true 时，并且 tooltip 在 canvas 边缘，从 tooltip 上离开出图表范围外，tooltip 不隐藏。
在 tooltip 的dom实例中添加 onmouseleave 事件，在未锁定的情况下，执行 hideTooltip 隐藏 tooltip
> fix(tooltip): tooltip hide when mouseleave tooltip

- src/index.ts
close #3896。
因为click事件改变了 unchecked 状态，然后再触发 legend-highlight 的 mouseleave 而 ListHighlight 当 unchecked 的时候会忽略，所以没有改变回来。
在 unchecked:toogle 之前，加上了 highlight:reset 相关动作。
>  fix(legend-highlight): reset highlighting after legend filter

- src/component/axis.ts
- src/interaction/action/transformer/tooltip.ts
- src/transform/statistic/select.ts
- selectFirst return the first index for each series.
- set textAnchor for axis.
-  tooltip throw an error in parallel coordinates for undefined x scale.
|Before      |After |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/49330279/184347463-b65e2066-0694-43bf-906b-1e72f74f4a56.png)    | ![image](https://user-images.githubusercontent.com/49330279/184347868-c78f0ba5-3ac2-434d-8310-5fca5976426a.png)     |
> fix: transform and guide

- src/shape/annotation/badge.ts
- src/shape/annotation/text.ts
Custom shape do not pass className to children, otherwise it will be unexpected select as elements.
> fix(annotation): do not pass className to children

- src/geometry/label/layout/hide-overlap.ts
- src/geometry/label/util/createWorker.ts
问题描述：web workers 执行多条任务时，返回结果混乱，导致 label 渲染出错。
解决方法：添加同步 queue 队列，将 worker 的执行结果推送到队列，将顺序 worker 任务结果。
| Before UI   | After UI  |
|  ----  | ----  |
| ![iShot_2022-08-16_11 44 10](https://user-images.githubusercontent.com/109653633/184793546-25dad661-8d7b-4534-ae37-2ac5aa356443.gif)  | ![iShot_2022-08-16_11 39 54](https://user-images.githubusercontent.com/109653633/184793109-86f531d3-9af4-4a99-93f4-c39add9f2522.gif) |
> fix(label): 修复 webworker 执行多条任务时 label 渲染混乱问题

- __tests__/unit/animation/scaleInX.spec.ts
- __tests__/unit/animation/scaleInY.spec.ts
- __tests__/unit/animation/scaleOutX.spec.ts
- __tests__/unit/animation/scaleOutY.spec.ts
- package.json
- src/animation/fadeIn.ts
- src/animation/fadeOut.ts
- src/animation/morphing.ts
- src/animation/scaleInX.ts
- src/animation/scaleInY.ts
- src/animation/scaleOutX.ts
- src/animation/scaleOutY.ts
和 CSS 保持一致，动画 keyframe 内支持使用 `''` 作为属性值，其含义等同于`unset`，因此无需从 `parsedStyle` 中获取。
```js
const {
fillOpacity,
strokeOpacity,
opacity,
} = shape.style;
// = shape.parsedStyle
{
fillOpacity,
strokeOpacity,
opacity,
offset: 0.99,
},
```
> fix: use attributes from style instead of parsed style

- __tests__/unit/runtime/annotationText.spec.ts
- src/runtime/plot.ts
See https://github.com/antvis/G2/issues/4106 for more detail.
```js
G2.render({
type: 'layer',
children: [
{
coordinate: [{ type: 'theta', innerRadius: 0.5 }],
scale: { color: { guide: null } },
data: [
],
encode: {
y: 'sold',
color: 'genre',
},
},
{
type: 'annotation.text',
data: [{ x: 0.5, y: 0.5, text: 'G2' }],
scale: {
x: { guide: null },
y: { guide: null },
},
encode: {
x: 'x',
y: 'y',
text: 'text',
color: 'black',
},
style: {
fontSize: 60,
textBaseline: 'middle',
fontWeight: 'bold',
},
},
],
})
```
> fix(runtime): fail to identify annotation as mark (close: #4106)

- __tests__/unit/api/chart.spec.ts
- __tests__/unit/api/node.spec.ts
- src/api/chart.ts
- src/api/node.ts
**Bug**
```js
const chart = new Chart({});
const date = new Date();
chart.grid().data([{ date }]);
// Expected 
chart.data(); // [{ date }]
// Received
chart.data(); // [{ date: {} }]
```
**Reason**
To make the chart options immutable, it will use the `clone` of @antv/util every time the options change. But `clone` fail to clone Date object.
```js
import { clone } from '@antv/util';
const date = new Date();
clone({date}); // { date: {} }
```
**Solution**
Remove the clone operation. It is unnecessary to mark the options immutable because it makes no sense to clone data every time.
> fix(api): do not clone the value of node when mapping

- src/chart/view.ts
- tests/bugs/4141-spec.ts
close: #4141 25倍 🚀
|Before| After|
|---|---|
|![image](https://user-images.githubusercontent.com/15646325/190667681-7a3ecf5e-7ba4-4af8-9cb0-81754fc54dd0.png)|![image](https://user-images.githubusercontent.com/15646325/190667981-8361c0b4-f072-417c-9e07-d76a583bce0a.png)|
- 思路：从 performance 中可以看到有 view.getComponents 的调用有异常（这里是 10000 * 10000）
> fix(#4141): avoid cost O(n^2) to getComponents

- __tests__/integration/charts/population2015-interval-pie.ts
- src/animation/waveIn.ts
`waveIn` 并不是一种形变动画，至少它对于过程中的效果有严格要求，例如固定扇形的圆心。因此使用 `onframe` 回调配合可插值的自定义属性来实现比较合适。
* 自定义属性注册：https://g-next.antv.vision/zh/docs/api/css/css-properties-values-api#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B1%9E%E6%80%A7
* animation 对象的 `onframe` 回调：https://g-next.antv.vision/zh/docs/api/animation#onframe
效果类似：https://g-next.antv.vision/zh/examples/ecosystem#d3-piechart
> fix: use custom transition instead of morphing in wavein animation

- site/examples/others/theme/demo/meta.json
- site/examples/others/theme/demo/rough-line.ts
- site/examples/others/theme/demo/rough-radial.ts
- site/package.json
饼图中包含大面积填充的图形适合使用 `fillStyle`，起到类似纹理的作用，适合无障碍中的报纸打印需求。目前支持的填充样式详见 [文档](https://github.com/antvis/G/blob/next/packages/site/docs/plugins/rough-canvas-renderer.zh.md#fillstyle)
可以通过 `roughness` 参数（[文档](https://github.com/antvis/G/blob/next/packages/site/docs/plugins/rough-canvas-renderer.zh.md#roughness)）调节手绘风格度，但折线图感觉不太适合过度风格化。
> docs(chore): add sketchy radial & line chart

- site/docs/api/overview.zh.md
增加 overview 的模板，方便后面填空。建议：
- 文档的命名使用驼峰，这样 url 和 api 保持一致。比如 fadeIn 如果文档地址为 fade-in.zh.md，那么访问地址就是 fade-in 和 API 不一致。
> docs: add overview document

- site/docs/api/common/style.en.md
- site/docs/api/common/style.zh.md
- site/docs/api/mark/interval.en.md
- site/docs/api/mark/interval.zh.md
- site/docs/api/mark/vector.en.md
- site/docs/api/mark/vector.zh.md
- site/docs/api/overview.zh.md
- site/examples/general/vector/demo/meta.json
- site/examples/general/vector/demo/wind.ts
建议：
-  table 的样式，参考此篇保持一致
- 文档的 pr 不用等 ci，可以强行合并
----
Vector 图形是将数据映射成为`箭头`的样式去可视化展示，通过控制箭头的位置、大小、颜色、角度等信息，去可视化一些向量场数据。它具备有以下视觉通道：
- `x`：水平方向的位置，对 x 轴刻度对应
- `y`：垂直方向的位置，对 y 轴刻度对应，位置锚点定位为箭头的中心
- `color`：箭头的颜色
- `size`：箭头的长度
- `rotate`：箭头的旋转角度，起始角度为直角坐标系中的 `右边`，旋转方向为 `顺时针`
Vector 图形标记会将数据通过上述通道映射成向量数据：`[start, end]`。
```ts
autoFit: true,
});
chart
.vector()
.data({
type: 'fetch',
value: 'https://gw.alipayobjects.com/os/antfincdn/F5VcgnqRku/wind.json',
})
.encode('x', 'longitude')
.encode('y', 'latitude')
.encode('rotate', ({ u, v }) => (Math.atan2(v, u) * 180) / Math.PI)
.encode('size', ({ u, v }) => Math.hypot(v, u))
.encode('color', ({ u, v }) => Math.hypot(v, u))
.scale('size', { range: [6, 20] }) …
```
> docs: add vector api

- src/transform/sample.ts
- src/transform/selectX.ts
- src/transform/selectY.ts
将 `selectX` 和 `selectY` 里面的 `Select` 改成 `select`
> fix(select): lowercase Select to select

- site/docs/manual/getting-started.zh.md
* **G2 版本**：v5
* **代码笔链接**：
```
<div id="container"></div>
```
```js
// 准备数据
const data = [
{ genre: "Sports", sold: 275 },
{ genre: "Strategy", sold: 115 },
{ genre: "Action", sold: 120 },
{ genre: "Shooter", sold: 350 },
{ genre: "Other", sold: 150 },
];
// 初始化图表实例
container: "container",
});
// 声明可视化
chart
.interval() // 创建一个 Interval 标记
.data(data) // 绑定数据
.encode("x", "genre") // 编码 x 通道
.encode("y", "sold"); // 编码 y 通道
// 渲染可视化
```
-----------------------------------------------------------------------------------------------------------------------------------------
修改文档 
在 https://g2.antv.antgroup.com/manual/getting-started --快速上手部分--包管理器章节，在安装成功之后给 G2 提供一个容器：该容器id为chart，而下面初始化图表实例中container值是container，container与容器id不对应，无法生成图表 …
> docs: change chart to container in getting-started

- __tests__/integration/interactions/index.ts
- __tests__/integration/interactions/indices-line-chart-facet-tooltip.ts
- __tests__/integration/interactions/temperatures-line-tooltip-discrete.ts
- src/composition/facetRect.ts
- src/composition/mark.ts
- src/composition/repeatMatrix.ts
- src/interaction/native/tooltip.ts
- src/mark/area.ts
- src/mark/line.ts
- src/runtime/types/mark.ts
- src/spec/interaction.ts
添加分面的 tooltip，但是现在只能用于折线图和面积图这种 series Mark。
```ts
export async function indicesLineChartFacetTooltip(): Promise<G2Spec> {
const data = await csv('data/indices.csv', autoType);
return {
type: 'facetRect',
height: 600,
width: 700,
paddingRight: 80,
paddingBottom: 50,
paddingLeft: 60,
encode: { y: 'Symbol' },
scale: { y: { paddingInner: 0.2 } },
data,
children: [
{
type: 'line',
frame: false,
scale: { y: { nice: true, facet: false } },
axis: { y: { labelAutoRotate: false } },
encode: {
x: 'Date',
y: 'Close',
color: 'Symbol',
key: 'Symbol',
title: (d) => new Date(d.Date).toLocaleDateString(),
},
},
],
interactions: [
{ type: 'tooltip', series: true, facet: true, crosshairs: true },
],
};
}
```
> feat(interaction): add facet tooltip

- src/interaction/native/legendFilter.ts
- 图例筛选 filter tranform 需要在第一位。如：饼图场景，合理：`transform: [{ type: 'fitler' }, { type: 'stackY' } ]`
饼图动画关闭动画之后，筛选有点问题，暂时不写单测
> fix(interaction): legend fitler transform should in first

- __tests__/integration/interactions/index.ts
- __tests__/integration/interactions/profit-interval-custom-legend-filter.ts
- __tests__/integration/main.ts
- src/interaction/native/legendFilter.ts
- src/interaction/native/utils.ts
- src/spec/interaction.ts
为了定制性，可以定制 LegendFilter 操作的图例。
给定 legend 的 DOM 结构如下：
```html
<div>
<div class="legend">
<div id="marker"></div>
<div id="label">Increase</div>
</div>
<div class="legend">
<div id="marker"></div>
<div id="label">Decrease</div>
</div>
<div class="legend">
<div id="marker"></div>
<div id="label">Total</div>
</div>
</div>
```
声明交互：
```js
import { G2Spec } from '../../../src';
import { profit } from '../data/profit';
export function profitCustomIntervalLegendFilter(): G2Spec {
return {
paddingLeft: 60,
data: profit,
axis: { y: { labelFormatter: '~s' } },
legend: false,
encode: {
x: 'month',
y: ['end', 'start'],
color: (d) =>
d.month === 'Total' ? 'Total' : d.profit > 0 ? 'Increase' : 'Decrease',
},
interactions: [
{
type: 'legendFilter',
channel: 'color', // 过滤的通道
legends: () …
```
> feat(interaction): legend filter support custom legend

- .github/workflows/deploy.yml
- site/.dumi/global.ts
- 修复  g2.antv.vision 以及 antv-g2.gitee.io 跳转问题
- push 到 v5 自动 deploy 构建产物到 gh-pages 分支上
> fix: fix site direct and auto-deploy when push to v5

- __tests__/unit/api/mark.spec.ts
- site/docs/api/chart.zh.md
- src/api/mark/mark.ts
- src/api/mark/types.ts
目前以下两种写法无效，是因为 interaction 和 coordinate 都应该配置到 chart 对象上。issue: https://github.com/antvis/G2/issues/4438
```js
chart.line().interaction(); // 无效
chart.line().coordinate();  // 无效
```
```js
chart.interaction();// 有效
chart.coordinate(); // 有效
```
所以移除这两个没有用的 API。
> fix(api): remove interaction and coordinate for mark (close: #4438)

- __tests__/integration/canvas.ts
- __tests__/integration/snapshot-animation.spec.ts
- __tests__/integration/snapshot-interaction.spec.ts
- __tests__/integration/snapshot.spec.ts
之前图片有不匹配，就是生成 diff 图片，但是期望是不匹配的像素点大于 maxError 的时候才生成 diff 图片。
> fix(test): write diff png when mismatch greater than maxError

- src/interaction/index.ts
- src/spec/action.ts
- src/spec/interaction.ts
修复 G2 打包时候遇见的一些类型问题，详见 issue：https://github.com/antvis/G2/issues/4508 
之前实现的交互相关的 types 暂时先保留，当新的交互实现完了之后再删除。
> fix(types): type errors

- site/docs/api/component/axis.zh.md
- site/docs/api/component/category.zh.md
- site/docs/api/component/continuous.zh.md
- `gridLength` 会在内部根据 coordinate 推断计算，不需要用户配置。增加文档说明，避免用户误传。
```ts
height: 320
});
chart
.line()
.data({
type: 'fetch',
value:
'https://gw.alipayobjects.com/os/bmw-prod/551d80c6-a6be-4f3c-a82a-abd739e12977.csv',
})
.encode('x', 'date')
.encode('y', 'close')
.axis('x', {
line: true,
//   gridLength: 100,
gridAreaFill: ['rgba(0,0,0,0.05)', 'rgba(0,0,0,0.02)']
})
.axis('y', {
line: true,
gridAreaFill: ['rgba(0,0,0,0.05)', 'rgba(0,0,0,0.02)']
})
```
> docs: add details of axis gridLength option

- .husky/pre-commit
- jest.config.js
- package.json
这个 PR：https://github.com/antvis/G2/pull/4584 的开发者提到本地单测不通过，所以在这里修复该问题。
这个问题是因为 G 4.0 这个 PR https://github.com/antvis/G/pull/1216/files 升级了 d3-interpolate 的版本，d3-interpolate 该版本只提供了 esm 文件，而 jest 只能使用 cjs 文件。
通过 `confg. transformIgnorePatterns` 转换 node_modules 里面的 d3-interpolate 成 cjs 文件。
```js
// Installing third-party modules by tnpm or cnpm will name modules with underscore as prefix.
// In this case _{module} is also necessary.
const esm = ['d3-*'].map((d) => `_${d}|${d}`).join('|');
module.exports = {
// ...
transformIgnorePatterns: [`<rootDir>/node_modules/(?!(${esm}))`],
// ....
};
```
同时还需要让 jest 使用 js 文件，需要修改 preset 为 `js-with-ts`，同时修改测试使用的 `tsconfig` 支持 js。
```js
module.exports = {
preset: 'ts-jest/presets/js-with-ts',
globals: {
'ts-jest': {
tsconfig: {
allowJs: true,
sourceMap: …
```
> fix(test): transform esm to cmjs in node_modules

- docs/api/general/interaction.zh.md
- examples/interaction/brush/demo/brush-x-multi.ts
- examples/interaction/brush/demo/meta.json
- src/index.ts
- src/interaction/action/mask/circle.ts
- src/interaction/action/mask/dim-rect.ts
- src/interaction/action/mask/multiple/base.ts
- src/interaction/action/mask/multiple/circle.ts
- src/interaction/action/mask/multiple/dim-rect.ts
- src/interaction/action/mask/multiple/path.ts
- src/interaction/action/mask/multiple/rect.ts
- src/interaction/action/mask/multiple/smooth-path.ts
- src/interaction/action/mask/path.ts
- src/interaction/action/mask/rect.ts
- src/interaction/action/mask/smooth-path.ts
- src/interaction/action/util.ts
- tests/unit/interaction/action/multi-mask-spec.ts
* **🎯 背景**: 项目业务需要在 AntV G2 气泡图中圈选出多个群组，每个群组的详细数据联动渲染在联动 AntV S2 交叉表上。因此需要实现多选模式的遮罩交互
* **🎨 效果**:
- 动图
- [rect-multi-mask.gif](https://img.alicdn.com/imgextra/i1/O1CN017YLP4G20CPChU3gPn_!!6000000006813-1-tps-728-512.gif)
- [x-rect-multi-mask.gif](https://img.alicdn.com/imgextra/i2/O1CN01PVHFdF1x5aSdxkVLS_!!6000000006392-1-tps-694-476.gif)
- [y-rect-multi-mask.gif](https://img.alicdn.com/imgextra/i1/O1CN01v6aK4Q29wVcD2Kf0w_!!6000000008132-1-tps-728-512.gif)
- [circle-multi-mask.gif](https://img.alicdn.com/imgextra/i3/O1CN01Srw9W01zT3zS4Lokh_!!6000000006714-1-tps-728-512.gif)
- [path-multi-mask.gif](https://img.alicdn.com/imgextra/i2/O1CN01ads8fz1GfkFdGTSjX_!!6000000000650-1-tps-728-512.gif)
- [smooth-path-multi-mask.gif](https://img.alicdn.com/imgextra/i2/O1CN01beKwr928IpgnqgdJu_!!600000000 …
> feat: multiple mask actions

- src/label-transform/overlapDodgeY.ts
G 这个 [PR](https://github.com/antvis/G/pull/1269#pullrequestreview-1251209956) 带来的问题。
G 上述更新之后，`shape.clone` 无法 clone 没有定义的属性。
```js
const shape = new Rect({});
shape.style.stroke = undefiend;
shape.clone(true); // 报错
```
在 G2 中目前只有 stroke 属性为 null 的问题，所以当 stroke 没有定义的时候，设置为空字符串。**当 G 修复之后，这里的修复代码可以去掉**。 @xiaoiver
> fix: g can't clone undefined attribute

- __tests__/integration/snapshot-animation.spec.ts
- __tests__/unit/api/chart.spec.ts
- package.json
- src/api/chart.ts
- src/api/props.ts
- src/runtime/plot.ts
- src/runtime/render.ts
- src/runtime/types/options.ts
- src/spec/composition.ts
- src/utils/event.ts
之前是希望事件也可以声明式的定义，所以增加了 `options.on` 的字段，但是目前看来没有必要，所以给 Chart 对象增加了一个 EventEmitter 作为一个事件总线：emitter，并且传递给了 runtime 的 render 函数。
- chart.on()
- chart.off()
- chart.emit()
- chart.once()
- chart.render() 返回一个 promise
```js
chart.render().then((c) => {
expect(c).toBe(chart);
})
```
下一个 PR 将实现以下功能：
```js
chart.emit('tooltip:show', {});
chart.emit('tooltip:hide');
chart.emit('tooltip:lock');
chart.emit('tooltip:unlock');
```
> refactor(api): add emitter

- src/index.ts
- tests/unit/interaction/action/sibling-filter-xy-action-spec.ts
问题：内置的 sibling-x-filter，sibling-y-filter 没有达到预期效果
复现：如果多个 view 的数据不一致，在交互中用到 sibling-x-filter 或 sibling-y-filter 是会出现数据不对
> fix: 修复 sibling-x-filter，sibling-y-filter 过滤全部数据的问题

- __tests__/integration/api-mark-change-data-tooltip.spec.ts
- __tests__/integration/snapshots/api/markChangeDataTooltip.html
- __tests__/main.ts
- __tests__/plots/api/index.ts
- __tests__/plots/api/mark-change-data-tooltip.ts
- __tests__/plots/api/mark-change-data.ts
- src/interaction/native/utils.ts
- fix: https://github.com/antvis/G2/issues/4650
- 原因：更新数据的时候，旧的元素不会马上删除（需要等到动画结束），于是交互把旧的元素也保存下来了，从而会同时显示新旧元素的 tooltip。
> fix(tooltip): selected expected elements (close: #4650)

- package.json
- site/package.json
- 更新版本到 5.0.0-beta.10
- 锁定 gui 版本，防止这周 gui 有 breaking change。
> chore(version): bump to 5.0.0-beta.10

- __tests__/unit/stdlib/index.spec.ts
- src/interaction/native/tooltip.ts
- src/runtime/mark.ts
- src/runtime/scale.ts
- src/runtime/transform.ts
- src/scale/constant.ts
- src/scale/index.ts
- src/spec/scale.ts
- src/stdlib/index.ts
增加 constant 比例尺。
当某一个通道的值为固定值的时候，比如：
```js
const mark = {
encode: {
color: 'steelblue',
}
}
```
这个通道对应的比例尺可以是 constant，也可以是 identity。区别在于 constant 比例尺的 range 会把这个值存下来，但是 identity 不会，这样就会出现下图中的问题：没有办法给图例加颜色。所以把非位置通道的常量通道设置成 constant 比例尺。
这个 PR 为解决 https://github.com/antvis/G2/issues/4603 提到的一个问题提供了基础。@Aarebecca
> feat(scale): add constant

- src/animate/animation/sector-path-update.ts
- src/animate/animation/wave-in.ts
- src/animate/animation/zoom.ts
- tests/unit/animate/animate-callback-spec.ts
* **G2 Version**: v4
fixes #4627
内置动画通过 callback 实现时确保外部 callback 配置生效
> fix(animate): 部分动画覆盖 callback 配置导致外部的 callback 配置失效

- __tests__/integration/chart-on-item-element.spec.ts
- __tests__/integration/chart-on-series-element.spec.ts
- __tests__/integration/utils/event.ts
- __tests__/plots/api/chart-on-item-element.ts
- src/interaction/native/event.ts
抛出更多 element 的事件。
- click
- dbclick
pointer 事件：
- pointertap
- pointerdown
- pointerup
- pointerover
- pointerout
- pointermove
- pointerenter
- pointerleave
- pointerupoutside
拖拽事件：
- dragstart
- drag
- dragend
- dragenter
- dragleave
- dragover
- drop
如果希望 rightup 事件生效，需要禁止默认的 contextmenu 事件。
```js
const chart = new Container({ container });
chart.on('element:rightup', console.log);
// 禁止默认的 contextmenu 事件。
container.addEventListener('contextmenu', (e) => {
e.preventDefault();
});
```
如果希望监听拖拽事件，需要设置 draggable 和 droppable 属性。
```js
chart.interval().style('draggable', true).style('droppable', true);
```
有了 `pointer*` 事件，还是否需要 `mouse*` 事件？@xiaoiver 的建议是不加，因为 pointer 事件已经包含了。
> feat(event): add more bubbles event

- __tests__/plots/api/chart-options.ts
- __tests__/unit/api/chart.spec.ts
补测试 `chart.options(options)` 返回的值。
> test(chart): chart.options(options) should return this

- __tests__/integration/utils/filterTests.ts
- __tests__/integration/utils/toMatchCanvasSnapshot.ts
- __tests__/integration/utils/toMatchDOMSnapshot.ts
之前线上 CI 反复出现两个问题：
- 新增集成测试案例之后，本地没有生成新的截图就推到远端了。
- 本地调试的时候把某些案例设置成 only，但是忘记删除了就推到远端了。
为了防止这两个问题出现，通过 `process.env.CI` 的值去判断是否需要抛出异常。
> feat(ci): throw error for .only and missing snapshot

- __tests__/plots/interaction/penguins-point-highlight.ts
- package.json
修复 node canvas [v2.11.1](https://github.com/Automattic/node-canvas/releases/tag/v2.11.1) 升级带来的问题。
- 问题原因：node canvas 修复了之前 letter-spacing 不正确的问题，导致截图有文本的地方全部不匹配。
- 解决办法：暂时锁定版本到 v2.11.0，因为之后要替换测试为 playwright，到时候再统一升级。
> fix(ci): lock version of canvas to 2.11.0

- site/docs/api/overview.zh.md
- site/docs/api/timingKeyframe.en.md
- site/docs/api/timingKeyframe.zh.md
- site/docs/spec/overview.zh.md
修复文档概览中timingKeyframe的链接错误。另外，发现api文档中Keyframe的拼写是"KeyFrame"。是否需要统一为'timingKeyframe'。
> docs(site): fix spec timingKeyframe url

- site/docs/spec/transform/sample.zh.md
There is a small typo in site/docs/spec/transform/sample.zh.md.
Should read `transform` rather than `transfrom`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, transfrom -> transform

- __tests__/integration/api-chart-render-clear-animation.spec.ts
- __tests__/plots/api/chart-render-clear-animation.ts
- __tests__/plots/api/index.ts
- __tests__/unit/api/chart.spec.ts
- __tests__/unit/api/interaction.spec.ts
- src/interaction/legendFilter.ts
- src/runtime/plot.ts
解决 https://github.com/antvis/G2/issues/4896 提到的问题的 95% 。
- chart.render 之前没有取消之前的 animation。
- 多次调用 chart.render 的时候没有正确销毁之前的交互，导致 markState 这个变量一直没有销毁。
- 在 render 之前把上一次的 animation 对象全部取消。
- 正确的保存和销毁交互
可以发现内存增长的很慢了，这个部分需要 @xiaoiver 进一步在 g 里面看看：调用 animation.cancel 时候完全清除了动画。
> fix(OOM): clear interaction and cancel animation when rerendering

- __tests__/integration/snapshots/tooltip/mock-line-falsy/step0.html
- __tests__/integration/snapshots/tooltip/mock-line-falsy/step1.html
- __tests__/integration/snapshots/tooltip/mock-line-falsy/step2.html
- __tests__/integration/snapshots/tooltip/profit-interval-legend-filter-ordinal/step1.html
- __tests__/plots/tooltip/index.ts
- __tests__/plots/tooltip/london-tube-lines-geo.ts
- __tests__/plots/tooltip/mock-line-falsy.ts
- src/interaction/tooltip.ts
- src/runtime/transform.ts
fix https://github.com/antvis/G2/issues/4891 ，目前 tooltip items 不会自动过滤 falsy 的值：
- null
- undefined
- NaN
- 0
如果希望过滤这些值，可以通过自定义 filter 函数：
```js
chart.interaction('tooltip', {
filter: (d) =>
d.value !== null && d.value !== undefined && !Number.isNaN(d.value),
});
```
> fix(tooltip): show falsy item by default

- __tests__/unit/api/chart.spec.ts
- src/api/chart.ts
- src/api/composition/base.ts
- `new Chart()` 不将默认 key 设置到 options 上去，而是设置到单独 `chart._key` 这个变量上。防止改变用户传入的 options。
```js
const chart = new Chart();
// ...
expect(chart.options().key).toBeUndefined();
expect(chart._key).toBe('G2_CHART_KEY');
```
- chart 的私有方法加上前缀 `_`
```js
// Before
chart.bindAutoFit();
// After
chart._bindAutoFit();
```
> fix(chart): new Chart() do not set default view key

- __tests__/integration/chart-on-brush-filter.spec.ts
- __tests__/integration/chart-on-series-element.spec.ts
- __tests__/integration/utils/event.ts
- __tests__/plots/api/chart-on-brush-filter.ts
- __tests__/plots/api/index.ts
- site/docs/spec/interaction/brushFilter.zh.md
- src/interaction/brushFilter.ts
- src/interaction/brushHighlight.ts
brushFilter 交互抛出当前选中的数据。
```js
container,
});
type: 'point',
data: {
type: 'fetch',
value: 'data/penguins.csv',
},
encode: {
color: 'species',
x: 'culmen_length_mm',
y: 'culmen_depth_mm',
},
state: { inactive: { stroke: 'gray' } },
interaction: { brushFilter: true },
});
chart.on('brush:filter', (event) => { // 监听事件
const { selection } = event.data;
const [domainX, domainY] = selection;
const [minX, maxX] = domainX;
const [minY, maxY] = domainY;
console.log(minX, maxX, minY, maxY);
});
```
当每次**刷选**和**重置**的时候都会触发这个事件。
> feat(interaction): brushFilter emit filter event

- __tests__/plots/api/chart-options.ts
- src/api/chart.ts
theme 属性支持在 `chart.options()` 里申明：
```js
const chart = new Chart({ container });
type: 'line',
clip: true,
data: {
type: 'fetch',
value: 'data/aapl.csv',
},
encode: {
x: 'date',
y: 'close',
},
});
```
> fix: chart.theme as unrequired params

- __tests__/unit/api/chart.spec.ts
- src/api/chart.ts
在 `Chart.options` 中申明 autoFit 属性无法正常绑定 onResize 事件。因为该事件绑定在 Chart 的初始化中进行，此时拿不到 autoFit 属性。
修改方式：将 `bindAutoFit` 方法放在 render 函数中执行。
```js
import { Chart } from "@antv/g2";
const chart = new Chart({ container: "container" });
type: "interval",
theme: "classic",
autoFit: true,
data: {
type: "fetch",
value:
"https://gw.alipayobjects.com/os/bmw-prod/fb9db6b7-23a5-4c23-bbef-c54a55fee580.csv",
},
encode: { x: "letter", y: "frequency" },
axis: { y: { labelFormatter: ".0%" } },
});
```
> feat: chart bind autoFit in render

- __tests__/integration/snapshots/tooltip/alphabet-interval-tooltip-render-update/step0.html
- __tests__/integration/snapshots/tooltip/alphabet-interval-tooltip-render-update/step1.html
- __tests__/plots/tooltip/alphabet-interval-tooltip-render-update.ts
- __tests__/plots/tooltip/index.ts
- src/runtime/plot.ts
- src/transform/filter.ts
close: https://github.com/antvis/G2/issues/4959
两个问题：
- tooltip 重新渲染配置传递错误。
- legendFilter 没有正确 filter 原始数据，导致 item 展示错误。
> fix(tooltip): rerender correctly

- __tests__/integration/api-chart-emit-item-tooltip.spec.ts
- __tests__/integration/api-chart-emit-pie-tooltip.spec.ts
- __tests__/integration/api-chart-emit-series-tooltip.spec.ts
- __tests__/integration/api-chart-on-item-element.spec.ts
- __tests__/integration/api-chart-on-series-element.spec.ts
- __tests__/integration/snapshots/api/chart-emit-item-tooltip/step0.html
- __tests__/integration/snapshots/api/chart-emit-item-tooltip/step1.html
- __tests__/integration/snapshots/api/chart-emit-pie-tooltip/step0.html
- __tests__/integration/snapshots/api/chart-emit-series-tooltip/step0.html
- __tests__/integration/snapshots/api/chart-emit-series-tooltip/step1.html
- __tests__/integration/utils/event.ts
- __tests__/plots/api/chart-emit-item-tooltip.ts
- __tests__/plots/api/chart-emit-pie-tooltip.ts
- __tests__/plots/api/chart-emit-series-tooltip.ts
- __tests__/plots/api/index.ts
- site/docs/spec/interaction/tooltip.zh.md
- src/interaction/brushFilter.ts
- src/interaction/event.ts
- src/interaction/tooltip.ts
手动触发 Tooltip 和抛出数据。
```js
chart.on('tooltip:show', (event) => {
console.log(event.data.data);
});
chart.on('tooltip:hide', () => {
console.log('hide');
});
```
对于 Interval、Point 等非系列 Mark，控制展示的方式如下：
```js
// 条形图、点图等
chart
.interval()
.data([
])
.encode('x', 'genre')
.encode('y', 'sold')
.encode('color', 'genre');
chart.render().then((chart) =>
chart.emit('tooltip:show', {
data: {
data: { genre: 'Sports' },
},
}),
);
```
对于 Line、Area 等系列 Mark，控制展示的方式如下：
```js
chart
.line()
.data({ type: 'fetch', value: 'data/aapl.csv' })
.encode('x', 'date')
.encode('y', 'close');
chart.render().then((chart) =>
chart.emit('tooltip:show', {
data: { …
```
> feat(tooltip): on and emit

- __tests__/unit/api/chart.spec.ts
- src/api/chart.ts
- src/api/utils.ts
fixed #4990
因为 PR #4721 将用户传入的 renderer omit 了，所以使用了默认的 canvas 渲染。@lxfu1
```ts
options(options?: G2ViewTree): Chart | G2ViewTree {
if (arguments.length === 0) {
return this._options || optionsOf(this);
}
this._options = deepMix(
this._options || optionsOf(this),
omit(options, SPEC_EXTERNAL_KEYS),
);
return this;
}
```
> fix: svg renderer not works in website demo

- package.json
- vite.config.js
让 GUI 可以本地 link 调试，link 了 GUI 之后，运行以下命令。
```js
npm run dev:link
```
- 开发的时候修改本地 GUI package.json 的 module 字段为 "./src/index.ts"。
- 测试的时候修改本地 GUI package.json 的 module 字段为 'esm/index.js'。
- 无法调试：每次需要发布一个 GUI 版本看效果。
- 没有热更新：每次需要 build，然后再看效果。
> chore(dev): make @antv/gui linkable

- __tests__/integration/api-chart-on-item-element.spec.ts
- __tests__/plots/api/chart-on-item-element.ts
- site/docs/manual/event.zh.md
- src/interaction/event.ts
支持监听 plot event.
```js
autoFit: true,
});
chart
.interval()
.data({
type: 'fetch',
value:
'https://gw.alipayobjects.com/os/bmw-prod/fb9db6b7-23a5-4c23-bbef-c54a55fee580.csv',
})
.encode('x', 'letter')
.encode('y', 'frequency')
.axis('y', { labelFormatter: '.0%' });
chart.on('plot:click', () => console.log('plot'));
```
> feat(event): emit plot events

- CHANGELOG.md
- package.json
- site/package.json
> chore: update to 5.0.7

- __tests__/unit/api/chart.spec.ts
- src/api/chart.ts
当容器大小没有发生变化的时候，调用 `chart.forceFit` 不会重新渲染。
> fix(chart): chart.forceFit rerender only when size changing

- __tests__/integration/api-chart-render-brush-end.spec.ts
- __tests__/plots/api/chart-render-brush-end.ts
- __tests__/plots/api/index.ts
- src/interaction/brushHighlight.ts
> fix(brush): rerender don't emit brush:end

- __tests__/integration/api-chart-render-brush-end.spec.ts
- __tests__/unit/api/options.spec.ts
- src/interaction/brushHighlight.ts
- 问题：初始化，触发 emit 'brush:highlight', 会触发两次 highlight。
- 解决办法： brush.move 判断是否需要触发事件。
> fix(brush): handle brush:highlight once when emit

- __tests__/plots/static/alphabet-interval-label-overflow-hide.ts
- site/docs/spec/label/overview.zh.md
- src/runtime/plot.ts
ref: https://github.com/antvis/G2/issues/5069
label formatter 函数传入更多参数供业务层识别。
```js
autoFit: true,
});
chart
.interval()
.data({
type: 'fetch',
value:
'https://gw.alipayobjects.com/os/bmw-prod/f129b517-158d-41a9-83a3-3294d639b39e.csv',
format: 'csv',
})
.transform({ type: 'stackY' })
.transform({ type: 'sortX', by: 'y', reverse: true })
.encode('x', 'state')
.encode('y', 'population')
.encode('color', 'age')
.axis('x', {
labelSpacing: 4,
style: {
labelTransform: 'rotate(90)',
},
})
.axis('y', { labelFormatter: '~s' })
.label({
text: 'population',
formatter: (value, datum, index) => {
// 1. 根据 index 匹配 formattedData
// 2. 根据 data 信息得到不同数据的 formatter
}
});
```
> fix: label formatter callback params

- __tests__/unit/api/node.spec.ts
- __tests__/unit/api/options.spec.ts
- src/api/chart.ts
- src/api/node.ts
- src/api/utils.ts
Spec API和 Chart API 可以同时使用。
Spec API 和 Chart API 理论上应该分开使用，但是两者也有点细小的区别：
- Spec API 更适合第一次声明图表的时候使用
- Chart API 更适合更新特定图表属性。
所以两者混合的一个场景可以如下：
```js
// 第一次渲染
const chart = new Chart({});
data: [
],
encode: {
x: 'genre',
y: 'sold',
},
});
// 更新数据
chart
.getNodeByType('interval') //  获得 interval 实例
.data([
//更新数据
]);
```
`chart.options(spec)` 类似声明 innerHTML，如果当前没有 node tree，内部会将 spec 解析成一棵 node tree，否者会根据当前 options 更新该 node tree。（详见讨论：https://github.com/antvis/G2/discussions/4718 ）
根据 height 和 index …
> feat(api): use api and spec together

- __tests__/integration/api-chart-render-clear-animation.spec.ts
- __tests__/unit/api/chart.spec.ts
- src/api/chart.ts
- src/api/utils.ts
对 chart.render 进行防抖处理：如果当图表在渲染中的时候，会推迟新的渲染任务，如果当前已经有推迟的渲染任务，那么覆盖。
因为 chart.render 是一个异步的方法，**所以不能被取消**。当连续多次调用 chart.render 的时候，只有等当前的执行完，然后执行最新的那个渲染任务。
```js
const chart = new Chart(options);
let count = 0;
chart.on(ChartEvent.BEFORE_RENDER, () => {
count++;
});
const p1 = chart.render().then(() => expect(count).toBe(1));
const p2 = chart.render().then(() => expect(count).toBe(2));
```
```js
const chart = new Chart(options);
let count = 0;
chart.on(ChartEvent.AFTER_RENDER, () => {
count++;
});
expect(count).toBe(2); // 只有第一次和最后一次被渲染了。
```
> feat(chart): debounce chart.render

- __tests__/unit/g/index.spec.ts
- src/index.ts
在 G2 代码里禁用 G 的 CSS Parsing 的能力。
之前是在 GUI 里面禁用的，但是官网不知道设置失效（可能和打包顺序有关系），导致官网报错：
G2 的 index.ts 中显示指定为 false，这个 PR 合并之后需要重新部署官网。
> fix(site): disable css parsing

- CHANGELOG.md
- package.json
- site/package.json
这里的问题 https://github.com/antvis/G2/pull/5091 造成线上版本也有问题。
> chore: update to 5.0.10

- __tests__/integration/api-chart-on-item-element.spec.ts
- __tests__/plots/api/chart-on-item-element.ts
- src/interaction/event.ts
`pointerupoutside` 这个事件没有 target 对象，`chart.emit` 需要注意。
> fix(event): there is no target for pointerupoutside event

- .gitignore
- __tests__/treeshaking/index.html
- __tests__/treeshaking/main.ts
- __tests__/treeshaking/vite.config.js
- package.json
为了验证使用 G2 的项目是否能够享受 treeshaking 特性。在 `__tests__/treeshaking` 下创建了一个测试项目（依赖构建后的 esm），使用 rollup-plugin-visualizer 验证效果：
```bash
$ npm run build
$ npm run test:treeshaking
```
执行后会在根目录下生成一个 `analyser.html` 文件：
> chore: show treeshaking effects via bundle analyzer

- __tests__/unit/api/options.spec.ts
- src/api/node.ts
- src/api/utils.ts
修复 chart.options 不能删除节点的问题：
```js
const chart = new Chart({});
type: 'view',
children: [{ type: 'line' }, { type: 'point' }],
});
type: 'view',
children: [{ type: 'line' }],
});
expect(chart.options()).toEqual({
type: 'view',
children: [{ type: 'line' }],
});
```
> fix(chart): chart.options should remove node

- src/animation/fadeIn.ts
- src/animation/fadeOut.ts
- src/animation/growInX.ts
- src/animation/growInY.ts
- src/animation/morphing.ts
- src/animation/pathIn.ts
- src/animation/scaleInX.ts
- src/animation/scaleInY.ts
- src/animation/scaleOutX.ts
- src/animation/scaleOutY.ts
- src/animation/utils.ts
- src/animation/waveIn.ts
- src/animation/zoomIn.ts
- src/animation/zoomOut.ts
- src/runtime/plot.ts
- src/runtime/types/component.ts
- src/runtime/types/options.ts
调整 Animation API
```js
// 之前
function FadeIn(options) {
return (from, to, value, coordinate, defaults) => {};
}
```
```js
function FadeIn(options, context) {
const { coordinate } = context;
return (from, to, defaults) => {};
}
```
- coordinate 从 context 里面取。
- value 和 defaults 在 runtime 里面就合并了。
> refactor(api): animation api

- src/label-transform/contrastReverse.ts
- src/label-transform/overflowHide.ts
- src/label-transform/overlapHide.ts
- src/runtime/plot.ts
去掉了 coordinate 参数（目前都没有使用到），如果之后，通过 context 获得：和 shape 以及 animation 等保持一致。
```js
// 之前
function Hide(options) {
return (labels, coordinate) => {};
}
```
```js
// 当前
function Hide(options) {
return (labels) => {};
}
```
> refactor(api): remove coordinate for label transform

- site/docs/manual/single-view/api.zh.md
- site/docs/manual/single-view/transform.zh.md
- site/docs/manual/view-composition.zh.md
> docs: typo fix

- site/examples/general/interval/demo/column-log.ts
- site/examples/general/interval/demo/meta.json
- src/spec/mark.ts
- src/transform/maybeGradient.ts
close: https://github.com/antvis/G2/issues/5185
添加一个 example 解决当 Log Scale 不能映射 0 值的问题。
经过排查，上面 issue 中的问题不是 bug。其中 y1 为 `[0, 0, 0, ..., 0]`，而 log 比例尺无法映射 0。如果真的希望使用 log 比例尺，可以修改 y1 为接近 0 的值，同时设置 labelFormatter。
```js
const EPSILON = 1e-6;
padding: 'auto',
autoFit: true,
});
chart
.interval()
.data({
type: 'fetch',
value:
'https://gw.alipayobjects.com/os/bmw-prod/fb9db6b7-23a5-4c23-bbef-c54a55fee580.csv',
})
.encode('x', 'letter')
.encode('y', 'frequency')
.encode('y1', EPSILON) // Log scale cant' map zero, set a value close to zero.
.scale('y', { type: 'log' })
.axis('y', { labelFormatter: (d) => (d === EPSILON ? 0 : d) });
```
> docs(interval): log scale with zero value

- __tests__/integration/api-chart-emit-item-tooltip-hide-content.spec.ts
- __tests__/plots/api/chart-emit-item-tooltip-hide-content.ts
- __tests__/plots/api/index.ts
- src/interaction/tooltip.ts
`chart.on('tooltip:show', () => {})` 依赖 tooltip 显示才能调用。
业务层期望使用 tooltip:show 但不使用 G2 tooltip 组件，使用业务层的 tooltip 组件。
```js
chart
.interval()
.data([
])
.encode('x', 'genre')
.encode('y', 'sold')
.encode('color', 'genre')
.interaction('tooltip', {
showContent: false,
});
chart.on('tooltip:show', ({ data }) => {
p.innerText = JSON.stringify(data);
});
chart.on('tooltip:hide', () => {
console.log('hide');
};);
```
> feat: tooltip interaction emit events when body hide

- src/animation/morphing.ts
* 当 morphing 动画结束时，需要清除原始 Path 上的 transform。原因是在 convertToPath 时已经考虑了 transform，如果不清除会出现动画结束后 Path 位置偏移的现象。https://github.com/antvis/G/pull/1406/commits/0eb5142d929feb3b90ad18fe1b1298d4c606c231
* 移除多余的 `scale(1, 1)`，现在可以直接通过设置 `transform: 'none'` 清空。
> fix: clear transform when animation finished

- __tests__/integration/api-chart-tooltip-multi-chart.spec.ts
- __tests__/plots/api/chart-tooltip-multi-chart.ts
- __tests__/plots/api/index.ts
- src/interaction/tooltip.ts
fix: https://github.com/antvis/G2/issues/5270
- 出现原因：tooltip 实例是存储在 container 上的，如果 container 是 body，那么所有图表共用一个 tooltip，因为只有一个 body。但是每个 canvas 的 offset 是不同的，所以更新位置出现问题。
- 解决办法：tooltip 实例存储在对应的 canvas 对象上，而不是 container 上。
> fix(tooltip): multi chart when mounting to body

- __tests__/integration/api-chart-on-text-click.spec.ts
- __tests__/plots/api/chart-on-text-click.ts
- __tests__/plots/api/index.ts
- src/interaction/event.ts
- fix: https://github.com/antvis/G2/issues/5279
- 存在问题：Text 是一个 Custom Shape，target 并没有 className 和 markType 属性， 只有顶层的 group 有这两个属性。
- 解决办法：向上查找 className 为 element 的节点。
> fix(event): emit events for extended shape

- __tests__/plots/static/github-star-interval-palette.ts
- __tests__/unit/api/chart.spec.ts
- src/component/legendContinuous.ts
- src/runtime/plot.ts
- src/runtime/scale.ts
- src/runtime/types/theme.ts
- src/theme/academy.ts
- src/theme/classic.ts
- src/theme/classicDark.ts
简单调整一下 Theme 的结构。
Theme 的本质是**默认值**，而 G2 是由一系列可视化组件构成的，所以 Theme 应该是所有组件的默认值。那么结构就应该是 key 为组件名（不用加 namespace），value 为该组件对应的默认值。用 ts 表示如下：
```ts
type ComponentName = 'interval' | 'axis' | 'binX'; // ....
type Theme = Record<ComponentName, Record<string, any>>;
```
一个简单的例子如下：
```js
const theme = {
binX: {}, // Transform
axis: {}, // Static Mark
tooltip: {},  // Interaction
interval: {}, // Mark
}
```
当然除了组件的默认值，还有一些全局属性，比如：默认颜色，色板等，这些直接作为顶层的属性。
```js
const theme = {
color: 'red',
size: 1,
category: 'category10'
}
```
或者说都放在 globals 下？
```js
const theme = {
globals: {
color: 'red',
size: 1,
category: 'category10'
}
}
```
- view 相关的属性都收口到 view 下: 按照上面的思路，view 是一个单独可视化组件，属性应该放在一起。
```js
// Before
const theme = {
viewFill: 'red',
contentFill: 'red', 
}
// After
const theme = {
view: { viewFill: …
```
> refactor(theme): change some theme attributes

- .github/workflows/weekly.yml
每周四晚上20点统计每周活跃情况，报告默认会存到 `workflows/weekly-stats` 分支下，以当日日期命名
报告示例：
> chore: add weekly stats

- CHANGELOG.md
- package.json
- site/package.json
> chore: bump to 5.0.17

- site/docs/spec/mark/wordcloud.en.md
修复这个 https://github.com/antvis/G2/pull/5352 带来的 site 构建问题。
> fix: broken link for wordcloud

- package.json
- src/geo/geoView.ts
- vite.config.js
- 修复 coordinate.map 传入 null 的情况报错：
```js
// 之前如下是可以的
// 现在会报错
// 应该是 tslib 生成的构建代码有关系
coordinate.map(null);
```
- 添加 link node_modules 的命令：
```bash
$ MODULE=@antv/coord tnpm run dev:link
```
基于此添加了 `dev:link-gui` 的命令作为一个示例。
> fix: projection null

- __tests__/integration/snapshots/tooltip/flare-treemap-poptip-custom/step0.html
- __tests__/integration/snapshots/tooltip/flare-treemap-poptip/step1.html
- __tests__/integration/snapshots/tooltip/flare-treemap-poptip/step3.html
- __tests__/plots/static/alphabet-interval-html-label.ts
- src/shape/text/advance.ts
- fixed https://github.com/antvis/G2/issues/5390
- https://github.com/antvis/G/issues/1475 G 底层 HTML 组件通过 id 查找的 bug
等待 G 发布版本解决。
> fix: label dom leak when chart re-render

- site/.dumirc.ts
> docs: fix broken link

- site/.dumi/global.ts
- site/examples/geo/geo/demo/hexbin-china.ts
- site/examples/geo/geo/demo/hexjson-usa.ts
- site/examples/geo/geo/demo/meta.json
- site/package.json
- fixed https://github.com/antvis/G2/issues/5134
> docs: add hex bin demo

- CHANGELOG.md
- package.json
- site/package.json
- src/api/chart.ts
- src/api/extend.ts
之前的 Chart 会有问题：
```ts
const chart = new Chart();
chart.interval() // 有提示！
```
```ts
const chart: Chart = new Chart();
chart.interval() // 报错，没有提示！
```
Chart 不是通过 class 声明的：
```ts
const Chart = extend(Runtime, library);
```
所以 Chart 不能作为类型，为了使得它可以作为类型，之前声明了一个空的 interface：
```ts
interface Chart {};
const Chart = extend(Runtime, library);
```
两者的类型理论上会合并，但是 `typeof Chart` 其实是 `new() => Runtime` 一个构造函数，并不是 `Runtime`，也没有 interval 方法。
所以不能用空的 interface，还是得生成类型。
```ts
export interface Chart extends API<G2Spec, typeof library> {}
export const Chart = extend(Runtime, library);
```
> fix(types): add types for Chart interface

- site/docs/manual/extra-topics/3d-charts.zh.md
- site/examples/threed/scatter/demo/camera-animation.ts
- site/examples/threed/scatter/demo/meta.json
当用户经过了一番相机操作，有时想回到初始状态，例如 [plot.ly](https://plotly.com/javascript/3d-line-plots/) 在操作工具栏中就提供了 “Reset camera to default” 按钮：
使用 G 提供的[相机动画 API](https://g.antv.antgroup.com/api/camera/animation)，我们可以实现在任意相机位置间平滑过渡：
> chore: add camera animation example

- __tests__/integration/api-chart-on-component-click.spec.ts
- __tests__/plots/api/chart-on-component-click.ts
- __tests__/plots/api/index.ts
- site/docs/manual/extra-topics/event.zh.md
- src/interaction/event.ts
增加 component 的全局监听事件，之前点击图例和坐标轴，通过 `chart.on('component:click')` 监听不到点击事件
> update component click event

- src/runtime/coordinate.ts
- src/runtime/plot.ts
close: https://github.com/antvis/G2/issues/5400
> fix(coordinate): layout

- src/interaction/action/component/tooltip/ellipsis-text.ts
- tests/bugs/5409-spec.ts
tooltip 中根据 region 和 curLoc 来处理最终显示位置，目前 region 只在首次 renderTooltip 时才会设置，导致后续 height 发生变更，tooltip 显示位置有误
fix  #5409
> fix(ellipsis-test) tooltip show must need update region

- __tests__/unit/utils/selection.spec.ts
- src/interaction/brushHighlight.ts
- src/runtime/plot.ts
- src/shape/utils.ts
- src/utils/selection.ts
> refactor: remove this in selection

- __tests__/unit/lib/graph.spec.ts
- __tests__/unit/lib/plot.spec.ts
- src/lib/graph.ts
- src/lib/plot.ts
调整 graphlib 和 plotlib：
```ts
export function graphlib() {
return {
'mark.forceGraph': ForceGraph,
'mark.tree': Tree,
'mark.pack': Pack,
'data.arc': Arc,
'data.cluster': Cluster,
'mark.sankey': Sankey,
'mark.treemap': Treemap,
} as const;
}
```
```ts
export function plotlib() {
return {
'data.venn': Venn,
'mark.boxplot': Boxplot,
'mark.gauge': Gauge,
'mark.wordCloud': WordCloud,
} as const;
}
```
> feat(lib): change graphlib and plotlib

- CHANGELOG.md
- package.json
- site/package.json
目前出现了一系列**开发环境**和**线上环境**运行结果不一致的问题。
经过排查这个问题和 https://github.com/antvis/G2/pull/5391 引入的 treeshaking 能力有关系: `package.json` 里面 `sideEffects` 写错文件，指定的有副作用的应该是构建后产物 `esm/index.js` 而不是 `src/index.ts`
```json
{
"sideEffects": ["src/index.ts"]
}
```
这导致打包后的产物少了以下的两行代码：
```js
import { runtime } from '@antv/g';
runtime.enableCSSParsing = false;
```
最后使得线上和线下的运行结果不一致。
修改 `package.json` 如下：
```json
{
"sideEffects": ["./esm/index.js"]
}
```
@xiaoiver  `@antv/g` 可以不把 `enableCSSParsing` 作为一个全局配置，而是和 canvas 的一个配置。这样 G2 就没有 sideEffects 了。 
```js
import { Canvas } from '@anvtv/g';
const canvas = new Canvas({
enableCSSParsing: false,
});
```
> fix(bundle): add ./esm/index.js to package.sideEffects

- site/docs/manual/core/animation.zh.md
- site/docs/manual/core/api.zh.md
- site/docs/manual/core/chart.zh.md
- site/docs/manual/core/composition.zh.md
- site/docs/manual/core/coordinate.zh.md
- site/docs/manual/core/data.zh.md
- site/docs/manual/core/encode.zh.md
- site/docs/manual/core/interaction.zh.md
- site/docs/manual/core/label.zh.md
- site/docs/manual/core/mark.zh.md
- site/docs/manual/core/scale.zh.md
- site/docs/manual/core/size.zh.md
- site/docs/manual/core/state.zh.md
- site/docs/manual/core/style.zh.md
- site/docs/manual/core/tooltip.zh.md
- site/docs/manual/core/transform.zh.md
- site/docs/manual/extra-topics/3d-charts.zh.md
- site/docs/manual/extra-topics/bundle.zh.md
- site/docs/manual/extra-topics/color.zh.md
- site/docs/manual/extra-topics/customization.zh.md
- site/docs/manual/extra-topics/experimental-spec-api.zh.md
- site/docs/manual/extra-topics/use-in-framework.zh.md
- site/docs/manual/introduction/getting-started.zh.md
- site/docs/manual/introduction/what-is-g2.zh.md
- site/docs/manual/introduction/why-g2.zh.md
把文档中的 `theme.classic` 和 `padding.auto` 去掉。
> docs: remove theme:'classic'and padding: 'auto'

- site/docs/manual/core/theme.zh.md
> docs: update custom theme

- __tests__/plots/static/gauge-default.ts
- src/runtime/plot.ts
- src/runtime/transform.ts
之前如下的代码无法正常渲染：
```ts
export function gaugeDefault(): G2Spec {
return {
type: 'view',
data: {
value: {
target: 120,
total: 400,
name: 'score',
},
},
children: [{ type: 'gauge' }],
};
}
```
原因是因为在 view 层会把非表格数据 `{ value: { target: 120,  total: 400, name: 'score', } }` 处理成 `{ target: 120,  total: 400, name: 'score', }` 给 gauge，导致 gauge 处理出错。
本质上还是非表格数据必须写成 `{ value: data }` 的形式，但是表格数据可以直接写成 `data`。
view 层处理数据的时候保证数据的结构：如果是表格数据就返回表格数据，否者返回 `{ value: data }` 形式的数据。
至于为啥 G2 官网上代码可以正常运行，是因为 G2 官网的 Chart 为了更好展示 Spec 会有一些额外的处理。
> fix(runtime): process data

- README.md
- package.json
- rollup.config.js
- tsconfig.json
将 umd 的 target 设置为 es5，在打包 src 的情况同时打包 node_modules 里面的文件。
> chore: set target to es5 for umd

- __tests__/unit/api/chart.spec.ts
- src/api/runtime.ts
fix: https://github.com/antvis/G2/issues/5472
`supportsCSSTransform` 这个属性默认设置为 true
> feat(chart): supportsCSSTransform

- src/runtime/transform.ts
Remove `console.log` introduced by https://github.com/antvis/G2/pull/5508
> fix: remove console.log in runtime

- index.html
- rollup.config.js
- vite.config.js
修复 https://github.com/antvis/G2/pull/5515 带来的问题：
- fix: https://github.com/antvis/G2/issues/5548
- fix: https://github.com/antvis/G2/issues/5552
出现原因是通过 tsc 打包 es5 的时候会存在一些问题。
- 暂时先提供 es6 的版本
- 增加 `npm run preview` 配置去预览 umd 绘制的图表，每次发包之前预览一下，防止打包环节引入的 bug。
> fix: set target to es6 for umd

- __tests__/integration/snapshots/tooltip/state-ages-interval-custom-style/step0.html
- __tests__/plots/tooltip/index.ts
- __tests__/plots/tooltip/stateages-interval-custom-style.ts
- site/docs/manual/core/tooltip.zh.md
- site/docs/spec/interaction/tooltip.zh.md
- site/examples/component/tooltip/demo/tooltip-style.ts
- src/interaction/tooltip.ts
- src/spec/interaction.ts
close: https://github.com/antvis/G2/issues/5545
```js
import { Chart } from "@antv/g2";
const chart = new Chart({ container: "container" });
type: "interval",
data: {
type: "fetch",
value:
"https://gw.alipayobjects.com/os/bmw-prod/f129b517-158d-41a9-83a3-3294d639b39e.csv",
format: "csv",
},
encode: { x: "state", y: "population", color: "age" },
transform: [
{ type: "sortX", by: "y", reverse: true, slice: 6 },
{ type: "dodgeX" },
],
scale: { y: { nice: true } },
axis: { y: { labelFormatter: "~s" } },
interaction: {
tooltip: {
shared: true,
css: {
".g2-tooltip": {
background: "#eee",
"border-radius": " 0.25em !important",
},
".g2-tooltip-title": {
"font-size": "20px",
"font-weight": "bold",
"padding-bottom": "0.25em",
},
".g2-tooltip-list-item": {
background: "#ccc", …
```
> feat(tooltip): support css

- __tests__/integration/snapshots/tooltip/mock-tooltip-closest/step0.html
- __tests__/integration/snapshots/tooltip/mock-tooltip-closest/step1.html
- __tests__/plots/tooltip/index.ts
- __tests__/plots/tooltip/mock-tooltip-closest.ts
- src/interaction/tooltip.ts
close: https://github.com/antvis/G2/issues/5543
双轴图，存在 Item Mark（比如 Interval）和 Series Mark（比如 Line）的时候会有问题：
- 没有拾取到 line 到数据：
- 没有拾取到 interval 的数据：
- Series Mark 默认不会去拾取超出范围的元素的数据
- Item Mark 默认只会拾取包含鼠标位置的元素的数据
当是 Band 比例尺的时候，Series tooltip 找到最近的元素。
> fix(tooltip): find closest for band scale

- __tests__/unit/api/chart.spec.ts
- __tests__/unit/lib/threed.spec.ts
- src/api/runtime.ts
- src/api/utils.ts
- 存在问题：chart.destroy 会把 container 从 DOM 树里面移除。
- 解决办法：如果 container 是外部传入，不移除；如果是内部创建，移除。
> fix(api): only remove created container

- site/docs/spec/threed/intervalThreed.zh.md
修复该页面由于库引用错误所导致的没有光照效果、元素全部为黑色的问题。https://g2.antv.antgroup.com/spec/threed/interval-threed
从全局引用相关变量：
- `CameraType.ORBITING` 改为 `g.CameraType.ORBITING`
- `new DirectionalLight` 改为 `new gPlugin3d.DirectionalLight`
> fix: 修复 `site/docs/../intervalThreed.zh.md` 中元素全部为黑的问题

- __tests__/unit/api/mark.spec.ts
- src/shape/connector/connector.ts
修改 connector connectLength1 属性值获取逻辑
> fix(connector): fix connectLength1 default value getting

- src/interaction/tooltip.ts
fix: https://github.com/antvis/G2/issues/5385
- 存在问题：band 比例尺 invert 会改变 domain
- 解决办法：clone 一个新的，再 invert
- 测试：因为不太好添加，这里就先不添加了
> fix(tooltip): cloned series invert

- src/interaction/fisheye.ts
- src/interaction/tooltip.ts
- src/runtime/plot.ts
- close: https://github.com/antvis/G2/issues/5577
- 出现原因：每次都新建一个 tooltip
- 解决办法：针对 fisheye 每次都是隐藏 tooltip，不选择新建一个
- 同时解决了一个 tooltip 内存泄漏的问题，可能解决了这个 https://github.com/antvis/G2/issues/5555 里面提到的相关问题
> fix(tooltip): for fisheye

- package.json
- rollup.config.js
- ref https://github.com/antvis/G2/pull/5597
- fix bundle sideEffects
- add `preview` scripts
前一个分支的构建，因为没有注意到 sideEffects，导致构建出来的 bundle 文件中，下面的代码被移除。
```ts
import { runtime } from '@antv/g';
runtime.enableCSSParsing = false;
```
带来了一些渲染问题。
> fix: bundle sideEffects config

- package.json
- site/docs/manual/extra-topics/bundle.zh.md
- src/component/axis.ts
- src/component/legendCategory.ts
- src/component/legendContinuous.ts
- src/component/scrollbar.ts
- src/component/slider.ts
- src/component/utils.ts
- src/interaction/tooltip.ts
- src/shape/connector/connector.ts
- src/shape/text/advance.ts
- src/shape/text/badge.ts
- src/spec/interaction.ts
- vite.config.js
-[x] 升级 gui 为 component，repo 名字更加语义化。
> chore: upgrade gui to component

- site/.dumi/theme/components/ColorPicker.less
- site/.dumi/theme/components/ColorPicker.tsx
- site/.dumi/theme/components/ConfigPanel.less
- site/.dumi/theme/components/ConfigPanel.tsx
- site/.dumi/theme/components/DemosView.tsx
- site/.dumi/theme/components/builtins.ts
- site/.dumi/theme/examples/bar-aggregated.ts
- site/.dumi/theme/examples/bar-dodged.ts
- site/.dumi/theme/examples/bar-range.ts
- site/.dumi/theme/examples/grouped-box.ts
- site/.dumi/theme/examples/line-bar.ts
- site/.dumi/theme/examples/line-connect-nulls.ts
- site/.dumi/theme/examples/line-normalized.ts
- site/.dumi/theme/examples/missing-data-area.ts
- site/.dumi/theme/examples/point-log.ts
- site/.dumi/theme/examples/rose-label.ts
- site/.dumi/theme/examples/sankey.ts
- site/.dumi/theme/examples/spider-label.ts
- site/.dumi/theme/examples/stacked-area.ts
- site/.dumi/theme/examples/treemap.ts
- site/.dumi/theme/index.tsx
- site/.dumi/theme/utils/getG2Tokens.ts
- site/package.json
- src/theme/academy.ts
- src/theme/dark.ts
- src/theme/light.ts
主题构建器添加以下 tokens：
- 色板
- 颜色
- 间距
完成这个 issue https://github.com/antvis/G2/issues/5571 里面的更多配置。
> feat: add more tokens to theme set

- __tests__/integration/api-chart-auto-fit-slider.spec.ts
- __tests__/plots/api/chart-auto-fit-slider.ts
- __tests__/plots/api/index.ts
- __tests__/plots/interaction/indices-line-brush-series.ts
- src/api/utils.ts
- src/utils/size.ts
fix: https://github.com/antvis/G2/issues/5610
问题原因：设置 autoFit 时候 depth 为 width 大小，非 0。sliderFilter 设置的 clip path 在 depth 为非 0 的时候有问题。
> fix: depth default to zero

- .gitignore
- src/api/utils.ts
Fix the issue when autoFit is `true` and the container is lost height, the height config  is not effect.
> fix: auto fit

- package.json
更新之后翻译文档的方式如下：
```bash
$ npm run translate site/docs/manual/introduction/getting-started.zh.md
```
> chore: update script for translate

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/oscp.yml
> chore: add oscp template

- .github/workflows/build.yml
之前 Build CI 在外部用户的 PR 一直无法运行：
应该是缺失在提交 PR 的时候运行 CI 能力造成的。所以这里修改运行 CI 的时机。
> chore: run build action when trigger pull_request

- src/theme/create.ts
Fiexs #5685 
折线图 line 的默认主题样式中增加 lineCap: 'round'
> style: 添加line默认样式

- site/examples/composition/facet/demo/meta.json
- site/examples/composition/facet/demo/rect-frame.ts
close: https://github.com/antvis/G2/issues/5644
> docs: add example for custom style of view frame

- __tests__/plots/tooltip/aapl-line-date-default-format.ts
- __tests__/plots/tooltip/index.ts
- src/transform/maybeTitle.ts
- src/utils/dateFormat.ts
#5684 当图表中 encode 的 x 为日期字段的时候，tooltip title 会默认显示 x 轴的数据，对于日期的默认格式化效果不是很友好。
1. 先判断当前的tooltip title 是否有用户自定义的处理，如果有，对title不做任何处理
2. 如果没有用户自定义处理，对日期格式进行动态字符处理
1. 存在自定义处理
```ts
import { G2Spec } from '../../../src';
import { seriesTooltipSteps } from './utils';
export function aaplLine(): G2Spec {
return {
type: 'view',
children: [
{
type: 'line',
data: {
type: 'fetch',
value: 'data/aapl.csv',
},
encode: {
x: 'date',
y: 'close',
},
tooltip: {
title: (d) => new Date(d.date).toUTCString(),
},
},
],
};
}
aaplLine.steps = seriesTooltipSteps([200, 300]);
```
2. 移除自定义处理
```ts
import { G2Spec } from '../../../src';
import { seriesTooltipSteps } from './utils';
export function aaplLine(): G2Spec {
return {
type: 'view',
children: [
{
type: 'line',
data: {
type: 'fetch',
value: 'data/aapl.csv',
}, …
```
> feat: add default format to tooltip title #5684

- site/docs/manual/extra-topics/color.en.md
- site/docs/manual/extra-topics/customization.en.md
- site/docs/manual/extra-topics/experimental-spec-api.en.md
- site/docs/manual/extra-topics/migration-from-g2v4.en.md
- site/docs/manual/extra-topics/use-in-framework.en.md
* 翻译进阶主题下，《在框架中使用》到《自定义》五篇文档为英文。
#5744
> docs: translate framework - customization to en.

- __tests__/plots/api/chart-3d.ts
- __tests__/plots/api/index.ts
- package.json
- site/docs/manual/extra-topics/3d-charts.en.md
- site/docs/manual/extra-topics/3d-charts.zh.md
- site/docs/spec/threed/intervalThreed.zh.md
- site/docs/spec/threed/lineThreed.zh.md
- site/docs/spec/threed/pointThreed.zh.md
更新 3D 相关文档中用法，改成使用 `g2-extension-3d`:
```ts
import { Runtime, corelib, extend } from '@antv/g2';
import { threedlib } from '@antv/g2-extension-3d';
const Chart = extend(Runtime, { ...corelib(), ...threedlib() });
renderer,
depth: 400,
});
```
> chore: update 3d relative docs

- site/docs/manual/introduction/getting-started.en.md
- site/docs/manual/introduction/what-is-g2.en.md
这个 RP https://github.com/antvis/G2/pull/5778 遗留的问题：
> fix(docs): intro of g2

- site/examples/storytelling/storytelling/demo/meta.json
- site/examples/storytelling/storytelling/demo/stocks-keyframe.ts
> docs: add example stocks dark

- __tests__/integration/snapshots/static/temperature2LineGradientColorTranspose.svg
- __tests__/integration/snapshots/static/temperatures3AreaBandGradientTranspose.svg
- __tests__/plots/static/index.ts
- __tests__/plots/static/temperature2-line-gradient-color-transpose.ts
- __tests__/plots/static/temperatures3-area-band-gradient-transpose.ts
- src/shape/area/curve.ts
- src/shape/line/curve.ts
- src/shape/utils.ts
* 修复transpose下折线图和面积图渐变颜色的渲染问题。
* 在`style('gradient', 'y')`的情况下，如果设置了`transpose`，渐变的渲染方向应该是从右往左渲染，对应的角度为`180deg`；如果是`style('gradient', 'x')`的情况下，如果设置了`transpose`，则渲染方向是从上往下渲染，对应的角度为`90deg`。
#5361
> fix: fix the transpose color gradient render

- site/.dumirc.ts
> fix: dumi-theme-antv footerTheme light

- README.md
- __tests__/integration/snapshots/tooltip/movies-interval-scale-key-scrollbar/step0.html
- __tests__/plots/tooltip/index.ts
- __tests__/plots/tooltip/movies-interval-scale-key-scrollbar.ts
- src/component/slider.ts
- src/runtime/scale.ts
> fix: https://github.com/antvis/G2/issues/5654
> fix: https://github.com/antvis/G2/issues/5535
修改这个 PR https://github.com/antvis/G2/pull/5291 带来的问题：不能根据 scaleKey 去存储 scale，还是根据通道名字和索引去存储。
```js
scale: { x: { key: 'main' }}
})
```
内部生成的 scale 如下：
```js
const scale = {
main: {}
}
```
而不是
```js
const scale = {
x: {}
}
```
所以导致了以上的两个问题。
> fix(scale): group scale by name and index

- site/examples/intelligent/auto/demo/auto-interval.ts
- site/examples/intelligent/auto/demo/auto-line.ts
- site/examples/intelligent/auto/demo/auto-pie.ts
- site/examples/intelligent/auto/demo/auto-scatter.ts
- site/examples/intelligent/insight/demo/category-outlier.ts
- site/examples/intelligent/insight/demo/change-point.ts
- site/examples/intelligent/insight/demo/insight.ts
- site/examples/intelligent/insight/demo/low-variance.ts
- site/examples/intelligent/insight/demo/time-series-outlier.ts
- site/examples/intelligent/insight/demo/trend.ts
- 更新 g2-extension-ava 相关案例使用 Mark 的方式。
- 给 g2-extension-ava 相关案例添加 AVA 和 g2-extension-ava 的 github 的链接。
```js
// Before
import { Runtime, corelib, extend } from '@antv/g2';
import { autolib } from '@antv/g2-extension-ava';
const Chart = extend(Runtime, {
...corelib(),
...autolib(),
});
});
chart.auto().data([
{ price: 100, type: 'A' },
{ price: 120, type: 'B' },
{ price: 150, type: 'C' },
]);
```
```js
// After
import { Auto } from '@antv/g2-extension-ava';
});
// 通过 chart.mark 直接使用 Auto Mark
chart.mark(Auto).data([
{ price: 100, type: 'A' },
{ price: 120, type: 'B' },
{ price: 150, type: 'C' },
]);
```
> docs(demo): use chart.mark

- __tests__/integration/snapshots/api/viewFacetCircle.svg
- __tests__/integration/snapshots/static/monthIntervalFacetCircle.svg
- src/composition/facetCircle.ts
使用facetCircle绘制时，月份的数据和具体图表对应不上的问题 https://github.com/antvis/G2/issues/5624
处理在会只过程中对于子坐标系的原点计算的逻辑
```ts
import { Chart } from '../../../src';
export function viewFacetCircle(context) {
const { container, canvas } = context;
const M = [
'Jan.',
'Feb.',
'Mar.',
'Apr.',
'May',
'Jun.',
'Jul.',
'Aug.',
'Sept.',
'Oct.',
'Nov.',
'Dec.',
];
const N = ['A', 'B', 'C', 'D'];
const data = M.flatMap((month, i) =>
N.map((name, j) => ({
month,
name,
value: i + j,
})),
);
container: container,
canvas,
});
const facetCircle = chart
.facetCircle()
.data(data)
.encode('position', 'month');
facetCircle
.interval()
.encode('x', 'name')
.encode('y', 'value')
.encode('color', 'name');
const finished = chart.render();
return { chart, finished };
}
```
> fix: fix subLayoutFacetCircle cal center y problem

- src/interaction/tooltip.ts
任意 Element 可以通过如下方式获取画布，随后获取 DomElement：
```js
element.document.defaultView; // GCanvas
canvas.getContextService().getDomElement(); // <canvas> / <svg>
```
https://g.antv.antgroup.com/api/builtin-objects/document#defaultview
https://g.antv.antgroup.com/api/canvas/built-in-objects#getcontextservice
目前无法兼容 container 传入字符串（容器 id）的情况，导致 G6 相关示例报错。
> fix: tooltip should account for container in string format

- .gitignore
- src/runtime/library.ts
- src/runtime/render.ts
for `renderToMountedElement` func.
if cell is dynamic render, and removed outside of the viewport. G2 cannot find document
1. add canvas document default value
2. add plot type validate
```ts
curve.ts:113 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'createElement')
render.ts:149 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'defaultView')
```
| Before | After |
| -  |  - |
|  ![image](https://github.com/antvis/G2/assets/21015895/be33c207-115f-41f3-8022-04212a24486a) |  ![image](https://github.com/antvis/G2/assets/21015895/8b4c3568-eccf-4b89-931b-45c115a06dc9) |
> fix: cannot find document if group destroyed

- scripts/bench/chart.ts
- scripts/bench/tests/chart/point-temperatures/g2-v4-canvas.ts
- scripts/bench/tests/chart/point-temperatures/g2-v5-canvas-spec.ts
- src/runtime/library.ts
- 修复 https://github.com/antvis/G2/pull/5870 的类型问题
- 修复 bench 不能运行的问题
> fix: ci and bench

- __tests__/integration/api-chart-emit-enable-disable-tooltip.spec.ts
- __tests__/integration/api-chart-emit-item-tooltip-hide-content.spec.ts
- __tests__/integration/api-chart-emit-item-tooltip.spec.ts
- __tests__/integration/api-chart-tooltip-multi-chart.spec.ts
- __tests__/integration/snapshots/tooltip/alphabet-interval-enterable/step0.html
- __tests__/plots/interaction/stateages-interval-highlight-group-background.ts
- __tests__/plots/tooltip/alphabet-interval-enterable.ts
- __tests__/plots/tooltip/alphabet-interval-tooltip-render-update.ts
- __tests__/plots/tooltip/flare-treemap-poptip.ts
- __tests__/plots/tooltip/index.ts
- __tests__/plots/tooltip/profit-interval-legend-filter-ordinal.ts
- __tests__/plots/tooltip/utils.ts
- package.json
- src/interaction/tooltip.ts
- src/spec/interaction.ts
- rel https://github.com/antvis/component/pull/310
- fixed https://github.com/antvis/G2/issues/5620
----
> fix: tooltip enterable

- __tests__/integration/snapshots/animation/stocks-keyframe/interval2-0.svg
- __tests__/integration/snapshots/animation/stocks-keyframe/interval2-1.svg
- __tests__/integration/snapshots/api/chart-emit-scrollbar-filter/step0.svg
- __tests__/integration/snapshots/api/chart-emit-scrollbar-filter/step1.svg
- __tests__/integration/snapshots/api/chart-emit-slider-filter/step0.svg
- __tests__/integration/snapshots/api/chart-emit-slider-filter/step1.svg
- __tests__/integration/snapshots/api/chart-render-update-attributes/step0.svg
- __tests__/integration/snapshots/api/chart-render-update-attributes/step1.svg
- __tests__/integration/snapshots/api/chartChangeDataLegend.svg
- __tests__/integration/snapshots/api/markChangeData.svg
- src/runtime/plot.ts
[BUG: 自定义轴标签在缩放页面时消失#5826](https://github.com/antvis/G2/issues/5826)
解决办法：
导致问题产生的核心问题是由于异步渲染的问题，将animate的动画在axis组件渲染后，runtime的时候关闭掉更新的动画渲染。
DEMO: 访问官网示例 https://g2.antv.antgroup.com/examples/component/axis/#axis
```tsx
autoFit: true,
});
chart.data([
{
pos: 1,
no: 1,
driver: 'Max Verstappen',
car: 'RED BULL RACING HONDA RBPT',
laps: 57,
time: '1:33:56.736',
pts: 25,
},
{
pos: 2,
no: 11,
driver: 'Sergio Perez',
car: 'RED BULL RACING HONDA RBPT',
laps: 57,
time: '+11.987s',
pts: 18,
},
{
pos: 3,
no: 14,
driver: 'Fernando Alonso',
car: 'ASTON MARTIN ARAMCO MERCEDES',
laps: 57,
time: '+38.637s',
pts: 15,
},
{
pos: 4,
no: 55,
driver: 'Carlos Sainz',
car: 'FERRARI',
laps: 57,
time: '+48.052s',
pts: 12,
},
{ …
```
> fix(axis): custom axis tags disappear when the page is zoomed

- __tests__/integration/snapshots/interaction/alphabet-interval-active-scrollbar/step1.svg
- __tests__/integration/snapshots/interaction/alphabet-interval-highlight-background-polar/step0.svg
- __tests__/integration/snapshots/interaction/alphabet-interval-highlight-background-style/step0.svg
- __tests__/integration/snapshots/interaction/alphabet-interval-highlight-background-style/step2.svg
- __tests__/integration/snapshots/interaction/alphabet-interval-highlight-background-transpose/step0.svg
- __tests__/integration/snapshots/interaction/alphabet-interval-highlight-background/step0.svg
- __tests__/integration/snapshots/interaction/alphabet-interval-highlight-background/step1.svg
- __tests__/integration/snapshots/interaction/alphabet-interval-highlight-background/step3.svg
- __tests__/integration/snapshots/interaction/alphabet-interval-select-background/step0.svg
- __tests__/integration/snapshots/interaction/alphabet-interval-select-background/step2.svg
- __tests__/integration/snapshots/interaction/alphabet-interval-select-background/step3.svg
- __tests__/integration/snapshots/interaction/alphabet-interval-select-single-background/step0.svg
- __tests__/integration/snapshots/interaction/alphabet-interval-select-single-background/step2.svg
- __tests__/integration/snapshots/interaction/mock-interval-tooltip-background/step0.svg
- __tests__/integration/snapshots/interaction/penguins-point-highlight/step0.svg
- __tests__/integration/snapshots/interaction/state-ages-interval-highlight-color-background/step0.svg
- __tests__/integration/snapshots/interaction/state-ages-interval-highlight-group-background/step0.svg
- __tests__/integration/snapshots/interaction/state-ages-interval-highlight-group-background/step2.svg
- __tests__/integration/snapshots/interaction/waffle-cell-highlight-background/step0.svg
- __tests__/plots/interaction/index.ts
- __tests__/plots/interaction/mock-interval-tooltip-background.ts
- src/interaction/utils.ts
fix: https://github.com/antvis/G2/issues/5955
- 存在问题：两个 interval 属于不同的 layer，background 是跟随每个 layer 的，会存在相互重叠，影响 tooltip 的拾取。
- 解决办法：background 跟随图表区域，而不是 layer，这样所有 mark 的 background 都在一层了。
> fix(series): interval background

- __tests__/unit/api/options.spec.ts
- src/api/utils.ts
解决问题：
fixes #5783  修复当 root 是一个 composition node 时候，丢失chart options的问题
解决方案：
当检测到跟节点是composition node的时候，将chart配置的 VIEW_KEYS 下发到composition中
修改后：
https://github.com/antvis/G2/assets/35752509/0a163f36-a7c5-4bce-a0f9-66210a1de415
> fix(composition): fix composition lost chart value options

- __tests__/integration/snapshots/tooltip/disasters-point-slider/step0.html
- __tests__/plots/tooltip/disasters-point-slider.ts
- __tests__/plots/tooltip/index.ts
- src/interaction/tooltip.ts
修复当有 slider 的时候，tooltip 不自动调整位置的问题：
- 原因：有 slider 的时候有 clip path，使用 getBounds 获得容器包围盒有问题
- 解决办法：用 getRenderBounds 替换
> fix(slider): adjust tooltip's position when clipped

- site/docs/spec/component/axis.zh.md
> fix(docs): add axis missing property  `labelOpacity`

- src/interaction/elementPointMove.ts
1、tooltip 为 false 时， seriesTitle 为空，导致的错误
2、coordinate 运算极限值，会出现 1 或者 3.3333e-17 的问题，改用 y1.
> fix(pointmove): 修复 pointmove 事件的两个问题

- __tests__/integration/snapshots/tooltip/alphabet-text/step0.html
- __tests__/plots/tooltip/alphabet-text.ts
- __tests__/plots/tooltip/index.ts
- src/interaction/event.ts
- src/interaction/tooltip.ts
- src/interaction/utils.ts
- 问题：修复词云图 tooltip 不展示。
- 原因：text 是一个 custom shape，触发事件的对象不是 element 元素，而是子元素，导致当前判断失效。
- 解决办法：触发的标注改成：该元素是 element 的子元素。
> fix: tooltip for custom element

- __tests__/integration/snapshots/api/chart-emit-series-tooltip/step0.html
- __tests__/integration/snapshots/tooltip/mock-line-flex/step0.html
- __tests__/plots/tooltip/index.ts
- __tests__/plots/tooltip/mock-line-flex.ts
- src/interaction/utils.ts
close: https://github.com/antvis/G2/issues/6130
- 问题：多视图 tooltip 展示失败。
- 原因：通过 style 获得 rect bbox 没有考虑 transform，会导致拾取不到。
- 解决办法：通过 getGeometryBounds + transform 来获得真实的 bbox。
> fix: tooltip for multi view

- CHANGELOG.md
- package.json
- site/examples/annotation/shape/demo/watermark.ts
- site/examples/geo/geo/demo/hexjson-usa.ts
- site/examples/interesting/interesting/demo/petal.ts
- site/package.json
发布 5.1.18
案例都检查了一遍，发现目前线上有一个例子报错：
https://g2.antv.antgroup.com/zh/examples/geo/geo#hexjson-usa
> chore: bump to 5.1.18

- src/runtime/plot.ts
- src/runtime/types/component.ts
- feat: add context for customize label transform https://github.com/antvis/G2/pull/6209
> feat: add context for customize label transform

- src/runtime/layout.ts
- src/runtime/transform.ts
Only display axisZ when axis enabled. Add `Z` to axis channels so that it can be toggled with `axis` option.
```ts
chart
.point3D()
.data({
type: "fetch",
value: "data/cars2.csv",
})
.encode("x", "Horsepower")
.encode("y", "Miles_per_Gallon")
.encode("z", "Weight_in_lbs")
.encode("size", "Origin")
.encode("color", "Cylinders")
.encode("shape", "cube")
.coordinate({ type: "cartesian3D" })
.scale("x", { nice: true })
.scale("y", { nice: true })
.scale("z", { nice: true })
.axis(false)
.legend(false);
```
> fix: hide axisZ when axis disabled

- site/.dumi/theme/index.less
fix: horizontal srcoll causes the side theme button invisible
> docs: horizontal srcoll causes the side theme button invisible

- __tests__/integration/snapshots/tooltip/mock-dual-bar-share-tooltip/step0.html
- __tests__/plots/tooltip/index.ts
- __tests__/plots/tooltip/mock-dual-bar-share-tooltip.ts
- src/interaction/tooltip.ts
close: https://github.com/antvis/G2/issues/5930
> fix(tooltip): dual axes with mult-series bar

- __tests__/integration/api-chart-emit-series-tooltip.spec.ts
- __tests__/plots/tooltip/alphabet-line-enterable.ts
- __tests__/plots/tooltip/index.ts
- src/interaction/tooltip.ts
close: https://github.com/ant-design/ant-design-charts/issues/2560
> fix(tooltip): series enterable

- site/examples/component/tooltip/demo/meta.json
- site/examples/component/tooltip/demo/tooltip-two.ts
close: https://github.com/antvis/G2/issues/4859
添加了一个例子：在一个图表里面画两个 tooltip。
```js
function css(...styles) {
return styles
.map((obj) =>
Object.entries(obj)
.map(([k, v]) => k + ':' + v)
.join(';'),
)
.join(';');
}
autoFit: true,
});
chart.data([
{ time: '16', north: 0, south: 0 },
{ time: '18', north: 7, south: -8 },
{ time: '20', north: 6, south: -7 },
{ time: '22', north: 9, south: -8 },
{ time: '00', north: 5, south: -7 },
{ time: '02', north: 8, south: -5 },
{ time: '04', north: 6, south: -7 },
{ time: '06', north: 7, south: -8 },
{ time: '08', north: 9, south: -9 },
{ time: '10', north: 6, south: -9 },
{ time: '12', north: 5, south: -9 },
]);
chart
.area()
.encode('x', (d) => d.time)
.encode('y', …
```
> docs: add two tooltips in one chart

- __tests__/integration/snapshots/api/chart-emit-item-tooltip/step0.html
- __tests__/integration/snapshots/api/chart-emit-item-tooltip/step1.html
- __tests__/plots/api/chart-emit-item-tooltip.ts
- site/docs/spec/interaction/tooltip.zh.md
- site/examples/component/tooltip/demo/meta.json
- site/examples/component/tooltip/demo/tooltip-click.ts
- src/interaction/tooltip.ts
优化点击展示 tooltip 的例子，为了完成这个例子，增加了以下的能力：
- 传递 offset
- chart.emit('tooltip:show")  可以传递 offsetX 和 offsetY
> docs(tooltip): update click example

- __tests__/integration/snapshots/api/chart-emit-series-tooltip/step0.html
- __tests__/integration/snapshots/api/chart-emit-series-tooltip/step1.html
- __tests__/plots/api/chart-emit-item-tooltip.ts
- __tests__/plots/api/chart-emit-series-tooltip.ts
- site/docs/spec/interaction/tooltip.zh.md
- site/examples/component/tooltip/demo/meta.json
- site/examples/component/tooltip/demo/tooltip-click-line.ts
- site/examples/component/tooltip/demo/tooltip-click.ts
- site/examples/component/tooltip/demo/tooltip-render.ts
- src/interaction/tooltip.ts
- src/spec/interaction.ts
支持可以通过点击展示 tooltip，主要的使用方式如下：
```js
chart.on('plot:click', ({ offsetX, offsetY, target }) => {
chart.emit('tooltip:show', { offsetX, offsetY: 20, target });
});
```
> feat(tooltip): click to show line tooltip

- __tests__/integration/api-chart-word-cloud-canvas.spec.ts
- __tests__/plots/api/chart-word-cloud-canvas.ts
- __tests__/plots/api/index.ts
- site/docs/spec/mark/wordcloud.zh.md
- src/api/runtime.ts
- src/data/utils/d3-cloud/index.ts
- src/data/wordCloud.ts
- src/runtime/mark.ts
- src/runtime/plot.ts
- src/runtime/render.ts
- src/runtime/transform.ts
- src/runtime/types/data.ts
- src/runtime/types/transform.ts
WordCloud Mark 支持传入自定义的 Canvas，可以用于服务端渲染。
```js
createCanvas: () => {
// 传入自定义的 Canvas
return document.createElement('canvas');
},
});
type: 'wordCloud',
data: {
type: 'fetch',
value: 'data/philosophyWord.json',
}
});
```
> feat(wordcloud): accept custom canvas

- __tests__/integration/snapshots/interaction/alphabet-interval-active-marker-type/step0.svg
- __tests__/integration/snapshots/interaction/alphabet-interval-active-marker-type/step1.svg
- __tests__/integration/snapshots/interaction/change-size-polar-crosshairs-x-y/step0.svg
- __tests__/integration/snapshots/interaction/change-size-polar-crosshairs-x-y/step1.svg
- __tests__/integration/snapshots/interaction/indices-line-crosshairs-x-y/step0.svg
- __tests__/integration/snapshots/interaction/indices-line-crosshairs-x-y/step1.svg
- __tests__/integration/snapshots/interaction/missing-area-tooltip-marker/step1.svg
- __tests__/integration/snapshots/interaction/points-point-tooltip-marker/step0.svg
- __tests__/integration/snapshots/interaction/stocks-line-slider/step1.svg
- __tests__/integration/snapshots/tooltip/temperature-line-marker/step0.html
- __tests__/integration/snapshots/tooltip/temperature-line-marker/step1.html
- __tests__/plots/tooltip/index.ts
- __tests__/plots/tooltip/temperatures-line-marker.ts
- site/examples/component/tooltip/demo/meta.json
- site/examples/component/tooltip/demo/tooltip-click-line.ts
- site/examples/component/tooltip/demo/tooltip-line-marker.ts
- src/interaction/tooltip.ts
Tooltip 可以自定义 marker 的 tooltip：
> feat(tooltip): custom marker tooltip

- CHANGELOG.md
- README.md
- README.zh-CN.md
- jest.config.js
- package.json
- site/package.json
> chore: v5.2.3

- __tests__/plots/bugfix/index.ts
- __tests__/plots/bugfix/issue-6399.ts
- src/interaction/tooltip.ts
fixes #6399 
After setting the height of the outer container of the canvas to 100vh and the overflow to auto, set the height of the inner container to a relatively high value like 4000px. When scrolling and moving the mouse to the lower half of the chart, the tooltip is displayed in the correct position.![image](https://github.com/user-attachments/assets/d7e4dce1-7a0f-4567-af8b-d0c85dfb1ac6)
> fix: when update the position of tooltip, calculate the containerOffset

- CHANGELOG.md
- package.json
> chore: change log

- __tests__/plots/bugfix/index.ts
- __tests__/plots/bugfix/issue-chart-2719.ts
- src/interaction/tooltip.ts
https://github.com/ant-design/ant-design-charts/issues/2719
> fix: tooptip position offset in dodgeX

- src/label-transform/exceedAdjust.ts
- src/runtime/plot.ts
- src/runtime/types/component.ts
Prevent label overlap in multiple charts by calculating layouts separately to avoid collisions.
> fix:  prevent label overlap in multiple charts

- site/docs/spec/common/navigator.zh.md
chart.legend官方文档,分页属性名无效，进行了修改；
https://g2.antv.antgroup.com/spec/component/legend#%E5%9B%BE%E4%BE%8B%E9%A1%B9
原文档无效属性:
navOrient 是无效的; 应该是navOrientation；
navInitPage 是无效的; 应该是navDefaultPage；
原文档缺失属性：
navPageNumFill：分页数字颜色
navPageNumFontSize：分页数字大小
navPageNumOpacity：分页数字透明度
navPageNumStroke：分页数字描边
navPageNumStrokeOpacity：分页数字描边透明度
navButtonFill：分页按钮颜色
navButtonOpacity： 分页数按钮透明度
navButtonStroke：分页按钮描边颜色
navButtonStrokeOpacity：分页按钮描边透明度
> 'fix(docs):chart.legend文档,分页属性名错误修改'

- site/docs/spec/component/slider.zh.md
- src/component/slider.ts
update the slider documentation that are already supported options but not shown in the docs.
For example：
To avoid label overlap, set autoFitLabel to false and add paddingRight to the chart
> docs: update slider options

- __tests__/integration/snapshots/static/gaugeCustomTextTooltip.svg
- __tests__/plots/static/gauge-custom-text-tooltip.ts
- __tests__/plots/static/index.ts
- src/mark/gauge.ts
- Add gauge-custom-text-tooltip.ts test case
- Update gauge mark to support text tooltip configuration
- Remove default tooltip from DEFAULT_TEXT_OPTIONS
- Extract tooltip from textStyle in gauge mark
> feat(gauge): add custom text tooltip support for gauge chart

- __tests__/plots/bugfix/issue-5474.ts
- site/docs/spec/label/overview.zh.md
- src/runtime/plot.ts
- Removed redundant structure in the label rendering process.
- Replaced elementStyle with element to expose the correct attributes in label functions.
> fix: remove unnecessary structure and update label attributes

- package.json
- site/package.json
- Downgrade fmin version to fix development packaging issues
- Solve the ghost dependency problem of lodash in site when using `pnpm install`
> fix: site dev error & lodash ghost dependency

- src/shape/heatmap/heatmap.ts
- fixed #6512 
After the upgrade of the underlying G engine, the `src` attribute of the image element no longer supports directly passing the canvas instance. The abnormal rendering problem of the heat map can be solved by passing the dataurl string.
> fix: heatmap render error

- __tests__/unit/api/chart.spec.ts
- src/api/runtime.ts
解决类型错误：Property 'supportsCSSTransform' does not exist on type 'CanvasConfig'
底层依赖g版本升级，supportsCSSTransform=true是默认设置，g2中不再需要设置supportsCSSTransform属性
> fix:  g版本升级，supportsCSSTransform=true是默认设置

- site/docs/api/chart.zh.md
- site/docs/api/facetCircle.zh.md
- site/docs/api/facetRect.zh.md
- site/docs/api/geoView.zh.md
- site/docs/api/mark.zh.md
- site/docs/api/repeatMatrix.zh.md
- site/docs/api/spaceFlex.zh.md
- site/docs/api/spaceLayer.zh.md
- site/docs/api/timingKeyframe.zh.md
- site/docs/api/view.zh.md
本次文档修订覆盖官网的api部分，以下均为共通的问题，不止一处，不一一列出：
- connector 文档缺失，隐藏链接。
- wordCloud 文档链接错误
- width、height、title、tooltip 文案优化，统一为中文
- encode 文档链接错误
- slider 文案错误 坐标轴=>缩略轴
- theme 文档链接错误
- labelTransform 文案补充 具体见 label=>具体见 label里的transform配置
- chart.off 文案错误 写在 chart 上的监听事件。=>卸载 chart 上的监听事件。
- mark.encode mark.theme mark.animatemark.axismark.legendmark.slidermark.scrollbarmark.statemark.tooltip 文档链接错误
- geoView.sankey 文档链接错误
- shape 文案错误 添加 shape 图形=>添加自定义图形
- mark.changeData mark.getGroup mark.getScale mark.getScaleByChannel都写成chart了，已统一修改
> docs: g2官网api文档跳转以及文案错误订正

- __tests__/plots/static/barley-line-trail.ts
- __tests__/plots/static/income-statement-by-region-interval-custom.ts
- package.json
- src/data/utils/arc/arc.ts
- src/data/utils/arc/types.ts
- src/interaction/legendHighlight.ts
- src/runtime/layout.ts
- src/transform/bin.ts
- 将 vendor 版本设置为 ^1.0.8，解决了 @types/d3-array 锁死的问题
> chore: resolve d3-array type locked issue

- .github/workflows/scripts/updateYuque.js
- .github/workflows/update-yuque.yml
- 添加 GtiHub Action 当PR合并时将自动检测 `**/*.md` 文件是否变更，有变更将同步到语雀知识库
知识库地址：https://www.yuque.com/antv/luaak6
> feat: add action to update documentations to yuque

- site/docs/manual/core/mark/range.zh.md
- site/docs/manual/core/mark/rangeX.zh.md
- site/docs/manual/core/mark/rangeY.zh.md
> mark-range
> mark-rangeX
> mark-rangeY
> docs: mark-range、mark-rangeX、mark-rangeY

- __tests__/unit/utils/helper.test.ts
- src/api/runtime.ts
- src/exports.ts
- src/interaction/event.ts
- src/interaction/tooltip.ts
- src/utils/helper.ts
1. 导出一些常用的工具方法，调整了工具函数的目录结构
2. 简化 dataOf 函数，支持直接传入 element 得到原始数据
```tsx
import { dataOf } from '@antv/g2'
...
chart.on('plot:click', e => {
console.log(dataOf(e.target)) // do something with original data
})
```
> chore: export some useful utils func

- __tests__/integration/snapshots/interaction/alphabet-interval-active-marker-type/step0.svg
- __tests__/integration/snapshots/interaction/alphabet-interval-active-marker-type/step1.svg
- __tests__/integration/snapshots/interaction/change-size-polar-crosshairs-x-y/step0.svg
- __tests__/integration/snapshots/interaction/change-size-polar-crosshairs-x-y/step1.svg
- __tests__/integration/snapshots/interaction/indices-line-crosshairs-x-y/step0.svg
- __tests__/integration/snapshots/interaction/indices-line-crosshairs-x-y/step1.svg
- __tests__/integration/snapshots/interaction/missing-area-tooltip-marker/step1.svg
- __tests__/integration/snapshots/interaction/points-point-tooltip-marker/step0.svg
- __tests__/integration/snapshots/interaction/stocks-line-slider/step1.svg
- src/interaction/tooltip.ts
tooltip marker 阻挡了 element select，把这个 marker 改为 `pointerEvents: 'none'` 了
https://stackblitz.com/edit/react-chvm779o-6ubq4v8q?file=src%2Findex.js
> fix: tooltip marker blocked elements select

- __tests__/unit/utils/expr.spec.ts
- site/.dumirc.ts
- site/docs/manual/extra-topics/expr.en.md
- site/docs/manual/extra-topics/expr.zh.md
- site/examples/expr/base/demo/expr.ts
- site/examples/expr/base/demo/meta.json
- site/examples/expr/base/index.en.md
- site/examples/expr/base/index.zh.md
- src/utils/expr.ts
> docs: add documentation for expr function expression support

- site/docs/manual/core/transform/diffY.zh.md
- src/spec/transform.ts
- src/transform/diffY.ts
- src/transform/utils/helper.ts
> docs: update transform.diffY

- site/docs/manual/core/transform/normalizeY.zh.md
- Fixed: #6682 
先写了一版demo 麻烦帮看看是否可行
> docs: 改造文档「核心概念 - 转换（Transform）- normalizeY

- site/package.json
Lock the dumi version to prevent errors on the official website.
> chore: lock the dumi version

- __tests__/integration/snapshots/tooltip/reverse-scale-range/step0.html
- __tests__/plots/tooltip/index.ts
- __tests__/plots/tooltip/reverse-scale-range.ts
- src/interaction/tooltip.ts
handle the case where stepWidth is negative such as
```
.scale:('x', { range:[1, 0]})
```
> fix: handle the case where stepWidth is negative

- __tests__/plots/bugfix/index.ts
- __tests__/plots/bugfix/issue-6762.ts
- src/interaction/tooltip.ts
- fixed: #6762 
- 之前对于单一element的tooltip拾取只考虑了scale为point的情况，在linear情况下没有参数adjustedRange，会报错
> fix(tooltip): tooltip with one element

- site/docs/manual/core/transform/flexX.zh.md
- Fixed:  #6677
目前是用了两个例子 看看可行性如何
> docs: 完善 flexX 转换文档，增加使用场景和示例

- site/docs/manual/core/scale/ordinal.zh.md
修复了 [Scale 文档中 ordinal 表格](https://g2.antv.antgroup.com/manual/core/scale/ordinal#%E9%80%89%E9%A1%B9) 渲染 ts 类型定义时的错误
> fix(docs): fix a render error of char '|'

- __tests__/integration/snapshots/static/flareTreemapCustom.svg
- __tests__/integration/snapshots/static/flareTreemapDefault.svg
- __tests__/integration/snapshots/static/flareTreemapDrillDown.svg
- src/interaction/treemapDrillDown.ts
- src/mark/treemap.ts
之前修复矩阵树图点击 `label` 时下钻不成功的问题 #6765 的时候的 PR 将鼠标事件设置为了 `none` ,导致 `poptip`交互无法触发，现改变方式，通过识别矩阵树图每个区域的 `label` 来实现下钻。
> fix(interaction): the poptip is not working

- __tests__/plots/api/chart-element-highlight-region.ts
- __tests__/plots/api/index.ts
- site/docs/manual/core/interaction/elementHighlight.zh.md
- site/docs/manual/core/state.zh.md
- src/interaction/elementHighlight.ts
- src/interaction/elementSelect.ts
- src/interaction/utils.ts
- src/spec/interaction.ts
1. 参考 https://github.com/antvis/G2/pull/6724 ，增加 region 参数使 elementHighligh 支持在空白处触发，达到类似 v4 版本 active-region 的效果，解决 https://github.com/antvis/G2/issues/6582
2. 定义多交互共存时优先级，让多交互之间效果可共存，冲突时根据优先级排序，解决 https://github.com/antvis/G2/issues/6803
> feat: support region highlight

- __tests__/integration/snapshots/interaction/multiple-interactions-coexist/step0.svg
- __tests__/integration/snapshots/interaction/multiple-interactions-coexist/step1.svg
- __tests__/plots/interaction/index.ts
- __tests__/plots/interaction/multiple-interactions-coexist.ts
- src/interaction/elementHighlight.ts
- src/interaction/elementSelect.ts
- src/interaction/utils.ts
- related: https://github.com/antvis/G2/issues/6803
- 引入了新的 `isReset` 参数到 `useState` 实用程序中，只有当 `isReset` 为 `false` ，才会融合 style，用于控制样式的合并或重置行为。  
- 目前只有`elementSelect` 和 `elementHighlight` 的样式将合并而非被重置，确保最小改动。  
- 添加了新的测试用例 `multipleInteractionsCoexist`，用于验证多个交互状态可以共存的情况。
> feat(interaction): add support for merging styles in interaction

- __tests__/plots/static/words-wordCloud-basic.ts
- src/mark/wordCloud.ts
> fix: wordCloud default tooltip config

- .gitignore
- package.json
- tsconfig.json
主要是删除 tsconfig 中的 sourceRoot，这样生成的 map 文件的 sources 数组会是["../src/xxx.ts"]，从而能被 vite 正确加载
> fix: sourcemap issue #6807

- package.json
整个过程是在 Github CodeSpace 进行的，使用的是 [linux-universal](https://github.com/microsoft/vscode-dev-containers/blob/main/containers/codespaces-linux/README.md) 环境。
以下步骤会出错：
``` bash
pnpm install
pnpm build 
```
报错如下
```bash
➜ /workspaces/antp/G2 (v5) $ pnpm build 
> @antv/g2@5.3.2 build /workspaces/antp/G2
> run-p build:*
> @antv/g2@5.3.2 build:esm /workspaces/antp/G2
> rimraf ./esm && tsc --module ESNext --outDir esm
> @antv/g2@5.3.2 build:cjs /workspaces/antp/G2
> rimraf ./lib && tsc --module commonjs --outDir lib
> @antv/g2@5.3.2 build:umd /workspaces/antp/G2
> rimraf ./dist && node node_modules/rollup/dist/bin/rollup -c && npm run size
bundle/g2.std.ts → dist/g2.min.js...
[!] (plugin rpt2) Error: src/utils/helper.ts:112:23 - error TS2354: This syntax requires an imported helper but module …
```
> fix(build): resolve tslib not found error in UMD build

- __tests__/unit/data/venn/fmin/fmin.spec.ts
- package.json
- src/data/utils/venn/fmin/bisect.ts
- src/data/utils/venn/fmin/blas1.ts
- src/data/utils/venn/fmin/conjugateGradient.ts
- src/data/utils/venn/fmin/gradientDescent.ts
- src/data/utils/venn/fmin/index.ts
- src/data/utils/venn/fmin/linesearch.ts
- src/data/utils/venn/fmin/nelderMead.ts
- src/data/utils/venn/layout.ts
https://github.com/antvis/G2/pull/6515#issuecomment-2881905509
> fix: integrate fmin internally

- site/docs/charts/multi-set-bar.en.md
- site/docs/charts/multi-set-bar.zh.md
> docs: 新增「分组柱状图」文档

- .github/workflows/build.yml
- __tests__/integration/snapshots/bugfix/issue6654/step0.svg
- __tests__/integration/snapshots/bugfix/issue6654/step1.svg
- __tests__/integration/snapshots/static/weatherLineMultiAxesSync.svg
- __tests__/integration/snapshots/tooltip/flare-treemap-poptip-custom/step0.html
- __tests__/integration/snapshots/tooltip/flare-treemap-poptip/step1.html
- __tests__/integration/snapshots/tooltip/flare-treemap-poptip/step3.html
- __tests__/integration/utils/toMatchDOMSnapshot.ts
- __tests__/plots/tooltip/flare-treemap-poptip-custom.ts
- __tests__/plots/tooltip/flare-treemap-poptip.ts
- src/runtime/mark.ts
- src/runtime/transform.ts
- fixed https://github.com/antvis/G2/issues/5250
- fixed https://github.com/antvis/G2/issues/6657
- fixed https://github.com/antvis/G2/issues/6753
之前所有的 mark 都会共享 series，而类似柱形图这种 mark 会根据 series 来计算 bandWidth，当多轴时，折线的 series 就会挤占柱形图的横向空间，导致看起来是错位的。
本次更改：
series 共享机制变为：同类型 mark 共享 series，不同类型 mark 之间 series 隔离。比如多个 interval mark，它们之间就会共享 series，计算自己的布局空间。而 line 和 interval 的 series 就是独立的，不影响各自的布局空间。
> feat: make mark series scale independent

- package.json
- src/interaction/action/util.ts
> fix: 修复interaction内存在子视图时图元的获取
