src/util/context.ts, src/util/text.ts
fix early create canvas context cause build error in server side
see https://github.com/antvis/G2Plot/pull/2066#issuecomment-737712679
=> fix: fix early create canvas context cause build error in server side

tests/bugs/3085-spec.ts
修复 https://github.com/antvis/G2/issues/3085 中反馈的 DEMO 问题
=> docs: update time bar demo

CHANGELOG.md, package.json, src/core.ts
=> chore: 4.1.2

src/chart/chart.ts
=> fix: width和height传null或不传时，不要覆盖原有数据

tests/bugs/3111-spec.ts
related to: https://github.com/antvis/g/pull/679
close: #3113
=> feat(testcases): 增加单测，g 层修复 animate shape 在 changesize 的时候报错

CHANGELOG.md, package.json, src/core.ts
=> feat: change log

src/geometry/element/index.ts
=> fix: 修复element shape进行syncShapeStyle时，可能存在空对象的情况

src/core.ts, src/index.ts
ref: https://github.com/antvis/G2Plot/pull/2131
=> fix(export): add some export method

docs/common/marker-cfg.md, docs/manual/faq.zh.md, docs/manual/tutorial/legend.zh.md, docs/manual/upgrade.zh.md, package.json, src/util/legend.ts, tests/bugs/2474-spec.ts
=> legend marker

src/geometry/label/interval.ts
=> fix: 修复路径错误

CHANGELOG.md, docs/api/general/event.zh.md, docs/manual/concepts/component/overview.en.md, docs/manual/concepts/component/overview.zh.md, package.json, src/core.ts
=> chore 4.1.5

site/pages/index.zh.tsx
=> docs: remove notifications

src/geometry/base.ts, tests/bugs/g2plot-2165-spec.ts
fixed https://github.com/antvis/G2Plot/issues/2165
=> fix(geometry): geometry.update should update scale when data is changed

docs/api/general/scale.zh.md, site/pages/index.zh.tsx
=> docs: add mask documents

examples/bar/basic/demo/meta.json, examples/bar/basic/demo/radial-bar-with-background.ts, examples/case/column/demo/column5.ts, src/geometry/element/index.ts, src/geometry/interval.ts, src/geometry/shape/constant.ts, src/geometry/shape/interval/hollow-rect.ts, src/geometry/shape/interval/index.ts, src/geometry/shape/interval/util.ts, src/geometry/shape/util/get-style.ts, src/interface.ts, tests/bugs/tooltip-tip-max-width-spec.ts, tests/unit/geometry/interval-spec.ts, tests/unit/geometry/shape/interval-util-spec.ts, tests/unit/geometry/shape/util/get-style-spec.ts, tests/unit/geometry/state-spec.ts
`element/shape/interval/rect` 支持配置 background，支持 直角坐标系和极坐标系；配置方式：
```
chart.interval({  background: {} });
// 直角坐标系下的background 支持配置 radius
chart.interval({  background: { style: { radius: 4} });
chart.interval({  background: { style: { radius: [4, 4, 4, 4] } }});
```
|图表|预览|
|:---- |---|
|  进度环图  |![image](https://user-images.githubusercontent.com/15646325/103629632-8c660500-4f7b-11eb-9364-566a5a93e30d.png)|
|玉珏图|![image](https://user-images.githubusercontent.com/15646325/103629581-77897180-4f7b-11eb-83f2-7ffd50f56e4d.png)|
=> feat: interval shape 支持 background

CHANGELOG.md, package.json, src/core.ts
=> chore: v4.1.5

CHANGELOG.md, package.json, src/core.ts, src/geometry/area.ts, src/geometry/line.ts, tests/unit/geometry/area-spec.ts, tests/unit/geometry/line-spec.ts
关联PR：
https://github.com/antvis/scale/pull/69
https://github.com/antvis/component/pull/219
=> fix: performance improvement by disable default sort for line/area

tests/bugs/tooltip-tip-max-width-spec.ts
=> test: 修复 tooltip ci 报错问题

README.md, README.zh-CN.md, docs/manual/contact.en.md, docs/manual/contact.zh.md
=> docs: 添加钉钉联系方式

CHANGELOG.md, package.json, src/core.ts
=> chore: 4.1.7 & add changelog

docs/api/general/tooltip.zh.md, src/interface.ts, src/util/tooltip.ts, tests/unit/util/tooltip-spec.ts
=> feat(tooltip): tooltip.title support callback function

docs/api/general/interaction.en.md
=> docs: 交互的英文文档

docs/common/scrollbar-options.md
=> docs(scrollbar): 修改文档错误

src/core.ts
=> feat: 暴露获取扇形 path 的方法

docs/api/general/tooltip.zh.md, src/chart/controller/tooltip.ts, src/interface.ts, tests/bugs/g2plot-2223-spec.ts
fixed https://github.com/antvis/G2Plot/issues/2223
=> feat(tooltip): add tooltip.customItems config

CHANGELOG.md, package.json, src/core.ts
=> feat: add 4.1.8 changelog

src/geometry/label/util/index.ts
=> fix: label layout hide overlap

package.json, src/core.ts, src/geometry/label/util/index.ts
=> chore: 更新版本号

docs/api/general/adjust.en.md, docs/api/general/adjust.zh.md, docs/api/general/animate.zh.md, docs/api/general/coordinate.en.md, docs/api/general/coordinate.zh.md, docs/api/general/data.zh.md, docs/api/general/element.en.md, docs/api/general/element.zh.md, docs/api/general/geometry.en.md, docs/api/general/geometry.zh.md, docs/api/general/scale.en.md, docs/api/general/scale.zh.md
=> docs: 补充 geometry 和 element 的 api 文档

src/interaction/action/register.ts
=> typings: 增加 getAction 的返回参数类型定义

src/component/labels.ts
=> docs(labels.ts): 修改注释错别字

CHANGELOG.md, package.json, src/core.ts
=> chore: 4.1.10

src/interface.ts
修复 TooltipItem data 类型，修复 data 类型为 Datum 对象
=> fix(rose): 修复 TooltipItem data 类型

docs/api/general/geometry.zh.md, docs/common/api.zh.md, docs/manual/concepts/interaction.zh.md, package.json
=> docs: 日常文档走查, 层级处理

src/geometry/interval.ts, src/util/scale.ts, tests/bugs/2930-spec.ts, tests/unit/util/scale-spec.ts
=> fix(pie): 饼图数据 NaN 导致页面崩溃数据边界处理(#2930)

src/interaction/grammar-interaction.ts, tests/unit/interaction/passing-arg-spec.ts
=> feat: register interaction with action execute args

src/interaction/grammar-interaction.ts, tests/unit/interaction/grammar-interaction-spec.ts
=> test: 补充 action 单测

src/chart/controller/scrollbar.ts, src/interface.ts, src/theme/util/create-by-style-sheet.ts, tests/unit/chart/controller/scrollbar-spec.ts
- 滚动条增加主题样式设置，允许设置滑道、滑块颜色（依赖 https://github.com/antvis/component/pull/220 发布）
- 两种使用方式
```ts
// by theme
theme: {
components: {
scrollbar: {
default: {
style: {
trackColor: 'red',
thumbColor: 'green',
},
},
hover: {
style: {
thumbColor: 'yellow',
},
},
},
},
},
// by scrollbar option
chart.option('scrollbar', {
type: 'horizontal',
style: {
trackColor: 'lightblue',
thumbColor: 'lightgreen',
},
});
```
=> feat(scrollbar): 滚动条增加主题样式设置，允许设置滑道、滑块颜色

CHANGELOG.md, package.json, src/core.ts
=> chore: 4.1.11

src/chart/view.ts
=> feat(life-circle): view 生命周期事件触发，携带事件内容

src/animate/index.ts, src/interface.ts, tests/unit/animate/index-spec.ts
=> feat(animation): 动画添加重复执行参数

examples/interaction/component/demo/legend-focus.ts, examples/interaction/component/demo/meta.json, src/index.ts, src/interaction/action/component/list-checked.ts, tests/unit/component/legend-checked-spec.ts, tests/unit/interaction/action/list-check-spec.ts
=> feat: legend 增加 checked 单选交互

docs/common/scrollbar-options.md, src/chart/controller/scrollbar.ts, src/interface.ts, tests/unit/chart/controller/scrollbar-spec.ts
=> feat(scrollbar): 滚动条增加一个滚道激活样式配置

CHANGELOG.md, package.json, src/chart/view.ts, src/core.ts, src/interaction/action/component/tooltip/geometry.ts
=> feat(typings): 增强类型声明

src/chart/controller/axis.ts, src/interface.ts, tests/unit/chart/chart-spec.ts, tests/unit/chart/controller/axis-top-spec.ts, tests/unit/chart/controller/tooltip-spec.ts
在一些场景中，需要 axis 在图形上。比如玉珏图中，成环一圈之后，图形会把 axis 挡住， 这个时候就需要把 axis 放到 fore group 中。
=> feat(axis): axisCfg.top option

package.json, src/chart/controller/tooltip.ts, src/geometry/base.ts, src/geometry/label/base.ts, src/geometry/path.ts, src/geometry/util/group-data.ts, tests/bugs/2141-spec.ts, tests/performance/component/tooltip/pick-spec.ts, tests/performance/render/index-spec.ts, tests/performance/render/line-spec.ts, tests/performance/render/scatter-spec.ts, tests/unit/chart/chart-spec.ts, tests/unit/geometry/base-spec.ts, tests/unit/geometry/line-spec.ts
主要是一些小语法的优化，性能优化不多，主要的优化在 scale.translate https://github.com/antvis/scale/pull/72
=> perf: performance optimized

docs/api/advanced/require.en.md, docs/api/advanced/require.zh.md
=> docs: update old code in api/advanced/require

src/animate/animation/sector-path-update.ts
=> fix: getArcStartPoint function support path C (#3213)

src/chart/view.ts, src/interface.ts, tests/unit/util/legend-spec.ts
=> feat: 单 view 支持默认图例选中

CHANGELOG.md, package.json, src/core.ts
=> Chore new version

src/core.ts
=> chore: 修复 import type 导致网站无法启动，更新为 export type

.github/workflows/release.yml, package.json
=> chore: 添加 release create to trigger publish site

src/theme/style-sheet/dark.ts, src/theme/util/create-by-style-sheet.ts
=> fix: 修复主题相关的错误拼写

CHANGELOG.md, package.json, src/core.ts
=> chore: change log

webpack.config.js
=> fix: 修复 babel 配置

examples/interaction/others/demo/pie-legend.ts
demo 中交互的时候交互动画异常，原因就在于chart 多次 rander 导致交互响应不及时，这里把 Annotation 更新放在单独的 view 中，独立 render ,不再 render 外部图形
=> 修改饼图图例联动示例交互异常问题

docs/api/general/element.en.md, docs/api/general/element.zh.md, docs/manual/concepts/grammar-of-graphics.zh.md, package.json, src/interface.ts, src/theme/style-sheet/dark.ts, src/theme/style-sheet/light.ts, src/theme/util/create-by-style-sheet.ts
1. 增加了 滚动条的主题 token
2. 修复缩略轴的 label 在 dark 下的字体颜色
3. 文档 close: #3394
=> feat: scrollbar theme

package.json, src/core.ts
=> chore: 4.1.16

src/visual/adjust/adjust.ts, src/visual/adjust/index.ts, src/visual/adjust/stack.ts
=> feat(adjust): add module

__tests__/unit/visual/scale/index-spec.ts, src/types/scale.ts, src/visual/scale/index.ts
=> feat: update scale-def domain type

.eslintrc.js, __tests__/unit/chart/view/view-setter-api-spec.ts, __tests__/unit/visual/attribute/color-spec.ts, __tests__/unit/visual/attribute/index-spec.ts, __tests__/unit/visual/attribute/position-spec.ts, __tests__/unit/visual/attribute/shape-spec.ts, __tests__/unit/visual/attribute/size-spec.ts, __tests__/unit/visual/scale/index-spec.ts, package.json, src/chart/view.ts, src/facet/index.ts, src/facet/rect.ts, src/types/view.ts, src/util/facet.ts, src/util/interaction.ts, tsconfig.json
=> test: add test case for view api

__tests__/unit/visual/attribute/base-spec.ts, __tests__/unit/visual/attribute/index-spec.ts, src/types/common.ts, src/util/facet.ts, src/visual/attribute/attribute.ts
=> refactor: refactor base attribute class

__tests__/unit/chart/view/view-setter-api-spec.ts, __tests__/unit/visual/adjust/index-spec.ts, __tests__/unit/visual/attribute/base-spec.ts, __tests__/unit/visual/attribute/index-spec.ts, __tests__/unit/visual/attribute/position-spec.ts, __tests__/unit/visual/scale/cat-spec.ts, __tests__/unit/visual/scale/index-spec.ts, __tests__/unit/visual/scale/linear-spec.ts, __tests__/unit/visual/scale/log-spec.ts, __tests__/unit/visual/scale/pow-spec.ts, __tests__/unit/visual/scale/quantile-spec.ts, __tests__/unit/visual/scale/quantize-spec.ts, __tests__/unit/visual/scale/time-cat-spec.ts, __tests__/unit/visual/scale/time-spec.ts, package.json, src/types/scale.ts, src/util/facet.ts, src/visual/attribute/attribute.ts, src/visual/scale/index.ts, tsconfig.json
=> chore: add test case from scale v0.3

examples/other/other/demo/violin.ts, src/geometry/shape/violin/index.ts, src/index.ts, tests/unit/geometry/shape/violin-hollow-spec.ts, tests/unit/geometry/shape/violin-smooth-spec.ts, tests/unit/geometry/shape/violin-spec.ts
https://github.com/antvis/G2/pull/3416#issue-640707269
=> feat(violin): 完善小提琴图

__tests__/unit/visual/attribute/color-spec.ts, src/types/scale.ts, src/util/scale.ts, src/visual/attribute/attribute.ts, src/visual/attribute/color.ts, src/visual/scale/index.ts
=> refactor(attr): refactor color attribute

.github/workflows/auto-inspection.yml, CHANGELOG.md, package.json, src/core.ts
=> ci: changelog&inspect

__tests__/unit/visual/scale/index-spec.ts, __tests__/unit/visual/scale/pool-spec.ts, package.json, src/types/scale.ts, src/types/view.ts, src/util/scale.ts, src/visual/scale/index.ts, src/visual/scale/pool.ts
=> feat: add scale pool

.eslintrc.js, __tests__/unit/visual/attribute/color-spec.ts, __tests__/unit/visual/attribute/index-spec.ts, __tests__/unit/visual/attribute/position-spec.ts, __tests__/unit/visual/attribute/size-spec.ts, src/visual/attribute/attribute.ts, src/visual/attribute/size.ts, src/visual/scale/pool.ts
=> refactor: refactor size attribute

.github/workflows/auto-inspection.yml, src/util/annotation.ts, tests/bugs/annotation-spec.ts
=> fix: 修复 view 上没有正确的 scale 时，绘制 annotation 出错

examples/other/other/demo/word-cloud.ts
=> fix: remove speical data

.github/workflows/ci.yml, CHANGELOG.md, package.json, src/core.ts
=> chore: 4.1.18

.husky/pre-commit, __tests__/unit/visual/attribute/shape-spec.ts, src/visual/attribute/attribute.ts, src/visual/attribute/shape.ts
=> refactor: refactor shape attribute

.eslintrc.js, package.json, src/geometry/element.ts, src/geometry/factory.ts, src/types/common.ts, src/types/coordinate.ts, src/types/factory.ts, src/types/g.ts, src/types/geometry.ts, src/util/coordinate.ts, src/util/path.ts, src/visual/coordinate/index.ts
=> feat: add shape factory & shape

src/interface.ts
=> fix:fix trendCfg type definition of SliderCfg

src/interface.ts, tests/bugs/1744-spec.ts
close: https://github.com/antvis/G2Plot/issues/2648
=> fix(types): 修复类型定义，设置为可选项

src/interaction/action/element/link-by-color.ts, tests/unit/interaction/action/link-by-color-spec.ts, tests/unit/interaction/element-link-spec.ts
需求链接：https://github.com/antvis/G2Plot/issues/2602
使用方式：[diff](https://github.com/antvis/G2/pull/3483/files#diff-c384aa8f6408e0c08893c3bd7adf4b39875a4076c317167f51f2672e91f32f93)
=> feat(interaction/link-by-color): element-link 交互反馈增加参数配置

src/chart/event.ts, src/chart/view.ts, src/index.ts, src/interaction/action/data/range-filter.ts, src/interface.ts, tests/unit/interaction/action/range-filter-spec.ts
=> feat(events): 暴露 brush 交互的生命周期，便于在 G2Plot 层可以监听

src/chart/controller/tooltip.ts, src/interaction/action/active-region.ts, src/util/tooltip.ts, tests/unit/interaction/active-region-spec.ts
=> fix: active-region 若干问题

CHANGELOG.md, package.json, src/core.ts
=> chore: 4.1.19

docs/api/general/axis.zh.md
=> docs: 修改 AxisOption.title 文档

docs/manual/faq.en.md, docs/manual/faq.zh.md
=> docs: faq 文档更新

__tests__/unit/theme/index-spec.ts, package.json, src/chart/view.ts, src/index.ts, src/theme/dark.ts, src/theme/index.ts, src/theme/light.ts, src/theme/stylesheet.ts, src/types/theme.ts
=> feat(theme): basic api for theme

CHANGELOG.md, package.json, src/core.ts
=> chore: v4.1.20 & changelog

__tests__/unit/geometry/interval/interval-spec.ts, __tests__/unit/geometry/interval/shape/funnel-spec.ts, __tests__/unit/geometry/interval/shape/hollow-rect-spec.ts, __tests__/unit/geometry/interval/shape/line-spec.ts, __tests__/unit/geometry/interval/shape/pyramid-spec.ts, __tests__/unit/geometry/interval/shape/rect-spec.ts, __tests__/unit/geometry/interval/shape/tick-spec.ts, src/geometry/element.ts, src/geometry/geometry.ts, src/geometry/interval/index.ts, src/geometry/interval/shapes/funnel.ts, src/geometry/interval/shapes/hollow-rect.ts, src/geometry/interval/shapes/index.ts, src/geometry/interval/shapes/line.ts, src/geometry/interval/shapes/pyramid.ts, src/geometry/interval/shapes/rect.ts, src/geometry/interval/shapes/tick.ts, src/types/element.ts, src/types/factory.ts
=> feat(interval): add interval shapes

__tests__/unit/chart/view/view-init-spec.ts, __tests__/unit/chart/view/view-setter-api-spec.ts, __tests__/unit/util/bbox-spec.ts, src/chart/view.ts, src/types/g.ts, src/types/view.ts, src/util/bbox.ts, src/util/element.ts
=> feat(view): add region for layout

.eslintrc.js, __tests__/unit/chart/view/view-init-spec.ts, __tests__/unit/chart/view/view-render-spec.ts, __tests__/unit/chart/view/view-setter-api-spec.ts, __tests__/unit/geometry/interval/shape/pyramid-spec.ts, src/chart/view.ts, src/constant.ts, src/geometry/geometry.ts, src/geometry/index.ts, src/geometry/interval/index.ts, src/types/geometry.ts
=> feat(view): init ui in view.render

package.json
=> chore: 更新官网版本

src/geometry/base.ts, src/geometry/heatmap.ts, tests/unit/geometry/heatmap-spec.ts
=> fix: 修复 热力图 heatmap  style 唯一可用属性 shadowBlur 配置失败的问题

docs/api/general/legend.zh.md, src/chart/controller/legend.ts, src/interface.ts, tests/unit/component/legend-category-spec.ts
- docs(legend): 图例增加 itemName, itemValue style 回调的文档
- feat(legend): 图例支持以比例的方式，来设置图例容器的大小
close: https://github.com/antvis/G2/issues/2633
close: https://github.com/antvis/G2/issues/3128
=> feat(legend): 图例若干更新

src/geometry/base.ts, src/geometry/heatmap.ts, src/util/helper.ts, tests/unit/geometry/heatmap-spec.ts
=> fix(heatmap): 修复热力图 style shadowBlur 不生效 & color 使用回调会导致白屏

CHANGELOG.md, package.json, src/core.ts
=> chore: 4.1.21

docs/api/general/legend.zh.md
=> feat(legend): 图例支持多行分页

CHANGELOG.md, examples/other/other/demo/meta.json, package.json, src/core.ts
=> chore: v4.1.22 & changelog

docs/manual/concepts/component/tooltip.en.md, docs/manual/concepts/component/tooltip.zh.md
移除`G2/docs/manual/concepts/component/tooltip(zh|en).md` 中无效的代码，color 被定义后未被使用
=> docs(tooltip): remove useless code

docs/api/general/axis.zh.md
Some optional configuration is available, but the document is not fully described.
完善文档中关于 AxisTitleCfg 配置的可选参数
=> docs(AxisTitleCfg): added optional configuration

CHANGELOG.md, package.json, src/core.ts
=> chore: v4.1.23 & changelog

__tests__/unit/chart/view/view-init-spec.ts, __tests__/unit/chart/view/view-render-spec.ts, __tests__/unit/chart/view/view-setter-api-spec.ts, __tests__/unit/geometry/interval/interval-spec.ts, __tests__/unit/geometry/interval/shape/funnel-spec.ts, __tests__/unit/geometry/interval/shape/hollow-rect-spec.ts, __tests__/unit/geometry/interval/shape/line-spec.ts, __tests__/unit/geometry/interval/shape/pyramid-spec.ts, __tests__/unit/geometry/interval/shape/rect-spec.ts, __tests__/unit/geometry/interval/shape/tick-spec.ts, __tests__/unit/geometry/line/line-spec.ts, __tests__/unit/geometry/line/shape/line-spec.ts, __tests__/unit/geometry/line/shape/step-spec.ts, __tests__/unit/geometry/path/path-spec.ts, __tests__/unit/geometry/path/shape/line-spec.ts, src/chart/view.ts, src/geometry/element.ts, src/geometry/line/shapes/step.ts
=> fix(types): fix type change in g-canvas@1.0.0-alpha.3

src/chart/layout/index.ts, src/chart/view.ts, src/geometry/geometry.ts, src/types/layout.ts
=> feat(view): layout with constraint

docs/api/advanced/register-interaction.en.md, docs/api/advanced/register-interaction.zh.md, docs/api/general/interaction.zh.md
Some link path for interaction are wrong.  But I suspect there are more broken links.
=> docs: fix 404 links for interaction

site/pages/index.less
=> docs(style): fix style issues in docs

src/core.ts
=> feat: 导出 utils，供 G2Plot 使用

docs/manual/getting-started.en.md, docs/manual/getting-started.zh.md
=> docs(get-start): add docs when use with script

CHANGELOG.md, src/core.ts
=> chore: update chore.ts and changelog for v4.1.25

src/chart/controller/annotation.ts
=> fix(annotation): 修复annotation添加id失败

README.en-US.md, README.md
=> docs: set default lang = zh

src/interface.ts, src/util/legend.ts, tests/unit/chart/controller/legend-spec.ts
修复  [BUG] 自定义图例项，marker 无法使用回调
https://github.com/antvis/G2Plot/issues/2814
=> fix: legend 自定义items 添加marker回调

examples/facet/facet/demo/mirror-transpose.ts, examples/facet/facet/demo/mirror.ts
=> docs(facet): 修改了镜像分面的案例，使得轴标签居中显示

.eslintrc.js, package.json, src/interface.ts, src/theme/style-sheet/dark.ts, src/theme/style-sheet/light.ts, tests/unit/component/legend-category-spec.ts, tests/unit/geometry/label/layout/pie-outer-spec.ts, tests/unit/geometry/shape/interval-spec.ts, tests/unit/interaction/active-region-spec.ts, tests/unit/theme/create-theme-spec.ts, tests/unit/util/legend-spec.ts
修复了因为升级 eslint 而导致的 tests 文件的问题
=> fix(tests): eslint error

src/chart/view.ts, src/geometry/base.ts, src/util/helper.ts, tests/unit/util/helper-spec.ts
=> fix(uniq): when uniq element is not string

CHANGELOG.md, package.json, src/core.ts
=> chore: v4.1.26 & changelog

src/chart/view.ts, tests/bugs/labels-container-spec.ts, tests/unit/chart/chart-spec.ts, tests/unit/chart/controller/tooltip-spec.ts
=> fix(label): 处理clear+render之后labelsContainer重复生成的问题

CHANGELOG.md, src/core.ts
=> chore: update version to 4.1.27

.eslintrc.js, .github/workflows/auto-inspection.yml, .husky/pre-commit, src/geometry/base.ts, src/geometry/heatmap.ts, src/geometry/path.ts, src/geometry/util/diff.ts, tests/bugs/2141-spec.ts, tests/bugs/tooltip-dom-spec.ts, tests/unit/geometry/util/diff-spec.ts, tests/util/delay.ts
重构 createElements，并且 重命名为 updateElements，参考[这里](https://github.com/antvis/G2/pulls)
=> feat(geometry): refactor and rename createElements

CHANGELOG.md, package.json, src/core.ts
=> chore: update changelog

src/chart/controller/tooltip.ts, tests/bugs/tooltip-custom-content-spec.ts
问题复现：
https://codesandbox.io/s/recursing-mestorf-ni168?file=/src/index.js
=> fix(custom-content): 修复custom-content的undefined无法变回tooltip模版的问题

CHANGELOG.md, package.json, src/core.ts
=> chore: v4.1.30 & changelog

.github/workflows/release-notify.yml
=> chore: add release-notify

CHANGELOG.md, package.json, src/core.ts
https://github.com/semantic-release/semantic-release#release-steps
=> chore(release): v4.1.34 & changelog

examples/case/pie/demo/pie6.ts
=> 错别字：天平 -> 天秤

examples/column/basic/demo/custom-shape.ts
=> fix: demo 中自定义shape会有误导

docs/manual/concepts/component/label.en.md, docs/manual/concepts/component/label.zh.md
=> fix(docs): label link 404

CHANGELOG.md, package.json, src/core.ts
=> chore: v4.1.35 & changelog

src/geometry/base.ts, src/geometry/element/index.ts, tests/bugs/pie-update-spec.ts, tests/performance/geometry/point/index-spec.ts, tests/unit/animate/index-spec.ts, tests/unit/geometry/base-spec.ts, tests/unit/geometry/state-spec.ts
=> perf: 优化性能，由于set-zindex每次都会调用 sort，导致耗时为指数级别的

CHANGELOG.md, package.json, src/core.ts
=> chore: v4.1.36 & changelog

CHANGELOG.md, package.json, src/core.ts, tests/bugs/2295-spec.ts, tests/bugs/pie-update-spec.ts, tests/unit/animate/index-spec.ts, tests/unit/geometry/base-spec.ts
=> chore: v4.1.37 & changelog

CHANGELOG.md, package.json, src/core.ts, tests/unit/geometry/base-spec.ts
=> chore: v4.1.38 & changelog

.github/workflows/release.yml
=> fix: remove node 12 to fix release action failed

.github/workflows/release-notify.yml
=> chore: 增加dingtalk-release-nofity

examples/component/legend/demo/legend-focus.ts, src/interaction/action/component/list-focus.ts, src/interface.ts
=> fix(legend): 修复图例 radio focus 模式 & 增加 demo

CHANGELOG.md, package.json, src/core.ts
=> chore(version): update to 4.1.39

docs/manual/tutorial/scale.zh.md
=> chore:  添加对scale的值域说明，与d3 值域用法相对比，防止误解。

tests/unit/component/legend-category-radio-spec.ts
=> fix(legend): 修复 legend radio 设置样式不生效

package.json
=> chore: resolutions 更新 修复 remark-mdx 引入问题

CHANGELOG.md, package.json, src/core.ts
=> chore: v4.1.40 & changelog

src/geometry/base.ts, tests/bugs/3737-spec.ts
close: #3737 修复jitter点图adjust后点位置不正确的问题
=> fix: 修复 jitter 点图 adjust 后点位置不正确的问题

CHANGELOG.md, package.json, src/core.ts
=> chore: 4.1.41

src/chart/controller/tooltip.ts, tests/bugs/3079-spec.ts
https://github.com/antvis/G2Plot/issues/3079
=> fix(toolitp): 修复 limitInPlot属性无法屏蔽一些后出现的状态

tests/bugs/g2plot-2968-spec.ts
BEFORE
AFTER
两数全为负数
两数全为正数
数据有正有负
=> fix(slider): 修复slider过大挤压图形的问题 #2968

CHANGELOG.md, package.json, src/core.ts
=> chore: v4.1.42 & changelog

.github/release.yml, .github/workflows/conventional-labels.yml, CHANGELOG.md, package.json, src/chart/controller/annotation.ts, src/core.ts
fix: https://github.com/ant-design/ant-design-charts/issues/1137
=> fix(charts): 修复 annotations 创建失败

.github/workflows/ci.yml, .github/workflows/npm-publish.yml, .github/workflows/release.yml
=> chore: github actions 整理

.github/workflows/npm-publish.yml, package.json
=> chore: 修改 npm publish 脚本命令

.github/workflows/npm-publish.yml, package.json
=> Revert "chore: 修改 npm publish 脚本命令"

CHANGELOG.md, package.json, src/core.ts, src/util/scale.ts, tests/bugs/interval-tooltip-spec.ts
=> fix(interval): tooltip name when interval config `color` without mapping `field`

.github/workflows/ci.yml
update actions/checkout from @v1 to @v2 to avoid vulnerability. #3749
=> fix: update actions/checkout version to avoid vulnerability

CHANGELOG.md, package.json, src/core.ts, src/util/scale.ts, tests/bugs/timeCat-spec.ts
=> fix: 修复 timeCat scale 没有当作 groupScale，导致对应场景的折线图绘制无法正常分组

.github/workflows/build.yml, .husky/commit-msg, .husky/pre-commit, __tests__/index.spec.ts, __tests__/unit/drawRedRect.spec.ts, jest.config.js, package.json, src/drawRedRect.ts, src/index.ts
- Update workflows: Cached node_modules
- Update test env: Use Jest Electron
- Update husky to v7
=> chore: init dev env

src/animate/interface.ts, src/geometry/label/interface.ts, src/interface.ts
=> feat: 基于新版本注释规范调整 interface 文件代码注释

CHANGELOG.md, package.json, src/core.ts
=> chore: update to version 4.1.47

docs/api/general/animate.zh.md, docs/manual/tutorial/data-flow.en.md, docs/manual/tutorial/data-flow.zh.md, docs/manual/tutorial/legend.en.md, docs/manual/tutorial/legend.zh.md, docs/manual/tutorial/renderers.en.md, docs/manual/tutorial/renderers.zh.md, docs/manual/tutorial/tooltip.en.md, docs/manual/tutorial/tooltip.zh.md
=> docs: 更新文档，将chart.source 改为 chart.data

src/interface.ts, src/theme/style-sheet/dark.ts, src/theme/style-sheet/light.ts, tests/unit/theme/create-theme-spec.ts
=> feat(theme): 主题支持完整样式表的自定义

CHANGELOG.md, package.json, src/core.ts
=> chore: v4.1.48 & changelog

src/geometry/label/layout/pie/spider.ts
=> fix: 修复判空问题

CHANGELOG.md, package.json, src/core.ts
=> chore: v4.1.49 & changelog

__tests__/unit/transform/pick.spec.ts, src/spec/transform.ts, src/transform/index.ts, src/transform/pick.ts
=> feat(transform): add pick

__tests__/unit/transform/pick.spec.ts, __tests__/unit/transform/rename.spec.ts, __tests__/unit/transform/subset.spec.ts, src/spec/transform.ts, src/transform/index.ts, src/transform/pick.ts, src/transform/rename.ts, src/transform/subset.ts
=> feat: rename subset pick

__tests__/unit/utils/selection.spec.ts, src/utils/selection.ts
Make every shape of @antv/g have state and can handle event for interaciton.
**Shape with state.**
```js
// Render blue rect.
selection
.selectAll('rect')
.style('fill', 'blue')
// Change fill color of each rect from blue to red.
selection
.selectAll('rect')
.state('fill', 'red')
// Reset fill color of each rect to blue.
selection
.selectAll('rect')
.reset('fill')
```
**Handle event.**
```js
// Every event can only be registered once.
// When mouse move will log 'mousemove' instead of 'hello world'.
// Selection will provide method can override handler in the future.
selection
.select('rect')
.on('mousemove', () => console.log('mousemove'))
.on('mousemove', () => console.log('hello world'))
```
=> feat(selection): add on, state and reset for selection

docs/api/general/scale.zh.md, src/interface.ts
=> feat(scale): 优化 scale 文档，增加 showLast 配置说明

docs/api/general/axis.zh.md, package.json, src/chart/chart.ts, src/index.ts, src/interaction/action/component/axis/axis-description.ts, src/interface.ts, src/theme/style-sheet/dark.ts, src/theme/style-sheet/light.ts, src/theme/util/create-by-style-sheet.ts
为 icon 添加鼠标 hover 事件，当 mousemove 到 icon 上出现详情信息 tooltip，当 mouseleave 时 tooltip 消失。
=> feat(axis): 添加坐标轴标题详细说明 icon 交互事件

CHANGELOG.md, package.json, src/core.ts
=> chore: v4.1.50 & changelog

__tests__/unit/transform/utils.spec.ts, src/runtime/types/component.ts, src/transform/fetch.ts, src/transform/filterBy.ts, src/transform/rename.ts, src/transform/sankey.ts, src/transform/sortBy.ts, src/transform/subset.ts, src/transform/utils/memo.ts, src/transform/wordCloud.ts
fix(transform): cache transform component rather than transform function
```js
// Before
function Scale(n) {
return useMemo(a => a * n);
}
const s1 = Scale(2);
s1(1); //2;
// This will not recompute because it uses 
// the memoized scale transform.
s1(1); // 2;
const s2 = Scale(2);
// This will recompute because it creates 
// a new scale transform.
s1(1); //2;
```
```js
// After
function Transform(n) {
return a => a * n;
}
const Scale = useMemo(Transform);
const s1 = Scale(2);
s1(1); //2;
const s2 = Scale(2);
// This will not recompute because it uses the scale 
// transform from the memoized transform component.
s1(1); //2;
```
=> fix(transform): cache transform component rather than transform function

.genjirc, __tests__/unit/composition/flex.spec.ts, __tests__/unit/composition/layer.spec.ts, __tests__/unit/runtime/spatial.spec.ts, __tests__/unit/runtime/view.spec.ts, __tests__/unit/stdlib/index.spec.ts, docs/spatial.md, src/component/legendCategory.ts, src/composition/flex.ts, src/composition/index.ts, src/composition/layer.ts, src/runtime/layout.ts, src/runtime/plot.ts, src/runtime/render.ts, src/runtime/types/component.ts, src/runtime/types/options.ts, src/spec/composition.ts, src/spec/index.ts, src/stdlib/index.ts
feat(composition): add layer and space. **(Test coverage: 95%)**
[Online Demo](https://pearmini.github.io/hello-g2v5/#/spatial)
**Layer**
```js
G2.render({
type: 'layer',
data: [
],
children: [
{
transform: [{ type: 'sortBy', fields: ['sold'], order: 'DESC' }],
encode: {
x: 'genre',
y: 'sold',
color: 'genre',
},
},
{
paddingBottom: 200,
paddingLeft: 400,
statistic: [{ type: 'stackY' }],
coordinate: [{ type: 'transpose' }, { type: 'polar' }],
encode: {
y: 'sold',
color: 'genre',
},
},
],
});
```
**Row(Flex)**
```js
G2.render({
type: 'flex',
width: 800,
data: [
{ …
```
=> feat(composition): add layer and space

.genjirc, __tests__/unit/geometry/grid.spec.ts, __tests__/unit/runtime/grid.spec.ts, __tests__/unit/scale/index.spec.ts, __tests__/unit/shape/interval/rect.spec.ts, __tests__/unit/stdlib/index.spec.ts, docs/grid.md, docs/scale.md, src/geometry/grid.ts, src/geometry/index.ts, src/geometry/point.ts, src/infer/maybeTooltip.ts, src/runtime/render.ts, src/runtime/scale.ts, src/scale/index.ts, src/scale/quantile.ts, src/scale/quantize.ts, src/scale/threshold.ts, src/shape/interval/colorRect.ts, src/spec/geometry.ts, src/spec/scale.ts, src/stdlib/index.ts
feat(runtime): add grid geometry and related scales(threshold, quantize, quantile). ([Preview](https://pearmini.github.io/hello-g2v5/#/grid))
**Features**
- Scale: Threshold, Quantize, Quantile
- Geometry: Grid
**Bug Fixes**
- Runtime: undefined callback for render(options, context, callback) function.
- Shape: Negative width and height for rect shape.
**Docs**
- Geometry: Grid
- Scale: Threshold, Quantize, Quantile
**Basic Grid** 
```js
G2.render({
type: 'grid',
transform: [
{
type: 'fetch',
url: 'https://gw.alipayobjects.com/os/bmw-prod/bd287f2c-3e2b-4d0a-8428-6a85211dce33.json',
},
{
type: 'sortBy',
fields: ['y'],
},
],
height: 640,
encode: {
x: 'x',
y: 'y',
color: (d) => `${d.index}`,
},
style: {
stroke: 'black',
lineWidth: 1,
},
});
```
**Threshold**
```js
G2.render({
type: 'grid', …
```
=> feat(runtime): add grid geometry and related scales(threshold, quantize, quantile)

.gitignore, jest.config.js, package.json
=> chore: set coverage = false by default

__tests__/data/sales.ts, __tests__/unit/geometry/area.spec.ts, __tests__/unit/runtime/area.spec.ts, __tests__/unit/runtime/interval.spec.ts, __tests__/unit/statistic/stackY.spec.ts, __tests__/unit/stdlib/index.spec.ts, src/geometry/area.ts, src/geometry/index.ts, src/infer/maybeStackY.ts, src/shape/area/area.ts, src/shape/area/curveArea.ts, src/shape/area/smoothArea.ts, src/shape/index.ts, src/spec/geometry.ts, src/spec/statistic.ts, src/statistic/stackY.ts, src/stdlib/index.ts
=> feat: add area geometry and related area, smoothArea shape

__tests__/unit/geometry/edge.spec.ts, __tests__/unit/runtime/edge.spec.ts, __tests__/unit/stdlib/index.spec.ts, src/geometry/area.ts, src/geometry/edge.ts, src/geometry/index.ts, src/shape/edge/arc.ts, src/shape/edge/edge.ts, src/shape/index.ts, src/spec/geometry.ts, src/stdlib/index.ts
=> feat: add edge geometry and shapes

__tests__/unit/geometry/image.spec.ts, __tests__/unit/runtime/image.spec.ts, __tests__/unit/stdlib/index.spec.ts, src/mark/geometry/image.ts, src/mark/geometry/index.ts, src/shape/image/image.ts, src/shape/index.ts, src/spec/geometry.ts, src/stdlib/index.ts
=> feat: add image geometry and shape

__tests__/unit/mark/annotation/lineX.spec.ts, __tests__/unit/mark/annotation/lineY.spec.ts, __tests__/unit/runtime/annotationLine.spec.ts, __tests__/unit/shape/annotation/line.spec.ts, __tests__/unit/stdlib/index.spec.ts, src/component/axis.ts, src/mark/annotation/index.ts, src/mark/annotation/lineX.ts, src/mark/annotation/lineY.ts, src/shape/annotation/line.ts, src/shape/index.ts, src/spec/geometry.ts, src/stdlib/index.ts
**feat(annotation):** support lineX and lineY annotation. **Coverage: 100%**
- **Annotation:** lineX, lineY
- **Shape:** annotation.line
```ts
const chart = render({
type: 'view',
data: [
{ year: '1991', value: 15468 },
{ year: '1992', value: 16100 },
{ year: '1993', value: 15900 },
{ year: '1994', value: 17409 },
{ year: '1995', value: 17000 },
{ year: '1996', value: 31056 },
{ year: '1997', value: 31982 },
{ year: '1998', value: 32040 },
{ year: '1999', value: 33233 },
],
children: [
{
type: 'line',
encode: {
x: 'year',
y: 'value',
},
},
{
type: 'annotation.lineX',
encode: {
y: 30000,
},
style: {
stroke: 'green',
},
},
{
type: 'annotation.lineY',
transform: [
{
type: 'filterBy',
fields: ['year'],
callback: (d) => d === '1995' || d === '1998',
},
],
encode: {
x: 'year',
},
style: { …
```
=> feat(annotation): support lineX, lineY annotation

src/interaction/action/component/axis/axis-description.ts
更新 description 点击后 tooltip 样式，在 axis-title config 中添加自定义 descriptionTooltipStyle 配置
=> feat(axis): 更新 axis-description-tooltip 样式, 添加自定义 style 配置

CHANGELOG.md, package.json, src/core.ts
=> chore: v4.2.2 & changelog

__tests__/unit/runtime/area.spec.ts, src/mark/geometry/area.ts, src/shape/area/area.ts, src/shape/area/curveArea.ts, src/shape/area/smoothArea.ts
=> fix: close path in area shapes

.genjirc, __tests__/unit/mark/geometry/interval.spec.ts, __tests__/unit/runtime/statistic.spec.ts, __tests__/unit/stdlib/index.spec.ts, docs/normalize.md, docs/overview.md, src/mark/geometry/interval.ts, src/runtime/scale.ts, src/spec/statistic.ts, src/stdlib/index.ts, src/transform/index.ts, src/transform/statistic/normalizeY.ts, src/transform/statistic/stackY.ts
Add normalize transform. ([link](https://g2-next.antv.vision/normalize))
Normalize group marks into series by specified channels, and then transform each series's value, say to transform them relative to some basis to apply a moving average. The default basis is `max` and the marks are grouped by `x` channel by default. The built-in basis is as followed:
- min
- max
- first
- last
- mean
- extent
- median
- sum
- deviation
**Normalized Stacked Interval**
```js
G2.render({
data: [
{ city: 'London', month: 'Jan.', rainfall: 18.9 },
{ city: 'London', month: 'Feb.', rainfall: 28.8 },
{ city: 'London', month: 'Mar.', rainfall: 39.3 },
{ city: 'London', month: 'Apr.', rainfall: 81.4 },
{ city: 'London', month: 'May', rainfall: 47 },
{ city: 'London', month: 'Jun.', rainfall: …
```
=> feat: add normalize transform

.genjirc, __tests__/unit/runtime/interval.spec.ts, __tests__/unit/runtime/statistic.spec.ts, docs/normalize.md, docs/overview.md, docs/stack.md, package.json, src/spec/statistic.ts, src/transform/connector/fetch.ts, src/transform/inference/maybeStackY.ts, src/transform/statistic/normalizeY.ts, src/transform/statistic/stackY.ts, src/transform/statistic/utils.ts, src/transform/utils/helper.ts
Update stack transform, support _orderBy_ option to sort stacks. ([preview](https://g2-next.antv.vision/stack))
The **stack** transform group marks into series by color or series channel, and then produce new y channel for each series by specified order, say to form vertical "stacks" by specified channels. The built-in order is as followed:
- _sum_ - order stacks by ascending total value of corresponding series
- _value_ - order stacks by ascending values of y channel
- _series_ - order stacks by nature alphabetical order of series or color channel
- _maxIndex_ - order stacks by the index of their max value of corresponding series
- _a function_ - order stacks by the specified function of data
- _an array_ - order stacks by the specified array of fields
- _null_ - respect input order
The …
=> feat: update stack transform, support orderBy option to sort stacks

.genjirc, __tests__/unit/runtime/statistic.spec.ts, __tests__/unit/stdlib/index.spec.ts, docs/overview.md, docs/symmetry.md, package.json, src/spec/statistic.ts, src/stdlib/index.ts, src/transform/index.ts, src/transform/statistic/normalizeY.ts, src/transform/statistic/symmetryY.ts
feat: add symmetry ([preview](http://g2-next.antv.vision/symmetry))
The SymmetryY transform apply offset for y channels, say to transform
them to be symmetry.
**Symmetry Stacked Area**
```js
G2.render({
type: 'area',
transform: [
{
type: 'fetch',
url: 'https://gw.alipayobjects.com/os/bmw-prod/e58c9758-0a09-4527-aa90-fbf175b45925.json',
},
{ type: 'stackY' },
{ type: 'symmetryY' },
],
scale: {
x: { field: 'Date', utc: true },
y: { guide: { label: { formatter: (d) => `${+d.text / 1000}k` } } },
},
encode: {
shape: 'smoothArea',
x: (d) => new Date(d.date),
y: 'unemployed',
color: 'industry',
},
});
```
**Symmetry Interval**
```js
G2.render({
transform: [
{ type: 'sortBy', fields: ['sold'], order: 'DESC' },
{ type: 'symmetryY' },
],
data: [
{ …
```
=> feat: add symmetry

.genjirc, __tests__/unit/runtime/statistic.spec.ts, __tests__/unit/stdlib/index.spec.ts, docs/overview.md, docs/select.md, src/spec/statistic.ts, src/stdlib/index.ts, src/transform/index.ts, src/transform/statistic/select.ts, src/transform/statistic/selectX.ts, src/transform/statistic/selectY.ts
feat(transform): add select
The select transform groups marks with specified channels, and filter index by specified selector for each series, say to pull a single or multiple values out of each series. The default channel for grouping is _series_, and the built-in selector is as followed:
- _min_
- _max_
- _last_
- _first_
- a _function_
**Select**
```js
G2.render({
type: 'view',
transform: [
{
type: 'fetch',
url: 'https://gw.alipayobjects.com/os/antvdemo/assets/data/bubble.json',
},
],
children: [
{
type: 'point',
scale: {
size: { type: 'log', range: [4, 20] },
y: { field: 'Life' },
},
encode: {
x: 'GDP',
y: 'LifeExpectancy',
size: 'Population',
color: 'continent',
},
style: {
fillOpacity: 0.3,
lineWidth: 1,
},
},
{
type: 'text',
transform: [{ type: 'select', size: 'max' }],
encode: { …
```
=> feat(transform): add select

docs/manual/concepts/interaction.zh.md
=> typo: fix annotaion to annotation

__tests__/unit/runtime/facet.spec.ts, __tests__/unit/runtime/interaction.spec.ts, __tests__/unit/runtime/interval.spec.ts, __tests__/unit/runtime/view.spec.ts, __tests__/unit/stdlib/index.spec.ts, __tests__/unit/theme/light.spec.ts, src/component/index.ts, src/component/legendCategory.ts, src/component/title.ts, src/composition/mark.ts, src/runtime/component.ts, src/runtime/types/common.ts, src/runtime/types/options.ts, src/spec/composition.ts, src/spec/title.ts, src/stdlib/index.ts, src/theme/light.ts
**Feat:** support title component
```ts
type Title = string | null | G2TitleOptions;
// ① simple
{
title: 'xxx',
}
// ②
{
title: {
text: 'xxx',
style: {},
subtitle: 'xxx',
subtitleStlye: {}
}
}
```
- Options specified by users will be transformed to standard `G2TitleOptions`
```ts
type G2Title = {
text?: string;
subtitle?: string | null;
style?: Record<string, any>;
subtitleStyle?: Record<string, any>;
};
type G2TitleOptions = G2Title & {
position?: GuideComponentPosition;
size?: number;
zIndex?: number;
};
```
① simple usage
```ts
render<G2Spec>(
{
title: 'Chart Title',
data,
encode: {
x: 'genre',
y: 'sold',
},
},
{},
done,
);
```
② config title, subtitle and subtitleStlye
```ts
render<G2Spec>(
{
title: {
size: 40,
text: 'Chart Title',
subtitle: 'Chart …
```
=> feat(title): support title component

__tests__/data/sankey.ts, __tests__/unit/mark/geometry/polygon.spec.ts, __tests__/unit/runtime/polygon.spec.ts, __tests__/unit/stdlib/index.spec.ts, __tests__/unit/transform/connector.ts, __tests__/unit/transform/subset.spec.ts, src/mark/geometry/polygon.ts, src/runtime/mark.ts, src/shape/index.ts, src/shape/polygon/ribbon.ts, src/spec/transform.ts, src/stdlib/index.ts, src/transform/index.ts, src/transform/preprocessor/connector.ts, src/transform/preprocessor/subset.ts
=> feat: add `ribbon` shape for polygon

src/runtime/component.ts
=> fix(title): title support config a string

src/geometry/shape/interval/util.ts, tests/bugs/interval-background-radius-spec.ts
修复同时存在坐标系转制和 y 镜像的时候 的bakcground rradius 的错误
|  Before  |  After  |
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/65594180/172582013-86928944-2506-4557-9368-7208ed22b2eb.png) | ![image](https://user-images.githubusercontent.com/65594180/172582104-cf4aa865-e47d-43f1-a0ca-fb1242b9cf55.png) |
=> fix(interval): 修复同时存在坐标系转制和 y 镜像的时候 的bakcground radius 的错误

CHANGELOG.md, package.json, src/animate/animation/sector-path-update.ts, src/animate/animation/wave-in.ts, src/core.ts, tests/unit/animate/sector-path-update-spec.ts
=> fix(sector-path): 修复扇形非常小的时候, 角度 diff 会被重置为 Math.PI * 2

.genjirc, __tests__/unit/runtime/facet.spec.ts, docs/rect.md, src/composition/matrix.ts, src/composition/rect.ts, src/runtime/layout.ts, src/runtime/mark.ts, src/runtime/plot.ts, src/runtime/scale.ts
Split function `initializeView` into `initializeMarks` and `initializeState` to sync position scales among facets. ([preview](http://g2-next.antv.vision/rect#calendar-interval))
**Sync position scales** 
```js
(() => {
// Mock Data.
const days = ['Sun.', 'Mon.', 'Tues.', 'Wed.', 'Thur.', 'Fri.', 'Sat.'];
const mockData = () => {
const names = ['A', 'B', 'C'];
const week = (date) => {
const currentDate = date.getDate();
const newDate = new Date(date);
const firstDay = new Date(newDate.setDate(1)).getDay();
return Math.ceil((currentDate + firstDay) / 7);
};
const day = (date) => date.getDay();
return Array.from({ length: 30 }, (_, i) => {
const date = new Date(2022, 5, i + 1);
return names.map((name) => ({
activity: name,
value: Math.random(),
week: `${week(date)}`,
day: days[day(date)], …
```
=> refactor(rect): support sync scales among facets

.genjirc, __tests__/unit/runtime/facet.spec.ts, __tests__/unit/stdlib/index.spec.ts, docs/more-composition.md, src/component/axis.ts, src/composition/circle.ts, src/composition/index.ts, src/composition/matrix.ts, src/composition/rect.ts, src/composition/utils.ts, src/runtime/component.ts, src/shape/interval/colorRect.ts, src/spec/composition.ts, src/stdlib/index.ts, src/utils/vector.ts
feat(composition): add circle ([preview](http://g2-next.antv.vision/more-composition/))
```js
(() => {
const M = [
'Jan.',
'Feb.',
'Mar.',
'Apr.',
'May',
'Jun.',
'Jul.',
'Aug.',
'Sept.',
'Oct.',
'Nov.',
'Dec.',
];
const N = ['A', 'B', 'C', 'D'];
const mockData = M.flatMap((month) =>
N.map((name) => ({
month,
name,
value: Math.random(),
})),
);
return G2.render({
type: 'circle',
encode: {
position: 'month',
},
width: 480,
height: 480,
data: mockData,
children: [
{
encode: {
x: 'name',
y: 'value',
color: 'name',
},
},
],
});
})();
```
=> feat(composition): add circle

src/transform/utils/arc/arc.ts, src/transform/utils/arc/index.ts
=> fix: build error

__tests__/unit/interaction/elementHightlight.spec.ts, __tests__/unit/interaction/stdlib.spec.ts, __tests__/unit/stdlib/index.spec.ts, src/interaction/action/index.ts, src/interaction/action/service/elementSelection.ts, src/interaction/action/transformer/highlight.ts, src/interaction/builtin/elementHighlight.ts, src/interaction/builtin/elementHighlightByColor.ts, src/interaction/builtin/elementHighlightByX.ts, src/interaction/index.ts, src/interaction/stdlib.ts, src/spec/action.ts, src/spec/interaction.ts, src/stdlib/index.ts
- **feat(service action):** `elementSelection` (support filterBy: `x` or `color`)
- **feat(transformer action):** `highlight`
- **feat(interaction):** `elementHighlight`, `elementHighlightByX`, `elementHighlightByColor`
```ts
render<G2Spec>(
{
type: 'view',
data: [
{ genre: 'Sports', sold: 275, type: 'A' },
{ genre: 'Sports', sold: 115, type: 'B' },
{ genre: 'Strategy', sold: 115, type: 'A' },
{ genre: 'Strategy', sold: 95, type: 'B' },
{ genre: 'Action', sold: 120, type: 'A' },
{ genre: 'Action', sold: 190, type: 'B' },
{ genre: 'Shooter', sold: 350, type: 'A' },
{ genre: 'Shooter', sold: 250, type: 'B' },
],
title: 'ElementHighlight',
scale: {
x: { flex: [1, 2, 3, 4] },
},
children: [
{
encode: {
x: 'genre',
y: 'sold',
color: 'type',
},
scale: {
color: { guide: { …
```
=> feat(interaction): support element-highlight interactions

src/animate/animation/wave-in.ts, tests/bugs/3694-spec.ts
|  Before  |  After  |
| --- | --- |
| 更改前 waveIn 动画不会更新形状  | 更改后 更新形状  |
|  ![image](https://user-images.githubusercontent.com/65594180/175286220-647202a6-7f68-4abf-ade0-f109377b42b9.png) | ![image](https://user-images.githubusercontent.com/65594180/175286117-7d435e9a-efb6-4f67-a487-bc2331e92d99.png)|
fixed #3694
=> fix(animate waveIn): 修复 waveIn 动画 最后没有给 element 附上更新后样式的问题

__tests__/unit/animation/fadeOut.spec.ts, __tests__/unit/animation/helper.ts, __tests__/unit/animation/scaleInX.spec.ts, __tests__/unit/animation/scaleInY.spec.ts, __tests__/unit/animation/scaleOutX.spec.ts, __tests__/unit/animation/scaleOutY.spec.ts, __tests__/unit/runtime/animation.spec.ts, __tests__/unit/stdlib/index.spec.ts, jest.config.js, src/animation/fadeIn.ts, src/animation/fadeOut.ts, src/animation/index.ts, src/animation/scaleInX.ts, src/animation/scaleInY.ts, src/animation/scaleOutX.ts, src/animation/scaleOutY.ts, src/runtime/types/component.ts, src/spec/animate.ts, src/spec/geometry.ts, src/stdlib/index.ts
=> feat: add animation include fade, scale

src/chart/controller/slider.ts, tests/bugs/g2plot-1899-spec.ts, tests/bugs/slider-spec.ts, tests/unit/chart/controller/slider-spec.ts
修改 slider 的最大值最小值 位置 计算数据方式 floor 为 round
| --- | --- |
| ![image](https://user-images.githubusercontent.com/65594180/176402440-4c587c20-e139-4d30-ab6d-840025ce413d.png) | ![image](https://user-images.githubusercontent.com/65594180/176403709-23ab3608-7e99-48f8-8d79-37cb9ce060b6.png) |
fixed #3853
=> fix(slider): 修改 slider 的最大值最小值 位置 计算数据方式 floor 为 round

src/chart/controller/tooltip.ts, src/interface.ts, src/util/coordinate.ts, tests/bugs/crosshairs-spec.ts
=> fix(crosshairs): crosshairs 删除在坐标轴外不能显示的配置

__tests__/unit/runtime/keyframe.spec.ts, docs/keyframe.md, src/animation/morphing.ts, src/composition/keyframe.ts, src/composition/rect.ts, src/runtime/plot.ts, src/runtime/types/options.ts, src/spec/animate.ts, src/spec/composition.ts, src/spec/geometry.ts, src/utils/helper.ts, src/utils/selection.ts
feat(keyframe): support transition among facet and unit visualization(sand dance 2d).
- **Selection**
- _selectAllUpdate()_: Select update elements besides elements in this selection.
- _parent()_: Return _this._parent_
- **Runtime**: Update selection transform elements from _from shape_ to _to shape_ with different _parentNode_.
- **Morphing**: Fix flashing problem by reset the transform of current shape before animation start.
[**Among Facet**](http://g2-next.antv.vision/keyframe/#among-facets)
```js
(async () => {
const response = await fetch(
'https://gw.alipayobjects.com/os/bmw-prod/7fbb7084-cf34-4e7c-91b3-09e4748dc5e9.json',
);
const data = await response.json();
return G2.render({
type: 'keyframe',
direction: 'alternate',
iterationCount: 2,
children: [
{
type: 'rect',
paddingRight: …
```
=> feat(keyframe): support transition among facet and unit visualization

.eslintrc.js, CHANGELOG.md, package.json, src/chart/controller/annotation.ts, src/core.ts, tests/unit/theme/create-theme-spec.ts
=> chore: v4.2.5 & changelog

src/chart/controller/tooltip.ts, tests/unit/chart/controller/tooltip-spec.ts
-[x] 增加 tooltip marker 回调，以和 point 的不同形状保持一致 
fixed #4038
=> fix(tooltipMarker): 增加 tooltip marker 回调，以和 point 的不同形状保持一致

README.en-US.md, README.md, docs/manual/contact.en.md, docs/manual/contact.zh.md
=> feat(md): 更新钉钉群号

.genjirc, __tests__/unit/interaction/index.spec.ts, docs/connector.md, docs/image.md, docs/node-edge.md, docs/overview.md, docs/polygon.md, docs/schema.md, package.json, src/interaction/action/service/elementSelection.ts, src/interaction/action/service/surfacePointSelection.ts, src/interaction/action/transformer/activeRegion.ts, src/interaction/action/transformer/tooltip.ts, src/interaction/builtin/tooltip.ts, src/interaction/utils.ts, src/spec/action.ts, src/spec/transform.ts, src/transform/preprocessor/fetch.ts
- **transform:** `fetch` transform supports `csv` format
- **interactions:** `ElementSelection` support find **elements** by `axis`, `item` or any other info from shared variables, `SurfacePointSelection` focus on surface details (such as mouseX, mouseY, or the elements hit directly).
- **🐛 fix(tooltip)**: tooltip error when interval scale has `flex` options
> When scaleX is a linear scale, tooltip trigger by axis and activeRegion is also supported.
=> refactor(interaction): several changes of interactions

src/component/labels.ts, src/geometry/label/interface.ts
=> fix(label): label 可以配置 是否支持捕获

.genjirc, docs/animation.md, docs/area.md, docs/connector.md, docs/coordinate.md, docs/grid.md, docs/jitter.md, docs/keyframe.md, docs/line.md, docs/link.md, docs/matrix.md, docs/pack.md, docs/polygon.md, docs/scale.md, docs/schema.md, docs/stack-enter.md, docs/stack.md, docs/symmetry.md, docs/text.md, docs/vector.md
Add and update docs for marks, scales and coordinates.
=> docs: add and update demos

CHANGELOG.md, package.json, src/core.ts
=> chore: v4.2.6 & changelog

.genjirc, docs/coordinate.md, docs/line.md, docs/overview.md, docs/point.md, docs/scale.md, docs/spatial.md, docs/text.md
Preview: http://g2-next.antv.vision/overview/
=> docs: add preview for added examples

docs/interaction-brush.md, docs/interaction-component.md, docs/interaction-element.md, docs/interaction-more.md, docs/interaction-tooltip.md, docs/overview.md
Remove interaction suffix for interactions docs.
=> docs: remove interaction suffix for interactions docs

__tests__/unit/runtime/interval.spec.ts
Call done to tell jest that this test case is done to avoid timeout.
=> fix(test): call done in test

docs/overview.md
Preserve some nice or required demos.
=> docs(overview): remove and adjust demos

examples/interaction/component/demo/axis-label-highlight.ts, examples/interaction/component/demo/element-list-highlight.ts, examples/interaction/component/demo/legend-active.ts, examples/interaction/component/demo/legend-highlight.ts
=> docs(example): delete excess data

package.json
Update `version` of package.json to *5.0.0-alpha.0*
=> chore: ready to release 5.0.0-alpha.0

.genjirc, docs/introduction.md, docs/overview.md, package.json
A brief introduction of G2:
- design purpose
- core concepts
- basic usage
=> docs: add introduction

.genjirc, README.en-US.md, README.md, docs/basic.md, docs/examples.md, docs/introduction.md, docs/tutorials.md
Update README and outline of docs
=> docs: update README and outline of docs

docs/manual/tutorial/tooltip.en.md, docs/manual/tutorial/tooltip.zh.md
=> fix(docs): tooltip文档缺少花阔号

package.json, src/core.ts
=> chore: v4.2.7

.genjirc, __tests__/unit/api/chart.spec.ts, __tests__/unit/api/library.spec.ts, __tests__/unit/runtime/animation.spec.ts, __tests__/unit/runtime/annotationConnector.spec.ts, __tests__/unit/runtime/annotationRange.spec.ts, __tests__/unit/runtime/facet.spec.ts, __tests__/unit/runtime/interval.spec.ts, __tests__/unit/runtime/label.spec.ts, __tests__/unit/runtime/line.spec.ts, docs/basic.md, docs/register.md, package.json, src/api/chart.ts, src/api/index.ts, src/api/library.ts, src/index.ts, src/runtime/render.ts
- Register: `G2.register([namespace].[componentName])` should register named component for specified namespace.
- Update Data: `chart.render({...})` should rerender chart with updated data.
- Return Context: `chart.context()` should return the rendering context.
**Register**
```js
import { Chart, register } from '@antv/g2';
register('data.double', (options) => {
const { field } = options;
return (data) =>
data.map((d) => ({
...d,
[field]: d[field] * 2,
}));
});
const chart = new Chart({});
chart.data({
value: [
],
transform: [{ type: 'double', field: 'sold' }],
});
chart
.interval()
.encode('x', 'genre')
.encode('y', 'sold') …
```
=> feat(api): support register, update data and return context

.github/workflows/mirror.yml
=> Chore update mirror action

docs/mark-area.md
案例同：https://github.com/antvis/G2/pull/4182
=> docs: add area mark documents

__tests__/unit/stdlib/index.spec.ts, docs/animation.md, docs/mark-connector.md, src/animation/index.ts, src/animation/zoomIn.ts, src/animation/zoomOut.ts, src/stdlib/index.ts
=> feat(animation): add zoomIn & zoomOut animation

.eslintrc, __tests__/unit/api/chart.spec.ts, __tests__/unit/api/node.spec.ts, src/api/chart.ts, src/api/node.ts, src/api/props.ts, src/api/types.ts, src/runtime/index.ts, src/runtime/plot.ts, src/runtime/render.ts, src/runtime/types/options.ts, src/spec/composition.ts, src/utils/event.ts, src/utils/size.ts
Ref Docs: https://www.yuque.com/antv/g2-docs/kkpgr9#nwGq6
=> feat: chart API

docs/manual/getting-started.zh.md
=> 更新 BizCharts 地址，Viser 已经没人维护了，去掉

__tests__/unit/stdlib/index.spec.ts, __tests__/unit/theme/light.spec.ts, src/runtime/types/theme.ts, src/stdlib/index.ts, src/theme/dark.ts, src/theme/index.ts
**规范:**  ${组件 namespace}: 组件Styles
```ts
axis: {},
legend:{},
title:{},
subtitle:{},
```
**进度:**
=> feat: add theme token and dark theme

src/runtime/render.ts
* 恢复下误修改的代码  https://github.com/antvis/G2/pull/4229
=> chore(runtime): remove useless export

site/.dumirc.ts, site/examples/single-view/area/demo/area-difference.ts, site/examples/single-view/area/demo/area.ts, site/examples/single-view/area/demo/cascade-area.ts, site/examples/single-view/area/demo/label.ts, site/examples/single-view/area/demo/meta.json, site/examples/single-view/area/demo/missing-data-area.ts, site/examples/single-view/area/demo/orderly-area.ts, site/examples/single-view/area/demo/percentage-area.ts, site/examples/single-view/area/demo/stacked-area.ts, site/examples/single-view/area/demo/step-area.ts, site/examples/single-view/area/demo/streamgraph.ts
-----
目录中的 csv 数据转成 json 放到远程了。给一个 csv 转 json 的脚本。
```js
const path = require('path');
const fs = require('fs');
const glob = require('glob');
const csv = require('csvtojson');
function doa() {
const files = glob.sync('./*').filter((item) => {
return item.endsWith('.csv');
});
files.map(f => {
const base = path.basename(f)
const name = base.slice(0, base.length - 4);
csv()
.fromFile(f)
.then((jsonObj) => {
fs.writeFileSync(`t/${name}.json`, JSON.stringify(jsonObj, (k, v) => {
// 数字类型的字符串转成数字
if (typeof v === 'string' && !isNaN(Number(v))) {
return Number(v);
}
return v;
}));
})
});
}
doa()
```
=> feat: add area demos

site/examples/single-view/text/demo/meta.json, site/examples/single-view/text/demo/paragraph.ts, site/examples/single-view/text/demo/poetry.ts, site/examples/single-view/text/demo/train.ts
=> feat: add text demo

site/.dumi/global.ts, site/examples/single-view/polygon/demo/meta.json, site/examples/single-view/polygon/demo/treemap.ts, site/examples/single-view/polygon/demo/voronoi.ts, site/package.json
=> docs: add polygon demo, treemap and voronoi

site/examples/single-view/box/index.en.md, site/examples/single-view/box/index.zh.md, site/examples/single-view/cell/demo/cell-aggregated.ts, site/examples/single-view/cell/demo/cell-basic.ts, site/examples/single-view/cell/demo/cell-heatmap.ts, site/examples/single-view/cell/demo/cell-quantile.ts, site/examples/single-view/cell/demo/cell-quantize.ts, site/examples/single-view/cell/demo/cell-threshold.ts, site/examples/single-view/cell/demo/meta.json, site/examples/single-view/cell/index.en.md, site/examples/single-view/cell/index.zh.md, site/examples/single-view/hierarchy/index.en.md, site/examples/single-view/hierarchy/index.zh.md, site/examples/single-view/image/index.en.md, site/examples/single-view/image/index.zh.md, site/examples/single-view/link/index.en.md, site/examples/single-view/link/index.zh.md, site/examples/single-view/map/index.en.md, site/examples/single-view/map/index.zh.md, site/examples/single-view/network/index.en.md, site/examples/single-view/network/index.zh.md, site/examples/single-view/radial/index.en.md, site/examples/single-view/radial/index.zh.md, site/examples/single-view/text/index.en.md, site/examples/single-view/text/index.zh.md, site/examples/single-view/vector/index.en.md, site/examples/single-view/vector/index.zh.md, src/runtime/scale.ts
=> docs(demo): add cell

site/examples/single-view/dual/demo/line-bar.ts, site/examples/single-view/dual/demo/meta.json, site/examples/single-view/dual/demo/multi-line.ts, site/examples/single-view/dual/index.zh.md
=> docs: add dual-axis chart demo

src/runtime/plot.ts
=> chore(plot): remove console.log

site/examples/scenario/annotation/demo/line-badge.ts, site/examples/scenario/annotation/demo/line-text.ts, site/examples/scenario/annotation/demo/meta.json, site/examples/single-view/area/demo/range-spline-area.ts, site/examples/single-view/radial/demo/bar-radial.ts, site/examples/single-view/radial/demo/donut.ts, site/examples/single-view/radial/demo/pie.ts
- 增加两个 annotation demo
- 优化 饼图、环图 demo
=> docs: demo of annotation

site/docs/api/plugin/lottie.en.md, site/docs/api/plugin/lottie.zh.md, site/docs/api/plugin/rough.en.md, site/docs/api/plugin/rough.zh.md
=> docs(plugin): sketchy rendering & lottie

site/.dumi/global.ts, site/.dumi/style.css
- 设置 demo 的宽高比固定为 8:6
- 设置 background-size 为 cover
- 支持预览图片的滚动
=> feat(site): cover and scrollable

site/docs/api/overview.zh.md, site/docs/api/scale/band.en.md, site/docs/api/scale/band.zh.md, site/docs/api/scale/point.en.md, site/docs/api/scale/point.zh.md, site/docs/api/scale/time.en.md, site/docs/api/scale/time.zh.md
=> docs: add band, point, time scale api

site/docs/api/coordinate/fisheye.en.md, site/docs/api/coordinate/fisheye.zh.md, site/docs/api/coordinate/parallel.en.md, site/docs/api/coordinate/parallel.zh.md, site/docs/api/coordinate/polar.zh.md, site/docs/api/coordinate/radial.en.md, site/docs/api/coordinate/radial.zh.md, site/docs/api/coordinate/theta.en.md, site/docs/api/coordinate/theta.zh.md, site/docs/api/coordinate/transpose.en.md, site/docs/api/coordinate/transpose.zh.md
Coordinate API :
- polar
- transpose
- radial
- theta
- parallel
- fisheye
=> docs: add coordinate api

site/docs/api/animation/fade-in.en.md, site/docs/api/animation/fade-in.zh.md, site/docs/api/animation/overview.en.md, site/docs/api/animation/overview.zh.md, site/docs/api/overview.zh.md
动画的过程本质是视觉属性在时间上的变化，带来视觉上的动画效果。G2 内置有多种常规的动画类型。一个动画分成几个组成部分：
- `duration` - 动画持续时间
- `delay` - 动画延迟执行的时间
- `easing` - 动画的缓动函数
- `fill` - 
```ts
chart
.interval()
/* ... */
.animation({
/* options */
});
```
| 属性 | 描述 | 类型 | 默认值|
| -------------| ----------------------------------------------------------- | -----------------| ----------|
| duration     | 动画持续时间 (ms)                                             | `number`         |           |
| delay        | 延迟执行时间 (ms)                                             | `number`         |           |
| easing       | 动画的缓动函数                                                | `Easing`           |          |
| fill         | 动画处于非运行状态时的展示效果                                   | `Fill`           |           |
支持以下内置缓动函数，来自 …
=> docs: add animation api

site/docs/api/component/axis.en.md, site/docs/api/component/axis.zh.md
Axis Component Composition:
* Title 标题
* Line 轴线
* Tick 刻度
* Label 刻度值
* Grid 网格线
A simple G2 Axis usage:
```ts
chart
.interval()
.data(...)
.axis('x', {
labelAlign: 'parallel',
labelDirection: 'positive',
labelSpacing: 10,
labelFilter: (datum, index, data) => index % 5 === 0,
labelTransforms: [{ type: 'hide' }],
lineLineWidth: 5,
lineStroke: '#675193',
showGrid: true,
});
```
=> docs(axis): add axis component docs

site/docs/api/graph/circle-packing.en.md, site/docs/api/graph/circle-packing.zh.md, site/docs/api/graph/forceGraph.en.md, site/docs/api/graph/forceGraph.zh.md, site/docs/api/graph/sankey.zh.md, site/docs/api/graph/tree.en.md, site/docs/api/graph/tree.zh.md, site/docs/api/graph/treemap.en.md, site/docs/api/graph/treemap.zh.md, site/docs/api/graph/wordCloud.en.md, site/docs/api/graph/wordCloud.zh.md, site/examples/graph/network/demo/meta.json
- sankey
- tree
- treemap
- circle-packing
- forceGraph
- wordCloud
=> docs: add graph api

site/docs/api/geo/geo-path.en.md, site/docs/api/geo/geo-path.zh.md, site/docs/api/geo/geoPath.en.md, site/docs/api/geo/geoPath.zh.md, site/docs/api/geo/geoView.en.md, site/docs/api/geo/geoView.zh.md, site/docs/api/overview.zh.md
=> docs: add geo api

site/examples/theme/theme/demo/dark.ts, src/animation/waveIn.ts
=> fix: 修复 wave-in 添加 inset 不生效问题

site/.dumirc.ts
=> fix website desc

site/docs/api/coordinate/theta.zh.md, site/docs/api/mark/polygon.zh.md, site/docs/api/transform/jitter.zh.md, site/examples/annotation/annotation/demo/quadrant-scatter.ts, site/examples/general/interval/demo/bar-diverging-stacked.ts, site/examples/general/interval/demo/meta.json, site/examples/general/point/demo/point-bubble.ts, site/examples/general/polygon/demo/treemap.ts, site/examples/general/polygon/demo/voronoi.ts, site/examples/general/radial/demo/bar-stacked-radial.ts, site/examples/general/radial/demo/point-jitter-radial.ts
=> docs: add a custom demo

site/examples/animation/group/demo/area.ts, site/examples/animation/group/demo/gantt.ts, site/examples/animation/group/demo/interval-polar.ts, site/examples/animation/group/demo/interval.ts, site/examples/animation/group/demo/line.ts, site/examples/animation/group/demo/meta.json, site/examples/animation/group/demo/point.ts
=> docs: add group animation demo

package.json
=> chore: update version to 5.0.0-alpha.4

__tests__/integration/charts/english-wordCloud.ts, __tests__/integration/charts/flare-point-circle-pack-custom.ts, __tests__/integration/charts/flare-tree-custom.ts, __tests__/integration/charts/flare-treemap-custom.ts, __tests__/integration/charts/miserable-force-custom.ts, site/examples/animation/general/demo/meta.json, site/examples/general/text/demo/wordCloud-mask.ts, site/examples/general/text/demo/wordCloud.ts, site/examples/graph/hierarchy/demo/circle-packing.ts, site/examples/graph/hierarchy/demo/meta.json, site/examples/graph/hierarchy/demo/tree.ts, site/examples/graph/hierarchy/demo/treemap.ts, site/examples/graph/network/demo/meta.json, site/examples/graph/network/demo/sankey.ts, src/mark/pack.ts, src/mark/sankey.ts, src/mark/treemap.ts, src/mark/wordCloud.ts, src/spec/geometry.ts
=> fix(mark): hide axis for composite mark

README.md, site/docs/manual/introduction.zh.md
=> docs: update preview

package.json
更新 package.json，准备发布 5.0.0-beta.1
=> chore: update version to 5.0.0-beta.1

site/.dumirc.ts
官网问题：https://www.yuque.com/antv/g2-docs/rze61537e0otk5t2
=> fix(site): 404 url and news

site/examples/geo/geo/demo/meta.json
=> docs: remove choropleth-world demo

site/.dumi/global.ts, site/examples/analysis/bin/demo/meta.json, site/examples/analysis/bin/demo/poisson.ts, site/package.json
=> docs: add demo poisson

.gitignore, __tests__/integration/canvas.ts
发现有不匹配的像素，生成一张 diff 图片（文件名为 testcase.diff.png），并高亮展示。
=> 集成测试中展示不匹配的像素

site/examples/annotation/annotation/demo/point-point.ts, site/examples/general/area/demo/area-difference.ts, site/examples/general/area/demo/area-gradient.ts, site/examples/general/area/demo/area.ts, site/examples/general/area/demo/label.ts, site/examples/general/area/demo/missing-data-area.ts, site/examples/general/area/demo/percentage-area.ts, site/examples/general/area/demo/range-spline-area.ts, site/examples/general/area/demo/stacked-area.ts, site/examples/general/area/demo/streamgraph.ts
=> refactor: optimize area examples

__tests__/integration/charts/unemployment-area-stacked-sample.ts
=> chore: increase maxError to fix ci

package.json
=> chore: update to 5.0.0-beta.2

package.json, site/package.json
=> chore: update version to 5.0.0-beta.3

site/examples/analysis/bin/demo/binx.ts, site/examples/analysis/regression/demo/exponential-regression.ts, site/examples/analysis/regression/demo/linear-regression.ts, site/examples/analysis/regression/demo/logarithmic-regression.ts
将 `site-data-pre.alipay.com` 全部替换为线上版的 `assets.antv.antgroup.com`
=> docs: replace site-data-pre.alipay.com

site/.dumi/global.ts, site/docs/api/mark/box.zh.md, site/docs/api/mark/boxplot.en.md, site/docs/api/mark/boxplot.zh.md, site/docs/api/mark/shape.en.md, site/docs/api/mark/shape.zh.md, site/docs/api/overview.zh.md, site/examples/annotation/annotation/demo/meta.json, site/examples/annotation/annotation/demo/watermark.ts, site/package.json
=> docs: add boxplot、shape document

site/.dumirc.ts, site/docs/api/animation/overview.zh.md, site/docs/api/chart.zh.md
----
动画的过程本质是视觉属性在时间上的变化，带来视觉上的动画效果。在 G2 中，提供了三种动画场景类型：
- `enter` - 元素第一次出现的出场动画；
- `update` - 数据更新的时候，元素更新的动画；
- `exit` - 数据更新的时候，元素被销毁退出画布的动画；
利用这 3 种动画场景，结合 G2 动画语法使用数据驱动动画的方式，可以配制出各种各样需要的动画效果。
```ts
chart
.interval()
/* ... */
.animate({
/* options */
});
```
关于 `animate` API 的参数，有以下，主要 3 种动画场景（enter、update、exit）和 动画 5 个属性（type、duration、delay、easing、fill）的组合。
| 属性 | 描述 | 类型 | 默认值|
| -------------| ----------------------------------------------------------- | -----------------| ----------|
| enterType         | 动画类型                                                     | `Type`         |           |
| enterDuration     | 动画持续时间 (ms)                                             | `number`         |           |
| enterDelay        | 延迟执行时间 (ms)                                             | …
=> docs: update animation API

site/.dumirc.ts
隐藏「主题」页面入口，需要解决以下两个问题：
- GUI 组件更新问题
- 更新时，性能问题
=> feat: hide theme-set entry

package.json, site/package.json
=> chore: 5.0.0-beta.5

__tests__/unit/api/chart.spec.ts, src/api/chart.ts, src/runtime/render.ts
=> fix: listen window-resize in chart instead of render. (fix #4492)

__tests__/integration/snapshots/tooltip-indicesLineItems/step0.html, __tests__/integration/tooltips/index.ts, __tests__/integration/tooltips/indices-line-items.ts, src/interaction/native/tooltip.ts
fix: https://github.com/antvis/G2/issues/4552
=> fix(tooltip): custom group-items

site/examples/composition/space/demo/space-flex.ts, site/examples/composition/space/demo/space-layer.ts
修复这个 PR：https://github.com/antvis/G2/pull/4488 带来的文档问题。
=> fix(docs): remove mark.coordinate

site/docs/api/transform/select.zh.md, site/docs/manual/single-view/annotation.zh.md, src/spec/transform.ts, src/transform/select.ts, src/transform/selectX.ts, src/transform/selectY.ts
=> refactor: select options

src/api/chart.ts, src/api/composition/base.ts, src/api/composition/facetCircle.ts, src/api/composition/facetRect.ts, src/api/composition/geoPath.ts, src/api/composition/geoView.ts, src/api/composition/index.ts, src/api/composition/repeatMatrix.ts, src/api/composition/spaceFlex.ts, src/api/composition/spaceLayer.ts, src/api/composition/timingKeyframe.ts, src/api/composition/view.ts, src/api/mark/mark.ts, src/api/node.ts
```js
Node -> Interval/Point/...
Node -> Space/Facet/Chart...
```
```js
Node -> MarkBase -> Interval/Point/...
Node -> ViewBase -> Space/Facet/Chart...
```
=> feat: modify chartchart&mark class dependencies

package.json
=> chore: update version to beta.9

src/utils/selection.ts
换一种写法，暂时修复这个 issue 里面的编译问题：https://github.com/antvis/G2/issues/4614
=> fix(site): update selection.remove

site/docs/api/interaction/tooltip.zh.md
=> docs: error links in tooltip docs

__tests__/unit/api/mark.spec.ts, src/api/composition/base.ts, src/api/composition/facetCircle.ts, src/api/composition/facetRect.ts, src/api/composition/geoPath.ts, src/api/composition/geoView.ts, src/api/composition/index.ts, src/api/composition/repeatMatrix.ts, src/api/composition/spaceFlex.ts, src/api/composition/spaceLayer.ts, src/api/composition/timingKeyframe.ts, src/api/composition/view.ts, src/api/index.ts, src/api/mark/base.ts, src/api/mark/index.ts, src/api/mark/mark.ts, src/index.ts
```ts
export { MarkNode } from '@antv/g2';
```
=> feat(MarkBase): change the name from MarkBase to MarkNode (fix #4672)

__tests__/integration/snapshots/tooltip/alphabet-interval-custom-dom/step0.html, __tests__/integration/snapshots/tooltip/alphabet-interval-custom-dom/step1.html, __tests__/integration/snapshots/tooltip/alphabet-interval-custom-string/step0.html, __tests__/integration/snapshots/tooltip/alphabet-interval-custom-string/step1.html, __tests__/integration/snapshots/tooltip/indices-line-custom/step0.html, __tests__/integration/snapshots/tooltip/indices-line-custom/step1.html, __tests__/plots/tooltip/alphabet-interval-custom-dom.ts, __tests__/plots/tooltip/alphabet-interval-custom-string.ts, __tests__/plots/tooltip/index.ts, __tests__/plots/tooltip/indices-line-custom.ts, src/interaction/native/tooltip.ts, src/spec/geometry.ts, src/spec/interaction.ts
之前是通过 `tooltip.customContent`  去自定义内容，现在是通过 `tooltip.render` 去自定义内容。支持两种形式：
- HTML String 
- DOM
下面通过几种方式实现了如下的效果：
```ts
export function renderString(event, { title, items }) {
const { offsetX, offsetY } = event;
return `<dv>
<h2>${title}</h2>
<span>(${offsetX | 0}, ${offsetY | 0})</span>
<ul style="padding-left: 1em">
${items
.map((d) => `<li style="color: ${d.color}">${d.name}: ${d.value}</li>`)
.join('')}
</ul>
</div>`;
}
export function alphabetIntervalCustomString(): G2Spec {
return {
data: {
type: 'fetch',
value: 'data/alphabet.csv',
},
encode: {
x: 'letter',
y: 'frequency',
color: 'steelblue',
},
tooltip: ['letter', 'frequency'],
interaction: {
tooltip: {
render: renderString,
},
},
};
}
```
```ts
import { G2Spec } from '../../../src';
import { renderString } from …
```
=> feat(tooltip): support render (close: #4495)

.github/workflows/build.yml, package.json, scripts/uploadSnapshot.js
=> ci: when ci failed, it will upload to oss server

__tests__/unit/api/mark.spec.ts, src/geo/geoView.ts, src/mark/boxplot.ts, src/mark/forceGraph.ts, src/mark/pack.ts, src/mark/sankey.ts, src/mark/tree.ts, src/mark/treemap.ts, src/runtime/transform.ts, src/spec/mark.ts, src/utils/mark.ts
- 修复了测试环境中的 mark channel types 的类型问题。
- 抽象了一个 maybeAnimation 方法。
=> refactor(composite): add maybeAnimation

site/examples/plugin/rough/demo/interval.ts, site/examples/plugin/rough/demo/line.ts, site/examples/plugin/rough/demo/point.ts
=> docs: update site demos of sketching

src/geometry/shape/interval/hollow-rect.ts, src/geometry/shape/interval/index.ts
* **G2 Version**: v4
fixes: https://github.com/antvis/G2Plot/issues/2586
* Before:
* After:
=> fix(interval): 避免 background 在交互时被捕捉导致错误(如 element-selected)

CONTRIBUTING.md
=> docs: update contribution.md

__tests__/plots/interaction/appl-line-slider-filter.ts, site/examples/interaction/interaction/demo/slider.ts, src/interaction/sliderFilter.ts, src/runtime/plot.ts
=> feat(interaction): add sliderFilter to defaults

site/.dumirc.ts
relation issue: https://github.com/antvis/G2/issues/4793
=> docs: adjust the architecture of examples in website

__tests__/plots/animation/aapl-area-keyframe.ts, __tests__/plots/static/aapl-area-missing-data-transpose.ts, __tests__/plots/static/aapl-area-missing-data.ts, __tests__/plots/static/aapl-line-missing-connect.ts, __tests__/plots/static/aapl-line-missing-styled.ts, __tests__/plots/static/morley-box-extend.ts, __tests__/plots/static/penguins-boxplot-grouped-extent.ts, __tests__/plots/tooltip/morley-box-default-extend.ts, __tests__/unit/stdlib/index.spec.ts, site/docs/spec/coordinate/fisheye.zh.md, site/docs/spec/mark/area.zh.md, site/docs/spec/mark/line.zh.md, site/docs/spec/mark/point.zh.md, site/examples/general/area/demo/missing-data-area.ts, site/examples/general/box/demo/boxplot.ts, site/examples/general/line/demo/line-connect-nulls.ts, src/coordinate/fisheye.ts, src/interaction/fisheye.ts, src/mark/boxplot.ts, src/runtime/render.ts, src/shape/area/curve.ts, src/shape/line/curve.ts, src/spec/coordinateTransform.ts, src/stdlib/index.ts, src/theme/classic.ts, src/theme/classicDark.ts, src/theme/index.ts
修改了一些 API：
- fisheye.isVisual -> fisheye.visual
- area.style.connectNulls -> area.style.connect
- line.style.connectNulls -> line.style.connect
- boxplot.style.extend -> boxplot.style.point
- theme.light -> theme.classic
- theme.dark -> theme.classicDark
=> refactor(api): rename some api

__tests__/plots/interaction/movies-interval-highlight-multiple-state.ts, __tests__/plots/interaction/score-by-item-area-radar.ts, __tests__/plots/static/acme-crop-income-interval-connector.ts, __tests__/plots/static/alphabet-interval-title.ts, __tests__/plots/static/blockchain-line-annotation.ts, __tests__/plots/static/blockchain-line-badge-annotation.ts, __tests__/plots/static/cars3-line-parallel-vertical.ts, __tests__/plots/static/gdp-interval-flex.ts, __tests__/plots/static/indices-line-point-scale-key.ts, __tests__/plots/static/question8-interval-radial-gradient-color.ts, __tests__/plots/static/seasonal-weather-area-radial.ts, __tests__/plots/static/stateages-interval-stacked.ts, __tests__/plots/static/train-line-multi-axes.ts, __tests__/plots/static/weather-line-area-dual-axis.ts, __tests__/plots/static/weather-line-multi-axes.ts, __tests__/plots/static/weather-line-multi-scrollbar.ts, __tests__/plots/static/weather-line-multi-slider.ts, __tests__/plots/static/weather-line-view-label-transform.ts, __tests__/plots/static/world-history-interval-multi-tick-count.ts, __tests__/plots/tooltip/weather-line-interval.ts, src/component/axis.ts, src/component/legendCategory.ts, src/component/legendContinuous.ts, src/component/title.ts, src/interaction/brushFilter.ts, src/interaction/sliderFilter.ts, src/runtime/types/common.ts, src/spec/component.ts
调整 组件 API：
大部分配置收到 style 内，除了组件开关(如 `line`)、 formatter、filter
例：
```js
axis: {
y: {
title: 'Temperature (°C)',
grid: false,
style: {
titleFill: '#EE6666',
},
},
},
```
=> refactor: refactor component api

README.en-US.md, README.md
=> feat: update README.en-US.md

README.en-US.md, README.md
=> docs: update the book name of gg

__tests__/integration/snapshots/tooltip/aapl-line-area-basic-sample/step0.html, __tests__/plots/tooltip/aapl-line-area-basic-sample.ts, __tests__/plots/tooltip/index.ts, src/transform/maybeTitle.ts
修复 https://github.com/antvis/G2/issues/4809 提到的第一个问题
=> fix(tooltip): sample

__tests__/integration/snapshots/tooltip/aapl-area-missing-data-transpose/step0.html, __tests__/plots/tooltip/aapl-area-missing-data-transpose.ts, __tests__/plots/tooltip/index.ts, src/interaction/tooltip.ts
修复 https://github.com/antvis/G2/issues/4809 提到的第二个问题。
=> fix(tooltip): support NaN data in transpose

CHANGELOG.md, package.json, site/package.json
=> chore(version): update to 5.0.1 and add changelog

src/api/chart.ts
=> fix: chart render type (#4853)

site/docs/spec/data/sortBy.zh.md
=> fix: 文档中的sort->sortBy

site/docs/spec/component/axis.zh.md
=> docs: correct typo docs

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.0.3

site/docs/spec/component/legend.zh.md
=> docs: add legend layout docs

.github/workflows/cr.yml
=> chore: add gpt for code review

site/.dumi/global.ts, site/.dumirc.ts, site/examples/analysis/bin/demo/bin-color.ts, site/examples/component/legend/demo/continuous.ts, site/examples/composition/facet/demo/rect.ts, site/examples/composition/space/demo/space-flex.ts, site/examples/composition/space/demo/space-layer.ts, site/examples/general/area/demo/area-band.ts, site/examples/general/cell/demo/cell-aggregated.ts, site/examples/general/cell/demo/cell-heatmap.ts, site/examples/general/line/demo/line-gradient-encoding.ts, site/examples/general/parallel/demo/line-parallel-horizontal.ts, site/examples/general/parallel/demo/line-parallel-vertical.ts, site/examples/general/point/demo/point-sequential.ts, site/examples/general/radar/demo/parallel-radar.ts, site/examples/general/vector/demo/wind.ts, site/examples/geo/geo/demo/choropleth-usa.ts, site/examples/geo/geo/demo/projection-comparison.ts, site/examples/geo/geo/demo/world-map.ts, site/examples/style/pattern/demo/custom-pattern-with-canvas.ts, site/examples/style/pattern/demo/custom-pattern-with-g-api.ts, site/examples/style/theme/demo/layout-area.ts, src/runtime/render.ts
=> docs(site): add spec tab for examples

CHANGELOG.md, package.json, site/package.json
=> chore: bump to 5.0.5

site/docs/spec/plugin/renderer.zh.md
=> docs: 如何在 UMD 下使用非内置渲染器

CHANGELOG.md, package.json, site/package.json
=> chore: bump to 5.0.6

site/docs/spec/component/tooltip.zh.md, site/examples/general/dual/demo/meta.json, site/examples/general/dual/demo/pareto.ts
=> docs: add pareto chart demo

CHANGELOG.md, package.json, site/package.json
发一个版本，其中修复 brush 和 auto padding 可以先给业务用一下。
=> chore: update to 5.0.8

site/docs/manual/single-view/tooltip.zh.md, site/examples/interaction/interaction/demo/tooltip-render.ts
=> fix: tooltip.position example typo

site/.dumirc.ts
=> docs: update .dumirc.ts news

CHANGELOG.md, package.json, site/package.json
=> chore: udpate to 5.0.11

.github/workflows/discussion-notify.yml
ref: https://github.com/ant-design/ant-design/blob/master/.github/workflows/discussion-open-check.yml
=> chore: add discussion notify

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
issue and pr template are reversed 🥲, and I think the h5 in pr template is too small to distinguish title from text.
=> chore: issue and pr template

CHANGELOG.md, package.json, site/package.json
=> chore(version): bumps to 5.0.13

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.0.14

site/docs/manual/single-view/annotation.zh.md
=> doc:  修复文本错误

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.0.15

__tests__/integration/api-chart-render-event.spec.ts, __tests__/plots/api/chart-render-event.ts, __tests__/plots/api/index.ts, src/animation/morphing.ts, src/runtime/plot.ts
- fix: https://github.com/antvis/G2/issues/5272
- 存在问题：update 的时候没有设置 markType，导致没有 emit element 相关的事件。
=> fix(update): set markType for element

__tests__/unit/api/chart.spec.ts, src/api/chart.ts
close: https://github.com/antvis/G2/issues/5312
=> fix(chart): chart.clear preserve some global options

site/.dumirc.ts
- [x ] commit message follows commit guidelines
- [x ] documents are updated
文档头部导航栏路径修改，防止ctrl+点击打开新tab时404
=> docs: Update site/.dumirc.ts

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.0.19

scripts/treeshaking/size.json, site/docs/manual/extra-topics/bundle.en.md, site/docs/manual/extra-topics/bundle.zh.md, site/docs/manual/extra-topics/color.en.md
=> docs: add bundle

site/docs/manual/core/tooltip.zh.md, site/docs/manual/extra-topics/customization.zh.md
更新自定义文档，添加如下自定义能力：
- 自定义形状（Shape）
- 自定义提示（Tooltip）
- 自定义图例（Legend）
- 自定义拖动轴（Slider）
=> docs: update custom

__tests__/unit/lib/core.spec.ts, __tests__/unit/lib/std.spec.ts, site/docs/spec/data/log.en.md, site/docs/spec/data/log.zh.md, site/docs/spec/overview.zh.md, src/data/index.ts, src/data/log.ts, src/lib/core.ts, src/spec/dataTransform.ts
- fixed https://github.com/antvis/G2/issues/5415
=> feat: add data transform log

README.md, README.zh-CN.md
=> docs: fix 404 url

site/docs/manual/extra-topics/use-in-framework.zh.md
fix use-in-framework.zh.md vue sample code mistake.
=> docs: fix sample code typo

__tests__/integration/api-chart-on-component-click.spec.ts, __tests__/plots/api/chart-on-component-click.ts, src/interaction/event.ts
解决 https://github.com/antvis/G2/pull/5440 带来的 ci 问题。
=> fix: lint issues from #5440

site/docs/spec/data/fetch.en.md, site/docs/spec/data/fetch.zh.md
=> docs(data): update zh and en for fetch

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.0.21

CHANGELOG.md, package.json, site/package.json
=> fix(dep): add @antv/g-plugin-3d to dependencies

src/api/chart.ts, src/api/index.ts
=> fix(types): export ChartOptions replace RuntimeOptions

__tests__/unit/lib/lib.spec.ts, src/index.ts
=> fix(libs): export expected libs

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.0.23

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.1.0

README.md, README.zh-CN.md, site/docs/manual/introduction/getting-started.zh.md
=> docs: remove next

site/docs/spec/common/componentTitle.zh.md, site/docs/spec/common/navigator.zh.md, site/docs/spec/component/legend.zh.md
=> docs: update legend options

site/examples/component/tooltip/demo/meta.json, site/examples/component/tooltip/demo/tooltip-render.ts, site/examples/component/tooltip/demo/tooltip-style.ts
- 增加自定义 tooltip 样式的 demo
- 修改自定义 tooltip 的 demo
=> docs: add more demos for tooltip

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.1.1

__tests__/unit/api/type.spec.ts, src/api/chart.ts, src/api/extend.ts, src/api/index.ts, src/index.ts
fix: https://github.com/antvis/G2/issues/5525
=> fix(types): composition node

site/examples/general/bullet/demo/bullet-datas.ts, site/examples/general/bullet/demo/bullet.ts, site/examples/general/bullet/demo/bullets.ts
optimize bullet examples, add legend
=> feat(examples): optimize bullet examples

CHANGELOG.md, package.json, site/package.json
=> chore: update 5.1.2

README.md, README.zh-CN.md, __tests__/unit/ssr/index.spec.ts, site/docs/manual/extra-topics/ssr.en.md, site/docs/manual/extra-topics/ssr.zh.md
=> docs: update readme, add ssr document

CONTRIBUTING.md, CONTRIBUTING.zh-CN.md
In `CONTRIBUTING.md`, the file path for the api test cases is incorrect.
=> fix(CONTRIBUTING.md): fix incorrect file path

src/interaction/utils.ts
restoreCursor 恢复到上一次设置的 cursor 值。 Fix #5533
=> fix: restore to last cursor not default

CHANGELOG.md, package.json, site/package.json
=> chore:  update to 5.1.3

site/docs/spec/component/axis.zh.md
fixed #5554 :
options - label's attributes - text's color and opacity
=> docs: fix typo 

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.1.4

__tests__/plots/api/chart-render-3d-bar-chart-perspective.ts, site/.dumi/theme/components/ConfigPanel.tsx, site/.dumi/theme/components/DemosView.less, site/.dumi/theme/components/DemosView.tsx, site/.dumi/theme/examples/bar-aggregated.ts, site/.dumi/theme/examples/bar-dodged.ts, site/.dumi/theme/examples/bar-range.ts, site/.dumi/theme/examples/grouped-box.ts, site/.dumi/theme/examples/index.ts, site/.dumi/theme/examples/line-bar.ts, site/.dumi/theme/examples/line-connect-nulls.ts, site/.dumi/theme/examples/line-normalized.ts, site/.dumi/theme/examples/missing-data-area.ts, site/.dumi/theme/examples/point-log.ts, site/.dumi/theme/examples/rose-label.ts, site/.dumi/theme/examples/sankey.ts, site/.dumi/theme/examples/spider-label.ts, site/.dumi/theme/examples/stacked-area.ts, site/.dumi/theme/examples/treemap.ts, site/.dumi/theme/index.tsx, site/.dumi/tsconfig.json, site/.dumirc.ts
完成这个 issue：https://github.com/antvis/G2/issues/5571 的以下内容：
目前效果：
=> feat: show theme editor

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.1.5-beta.0

src/interaction/tooltip.ts, src/runtime/plot.ts
这个 https://github.com/antvis/G2/pull/5590 PR 处理问题没有彻底，这样才可能解决 https://github.com/antvis/G2/issues/5555 提到的内存泄漏问题。
=> fix(tooltip): destroy when reapply

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.1.5

CHANGELOG.md, package.json
=> chore: update to 5.1.6-beta

CHANGELOG.md, package.json
=> chore: update to 5.1.6-beta.1

site/docs/manual/core/mark.zh.md, site/docs/manual/core/view.zh.md
修改文档`核心-标记-一等公民`中的`slider`, `interaction`以及`theme`的引用跳转地址
修改文档`核心-视图-核心概念`中的`slider`, `interaction`以及`theme`的引用跳转地址
=> docs(site): 修改"标记"和"视图"中引用跳转地址

__tests__/integration/snapshots/tooltip/state-ages-interval-scrollbar/step0.html, __tests__/plots/tooltip/index.ts, __tests__/plots/tooltip/stateages-interval-scrollbar.ts, src/interaction/utils.ts
- fix: https://github.com/antvis/G2/issues/5605
- 问题原因：scrollbar 会导致 invert 不回去，导致分组失败
- 解决办法：不用 invert，映射后的值也可以分组
=> fix(tooltip): shared tooltip with scrollbar

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.1.6

.github/ISSUE_TEMPLATE/oscp.yml
=> chore: update oscp template

README.md, README.zh-CN.md
=> docs: update readme img

site/docs/spec/component/scrollbar.zh.md
=> doc: 滚动条监听滚动变化事件报错 #5656

site/docs/spec/transform/sample.zh.md, site/examples/general/line/demo/line-sample.ts, site/examples/general/line/demo/meta.json
Fixes #5681 
官网增加关于 sample 的 DEMO 实例
=> docs: 添加line-sample DEMO案例

site/examples/general/pie/demo/meta.json, site/examples/general/pie/demo/pie-donut-text.ts
=> docs: 添加包含中心文本的饼图案例

docs/api/general/chart.zh.md
fix chart.zh.md
修复 chart.zh.md 文字错误
=> docs: fix chart.zh.md

__tests__/unit/api/theme.spec.ts, site/docs/manual/core/theme.zh.md, src/exports.ts
close: https://github.com/antvis/G2/issues/5675
=> docs: custom theme

CHANGELOG.md, package.json, site/package.json
=> chore: bump to 5.1.7

site/docs/manual/extra-topics/customization.zh.md
=> Update: customization.zh.md

src/spec/mark.ts
Remove the reference imported from '@antv/ava'.
=> fix(mark): delete ava type

__tests__/integration/snapshots/static/singlePointBasic.svg, __tests__/plots/static/index.ts, __tests__/plots/static/single-point-basic.ts, src/component/legendContinuous.ts
=> fix: render error when signle data in point mark

site/examples/general/Liquid/demo/liquid-pin.ts, src/component/axis.ts, src/mark/liquid.ts, src/runtime/component.ts, src/utils/number.ts
=> fix(liquid): fix liquid precision

CHANGELOG.md, package.json, site/package.json
=> chore: publish beta

README.md, README.zh-CN.md, site/.dumirc.ts
=> docs: ecosystem and plugin

site/.dumirc.ts
=> docs: remove g2-react from eco for site

site/.dumirc.ts, site/package.json
=> chore: update dumi-theme-antv

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.1.9

src/chart/controller/tooltip.ts
Just added a check condition for element in case of undefined. Undefined error occurs in development
resolves #5835
=> fix: undefined tooltip element (#5835)

site/.dumirc.ts
=> fix: english title of site

__tests__/integration/snapshots/interaction/stocks-line-slider/step1.svg, __tests__/plots/interaction/index.ts, __tests__/plots/interaction/stocks-line-slider.ts, src/interaction/tooltip.ts
- fix: https://github.com/antvis/G2/issues/5816
=> fix(tooltip): handle undefined

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.1.10

package.json
> close: https://github.com/antvis/G2/issues/5791
升级 `@antv/component` 以用到这个 https://github.com/antvis/component/pull/313 的特性
=> chore: update @antv/component to 1.0.0

site/examples/general/interval/demo/bar-diverging.ts, site/examples/general/interval/demo/meta.json
=> docs: examples bar  update image

src/interaction/tooltip.ts
- 修复这个 https://github.com/antvis/G2/pull/5856 的问题
- 存在问题：tooltip 不会展现出来
- 相关 PR：
- https://github.com/antvis/G2/pull/5283
- https://github.com/antvis/G2/pull/5025
=> fix(tooltip): wrong container

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.1.11

site/examples/general/interval/demo/bar-basic-grouped.ts, site/examples/general/interval/demo/bar-basic-stacked.ts, site/examples/general/interval/demo/bar-basic-transposed.ts, site/examples/general/interval/demo/bar-basic.ts, site/examples/general/interval/demo/meta.json
迁移 4.0 官网案例中一些简单的条形图，下面红框中是最新添加的。
=> docs: add simple bar demos

site/docs/spec/scale/point.en.md
=> docs: 修改point比例尺英文文档嵌入的链接

site/docs/spec/component/title.zh.md
=> docs: fix image url

site/examples/interaction/brush/demo/brush.ts, site/examples/interaction/brush/demo/meta.json
x y 也添加 自定义 tooltip , 探查重叠的 散点
=> docs: add brush tooltip show

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.1.12

__tests__/plots/static/index.ts, __tests__/plots/static/liquid-content.ts, __tests__/plots/static/liquid-pin.ts, site/examples/general/Liquid/demo/liquid-content.ts, site/examples/general/Liquid/demo/meta.json, src/mark/liquid.ts
=> fix(mark): change liquid text name

site/examples/general/line/demo/base.ts, site/examples/general/line/demo/curved.ts, site/examples/general/line/demo/meta.json, site/examples/general/line/demo/step.ts
根据 #5896 的要求迁移了官网4.0的样例，截图如下：
【基础折线图】 
【曲线折线图】
【阶梯折线图】
=> docs: add simple line demos

site/docs/manual/core/mark.en.md, site/docs/manual/core/mark.zh.md
close: https://github.com/antvis/G2/issues/5961
=> 更正文档->核心概念->标记(Mark)->绝对定位/相对定位示例代码

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.1.13

__tests__/integration/api-chart-on-label-click.spec.ts, __tests__/plots/api/chart-on-label-click.ts, __tests__/plots/api/index.ts, site/docs/manual/extra-topics/event.en.md, site/docs/manual/extra-topics/event.zh.md, src/interaction/event.ts
解决问题：
* 增加label事件响应，返回对应的data数据，相关issues：https://github.com/antvis/G2/issues/6004
=> feat(event): label click event

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.1.14

.github/workflows/build.yml, package.json
恢复这个 PR 误删的代码：https://github.com/antvis/G2/issues/5733
=> fix(ci): add update coverall action

site/docs/manual/core/state.en.md, site/docs/manual/core/state.zh.md, site/examples/general/interval/demo/bar-basic.ts, site/examples/general/interval/demo/column-interactive.ts, site/examples/general/interval/demo/meta.json
=> feat: add interactive column

site/docs/manual/core/encode.zh.md
=> docs: update encode.zh.md

.github/workflows/ci.yml, src/component/update-label.ts, tests/bugs/6104-spec.ts
- fixed https://github.com/antvis/G2/issues/6104 图表开启Label配置，多次render后执行卸载操作导致图表底层报错。
=> fix(label): 图表开启label配置，多次render后卸载图表导致报错(#6104)

site/examples/general/radial/demo/meta.json, site/examples/general/radial/demo/radial-bar-with-background.ts, site/examples/general/radial/demo/radial-line.ts, site/examples/general/radial/demo/radial-stacked.ts
相关issue：https://github.com/antvis/G2/issues/5902
=> docs: add radial graph demos

src/runtime/scale.ts
fixed scale options rangeMax and rangeMax
=> fix: scale options rangeMin and rangeMax

CHANGELOG.md, package.json, site/package.json
=> chore: bump to 5.1.16

site/docs/manual/core/title.en.md, site/docs/manual/core/title.zh.md, site/docs/spec/component/title.zh.md
=> docs: fix title document typo

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.1.19

site/docs/spec/interaction/tooltip.zh.md
=> docs: 修改interaction中tooltip的crosshairs选项描述错别字

site/docs/spec/label/overview.zh.md, site/examples/analysis/group/demo/bar-aggregated-with-label.ts, site/examples/analysis/group/demo/meta.json
给这个 PR https://github.com/antvis/G2/pull/6250 的 feature 的功能添加文档和案例。
=> docs: example and docs for aggregated label

CHANGELOG.md, package.json, site/package.json
=> chore: update to 5.1.22

site/examples/component/tooltip/demo/meta.json, site/examples/component/tooltip/demo/tooltip-crosshairs.ts, site/examples/component/tooltip/demo/tooltip-marker.ts
* 增加tooltip相关的两个demo：十字辅助线和空心圆相关demo。
=> docs(tooltips): add component tooltip demos

__tests__/integration/api-chart-emit-series-tooltip.spec.ts, src/interaction/tooltip.ts
close: https://github.com/antvis/G2/issues/5910
=> fix(tooltip): show error data if dataset if large

site/examples/general/line/demo/line-zero-values.ts, site/examples/general/line/demo/meta.json
close: https://github.com/antvis/G2/issues/6306
=> docs: add example line with zero values

__tests__/integration/snapshots/api/chart-emit-series-tooltip/step0.html, __tests__/integration/snapshots/api/chart-emit-series-tooltip/step1.html, src/interaction/tooltip.ts
close: https://github.com/antvis/G2/issues/5912
=> fix(tooltip): emit show in large dataset

site/.dumirc.ts
=> docs: close api docs

CHANGELOG.md, package.json, site/package.json
=> chore: release 5.2.0

.github/workflows/deploy.yml
=> fix(deploy): use npm@20 to fix error

CHANGELOG.md, package.json, site/package.json
=> chore: release 5.2.2

site/examples/component/legend/demo/meta.json, site/examples/component/legend/demo/symbol.ts
=> docs: add custom symbol demo

CHANGELOG.md, package.json
=> chore: changelog

__tests__/integration/chart-emit-show-tooltip.spec.ts, __tests__/integration/snapshots/api/chart-emit-show-tooltip/step0.html, src/interaction/tooltip.ts
=> fix: the mouse position is offset of dodgeX tooltip event

site/docs/manual/core/interaction.en.md, site/docs/manual/core/interaction.zh.md
Updated custom interaction case.
=> chore: custom interaction case

site/docs/spec/component/slider.zh.md
=> fix: 订正slider组件属性文件

site/examples/interesting/interesting/demo/meta.json, site/examples/interesting/interesting/demo/national.ts
=> docs: add national day image

jest.config.js
=> chore: setup jest config to adapt pnpm

package.json
=> chore: update exports

package.json
chore(deps): update fmin version
fix: https://github.com/ant-design/ant-design-charts/issues/2724
=> chore(deps): update fmin version

CHANGELOG.md, package.json
=> chore: v5.2.9 changelog

src/interaction/tooltip.ts
| Before | After |
| ------ | ----- |
|    ![image](https://github.com/user-attachments/assets/3006def2-b2da-4f85-924e-2d89e365c5a6)    |  ![image](https://github.com/user-attachments/assets/7dbbbacd-e5af-42a2-85c3-197a5a9a90a6)  |
=> feat: add tooltip data to tooltip event callback

site/docs/spec/interaction/tooltip.zh.md
fix https://github.com/antvis/G2/issues/6552#issue-2734952237
=> docs: update tooltip.zh.md

site/.dumirc.ts
=> docs: fix broken link

site/.dumirc.ts
=> docs: add announcement for doc experience survey

__tests__/integration/snapshots/tooltip/indices-line-items/step0.html, __tests__/integration/snapshots/tooltip/items-callback/step0.html, __tests__/plots/tooltip/index.ts, __tests__/plots/tooltip/items-callback.ts, src/interaction/tooltip.ts, src/runtime/transform.ts
https://stackblitz.com/edit/react-chvm779o-bbhqthoe?file=src%2Findex.js
修复 series mark 下 items-callback 不生效的问题
=> fix: items callback's priority

site/docs/manual/core/mark/cell.zh.md, site/docs/manual/core/mark/chord.zh.md
=> docs: mark-cell,mark-chord

site/docs/manual/core/mark/density.zh.md
=> docs mark density

site/.dumi/global.ts, site/docs/manual/core/mark/image.zh.md, site/docs/manual/core/mark/lineX.zh.md, site/docs/manual/core/mark/lineY.zh.md, site/docs/manual/core/mark/link.zh.md, site/docs/manual/core/mark/liquid.zh.md, site/docs/manual/core/mark/polygon.zh.md, site/examples/annotation/line/demo/histogram-mean-line.ts, site/examples/annotation/line/demo/interval-mean-line.ts, site/examples/general/image/demo/contributor.ts, site/examples/general/link/demo/link-shape.ts, site/examples/general/link/demo/meta.json, site/examples/geo/geo/demo/States-usa-ploygon.ts, site/examples/geo/geo/demo/meta.json, site/package.json
update docs。
mark:  image、linX、lineY、link、liquid、polygon
=> feat(docs): update docs, image、linX、lineY、link、liquid、polygon

site/docs/manual/core/mark/gauge.zh.md, site/docs/manual/core/mark/heatmap.zh.md
docs: mark-densisy & mark-heatmap
=> Docs mark gauge

CHANGELOG.md, package.json
=> chore: change log v5.2.12

.github/ISSUE_TEMPLATE/4.oscp.yml
=> feat: update oscp issue template

site/docs/manual/core/mark/line.zh.md, site/examples/general/line/demo/line-style.ts, site/examples/general/line/demo/meta.json
=> docs: mark-line

site/.dumirc.ts
- update announcement for doc season
=> feat: update announcement for doc season

site/docs/manual/component/scrollbar.zh.md
更新 scrollbar 组件文档
- fixed #6689
=> feat(scrollbar): scrollbar docs update

site/docs/manual/core/data/fetch.zh.md, site/docs/manual/core/data/inline.zh.md
=> docs: update data type: inline, fetch

site/examples/general/histogram/demo/histogram-stacked.ts, site/examples/general/histogram/demo/histogram.ts
=> docs: update histogram demo

site/docs/manual/component/legend.zh.md, site/docs/manual/component/slider.zh.md, site/docs/manual/core/chart/chart-component.zh.md
- 修改slider文档结构和配置项
- 后续补充组成图和示例
- 解决文档反馈
=> docs: modify slider

.github/ISSUE_TEMPLATE/4.oscp.yml
=> feat: update oscp template

site/docs/manual/core/data/fetch.zh.md, site/docs/manual/core/data/inline.zh.md, site/docs/manual/core/data/overview.zh.md
- modify data overview
- 调整文档结构，补充描述
- 补充数据实时更新的例子
=> docs: modify data overview

site/docs/manual/core/data/sort.zh.md
=> docs: update data.transform.sort

site/docs/manual/core/mark/text.zh.md, site/examples/annotation/text/demo/meta.json, site/examples/annotation/text/demo/peak-value-text.ts
=> docs: add text example

site/docs/manual/core/mark/rect.zh.md
=> update rect doc

site/docs/manual/introduction/use-in-framework.en.md, site/docs/manual/introduction/use-in-framework.zh.md
- 解决官网反馈，[在前端框架里使用](https://g2.antv.antgroup.com/manual/introduction/use-in-framework)三个codebox打开404
新写了三个示例项目，更新代码地址
=> docs: fix broken codebox

site/docs/manual/core/mark/shape.zh.md
=> docs: 改造「核心概念 - 标记（Mark）- shape」文档

site/docs/manual/core/mark/wordcloud.zh.md
update wordcloud doc
- Fixed #6656
=> docs: update wordcloud doc

__tests__/plots/bugfix/index.ts, __tests__/plots/bugfix/issue-6747.ts, src/interaction/event.ts, src/interaction/tooltip.ts, src/utils/helper.ts
- fixed #6747 
- maybe fixed https://github.com/antvis/G2/discussions/6749
=> fix: element event error in wordcloud

site/docs/manual/core/data/filter.zh.md, site/docs/manual/core/data/map.zh.md, site/docs/manual/core/data/slice.zh.md, site/docs/manual/core/data/sort.zh.md, site/docs/manual/core/data/sortBy.zh.md
=> [Docs]: 改造文档「核心概念 - 数据（Data）- sortBy」文档 #6673

site/docs/manual/core/transform/bin.zh.md, site/docs/manual/core/transform/binX.zh.md
doc update bin,binX
fixed: #6674
=> docs: bin,binX doc update

.gitignore, site/.dumi/global.ts, site/.dumi/pages/theme.zh.tsx, site/.dumi/prism-one-light.css, site/.dumirc.ts, site/.gitignore, site/mako.config.json, site/package.json
- 升级依赖包
- 调整主页 TDK 信息
- 开启 Mako SSR构建
- 开启 sitemap配置
- 开启死链检查
=> chore: site seo optimization

site/docs/manual/extra-topics/expr.en.md, site/docs/manual/extra-topics/expr.zh.md, site/examples/expr/base/demo/meta.json
- 修复 expr 相关文档中 demo 未正常渲染。
- expr 当前的 example 预览图缺失，需要添加一下预览图的对象存储。
=> docs: add chart.render() call in expression examples

__tests__/integration/snapshots/static/flareTreemapCustom.svg, __tests__/integration/snapshots/static/flareTreemapDefault.svg, __tests__/integration/snapshots/static/flareTreemapDrillDown.svg, src/mark/treemap.ts, src/runtime/plot.ts
- fixed: https://github.com/ant-design/ant-design-charts/issues/2722
- 矩阵树图rect中的label阻塞了点击事件
=> fix(label): the labels in the treemap are blocking click interactions

site/.dumi/theme/index.less, site/package.json
- 修复因为antd版本冲突导致的ssr优化后的官网主题页面组件样式丢失
=> chore: fix theme style

site/docs/manual/FAQ/index.zh.md, site/docs/manual/component/legend.zh.md, site/docs/manual/core/transform/overview.zh.md, site/examples/general/area/demo/meta.json, site/examples/general/area/demo/rank-trend-area.ts
=> docs: add FAQ & modify transform overview

src/interaction/tooltip.ts
- fixed https://github.com/antvis/G2/issues/6787
=> feat: tooltip support pointerdown, pointerup event

CHANGELOG.md, package.json
=> chore: change log 5.3.1

site/docs/manual/core/transform/dodgeX.zh.md
=> docs: 改造「核心概念 - 转换（Transform）- dodgeX」文档

site/docs/manual/component/tooltip.zh.md, site/docs/manual/core/mark/gauge.zh.md, site/examples/general/gauge/demo/gauge-custom-shape.ts, site/examples/general/gauge/demo/meta.json
- tooltip 文档反馈修复以及文档走查，补充属性以及错误修复
- gauge 仪表盘文档补充完整属性以及示例
=> docs: fix documentation feedback issues and resolve problems

site/docs/manual/core/coordinate/helix.en.md, site/docs/manual/core/coordinate/helix.zh.md
- related: https://github.com/antvis/G2/issues/6726
=> docs: add documentation for helix coordinate system

site/docs/manual/core/interaction/scrollbarFilter.zh.md
- FIxed: #6800
按要求 改造文档「核心概念 - 交互（Interaction）- scrollbarFilter」
添加了
=> docs: 改造文档「核心概念 - 交互（Interaction）- scrollbarFilter」#6800

site/docs/manual/core/transform/jitter.zh.md, site/docs/manual/core/transform/jitterX.zh.md, site/docs/manual/core/transform/jitterY.zh.md
docs: update jitter transform documentation 📚
- Revise jitter transform overview for clarity and purpose.
- Add usage scenarios for scatter plots and data overlap avoidance.
- Include detailed configuration options with default values.
- Provide practical examples with code snippets for implementation.
=> docs: 改造「核心概念 - 转换（Transform）- jitter」文档

site/docs/manual/core/interaction/sliderFilter.zh.md, site/examples/interaction/element/demo/meta.json, site/examples/interaction/element/demo/slider.ts
- Fixed: #6801
- Update `sliderFilter` interaction documentation for clarity and detail.
- .Updated the `meta.json` file to include the new `slider.ts` example, with localized titles and a screenshot.
=> docs: 改造文档「核心概念 - 交互（Interaction）- sliderFilter」

site/docs/manual/core/interaction/legendFilter.zh.md
=> docs: 改造文档「核心概念 - 交互（Interaction）- legendFilter」

site/docs/manual/component/axis.zh.md, site/docs/manual/core/encode.zh.md, site/examples/composition/facet/demo/meta.json, site/examples/composition/facet/demo/rect-ring.ts
- Fixed: #6819 
- aixs 文档内容修改、补充示例
=> docs: 改造文档「核心概念 - 编码（Encode）」

site/docs/manual/core/interaction/chartIndex.zh.md
=> docs: 改造文档「核心概念 - 交互（Interaction）- chartIndex」( #6796)

package.json
=> 5.3.3-beta.0

site/docs/manual/core/mark/vector.zh.md
=> docs: 改造文档「核心概念 - 标记（Mark）- vector」(#6668)

site/package.json
- fixed https://github.com/antvis/G2/security/dependabot/1
=> chore: upgrade gh-pages to fix alert

site/docs/manual/core/interaction/brushFilter.zh.md, site/docs/manual/core/interaction/brushXFilter.zh.md, site/docs/manual/core/interaction/brushYFilter.zh.md
=> docs: 改造「核心概念 - 交互（Interaction）-brushFilter、brushXFilter、brushYFilter」文档

__tests__/integration/snapshots/static/cars3LineRadar.svg, __tests__/integration/snapshots/static/nbaLineRadar.svg, __tests__/plots/bugfix/issue-6020.ts, __tests__/plots/static/index.ts, __tests__/plots/static/nba-line-radar.ts, site/examples/general/radar/demo/meta.json, site/examples/general/radar/demo/multi-radar.ts, src/component/axis.ts, src/mark/line.ts, src/runtime/component.ts, src/theme/create.ts
=> fix: bugs for radar coord and plot

site/docs/manual/core/interaction/brushFilter.zh.md, site/docs/manual/core/interaction/brushXFilter.zh.md, site/docs/manual/core/interaction/brushYFilter.zh.md, site/docs/manual/core/transform/select.zh.md, site/docs/manual/core/transform/selectX.zh.md, site/docs/manual/core/transform/selectY.zh.md
=> docs: 改造「核心概念 - 转换（Transform）-select、selectX、selectY」文档

__tests__/integration/snapshots/api/chart-emit-legend-filter/step0.svg, __tests__/integration/snapshots/api/chart-emit-slider-filter/step1.svg, __tests__/integration/snapshots/interaction/penguins-point-repeat-matrix-legend-filter/step0.svg
- update snapshots because of the new version of `@antv/component`
=> test: update snapshots

src/spec/transform.ts, src/transform/group.ts, src/transform/groupN.ts
Fixed:  #6871 
修复 transform group spec 方式缺失的 channels 类型定义
=> fix: add channels property to GroupTransform type

package.json, scripts/bench/package.json, scripts/treeshaking/litelib/main.js, scripts/treeshaking/package.json, src/index.ts
=> fix: severity alert 10+ of vite

site/docs/manual/core/scale/log.zh.md
=> docs: 改造文档「核心概念 - 比例尺（Scale）-log」

__tests__/integration/issue-6863.spec.ts, __tests__/integration/snapshots/bugfix/issue6863.svg, __tests__/plots/bugfix/index.ts, __tests__/plots/bugfix/issue-6863.ts, __tests__/plots/static/acme-crop-income-interval-connector.ts, __tests__/plots/static/alphabet-interval-funnel-connector-label.ts, __tests__/unit/shape/connector.spec.ts, src/shape/connector/connector.ts
-Fixed: #6863 
选择了和offset一样的配置方式，方便更精确的控制
=> feat: 添加连接器的 offsetX 参数

site/docs/manual/core/coordinate/parallel.zh.md
=> docs: 改造文档「核心概念 - 坐标系（Coordinate）-parallel」

site/docs/manual/core/scale/sqrt.zh.md, site/docs/manual/core/scale/time.zh.md
=> docs: 改造文档「核心概念 - 比例尺（Scale）-sqrt」

site/docs/manual/core/coordinate/fisheye.zh.md
=> [Docs]: 改造文档「核心概念 - 坐标系（Coordinate）-fisheye」 

__tests__/integration/api-chart-get-data-by-xy.spec.ts, __tests__/integration/snapshots/api/chart-get-data-by-x-y/step0.svg, __tests__/integration/snapshots/api/chart-get-data-by-x-y/step1.svg, __tests__/plots/api/chart-get-data-by-xy.ts, __tests__/plots/api/index.ts, site/examples/interaction/event/demo/get-data-by-xy.ts, site/examples/interaction/event/demo/meta.json, src/api/runtime.ts, src/interaction/tooltip.ts, src/runtime/plot.ts, src/runtime/types/common.ts
=> chore: add a method to obtain data by point location

site/docs/manual/core/scale/quantile.zh.md
=> docs: 改造文档「核心概念 - 比例尺（Scale）-quantile」

site/docs/manual/core/coordinate/polar.zh.md
=> docs: 改造文档「核心概念 - 坐标系（Coordinate）-polar」

README.md, README.zh-CN.md
Hi antvis Team
We’re the team behind Openomy, We have received requests from your community to contribute to the graph,so we now prepare a contributor chart exclusively for your community, and we are excited to offer a brand-new contribution visualization chart for your GitHub repository, ready to be embedded directly into your README.
Unlike GitHub’s default contributor chart, the Openomy chart offers a more comprehensive view of community contributions. In addition to code-related actions like commits and pull requests, we also recognize other meaningful activities such as issues, comments, and even likes—because we believe every act of participation deserves to be seen and valued.
We’ve created a personalized data detail page in antvis/G2 …
=> docs: update a new contributions charts

site/.dumi/prism-one-dark.css, site/.dumi/prism-one-light.css, site/docs/charts/bar.en.md, site/docs/charts/bar.zh.md, site/docs/charts/demos/chart-card.tsx, site/docs/charts/demos/components-list.tsx, site/docs/charts/demos/list-card.tsx, site/docs/charts/demos/list-category.tsx, site/docs/charts/histogram.en.md, site/docs/charts/histogram.zh.md, site/docs/charts/multi-set-bar.en.md, site/docs/charts/multi-set-bar.zh.md, site/docs/charts/radial-bar.en.md, site/docs/charts/radial-bar.zh.md, site/docs/charts/stacked-bar.en.md, site/docs/charts/stacked-bar.zh.md, site/docs/manual/core/color.en.md, site/docs/manual/core/state.en.md, site/docs/manual/core/style.en.md, site/package.json
- 规范图表介绍页面样式和文档格式
- 公共组件封装，贡献者只需关注文档内容，不需要关注组件实现
- 图表介绍-柱状图中文、英文文档编写完毕，作为example参考
- 升级主题包版本，使用最新的代码块语法
=> docs: chart introduction & example

site/docs/manual/core/scale/point.zh.md
=> docs: 改造文档「核心概念 - 比例尺（Scale）-point」

site/docs/manual/core/mark/box.zh.md
=> docs: 改造文档「核心概念 - 标记（Mark）- box」

site/docs/manual/core/mark/boxplot.zh.md
=> docs: 改造文档「核心概念 - 标记（Mark）- boxplot」

site/docs/manual/core/interaction/elementHighlightByColor.zh.md, site/docs/manual/core/interaction/elementSelect.zh.md, site/docs/manual/core/interaction/elementSelectByColor.zh.md, site/docs/manual/core/interaction/elementSelectByX.zh.md
- Fixed: https://github.com/antvis/G2/issues/6794
=> docs: 改造文档「核心概念 - 交互（Interaction）- elementSelect、elementSelectByColor、elementSelectByX」

site/docs/manual/core/theme/overview.zh.md
=> docs: 改造文档「核心概念 - 主题（Theme）- 概览」

site/docs/manual/core/interaction/overview.en.md, site/docs/manual/core/interaction/overview.zh.md, site/examples/interaction/brush/demo/meta.json, site/examples/interaction/brush/demo/reset-brush.ts
=> docs: add examples of interaction events

site/docs/charts/area.en.md, site/docs/charts/area.zh.md
=> docs: 新增「面积图」文档

site/docs/charts/bullet.en.md, site/docs/charts/bullet.zh.md
=> docs: 添加子弹图介绍文档

site/docs/charts/contourline.en.md, site/docs/charts/contourline.zh.md
=> docs: 新增「等高线」文档

site/docs/charts/color-map.en.md, site/docs/charts/color-map.zh.md
=> docs: 新增「色块图」文档

site/docs/charts/funnel.en.md, site/docs/charts/funnel.zh.md
=> docs: 新增「漏斗图」文档

site/docs/charts/chord.en.md, site/docs/charts/chord.zh.md
=> docs: 新增「和弦图」文档

site/docs/charts/mosaic.en.md, site/docs/charts/mosaic.zh.md
=> docs: 新增「马赛克图」文档

site/examples/interaction/brush/demo/reset-brush.ts
=> fix: document example exception

site/docs/manual/introduction/use-in-framework.en.md, site/docs/manual/introduction/use-in-framework.zh.md
add cleanup for chart instance in "use-in-framework"
=> docs: add cleanup for chart instance on component unmount

site/docs/charts/arcdiagram.en.md, site/docs/charts/arcdiagram.zh.md
=> docs: 新增弧长连接图文档

site/docs/manual/extra-topics/ssr.en.md, site/docs/manual/extra-topics/ssr.zh.md
=> docs: update g2 ssr document

site/docs/charts/rose.en.md, site/docs/charts/rose.zh.md
=> docs: 新增「南丁格尔玫瑰图」文档

__tests__/integration/snapshots/static/flareTreemapDrillDownWithView.svg, __tests__/plots/static/flare-treemap-drill-down-with-view.ts, __tests__/plots/static/index.ts, src/mark/treemap.ts
https://github.com/ant-design/ant-design-charts/issues/2883
=> fix: treemap drilldown interaction is ineffective in view mode

site/docs/charts/pie.en.md, site/docs/charts/pie.zh.md
=> docs: 修改文档错误

CHANGELOG.md, package.json
=> chore: update version to 5.3.4

site/docs/charts/spiral.en.md, site/docs/charts/spiral.zh.md
=> docs: 新增「螺旋图」文档

site/docs/manual/component/legend.en.md, site/docs/manual/component/legend.zh.md
=> docs: add the documentation for legend item poptip

site/docs/manual/component/scrollbar.en.md, site/docs/manual/component/scrollbar.zh.md, site/docs/manual/component/tooltip.zh.md, site/docs/manual/core/interaction/scrollbarFilter.en.md, site/docs/manual/core/interaction/scrollbarFilter.zh.md
=> docs: fix document from user

__tests__/integration/snapshots/interaction/alphabet-interval-highlight-scrollbar/step0.svg, __tests__/plots/interaction/alphabet-interval-highlight-scrollbar.ts, __tests__/plots/interaction/index.ts, src/interaction/scrollbarFilter.ts
- 统一 `scrollbar`和 `slider` 的初始值处理逻辑，修复问题
- 补充单测
- Fixed: #7014
- Fixed: #7033
=> fix: fix scrollbar init

__tests__/integration/api-chart-emit-tooltip-with-resize.spec.ts, __tests__/integration/snapshots/api/chart-emit-show-tooltip-with-resize/step0.html, __tests__/plots/api/chart-emit-show-tooltip-with-resize.ts, __tests__/plots/api/index.ts, src/interaction/tooltip.ts, src/runtime/plot.ts
=> fix: tooltip fails caused by resize

site/docs/manual/api/index.en.md, site/docs/manual/api/index.zh.md
=> docs: add getDataByXY API

__tests__/integration/snapshots/static/alphabetIntervalAxisTickLengthCallback.svg, __tests__/plots/static/alphabet-interval-axis-ticklength-callback.ts, __tests__/plots/static/index.ts, src/component/axis.ts, src/runtime/component.ts
=> feat: tickLength支持回调函数配置，添加单测

__tests__/integration/api-chart-emit-legend-default-select.spec.ts, __tests__/integration/snapshots/api/chart-emit-legend-default-select/step0.svg, __tests__/integration/snapshots/api/chart-emit-legend-default-select/step1.svg, __tests__/plots/api/chart-emit-legend-default-select.ts, __tests__/plots/api/index.ts, site/docs/manual/FAQ/index.en.md, site/docs/manual/FAQ/index.zh.md, site/docs/manual/component/legend.en.md, site/docs/manual/component/legend.zh.md, src/interaction/legendFilter.ts
https://github.com/antvis/G2/issues/6916
增加默认选择图例值功能
=> feat: legend default select

__tests__/integration/api-chart-slider-brush-highlight.spec.ts, __tests__/integration/snapshots/api/chart-slider-brush-highlight/step0.svg, __tests__/integration/snapshots/api/chart-slider-brush-highlight/step1.svg, __tests__/integration/snapshots/api/chart-slider-brush-highlight/step2.svg, __tests__/plots/api/chart-slider-brush-highlight.ts, __tests__/plots/api/index.ts, src/interaction/brushHighlight.ts
=> fix: brushHighlight return incorrect selection after sliderFilter
